Introduce questions for students
dodona-edu/dodona pull request #2094
Opened 2020-07-02 16:50 UTC by MrKickkiller

This pull request allows students to ask questions on their own code and introduces a new questions page for a course where course admins can see all the questions on their course. 

- [x] Tests were added

2020-09-08 17:56 UTC, pdawyndt commented on app/assets/javascripts/auto_reload.ts
> +    timout: number = 0;
timeout?

2020-09-08 17:56 UTC, pdawyndt commented on app/assets/javascripts/auto_reload.ts
> +        this.timout = window.setTimeout(() => {
timeout?

2020-09-08 17:56 UTC, pdawyndt commented on app/assets/javascripts/auto_reload.ts
> +        this.timout = 0;
timeout?

2020-09-08 17:56 UTC, pdawyndt commented on app/assets/javascripts/auto_reload.ts
> +        window.clearTimeout(this.timout);
timeout?

2020-09-09 20:55 UTC, pdawyndt commented on app/policies/question_policy.rb
> +    unanswered_question_count < 5 && total_question_count < 15
Do we want to keep these rather arbititrary restrictions? Discussion needed.

2020-09-10 08:44 UTC, niknetniko commented on app/policies/question_policy.rb
> +    unanswered_question_count < 5 && total_question_count < 15
We decided to remove this limit

2020-09-10 16:04 UTC, bmesuere requested changes
Nice work! Some small remarks:
- On the course settings page, don't make a separate section for questions and add it just below the description. Also, enable the setting for all existing courses and make it the default for new courses
- not convinced of the question mark icon in the nav bar. Maybe use account-question? I would also expand the tooltip to "questions from students" and not just "questions"
- add a tooltip to the ask a question button in the gutter
- button to send "vraag versturen" -> "vraag stellen"
- student tooltip "als behandeld markeren" -> "als beantwoord markeren" ?
- An answered question looks the same as an open question for students (minus the buttons) maybe add an extra (textual) indicator next to the date
- I'm not happy with the icons, suggestions welcome
- On the overview questions page, I wouldn't show the "in behandeling" section if there are no questions with that status
- "(elke 2 seconden als de pagina niet gebruikt wordt)" in fact it only refreshes when the page is used, but I would remove that part of the setting.
- maybe also add the setting to enable questions for the course to the questions page?
- the column width of the tables is not fixed which causes unaligned columns over the 2 or 3 tables

2020-09-10 16:39 UTC, niknetniko commented
> * I'm not happy with the icons, suggestions welcome

I'll look at the rest tomorrow, but I did consider this briefly, and this is were I ended:

![image](https://user-images.githubusercontent.com/1756811/92764253-8cbb0e80-f394-11ea-9897-be1cb67a75c3.png)

With the two people (`account-supervisor`) meaning in progress, from the idea that someone is next to student explaining things.

2020-09-10 17:01 UTC, pdawyndt commented
`chat-processing` (busy talking ... to student)
`comment-quote` (busy writing answer ... to student)
`message-draw` (busy writing answer ... to student)

2020-09-15 12:30 UTC, charvp requested changes
Some nitpicks, some questions, but I don't see any major problems with the code.

2020-09-15 12:30 UTC, charvp commented on app/assets/javascripts/code_listing/code_listing.ts
> +        const type = this.questionMode? "user_question" : "user_annotation";
```suggestion
        const type = this.questionMode ? "user_question" : "user_annotation";
```

2020-09-15 12:30 UTC, charvp commented on app/assets/javascripts/code_listing/code_listing.ts
> +                const type = this.questionMode? "user_question" : "user_annotation";
```suggestion
                const type = this.questionMode ? "user_question" : "user_annotation";
```

2020-09-15 12:30 UTC, charvp commented on app/assets/javascripts/code_listing/user_annotation.ts
>  export class UserAnnotation extends Annotation {
Did you consider subtyping a `QuestionAnnotation` from `UserAnnotation`? There's a few times where you `if` on `this.type` which very much feels like it could be cleaner with inheritance.

2020-09-15 12:30 UTC, charvp commented on app/controllers/annotations_controller.rb
> +  end
These feel like updates that could/should be part of the `update` action.

2020-09-15 12:30 UTC, charvp commented on app/controllers/courses_controller.rb
> +                                [],
These are only whitespace changes?

2020-09-15 12:30 UTC, charvp commented on app/helpers/application_helper.rb
> +    param_name = params[:param_name] || 'page'
I would prefer a sixth argument for this. `params` is meant to pass on parameters for `will_paginate`, not for params to this method.

2020-09-15 12:30 UTC, charvp commented on app/models/annotation.rb
> +  def to_partial_path
Doesn't look like this is used? Or is this some rails magic?

2020-09-15 12:30 UTC, charvp commented on app/models/question.rb
> +  def self.model_name
Is there really no other way to do this? This very much feels like a hack.

2020-09-15 12:30 UTC, charvp commented on app/models/question.rb
> +  def self.per_page
I think we always prefer not to have any presentation layer concerns in the models. In this case, adding the `per_page` argument to the `paginate` call in the controller seems cleaner to me.

2020-09-15 12:30 UTC, charvp commented on app/views/annotations/_annotation.json.jbuilder
> +json.type annotation.type&.downcase || 'annotation'
I would hope that the `||` here isn't actually required?

2020-09-15 12:30 UTC, charvp commented on db/migrate/20200629132522_add_questions.rb
> +        add_column :annotations, :type, :string
As mentioned before, I wouldn't allow this to be null and just add a default of `annotation`. Or you could do it in three steps: add the column, fill it for all existing annotations and then change the nullability.

2020-09-15 12:59 UTC, bmesuere commented
Maybe move the notification dot to the lower left corner instead of the right? This solves the overlap problem.

2020-09-15 13:09 UTC, bmesuere requested changes
- "Vragen zijn uitgeschakeld. Schakel dit in in de cursusopties." Maybe link "cursusopties" to the correct page? Or even better, make it possible to enable/disable from this page.
- Turn "auto refresh" on by default
- I think `comment-processing-outline` is clearer for use as pending icon
- The questions aren't paginated right now. If we don't add this now, we'll probably have to hotfix it after the first week. An alternative is to cap the list to the first 20/30/50 questions and add a link to a separate page where all questions can be seen (with pagination). This would make it a bit easier to implement without having to mess with the pagination in combination with the auto reload

2020-09-15 14:53 UTC, niknetniko commented on app/assets/javascripts/code_listing/user_annotation.ts
>  export class UserAnnotation extends Annotation {
I have tried this, but the subtype resulted in a bunch of `if`s inside the code listing, since all annotations (normal ones and questions) come from the same endpoint `/annotations`.

2020-09-15 15:20 UTC, niknetniko commented on app/controllers/annotations_controller.rb
> +  end
The current method has a big advantage: the policy for the question is relatively clean. I tried putting this all together in update, but I wasn't sure how the policy object should look in that case (e.g. course administrators are allowed to update the state of the question, but not the text of the question at the moment)

2020-09-15 15:24 UTC, niknetniko commented on app/controllers/courses_controller.rb
> +                                [],
My bad, I've reverted them

2020-09-15 15:32 UTC, niknetniko commented on app/models/annotation.rb
> +  def to_partial_path
Indeed rails magic, this determines the path for the partials for this model. I've moved it to the `Question` model.

2020-09-15 15:54 UTC, niknetniko commented on app/models/question.rb
> +  def self.model_name
I haven't found a way 😢

2020-09-15 16:44 UTC, niknetniko commented
> Turn "auto refresh" on by default

It is on by default if questions are enabled for the course.

> The questions aren't paginated right now. If we don't add this now, we'll probably have to hotfix it after the first week. An alternative is to cap the list to the first 20/30/50 questions and add a link to a separate page where all questions can be seen (with pagination). This would make it a bit easier to implement without having to mess with the pagination in combination with the auto reload

They are paginated, but the pagination controls only show if there are enough questions (each sections gets its own, independent pagination). Perhaps we should always show them?
![image](https://user-images.githubusercontent.com/1756811/93237685-bb642b00-f780-11ea-9724-98858fecf859.png)

Will look at changing options from this page tomorrow.

2020-09-15 17:48 UTC, charvp commented on app/assets/javascripts/code_listing/user_annotation.ts
>  export class UserAnnotation extends Annotation {
Hmm, I think I would still prefer the if's to be in code listing, because then we can dispatch to the right class and not worry about it for the rest of the runtime. But that's not a strong opinion, so if you feel otherwise, feel free to ignore me.

2020-09-15 17:49 UTC, charvp commented on app/controllers/annotations_controller.rb
> +  end
`permitted_attributes` should be used to determine what elements of the model are allowed to be updated.

2020-09-15 17:50 UTC, charvp commented on app/models/question.rb
> +  def self.model_name
How do we do this for exercises and reading activities? They both show up under `activities_url`, so it's not entirely the same, but maybe there is some inspiration to take from there.

2020-09-16 09:28 UTC, niknetniko commented on app/assets/javascripts/code_listing/user_annotation.ts
>  export class UserAnnotation extends Annotation {
I've changed it to use a subclass

2020-09-16 09:30 UTC, niknetniko commented on app/models/question.rb
> +  def self.model_name
The comment was bit misleading; one of the main issues was that rails expects values with a name based on the class (e.g. it expects `question` vs `annotation`). This was solved relatively easily with the subclass in typescript, so I've removed these lines.

2020-09-16 10:51 UTC, charvp approved these changes

2020-09-16 10:51 UTC, merged