First version of masonry working
dodona-edu/dodona pull request #2157
Opened 2020-08-11 10:13 UTC by LucianosLionakis

This pull request fixes a problem were homepage cards did not fit nicely.

Trying to fix this:
![](https://user-images.githubusercontent.com/3226995/69968973-cca6b880-151b-11ea-9590-8771117bb481.png)
Currently is like this:
![image](https://user-images.githubusercontent.com/48768719/89885607-9b62aa00-dbcb-11ea-97e8-3ba182564161.png)

- [ ] Need to trigger masonry when favorite courses are altered.
- [ ] Do not allow cards to fill the whole row if they are alone in a two column setup. 
- [ ] Change number of columns if size screen changes (just like before).
Closes #1551.

2020-08-13 06:07 UTC, rien commented on app/assets/javascripts/masonry.ts
> +        this.roots = Array.prototype.map.call(rootElements, (rootElement: HTMLElement) => {
Is there a reason why `rootElements.map(...)` isn't used here?

2020-08-13 06:12 UTC, rien commented on app/assets/javascripts/masonry.ts
> +            const newColumnNumber = window.innerWidth > 1024 ? 2 : 1;
I would extract `1024` to a class constant and make sure this value agrees with the bootstrap change points.

2020-08-13 06:15 UTC, rien commented on app/assets/stylesheets/pages/home.css.less
> +    @media (min-width: 1023px){
I think the bootstrap `lg` class (where we start using two columns for our cards) uses `min-width: 1200px`.

2020-08-13 06:26 UTC, thepieterdc commented on app/assets/stylesheets/pages/home.css.less
> +    @media (min-width: 1023px){
`lg` is `1200px` indeed. However, rather than hardcoding this, I'm sure that has been defined as a variable in the bootstrap source, which you can simply import.

`@screen-lg-min` probably

2020-08-13 07:10 UTC, LucianosLionakis commented on app/assets/javascripts/masonry.ts
> +        this.roots = Array.prototype.map.call(rootElements, (rootElement: HTMLElement) => {
Not that I know of. I will change it and see if it has any effect (which it probably won't).

2020-08-13 07:21 UTC, LucianosLionakis commented on app/assets/javascripts/masonry.ts
> +        this.roots = Array.prototype.map.call(rootElements, (rootElement: HTMLElement) => {
Apparently the `HTMLCollectionOf<>`  type has no `map` property.

2020-08-13 08:20 UTC, LucianosLionakis commented
> Can you also try to restore the padding/margin between the cards? I think this is called the "gutter" in bootstrap.

I tried using padding-left and -right in the CSS of the masonry-items class. This leads to larger paddings around the course card listing as seen below (the red arrows indicate the problem).
![image](https://user-images.githubusercontent.com/48768719/90110935-3b484100-dd4e-11ea-8519-40d92e0e39c8.png)

I tried finding out how bootstrap handles the padding of columns and rows. Unfortunately, I didn't find anything helpful so I decided to solve this problem in the masonry script since it is easy to find the cards in the first and last columns and give them the appropriate padding.

I edited the description to reflect the current state of changes.

2020-08-25 12:09 UTC, bmesuere requested changes
I don't think a homepage pack + binding to the global context is needed. Instead, 
- import Masonry inside favorite_course_buttons just like the toast
- rename `initFavoriteButtons` to something more general (initHomePageCards?) and do the initialization that's in home.html.erb over there

2020-08-25 16:43 UTC, bmesuere requested changes
👍 the cards now flow as expected and this way of importing is cleaner. I have few small remarks about the code. Since this js file and pack are only used on the homepage, it might be better to rename them from `favorite_course_buttons.js` to `home_page.js`

2020-08-25 16:43 UTC, bmesuere commented on app/assets/javascripts/masonry.ts
> +    onLoad(): void {
Rename `onLoad` and `onResize` to what it does and not when it is called. It doens't make sense to call a function named `onLoad` when adding a favorite, or calling `onResize` at the end of `onLoad`

2020-08-25 16:43 UTC, bmesuere commented on app/assets/javascripts/masonry.ts
> +        this.roots = Array.prototype.map.call(rootElements, (rootElement: HTMLElement) => {
I don't like this construction. If it stays in the code, a comment should be added. Can't it be solved by using `Array.from(rootElements).map` ?

2020-08-25 16:43 UTC, bmesuere commented on app/assets/javascripts/masonry.ts
> +            const cells: CustomElement[] = Array.prototype.map.call(cellElements, (cellElement: HTMLElement) => {
same here

2020-08-25 16:43 UTC, bmesuere commented on app/assets/javascripts/masonry.ts
> +                const columns = Array.from(new Array(root.columnNumber)).map( () => {
What is the goal of this `Array.from(new Array(root.columnNumber))` construct?

2020-08-25 16:43 UTC, bmesuere commented on app/assets/javascripts/masonry.ts
> +                    const column = columns.find(column => column.outerHeight == minOuterHeight);
```suggestion
                    const column = columns.find(column => column.outerHeight === minOuterHeight);
```

2020-08-25 16:43 UTC, bmesuere commented on app/assets/javascripts/masonry.ts
> +                        column.cells[column.cells.length - 1].element.style.flexBasis = String(column.cells[column.cells.length - 1].element.offsetHeight + masonryHeight - column.outerHeight - 1) + "
use template string (with backticks) instead of wrapping it in String and using a +

2020-08-25 16:43 UTC, bmesuere commented on app/assets/javascripts/masonry.ts
> +                root.element.style.maxHeight = String(masonryHeight) + "px";
template string

2020-08-25 16:43 UTC, bmesuere commented on app/assets/javascripts/masonry.ts
> +                if (root.element.className.includes("favorite")) {
these logs probably shouldn't be here?

2020-08-25 16:54 UTC, thepieterdc commented on app/assets/javascripts/masonry.ts
> +                    return rootElement;
What happens if you do `return { cells: [], outerHeight: 0}` (can subsequently remove the return as well to truly oneline it)

2020-08-26 11:55 UTC, bmesuere approved these changes
looks good 👍

2020-08-26 11:55 UTC, bmesuere commented on app/assets/javascripts/masonry.ts
> +            if (newColumnNumber != root.columnNumber) {
```suggestion
            if (newColumnNumber !== root.columnNumber) {
```

2020-08-26 11:56 UTC, merged