Fix/sign in page rework
dodona-edu/dodona pull request #2165
Opened 2020-08-13 14:40 UTC by LucianosLionakis

This pull request

- [x] bottom section with secondary schools should be removed (also remove the images from the repo)
- [ ] The new bottom section should be a large, centered, auto-complete select with all schools
- [ ] only include schools with smartschool/office/g-suite as the primary provider
- [ ] next to the select, there should be a big sign in button that redirects to the providers of the selected institution
- [ ] the selected institution should be stored in local storage
- [ ] if there is an institution in local storage (from a previous sign-in), make it the selected institution on autocomplete

Closes #2162.

2020-08-13 14:42 UTC, thepieterdc commented on app/controllers/auth/authentication_controller.rb
> +    @institution_providers = apply_scopes(@providers.where.not(type: Provider::Saml.name))
Possibly confusing variable name since Saml is as much a provider as the other three

2020-08-13 14:45 UTC, LucianosLionakis commented on app/controllers/auth/authentication_controller.rb
> +    @institution_providers = apply_scopes(@providers.where.not(type: Provider::Saml.name))
Maybe `high_school_providers` is beter?

2020-08-13 14:50 UTC, thepieterdc commented on app/controllers/auth/authentication_controller.rb
> +    @institution_providers = apply_scopes(@providers.where.not(type: Provider::Saml.name))
UGent can also sign in through Office 365 ;)

2020-08-19 09:04 UTC, LucianosLionakis commented on app/controllers/auth/authentication_controller.rb
> +    @institution_providers = apply_scopes(@providers.where.not(type: Provider::Saml.name))
What do you think of `education_providers`? If you have a better suggestion it's more than welcome :smile:.

2020-08-19 09:19 UTC, thepieterdc commented on app/controllers/auth/authentication_controller.rb
> +    @institution_providers = apply_scopes(@providers.where.not(type: Provider::Saml.name))
Anything that's not `SAML` is considered an `oauth_provider` in the `omniauth_callbacks`.

2020-08-19 09:27 UTC, thepieterdc requested changes

2020-08-19 09:27 UTC, thepieterdc commented on app/controllers/auth/authentication_controller.rb
> +    @oauth_provider = apply_scopes(@providers.where(:type => [Provider::Smartschool, Provider::Office365, Provider::GSuite]))
`@oauth_providers`

2020-08-19 09:27 UTC, thepieterdc commented on app/views/auth/sign_in.html.erb
> +  let institutions = <%= raw @oauth_provider.map{|i| {id: i.id, name: i.institution.name, type: i.type}}.to_json %>;
`@oauth_providers`

2020-08-19 10:15 UTC, rien reviewed
The searchbar looks nice, but is not so discoverable. Maybe it needs a subtitle above:
> Geen idee welke login je kan gebruiken? Zoek hier je onderwijsinstelling:

In the search results I would also show the provider, so they remember which button to click next time.

2020-08-19 11:25 UTC, rien commented on app/models/provider.rb
> +  scope :by_institution, ->(institution) { where(institution: [institution, nil]) }
Why is an array used here? If you use `where institution_id: institution` here, it will automatically pass the id if an institution object is given.

2020-08-19 11:25 UTC, rien commented on app/views/auth/sign_in.html.erb
> +      <div class="col-xs-1">
This will probably too small on small devices, can you test this?

2020-08-25 12:47 UTC, bmesuere requested changes
Looks good! A few remarks:
- make the sign in button primary
- wrap the search field in a card (without headers) to make it more prominent
- disable the sign in button if no school is selected yet
- add a divider (eg ndash or middle dot) between institution name and provider in the dropdown
- filter institutions that don't have a name (yet)
- improve the placeholder text to something that nudges towards typing the name of the school (e.g. type to search institution)
- Add a small help text containing "Users of i-Learn can currently only sign in through the i-Learn website."
- some files have missing trailing new lines

2020-08-26 07:11 UTC, bmesuere requested changes
I probably wasn't clear about what I meant for some items, sorry for that. I still see these issues:
- linting 
- ilearn text still missing
- button doesn't seem to be disabled yet
- placeholder text is still missing
- add some bottom margin to the select so that the suggestions don't add whitespace below the footer when the window height is log
- maybe give focus to the field on load?

2020-08-26 11:42 UTC, bmesuere requested changes
the functionality now seems to work as expected 👍 

To make the page a bit clearer, we could maybe add h2 headers with "hoger onderwijs" and "secundair onderwijs" above the buttons. The ilearn text could then be a helptext below that header as we have on a few other locations on Dodona. The sign in divider element would then also become obsolete.

2020-08-26 14:39 UTC, LucianosLionakis commented
How it looks with the new titles:
![image](https://user-images.githubusercontent.com/48768719/91317643-99e3d500-e7ba-11ea-8e6f-df6baad53f71.png)

2020-08-26 14:53 UTC, thepieterdc commented on config/locales/views/auth/nl.yml
> +      institution-search: "Typ om jou instelling te vinden"
jouw*

2020-08-26 14:53 UTC, thepieterdc commented on config/locales/views/auth/nl.yml
> +      ilearn-help: "i-Learn gebruikers kunnen momenteel enkel inloggen met de i-Learn website."
s/met/via?

2020-08-26 14:53 UTC, thepieterdc commented on config/locales/views/auth/nl.yml
> +      sign-in-help: "Geen idee welke login je kan gebruiken? Zoek hier je onderwijsinstelling:"
First sentence sounds a little odd IMO

2020-08-26 14:57 UTC, LucianosLionakis commented on config/locales/views/auth/nl.yml
> +      sign-in-help: "Geen idee welke login je kan gebruiken? Zoek hier je onderwijsinstelling:"
Misschien: "Weet je niet welke login je kan gebruiken?"

2020-08-26 15:15 UTC, thepieterdc commented on config/locales/views/auth/nl.yml
> +      sign-in-help: "Geen idee welke login je kan gebruiken? Zoek hier je onderwijsinstelling:"
@bmesuere ^?

2020-08-28 09:09 UTC, bmesuere requested changes

2020-08-28 09:09 UTC, bmesuere commented on config/locales/views/auth/nl.yml
> +      sign-in-help: "Geen idee welke login je kan gebruiken? Zoek hier je onderwijsinstelling:"
```suggestion
      sign-in-help: "Weet je niet welke login je moet gebruiken? Zoek hieronder je school en klik op aanmelden:"
```

2020-08-28 09:09 UTC, bmesuere commented on config/locales/views/auth/en.yml
> +      sign-in-help: "No idea which login you can use? Search for your educational institution bellow:"
```suggestion
      sign-in-help: "Don't know which login you can use? Search for your school and click the sign in button:"
```

2020-08-28 09:10 UTC, bmesuere approved these changes

2020-08-28 09:11 UTC, merged