Feature/exercises judge listing
dodona-edu/dodona pull request #2175
Opened 2020-08-19 06:10 UTC by winniederidder

This pull request adds an exercise link to the judges page and allows filtering activities by used judge.

Judge page:
![judge-show](https://user-images.githubusercontent.com/53743234/90598352-29094f80-e1f3-11ea-8c62-b9b116c540a7.png)

Following the link:
![judge-label](https://user-images.githubusercontent.com/53743234/90598370-2dce0380-e1f3-11ea-99c0-f6ea22a0770b.png)

Filtering by judge:
![Uploading judges-searchbar.png…]()

Regular users cannot use this feature, only staff and above:
![judges-filtered-student](https://user-images.githubusercontent.com/53743234/90598394-37576b80-e1f3-11ea-87dd-e9126c421bb5.png)

- [x] Tests were added

Closes #2166  .

2020-08-19 10:10 UTC, rien commented on db/seeds.rb
> +  python_judge = Judge.create name: 'python-judge', image: 'dodona-python', remote: 'git@github.com:dodona-edu/judge-pythia.git', renderer: PythiaRenderer
The judges used in Dodona right now don't have 'judge' in their name. So I would keep it like this in the seeds. See my comment in `_searchbar.html` for a solution.

2020-08-19 10:10 UTC, rien commented on app/views/layouts/_searchbar.html.erb
> +            data: <%= raw local_assigns.fetch(:judges, []).map{|judge| {id: judge.id, name: judge.name}}.to_json %>,
```suggestion
            data: <%= raw local_assigns.fetch(:judges, []).map{|judge| {id: judge.id, name: "#{judge.name}-judge"}}.to_json %>,
```

2020-08-19 10:17 UTC, winniederidder commented on app/models/activity.rb
> +  scope :by_judge, ->(judge_id) { where(judge_id: judge_id) }
Does this work for the has_scope aswell, where the judge_id is present in the url parameter?

2020-08-19 10:57 UTC, rien commented on app/models/activity.rb
> +  scope :by_judge, ->(judge_id) { where(judge_id: judge_id) }
Yes, if you pass an integer it will use that as the id.

2020-08-19 11:18 UTC, rien approved these changes

2020-08-24 08:48 UTC, bmesuere requested changes

2020-08-24 08:48 UTC, bmesuere commented on app/controllers/activities_controller.rb
> +  has_scope :by_judge, as: 'judge_id', if: ->(this) { Pundit.policy!(this.current_user, Judge).index? }
I'm not sure if we want this policy check here?

2020-08-24 08:53 UTC, rien commented on app/controllers/activities_controller.rb
> +  has_scope :by_judge, as: 'judge_id', if: ->(this) { Pundit.policy!(this.current_user, Judge).index? }
I don't know if there is a better place? We _could_ just omit the check, because it's not really an issue if students can request activities for a specific judge.

2020-08-24 08:56 UTC, bmesuere commented on app/controllers/activities_controller.rb
> +  has_scope :by_judge, as: 'judge_id', if: ->(this) { Pundit.policy!(this.current_user, Judge).index? }
Sorry if I wasn't clear. My proposal was indeed to remove this check here (since it just defines a scope) and simply not list the judges in the autocomplete for normal users. The reason not to show it is because it isn't relevant for them and would only add confusion not because they shouldn't be allowed to see it.

2020-08-24 09:01 UTC, rien commented on app/controllers/activities_controller.rb
> +  has_scope :by_judge, as: 'judge_id', if: ->(this) { Pundit.policy!(this.current_user, Judge).index? }
The judge search filter won't show up for students because the `policy_scope` is empty for them. Or do you also want to hide this filter for teachers?

2020-08-24 09:04 UTC, bmesuere commented on app/controllers/activities_controller.rb
> +  has_scope :by_judge, as: 'judge_id', if: ->(this) { Pundit.policy!(this.current_user, Judge).index? }
The judge/index view is visible to zeus+staff so it should probably be hidden for course admins without staff privileges?

2020-08-24 09:10 UTC, rien commented on app/controllers/activities_controller.rb
> +  has_scope :by_judge, as: 'judge_id', if: ->(this) { Pundit.policy!(this.current_user, Judge).index? }
Ah yes, I meant staff. There won't be any judge filter unless `user.admin?` is true. If there are no judges to filter on, the autocomplete won't show them. We could also explicitly disable that behavior by placing a policy check around the `filterCollection["judges"]` call in [the searchbar](https://github.com/dodona-edu/dodona/pull/2175/files#diff-608825a8bb59cd289c36a2c1510cd4a5R140).

2020-08-24 09:36 UTC, winniederidder commented on app/controllers/activities_controller.rb
> +  has_scope :by_judge, as: 'judge_id', if: ->(this) { Pundit.policy!(this.current_user, Judge).index? }
Does this imply the policy scope change for judges should also be reverted?

2020-08-24 12:09 UTC, bmesuere approved these changes

2020-08-24 12:09 UTC, merged