LTI Content Selection
dodona-edu/dodona pull request #2177
Opened 2020-08-23 16:33 UTC by thepieterdc

This PR adds LTI Deep Linking support with Content Selection.

**Tests:**
- Moodle (https://sandbox.moodledemo.net) and local instance
- Brightspace via Ufora (https://ufora.ugent.be); can only be done by deploying to naos.

**Roadmap:**
- [x] Select 1 activity on Moodle
- [x] Select 1 activity on Brightspace
- [x] Improve layout for content selection (#2231)
- [x] Allow multiple items to be selected (#2231)
- [x] Fix cookies (see below)
- [ ] Decide if we want analytics in the iframes (https://github.com/dodona-edu/dodona/pull/2214#discussion_r486623107)

See #2214 for the UI when logging in for the first time.

**Remarks:**
We need to verify that the SameSite policy of our cookies is correct. Because of an update in Chrome, the security for cookies in iframes has been tightened and this might break content selection. Can be temporarily disabled in `chrome://flags` by disabling everything related to SameSite cookies.

Grouping issue: #737

2020-09-11 08:18 UTC, niknetniko commented on app/controllers/auth/omniauth_callbacks_controller.rb
> +    redirect_to root_path, status: :bad_request
@thepieterdc What does the `status: :bad_request` do? I ask since it breaks the tests

2020-09-15 13:30 UTC, charvp requested changes
There's quite a lot of duplication between the top-level layout erb files. Can we extract some of that to partials?

Otherwise looks good to me, but I'm not familiar with the LTI standard, so I didn't really check for implementation mistakes there. I assume that since things are working on naos, we're good in that department though.

2020-09-15 20:28 UTC, niknetniko commented
> There's quite a lot of duplication between the top-level layout erb files. Can we extract some of that to partials?

I intended to rename "embedded" to "lti", but somehow ended up with both. I've removed the "embedded" one (they were identical).

2020-09-16 06:54 UTC, charvp commented
> > There's quite a lot of duplication between the top-level layout erb files. Can we extract some of that to partials?
> 
> I intended to rename "embedded" to "lti", but somehow ended up with both. I've removed the "embedded" one (they were identical).

I do think there's still some duplication between `application.html.erb` and `lti.html.erb` (and maybe `frame.html.erb`). Can you look into removing some of that? (It might not be worth it, I'll leave that up to your judgment.)

2020-09-16 07:47 UTC, niknetniko commented
> I do think there's still some duplication between `application.html.erb` and `lti.html.erb` (and maybe `frame.html.erb`). Can you look into removing some of that? (It might not be worth it, I'll leave that up to your judgment.)

I've extracted some more common code into partials. I think the remaining code is either different or too small (a few lines) to extract into a partial.

2020-09-16 07:48 UTC, charvp approved these changes

2020-09-16 08:00 UTC, bmesuere approved these changes

2020-09-16 08:08 UTC, merged