[LTI] Content selection UI
dodona-edu/dodona pull request #2231
Opened 2020-09-07 14:19 UTC by niknetniko

Depends on #2230 and also contains a cherry pick from #2214, which I'll delete if/when that PR is merged. 

- If the platform does not support `LtiResourceLink`s, we display that we don't support any content. In the future, we might expand to also support links or other content types.
- Multiple selection is implemented, but only for activities, not for courses or series. This because we plan to rewrite this view in Vue in the future, where we'll have a better UI to support this.
- Technically: all courses are loaded, and the series & activities for one courses are inserted when the course is selected (using the same technique as the search pages).

2020-09-10 21:21 UTC, thepieterdc requested changes
Looking good! Some minor remarks, mostly refactorings.

2020-09-10 21:21 UTC, thepieterdc commented on app/assets/javascripts/lti.ts
> +}
These functions are not LTI specific and can therefore be refactored to a more general util file

2020-09-10 21:21 UTC, thepieterdc commented on app/assets/javascripts/lti.ts
> +
Same comment as above

2020-09-10 21:21 UTC, thepieterdc commented on app/assets/javascripts/lti.ts
> +        const url = new URL(baseUrl);
Didn't know about this, cool!

2020-09-10 21:21 UTC, thepieterdc commented on app/assets/javascripts/lti.ts
> +        })
I might be wrong, but I believe that the Dodona `fetch` implementation already does this (`assets/javascripts/util.js` ~ line 160). Optionally add the `same-origin` there using a parameter or so

2020-09-10 21:21 UTC, thepieterdc commented on app/assets/javascripts/lti.ts
> +        console.log(`Selected ${id}`);
Remove console logs

2020-09-10 21:21 UTC, thepieterdc commented on app/controllers/lti_controller.rb
> +    @grouped_courses = courses.group_by(&:year)
Not using the `courses` variable (local scope), since it's not too long I'd just inline it

```suggestion
    @grouped_courses = policy_scope(Course.all).group_by(&:year)
```

2020-09-10 21:21 UTC, thepieterdc commented on app/controllers/lti_controller.rb
> +  def create_items_from_params(params)
Move out of controller and into lti_helper (create if not yet exists). Try to keep controllers concise.

2020-09-10 21:21 UTC, thepieterdc commented on app/controllers/lti_controller.rb
> +  end
Move to series helper

2020-09-10 21:21 UTC, thepieterdc commented on app/controllers/lti_controller.rb
> +  end
Move to course helper

2020-09-10 21:21 UTC, thepieterdc commented on app/views/lti/series_and_activities.js.erb
> +$("#series").html("<%= escape_javascript(render partial: 'series_and_activities', locals: {series: @series, multiple: @multiple}) %>");
Can de-jQuery-fi

```suggestion
document.getElementById("series").innerHTML = "<%= escape_javascript(render partial: 'series_and_activities', locals: {series: @series, multiple: @multiple}) %>";
```

2020-09-11 08:53 UTC, niknetniko commented on app/assets/javascripts/lti.ts
> +
I agree with the previous comment, but these are pretty specific to this page (e.g. removing/adding the ID attribute of the first `select` element to make elements active and inactive).

2020-09-11 08:53 UTC, niknetniko commented on app/assets/javascripts/lti.ts
> +        })
Same origin is the default value, so I'll just remove it

2020-09-11 10:27 UTC, merged