Prompt when logging in from LTI
dodona-edu/dodona pull request #2264
Opened 2020-09-17 13:10 UTC by niknetniko

This pull request adds a prompt when logging in from LTI. Technically, opening a link via LTI is a `LtiResourceLinkRequest`, so we use that to detect LTI and extract some data (we use the name of the learning platform if available, otherwise "een andere leeromgeving").

The dialog is shown on:

- The course page (also when linking to series)
- The series page (e.g. a hidden series)
- The activity page

Currently the dialog looks like this:
![image](https://user-images.githubusercontent.com/1756811/93466759-fedba800-f8ec-11ea-8364-ab406b411e62.png)

Closes #2212.

TODO:

- [ ] Deploy & test on naos

2020-09-17 17:49 UTC, thepieterdc commented on app/controllers/concerns/set_lti_message.rb
> +require_relative '../../../lib/LTI/jwk.rb'
Good abstraction :+1:

2020-09-17 17:49 UTC, thepieterdc commented on app/views/courses/_not_a_member_dialog.html.erb
> +            <p><%= t('courses.registration.lti', lms: @lti_message.platform_name || t('courses.registration.lms_default')) %></p>
Maybe we can use `provider.institution.name` because then we have control over the name and we are sure that it always exists.

2020-09-17 17:49 UTC, thepieterdc commented on config/locales/views/courses/en.yml
> +      lti_title: Welkom
Dutch

2020-09-18 07:23 UTC, niknetniko commented on app/views/courses/_not_a_member_dialog.html.erb
> +            <p><%= t('courses.registration.lti', lms: @lti_message.platform_name || t('courses.registration.lms_default')) %></p>
I'm not sure if this won't be confusing for students with the current wording. If we want to use this, we should maybe reword it to something like "We hebben gemerkt dat je een link hebt gevolgd uit een leeromgeving van $institution".

2020-09-18 07:44 UTC, charvp approved these changes

2020-09-18 12:35 UTC, bmesuere requested changes
👍 Code looks good, a few small UI/text suggestions. Nice work!

2020-09-18 12:35 UTC, bmesuere commented on app/views/courses/_not_a_member_dialog.html.erb
> +            <%= image_tag "idp/#{@provider.institution.logo}", class: "img-responsive" %>
I would not use the image because not all institutions have one (only the ones with a button on the home page).

2020-09-18 12:35 UTC, bmesuere commented on config/locales/views/courses/nl.yml
> +      lti_title: Welkom
```suggestion
      lti_title: Welkom op Dodona!
```

2020-09-18 12:35 UTC, bmesuere commented on config/locales/views/courses/en.yml
> +      lti_title: Welcome
```suggestion
      lti_title: Welcome to Dodona!
```

2020-09-18 12:35 UTC, bmesuere commented on config/locales/views/courses/nl.yml
> +      lti: "We merken dat je een link volgde uit %{lms}, maar dat je nog niet bent ingeschreven voor deze cursus. Klik op registreren om dat wel te doen zodat de lesgever je kan opvolgen."
```suggestion
      lti: "Je volgde een link uit %{lms} naar deze pagina. Om je ingediende oplossingen correct bij te houden is het nodig om je op Dodona te registreren voor deze cursus. Dat kan eenvoudig door hieronder op registreren te klikken, of later vanaf de cursuspagina."
```

2020-09-18 12:35 UTC, bmesuere commented on config/locales/views/courses/en.yml
> +      lti: "We've noticed you followed a link from %{lms}, but you're not registered for this course yet. Click on register to enable the course administrator to follow your progress."
```suggestion
      lti: "You followed a link from %{lms} to this page. To correctly store your submissions, you should register for this course on Dodona. You can do this easily by clicking the "register" button below, or later from the course page."
```

2020-09-18 13:53 UTC, bmesuere approved these changes

2020-09-18 13:56 UTC, merged