Add iframe warning modal
dodona-edu/dodona pull request #2267
Opened 2020-09-21 09:23 UTC by niknetniko

I've added this warning modal on the "show" page for courses, series and activities. Technically course administrators could link to any page, but I think these would be the main ones where this is necessary. Adding it to all pages seemed too much.

![image](https://user-images.githubusercontent.com/1756811/93749855-ea542400-fbfa-11ea-818a-b7b0d38814b3.png)

If a student is not registered for a course, this modal will show above the modal from (#2264). Not very beautiful, but it works.

2020-09-21 09:48 UTC, niknetniko commented
I changed it to use a flash message

2020-09-21 10:20 UTC, charvp reviewed
Don't we want to do this on every page?

2020-09-21 10:30 UTC, niknetniko commented
> Don't we want to do this on every page?

I've added it on all pages. I originally didn't because the modal was pretty obtrusive if we had a false positive in iframe detection, but with the flash message, it's not really an issue.

2020-09-21 11:16 UTC, charvp requested changes

2020-09-21 11:16 UTC, charvp commented on app/assets/javascripts/util.js
> +import { isInIframe } from "iframe";
The comment above is for the function below.

2020-09-21 11:19 UTC, beardhatcode commented
Maybe add the message should make it clear that the teacher can fix this?

2020-09-21 11:44 UTC, niknetniko commented
> Maybe add the message should make it clear that the teacher can fix this?

Maybe something like this?

![image](https://user-images.githubusercontent.com/1756811/93762838-95bba380-fc10-11ea-8beb-5e2e6283e64a.png)

2020-09-22 09:15 UTC, bmesuere commented
> > Maybe add the message should make it clear that the teacher can fix this?
> 
> Maybe something like this?
> 
> ![image](https://user-images.githubusercontent.com/1756811/93762838-95bba380-fc10-11ea-8beb-5e2e6283e64a.png)

Opgepast Het lijkt erop dat je Dodona gebruikt binnen een andere webpagina waardoor mogelijk niet alles goed werkt. Laat dit weten aan je lesgever zodat hij het probleem kan oplossen door een instelling in de leeromgeving aan te passen. Ondertussen kan je **op deze link klikken** om Dodona te openen in een nieuw venster.

2020-09-22 11:56 UTC, niknetniko commented
> Opgepast Het lijkt erop dat je Dodona gebruikt binnen een andere webpagina waardoor mogelijk niet alles goed werkt. Laat dit weten aan je lesgever zodat hij het probleem kan oplossen door een instelling in de leeromgeving aan te passen. Ondertussen kan je **op deze link klikken** om Dodona te openen in een nieuw venster.

Applied & translated to English

2020-09-22 12:05 UTC, bmesuere approved these changes

2020-09-22 12:05 UTC, merged