UI tweaks for question table
dodona-edu/dodona pull request #2299
Opened 2020-09-28 10:14 UTC by niknetniko

This pull request tweaks the question table UI as discussed. Changes:
- Entire row is clickable and links to the question in a new tab
- "Last edited by" is displayed for question in progress & answered
- Ordering has changed: open questions are now oldest first, while the two others are last edited first.
- Adjust wording when there are no questions.

Screenshot:
![image](https://user-images.githubusercontent.com/1756811/94410842-20078880-0178-11eb-8b0c-25a229dc1453.png)

This implements some of the suggestions made in #2265.

2020-09-28 11:32 UTC, charvp approved these changes

2020-09-28 15:05 UTC, bmesuere requested changes
looks good 👍 
- include "ago" or "geleden" in the time indication
- put the time indication on top in the bottom two sections (similar to the open questions section)
- include "closed by" in front of the course admin name

2020-09-28 15:31 UTC, niknetniko commented
Applied the suggestions, resulting in:

![image](https://user-images.githubusercontent.com/1756811/94452487-e18dc000-01af-11eb-8b70-869ca2929e12.png)

2020-10-01 14:25 UTC, bmesuere approved these changes

2020-10-01 14:55 UTC, merged