Check notifications every minute
dodona-edu/dodona pull request #2308
Opened 2020-09-29 14:16 UTC by charvp

Depends on #2302.

2020-10-06 08:21 UTC, niknetniko requested changes
After a refresh has happened, toggling the read state of a notification is broken for me. Clicking the dot of a notification doesn't seem to do anything.

2020-10-06 08:34 UTC, bmesuere approved these changes

2020-10-06 09:04 UTC, bmesuere commented
I didn't run it locally, so my approval is not because it works for me

2020-10-07 07:22 UTC, charvp commented
Apparently contained JavaScript isn't executed when using `innerHtml = `. jQuery does some special stuff for that in its `html()` method. There's [some ways](https://stackoverflow.com/questions/2592092/executing-script-elements-inserted-with-innerhtml) of doing it, but they're all pretty involved, so I just opted for using jQuery for now, while we still have it. If/when we ever get rid of it, this will have to be fixed in a lot of places anyway.

2020-10-07 07:46 UTC, niknetniko approved these changes

2020-10-07 09:51 UTC, merged