Periodically reload to watch for new submissions II
dodona-edu/dodona pull request #2310
Opened 2020-10-01 14:10 UTC by niknetniko

This pull request supersedes #1950. It is mainly the same PR, but updated. There are some differences:
- The toggle to enable refresh is now an option instead of an action. The options have been renamed from "Filter options" to "Options". Screenshot when there are other options:
![image](https://user-images.githubusercontent.com/1756811/94818459-70901780-03fe-11eb-80e4-103de3761d6d.png)

- The refresh uses the interaction detection mechanism, so it won't refresh while scrolling, typing or otherwise interacting with the results.

- [x] Tests were added

Closes #1874.

2020-10-01 14:22 UTC, charvp commented on app/assets/javascripts/index.js
> +    if (loader !== null) {
This shouldn't happen right? The `toggleIndexReload` function is (should) only be used on pages where `refreshElement` wasn't `null`, which means that `window.dodona.index.periodicReload` will have been set by `initRefresh()`.

I'm not necessarily saying it should be changed, justed wanted to check.

2020-10-01 14:24 UTC, charvp commented on app/assets/javascripts/index.js
> +    if (loader !== null) {
Although, if someone forgets to pass `refreshElement` in the future, this will probably make it harder to debug why things aren't working. Maybe we should just let it error out in that case?

2020-10-01 14:32 UTC, bmesuere requested changes

2020-10-01 14:32 UTC, bmesuere commented on config/locales/views/submissions/nl.yml
> +      watch_submissions: Nieuwe oplossingen inladen
```suggestion
      watch_submissions: Oplossingen automatisch herladen
```

2020-10-01 14:32 UTC, bmesuere commented on config/locales/views/submissions/en.yml
> +      watch_submissions: Watch for new submissions
```suggestion
      watch_submissions: Automatically reload submissions
```

2020-10-01 14:36 UTC, niknetniko commented on app/assets/javascripts/index.js
> +    if (loader !== null) {
Correct on both accounts, I've changed it (and moved the toggle code to the class instead).

2020-10-01 14:43 UTC, bmesuere approved these changes

2020-10-07 09:52 UTC, charvp commented
This has a merge conflict, but otherwise can be merged?

2020-10-07 13:13 UTC, merged