Exercise statistics visualisation
dodona-edu/dodona pull request #2598
Opened 2021-04-08 13:01 UTC by tibdhond

2021-04-14 22:21 UTC, tibdhond commented
The visualisations have now been integrated into the course page. However, since there isn't a lot of dummy data available, it's hard to say what should change in terms of styling (of the graphs themselves). This requires some further application to more realistic data.

![image](https://user-images.githubusercontent.com/32074366/114786702-dd597680-9d7e-11eb-8b18-e0b98f4c308d.png)

![image](https://user-images.githubusercontent.com/32074366/114787621-645b1e80-9d80-11eb-95fc-2be015dcb773.png)

2021-04-20 10:26 UTC, tibdhond commented
The latest version has been deployed to naos with the following results:

![image](https://user-images.githubusercontent.com/32074366/115378652-0f306a00-a1d1-11eb-9901-ff55bc8e8d81.png)

![image](https://user-images.githubusercontent.com/32074366/115380949-62a3b780-a1d3-11eb-841c-d09e7a4320d4.png)

![image](https://user-images.githubusercontent.com/32074366/115381013-72bb9700-a1d3-11eb-832e-6f2363ff0914.png)

![image](https://user-images.githubusercontent.com/32074366/115381128-8ff06580-a1d3-11eb-8a38-dfa4914572f0.png)
The black spots here are caused by unfinished code that was accidentally pushed.

2021-04-20 10:39 UTC, pdawyndt commented
- [ ] order of exercises in the plots differs from order of exercises in series

2021-04-20 10:39 UTC, tibdhond commented
Changes that should still be made:

**General**
- [ ] proper usage of localisation
- [ ] proper usage of authorization
- [ ] sort exercises in right order
- [ ] hide stats button for non-course admins
- [ ] more padding to the left of graphs / a way to make sure titles aren't cut off
- [ ] some sort of explanation on how to use/interpret the graphs
- [ ] different styling / positioning for the graph tabs?

**Violin**
- [ ] Decide on a colour for the graph
- [ ] Reposition x-axis label

**Stacked Status**
- [ ] Decide on colours for each status

**Timeseries**
- [ ] Decide on colours for each status
- [ ] fix time scoping problem
- [ ] only display min and max values on y-axis
- [ ] re-enable interpolation (while making sure the graph doesn't drop below 0)

2021-04-20 10:59 UTC, tibdhond commented
Some issues:

**Authorization**
Not quite sure how to make use of the authorization. 
I assume I'd have to do something along the lines of `authorize course` or `authorize series` in statistics_controller.rb and create new policies in series_policy.rb or course_policy.rb?

**Exercise order**
How do I determine the exercise order? Is it safe to assume they will be in the correct order when fetching them from a series object?

**minor problem: typescript error**
I'm getting several typescript errors when setting the area (in violin and timeseries). Typescript seems to insist that the input for area must have type [[number, number]], while this shouldn't be necessary. Is there something I can do about this or do I just ignore it?

2021-04-20 11:12 UTC, tibdhond commented
I tried the green/shades of red colour scheme (using d3.interpolateReds) for timeseries on a local graph with following results:
![image](https://user-images.githubusercontent.com/32074366/115386445-b0bbb980-a1d9-11eb-8053-1e13a1321382.png)

I feel like the reds are only barely distinguishable from each other on this large example, so they probably won't be in their reduced size. 
The 'wrong' statusse might have to be aggregated if we want to use this kind of colour scheme, or we will have to decide on another one.

2021-04-21 19:20 UTC, tibdhond commented
All strings now use proper translations.
Not sure how/whether to translate the stats tab (violin/stacked status/timeseries)

2021-04-21 19:41 UTC, tibdhond commented
Retaining the card height causes some slight issues when there's only one exercise in a series:
![image](https://user-images.githubusercontent.com/32074366/115611398-50686d00-a2ea-11eb-9992-29018aa0392e.png)

2021-04-24 09:53 UTC, bmesuere commented
Regarding show statistics button:
- I would add 📈 icon next to the 3 dots to enable them. If graphs are shown, I would switch out the 📈 for a format-list-bulleted icon
- violin: discuss on Monday if we want a cutoff for outliers. Right now they make the rest less interpretable
- colors: maybe try if we can use the same color scheme for both plots? The default scheme is a bit ugly, especially in dark mode. The dark2 scheme probably is a better fit (at least in dark mode)
- stacked: consider grid lines every 20%
- time series: put exercise labels to the left
- time series: discuss on Monday: do we take a cutoff date at the deadline? Right now it doesn't look good because too stretched
- general: discuss on Monday: include reading activities?
- general: discuss on Monday: I thought we needed to keep the height of the original table to prevent jumps or the lazy loading of series from breaking, but this is not the case so we can reevaluate this.

2021-04-26 13:51 UTC, tibdhond commented
Some more problems that need fixing:

**Timeseries**

- [ ] Tooltips don't seem to work
- [ ] sometimes freezes the page (I assume it gets stuck in a loop)

**Violin**

- [ ] x-axis label overlaps with axis
- [ ] mouse cursor can overlap with graph cursor when graph is small (making it hard to see)
- [ ] fallback when there is no data

**Stacked status**

- [ ] fallback when there is no data

2021-04-26 14:56 UTC, tibdhond commented
- [ ] move tab buttons to the right

- [ ] violin lighter variant of primary colour
- [ ] violin move x-axis label to the left
- [ ] violin bigger tooltip label #users # submissions
- [ ] violin show cursor over all exercises at once
- [ ] stacked status: horizontal legend
- [ ] stacked status: gridlines labels
- [ ] stacked status: expand tooltip with amounts
- [ ] stacked status: total submissions to the right
- [ ] stacked status: move tooltip closer to mouse cursor
- [ ] timeseries: insert empty datapoints for every day
- [ ] cumulative timeseries: only one graph, only first correct, stack exercises

2021-04-27 11:35 UTC, tibdhond commented
Violin tooltips have been changed to show tooltips for all exercises at once and the colour has been changed to (a shade of) the primary colour.

![image](https://user-images.githubusercontent.com/32074366/116234783-52ed1b80-a75d-11eb-96f7-42aba5e26dd5.png)

2021-04-27 18:16 UTC, tibdhond commented
Stacked status has undergone some changes:

![image](https://user-images.githubusercontent.com/32074366/116291938-73d16300-a795-11eb-88c3-2b016ee36008.png)

2021-05-01 18:00 UTC, tibdhond commented
The cumulative timeseries has been implemented. I went for a line graph instead of an area graph since this format felt like it would be better interpretable.  I still have to figure out how to translate the date strings however.

![image](https://user-images.githubusercontent.com/32074366/116791005-d4bfaa80-aab7-11eb-916d-e2afb5ed30d4.png)

2021-05-01 19:36 UTC, tibdhond commented
The regular timeseries also had some updates and bugfixes. I feel like the way tooltips are displayed right now could be improved, but can't think of a better way at the moment.

![image](https://user-images.githubusercontent.com/32074366/116793156-42260800-aac5-11eb-80d5-aa8a0004ba29.png)

2021-05-02 11:16 UTC, tibdhond commented
TODOS

- [ ] authorization + hide button
- [ ] violin: tooltip design (not too happy with how it currently looks)
- [ ] timeseries: tooltip design (not too happy with how it currently looks)
- [ ] ctimeseries: translate date strings
- [ ] translation of graph names? (in the toggle tab)

2021-05-04 20:24 UTC, tibdhond commented
The violin tooltip has received another redesign and now has the following look:

![image](https://user-images.githubusercontent.com/32074366/117065171-6d0f9680-ad27-11eb-91c5-0ea14645f015.png)

2021-05-06 14:14 UTC, tibdhond commented
The cumulative timeseries has been changed to display percentages instead of absolute numbers. The tooltips now display both the absolute and relative amounts. This might cause things to get a bit crowded however.

![image](https://user-images.githubusercontent.com/32074366/117313287-0bb20980-ae86-11eb-91da-05f56a451021.png)

2021-05-06 21:10 UTC, tibdhond commented
The violin plot icon from _the noun project_ didn't show up for some reason (+ has credentials in free version) so I went with the closest thing I could find.

![image](https://user-images.githubusercontent.com/32074366/117365761-112c4580-aec0-11eb-9dd5-e00b928de4a7.png)

2021-05-06 21:32 UTC, tibdhond commented
Authorization has been implemented, but is turned off. This will need to be turned back on before deploying.

2021-05-16 13:42 UTC, tibdhond commented
New styling for stacked status additional metrics:
![image](https://user-images.githubusercontent.com/32074366/118399400-3efe5080-b65d-11eb-8284-4e13aa4c98d3.png)

2021-05-19 11:56 UTC, tibdhond commented
- [ ] finish timeseries
- [ ] ctimeseries: x-axis date format
- [ ] violin/stacked border colour

2021-05-25 11:21 UTC, tibdhond commented
Changed the violin and stacked status metric container border colour to panel-primary:

![image](https://user-images.githubusercontent.com/32074366/119489625-288e7e00-bd5c-11eb-912b-82923ce442bb.png)

2021-05-27 11:27 UTC, bmesuere commented
@tibdhond I rebased this on develop and (hopefully) fixed all things to account for our switch from less to sass. Be sure to pull first before applying changes locally because I had to force push this.

2021-05-27 12:23 UTC, bmesuere commented on app/assets/javascripts/cumulative_timeseries.ts
> +    dateArray.unshift(metaData["minDate"]);
This is a strange way of writing this. I would expect a concat on the previous line. In addition, the d3 range function includes the time of start and excludes the time of stop. If your minDate is not included, you probably have a timezone problem somewhere.

2021-05-27 12:26 UTC, bmesuere commented on app/assets/javascripts/cumulative_timeseries.ts
> +    const mapEx = (target: string): string => // map id to exercise name
This is a strange function and probably indicates that your data isn't in an optimal format.

2021-05-27 12:28 UTC, bmesuere commented on app/assets/javascripts/cumulative_timeseries.ts
> +function drawCumulativeTimeSeries(data, metaData, exMap): void {
- Metadata is written in a single word, so the D should be lower case.
- Give exMap a better name
- Add docs

2021-05-27 12:31 UTC, bmesuere commented on app/assets/javascripts/cumulative_timeseries.ts
> +        .call(d3.axisLeft(y).ticks(5).tickFormat((v: number) => `${100*v}%`));
I think the ticks function accespts a number formatter as second argument, so you can probably just pass `"%"` instead of the verbose tickFormat

2021-05-27 12:32 UTC, bmesuere commented on app/assets/javascripts/cumulative_timeseries.ts
> +    let ticks = d3.timeDay.filter(d=>d3.timeDay.count(metaData["minDate"], d) % 2 === 0);
Does this select every other day as tick? Or what is this used for? This doesn't seem very scalable.

2021-05-27 12:36 UTC, bmesuere commented on app/assets/javascripts/cumulative_timeseries.ts
> +        .attr("y", tooltipLabel.node().getBBox().height);
This, in combination with the dummy text, is not ok. Use a fraction of the font-size (or line height) or even better, use the alignment-baseline property.

2021-05-27 12:38 UTC, bmesuere commented on app/assets/javascripts/cumulative_timeseries.ts
> +        .data(Object.entries(data), d => d[0])
What exactly is set as the data here?

2021-05-27 12:41 UTC, bmesuere commented on app/assets/javascripts/cumulative_timeseries.ts
> +    const tooltipDots = graph.selectAll("dots")
This selectAll doesn't make sense. I know the initial selection will be empty, but calling `selectAll("dots")` is very confusing because it hints that elements of the type dots will be added which is not the case.

2021-05-27 12:41 UTC, bmesuere commented on app/assets/javascripts/cumulative_timeseries.ts
> +        tooltipI = -1;
What is this `tooltipI` used for?

2021-05-27 12:43 UTC, bmesuere commented on app/assets/javascripts/cumulative_timeseries.ts
> +    tooltipNotFocused();
Calling this function in the middle of the file is bad style. If it is needed, add the function call where the other stuff is initialized.

2021-05-27 12:45 UTC, bmesuere commented on app/assets/javascripts/cumulative_timeseries.ts
> +        `translate(${width/2 - legend.node().getBBox().width/2},
As before, using getBBox for positioning stuff is not great. Aren't there any other alignment options?

2021-05-27 12:48 UTC, bmesuere commented on app/assets/javascripts/cumulative_timeseries.ts
> +        .style("height", `${height}px`) // prevent shrinking after switching graphs
Aren't these style things more appropriate to do in css?

2021-05-27 12:51 UTC, bmesuere commented on app/assets/javascripts/cumulative_timeseries.ts
> +    const processor = function (raw): void {
Why is this an inline function? You can simply use await on the json call below.

2021-05-27 12:54 UTC, bmesuere commented on app/assets/javascripts/cumulative_timeseries.ts
> +        metaData["dateRange"] = Math.round(
I'm sure there's a d3 helper function for this.

2021-05-27 12:57 UTC, bmesuere commented on app/assets/javascripts/cumulative_timeseries.ts
> +        Object.entries(data).forEach(entry => {
I'm not sure which data format you used for your data. I see a lot of calls to Object.entries(data) which is a bit of red flag (you would expect data to be an array in the first place). In addition, I see you used numeric adressing below where you would expect named fields (e.g., an object instead of an array).

2021-05-30 20:32 UTC, tibdhond commented on app/assets/javascripts/cumulative_timeseries.ts
> +function insertFakeData(data, maxCount): void {
removed

2021-05-30 20:34 UTC, tibdhond commented on app/assets/javascripts/cumulative_timeseries.ts
> +let selector = "";
All graphs have been rewritten as classes. Since this opens up opportunities for class inheritance, I will be looking into creating a common super class (once I've fixed the other problems).

2021-05-30 20:34 UTC, tibdhond commented on app/assets/javascripts/timeseries.ts
> +function insertFakeData(data): void {
removed

2021-05-30 20:35 UTC, tibdhond commented on app/assets/javascripts/cumulative_timeseries.ts
> +    d3.timeFormatDefaultLocale({
The locale has been moved to graph helper and is now imported in the other files.

2021-05-30 20:36 UTC, tibdhond commented on app/assets/javascripts/graph_helper.js
> +        const words = exMap.find(ex => ex[0].toString()===datum.toString())[1].split(" ").reverse();
This was me over-complicating things. This part has been replaced by a simple object mapping exercise id's to exercise names. Some more comments have been added to graph_helper.

2021-05-30 20:38 UTC, tibdhond commented on app/assets/javascripts/cumulative_timeseries.ts
> +    dateArray.unshift(metaData["minDate"]);
This was resolved by setting the minDate to midnight of the earliest data point.

2021-05-30 20:38 UTC, tibdhond commented on app/assets/javascripts/cumulative_timeseries.ts
> +    const mapEx = (target: string): string => // map id to exercise name
Related to the confusing line in graph_helper.
Has been replaced by the exId -> exName object.

2021-05-30 20:40 UTC, tibdhond commented on app/assets/javascripts/cumulative_timeseries.ts
> +function drawCumulativeTimeSeries(data, metaData, exMap): void {
The function arguments have all been removed in favour of (typed) class variables.
All functions have received an explanation of their purpose.

2021-05-30 20:42 UTC, tibdhond commented on app/assets/javascripts/cumulative_timeseries.ts
> +        .call(d3.axisLeft(y).ticks(5).tickFormat((v: number) => `${100*v}%`));
now using .ticks(5, ".0%"));

2021-05-30 20:42 UTC, tibdhond commented on app/assets/javascripts/cumulative_timeseries.ts
> +    let ticks = d3.timeDay.filter(d=>d3.timeDay.count(metaData["minDate"], d) % 2 === 0);
This line has been removed.
Tick generation is now left to d3 itself.

2021-05-30 20:43 UTC, tibdhond commented on app/assets/javascripts/cumulative_timeseries.ts
> +        .attr("y", tooltipLabel.node().getBBox().height);
Now using 
      .attr("dominant-baseline", "hanging")
to achieve the same result.

2021-05-30 20:44 UTC, tibdhond commented on app/assets/javascripts/cumulative_timeseries.ts
> +    const tooltipDots = graph.selectAll("dots")
This was caused by me not really thinking about what 'selectAll' actually does.
This and similar occurrences have been replaced by sensible selects.

2021-05-30 20:45 UTC, tibdhond commented on app/assets/javascripts/cumulative_timeseries.ts
> +        tooltipI = -1;
Variable has been renamed to tooltipIndex along with a short explanation.
It keeps track of where in the data array the tooltip is located and is used to prevent unnecessary updates.

2021-05-30 20:47 UTC, tibdhond commented on app/assets/javascripts/cumulative_timeseries.ts
> +    tooltipNotFocused();
Function call has been removed.
The settings it affects have been incorporated in the initialization.

2021-05-30 20:49 UTC, tibdhond commented on app/assets/javascripts/cumulative_timeseries.ts
> +        `translate(${width/2 - legend.node().getBBox().width/2},
There are not a whole lot of different options.
One option is to used html elements, but this is difficult to combine with the svg elements.
The option that is used currently is a similar approach, however the offset is now calculated using (a fraction of) the fontsize and the text length (amount of characters).
Not sure if this solution is much better.

2021-05-30 20:54 UTC, tibdhond commented on app/assets/javascripts/cumulative_timeseries.ts
> +    const processor = function (raw): void {
This is how the data fetching also happens in the heatmap and punchcard graphs which I used as a template.
My guess is that it's an inline function so it could easily be called recursively (which seems necessary since the backend can send a 'not yet ready' response).
That being said this has now been split into an 'init' function which takes care of initializing the container (+ setting 'loading' text) and a 'prepareData' function which is essentially the same as the inline function with the difference that it is now a class function.

2021-05-30 21:00 UTC, tibdhond commented on app/assets/javascripts/cumulative_timeseries.ts
> +        metaData["dateRange"] = Math.round(
replaced by `d3.timeDay.count(minDate, maxDate) + 1`

2021-05-30 21:17 UTC, tibdhond commented on app/assets/javascripts/cumulative_timeseries.ts
> +        Object.entries(data).forEach(entry => {
The data is grouped by exercise like this:
{exId: [data_for_exercise]} where '[data_for_exercise]' is always an array.
The numeric adressing is no longer present in the code, but I imagine it was used to unpack `entry` since Object.entries() turns the data into a list of key-value pairs (entry=[exId, <data_for_ex>]). I could resolve this by unpacking entry in the function parameters ([exId, records] => {...}) but this sometimes causes typescript to get angry.

If iterating over the exercises using Object.entries() is a no-go, there are a few other options available, but I'm not quite sure which would be the best one:
1) Iterate using Object.keys() (although this would be essentially the same)
2) Iterate using exOrder, an array containing the exercise id's. In this case a check will have to be added since it's possible that not all the id's in the array are also present in the data
3) Don't call `.to_h` in the backend code which will cause the data to be structured as an array of key-value pairs (I feel like this solution would make the structure of the data more confusing and the code to process it less readable).
4) Don't group the data by exercise (same issue as 3) )

2021-05-30 21:31 UTC, tibdhond commented on app/assets/javascripts/cumulative_timeseries.ts
> +        .style("height", `${height}px`) // prevent shrinking after switching graphs
These lines along with some other non-dynamic style settings have been moved to the visualisations stylesheet.

2021-06-02 08:09 UTC, bmesuere requested changes
This is already a big improvement over the previous round. I would advise that you review your code again while keeping the separation of concerns in mind. Right now, it seems that many of the separate functions could as well  be one large function with the separation being done somewhat arbitrary. I think we want to 
- fetch the data
- process the data
- visualize the data

These 3 parts are not clear from your code. If (but not sure if we want that here) we want to be able to update the data, these parts could be further split into code that's only run once during setup and code that needs to run on every data update.

2021-06-02 12:48 UTC, bmesuere commented on app/javascript/packs/visualisations_series.js
> +function toggleStats(button, seriesId) {
There should be no actual code in the pack files

2021-06-02 12:50 UTC, bmesuere commented on app/javascript/packs/visualisations_series.js
> +    const card = $(`#series-card-${seriesId}`);
We have deprecated the use of jquery so we don't want to add new code that uses it. In this case, you can use getElementById.

2021-06-03 23:15 UTC, tibdhond commented on app/assets/javascripts/cumulative_timeseries.ts
> +    bisect(mx: number): {"date": Date; "i": number} {
this function is now private

2021-06-03 23:16 UTC, tibdhond commented on app/assets/javascripts/cumulative_timeseries.ts
> +    draw(): void {
All functions have been made protected/private.
The function chain (data fetch -> data process -> draw) is now started through the constructor.

2021-06-03 23:17 UTC, tibdhond commented on app/assets/javascripts/cumulative_timeseries.ts
> +    // draws the graph's svg (and other) elements on the screen
Multiple line comments have been replaced with jsdoc comments

2021-06-03 23:20 UTC, tibdhond commented on app/assets/javascripts/cumulative_timeseries.ts
> +    tooltipNotFocused(): void {
The entire setup of the tooltip has been extracted out of the main draw function into two separate functions. `tooltipInit` handles the actual setup (adding the element + setting attributes that never change) and `tooltipDefault` sets attributes that do change in the course of execution. (`tooltipInit` calls `tooltipDefault`). Apart from that, the onMove function has also been extracted to a separate function.

2021-06-03 23:20 UTC, tibdhond commented on app/assets/javascripts/cumulative_timeseries.ts
> +        // tooltip initialisation
see previous comment

2021-06-03 23:22 UTC, tibdhond commented on app/assets/javascripts/cumulative_timeseries.ts
> +        const data = raw["data"] as Record<string, Date[]>;
Fixed names are now being used wherever eslint doesn't complain about it (sometimes happens in certain lambda functions. Explicitly typing in these instances would hurt readability).

2021-06-03 23:23 UTC, tibdhond commented on app/assets/javascripts/cumulative_timeseries.ts
> +        const legend = svg
Moved to `legendInit`

2021-06-04 00:40 UTC, tibdhond commented on app/assets/javascripts/cumulative_timeseries.ts
> +                .then((r: Record<string, unknown>) => this.prepareData(r, url)), 1000);
This part of the code has been extracted to `fetchData`. It has been refactored into a while loop with two awaits:
one to wait for the response and one to wait for a 1 second timeout if a 'not yet ready' response is sent received'.

2021-06-04 00:41 UTC, tibdhond commented on app/assets/javascripts/cumulative_timeseries.ts
> +        this.innerWidth = this.width - this.margin.left - this.margin.right;
moved to draw (can't move height/innerheight to the constructor since it is calculated based on the amount of exercises)

2021-06-04 00:42 UTC, tibdhond commented on app/assets/javascripts/cumulative_timeseries.ts
> +            .reduce((map, [id, name]) => ({ ...map, [id]: name }), {});
This part has been given its own function (in the superclass). It now builds the two variables using a foreach (and a check to see if the exercise is present in the data)

2021-06-04 00:43 UTC, tibdhond commented on app/assets/javascripts/cumulative_timeseries.ts
> +        this.height = 75 * Object.keys(raw.data).length;
moved to draw (see related comment)

2021-06-04 00:44 UTC, tibdhond commented on app/assets/javascripts/cumulative_timeseries.ts
> +        Object.entries(data).forEach(entry => { // parse dates
Since dates seem to get converted to strings after being sent from the backend, this piece of code converts them to Javascript Date objects.
This part has been slightly rewritten (unpacked the entry variable) and a slightly longer explanation is given.

2021-06-04 00:45 UTC, tibdhond commented on app/assets/javascripts/cumulative_timeseries.ts
> +        this.maxSum = raw["students"] ? raw["students"] as number : 0; // max value
done

2021-06-04 00:45 UTC, tibdhond commented on app/javascript/packs/visualisations_series.js
> +function toggleStats(button, seriesId) {
moved to visualisations_series.js in assest/javascript

2021-06-04 00:46 UTC, tibdhond commented on app/javascript/packs/visualisations_series.js
> +    const card = $(`#series-card-${seriesId}`);
All usage of jQuerry has been replaced with plain javascript alternatives.

2021-06-09 15:26 UTC, bmesuere requested changes
I still have the feeling there is something not ok with your data internal data representation. As I said before, the code is littered with `Object.entries` calls with is a red flag that these entries should be save as an array in the first place. In addition, I see a lot of magic numbers like `d[0]` to access the first property of a list of properties which indicates that these probably should have been objects insteads of arrays.

A specific example of that is in your legend function where you create an `exPosition` array containing `[ex, pos]` arrays. If you would add objects like `{exerciseId: ex, position: pos}` instead, the resulting code would become a lot more readable.

2021-06-09 15:26 UTC, bmesuere commented on app/assets/javascripts/cumulative_timeseries.ts
> +        const last = this.dateArray.length-1;
```suggestion
        const last = this.dateArray.length - 1;
        const date = this.dateArray[last];
```

2021-06-09 15:26 UTC, bmesuere commented on app/assets/javascripts/cumulative_timeseries.ts
> +                d => `${Math.round(d[1][last][1]/this.maxSum*10000)/100}%`
Use d3 format instead of round, *10000 and /100 %

2021-06-09 15:26 UTC, bmesuere commented on app/assets/javascripts/cumulative_timeseries.ts
> +            5 > this.innerWidth;
indentation and spaces

2021-06-09 15:26 UTC, bmesuere commented on app/assets/javascripts/cumulative_timeseries.ts
> +                    d => `${Math.round(d[1][i][1]/this.maxSum*10000)/100}%
use format function

2021-06-09 15:26 UTC, bmesuere commented on app/assets/javascripts/cumulative_timeseries.ts
> +        });
I'm not sure without trying, but you can probably write `this.svg.on("mouseleave", this.tooltipDefault);`

2021-06-09 15:26 UTC, bmesuere commented on app/assets/javascripts/cumulative_timeseries.ts
> +        // -----------------------------------------------------------------------------------------
```suggestion
        this.tooltipInit();
        this.legendInit();
```

2021-06-09 15:26 UTC, bmesuere commented on app/assets/javascripts/cumulative_timeseries.ts
> +                "translate(" + this.margin.left + "," + this.margin.top + ")");
use template string

2021-06-09 15:26 UTC, bmesuere commented on app/assets/javascripts/cumulative_timeseries.ts
> +
```suggestion
```

2021-06-09 15:26 UTC, bmesuere commented on app/assets/javascripts/cumulative_timeseries.ts
> +
```suggestion
```

2021-06-14 21:27 UTC, tibdhond commented
(Input) data structure has been changed from {<exId>: <exData>} to {exId: <exId>, exData: <exData>}[];
As a result all Object.entries(), Object.keys() and Object.values() calls have been removed.

A similar treatment has been given to the processed data.
As a result of this most (if not all) magic numbers have been replaced with named properties.

This was also applied to the legend functions.

2021-06-14 21:32 UTC, tibdhond commented on db/schema.rb
> +  create_table "score_items", charset: "utf8mb4", force: :cascade do |t|
removed

2021-06-14 22:09 UTC, tibdhond commented on app/assets/javascripts/cumulative_timeseries.ts
> +    protected readonly baseUrl = "/nl/stats/cumulative_timeseries?series_id=";
fixed

2021-06-14 22:09 UTC, tibdhond commented on app/assets/javascripts/cumulative_timeseries.ts
> +    protected draw(): void {
added

2021-06-14 22:16 UTC, tibdhond commented on app/assets/javascripts/cumulative_timeseries.ts
> +     */
implemented this change

2021-06-14 22:17 UTC, tibdhond commented on app/assets/javascripts/cumulative_timeseries.ts
> +        raw: {data: Record<string, unknown>, exercises: [number, string][], students?: number}
created type 'RawData' (defined in superclass file) and destructured the input data

2021-06-14 22:21 UTC, tibdhond commented on app/assets/javascripts/cumulative_timeseries.ts
> +                        .ticks(d3.timeDay)
moved outside of the loop

2021-06-14 22:33 UTC, tibdhond commented on app/assets/javascripts/cumulative_timeseries.ts
> +    protected draw(): void {
looks like lgtm  can't handle the override keyword yet, so it's giving errors

2021-06-14 22:43 UTC, tibdhond commented on app/assets/javascripts/cumulative_timeseries.ts
> +        const maxDate = new Date(d3.max(Object.values(data), records => d3.max(records)));
done

2021-06-14 22:45 UTC, tibdhond commented on app/assets/javascripts/cumulative_timeseries.ts
> +     * determine where to put tooltip line by 'injecting' the cursor position in the date array
implemented this change

2021-06-14 22:47 UTC, tibdhond commented on app/assets/javascripts/cumulative_timeseries.ts
> +        const last = this.dateArray.length-1;
implemented this change

2021-06-14 22:55 UTC, tibdhond commented on app/assets/javascripts/cumulative_timeseries.ts
> +                d => `${Math.round(d[1][last][1]/this.maxSum*10000)/100}%`
this and similar instances have been replaced with format

2021-06-14 22:56 UTC, tibdhond commented on app/assets/javascripts/cumulative_timeseries.ts
> +                    d => `${Math.round(d[1][i][1]/this.maxSum*10000)/100}%
replaced with format

2021-06-14 22:56 UTC, tibdhond commented on app/assets/javascripts/cumulative_timeseries.ts
> +            5 > this.innerWidth;
indented

2021-06-14 22:58 UTC, tibdhond commented on app/assets/javascripts/cumulative_timeseries.ts
> +        });
Using this method, the 'this' keyword is rebound the source of the event, causing class variables to become inaccessible.
So unless there's a way to prevent this, feeding the function directly is not an option.

2021-06-14 22:58 UTC, tibdhond commented on app/assets/javascripts/cumulative_timeseries.ts
> +        // -----------------------------------------------------------------------------------------
implemented this change

2021-06-14 22:59 UTC, tibdhond commented on app/assets/javascripts/cumulative_timeseries.ts
> +                "translate(" + this.margin.left + "," + this.margin.top + ")");
now using template string

2021-06-14 23:03 UTC, tibdhond commented on app/assets/javascripts/cumulative_timeseries.ts
> +
removed

2021-06-14 23:03 UTC, tibdhond commented on app/assets/javascripts/cumulative_timeseries.ts
> +
removed

2021-06-20 11:56 UTC, bmesuere requested changes
The last update significantly improved the readability of the code 👍 

I would mode the newly added js files to a separate subdirectory.

In addition to the comments I left, a next step is adding tests. I think we want unit tests for both the JS (using jest) and rails part + some integration tests (see the "system" tests).

@chvp Do you have some time to go over the rails code or are you still busy grading exams?

2021-06-20 11:56 UTC, bmesuere commented on app/assets/javascripts/series_graph.ts
> +            .then((r: RawData) => {
Prefer await here over the `then`

2021-06-20 11:56 UTC, bmesuere commented on app/assets/javascripts/series_graph.ts
> +                d3.select(`${this.selector} *`).remove();
This is strange, can't you reset the html instead of using a wildcard selector?

2021-06-20 11:56 UTC, bmesuere commented on app/assets/javascripts/series_graph.ts
> +                if (Object.keys(r.data).length === 0) {
Isn't there a more explicit way to check this? The length of the keys of a sub object seems a bit strange.

2021-06-20 11:56 UTC, bmesuere commented on app/assets/javascripts/stacked_status.ts
> +        });
```suggestion
        this.statusOrder.forEach(status => {
            statePosition.push({ status, pos });
            // rect size (15) + 5 padding + 20 inter-group padding + text length
            pos += 40 + this.fontSize/2*status.length;
        });
```

2021-06-20 11:56 UTC, bmesuere commented on app/assets/javascripts/stacked_status.ts
> +                .text(`${t}`)
?

2021-06-20 11:56 UTC, bmesuere commented on app/assets/javascripts/visualisation_series.js
> +    if (getComputedStyle(tabs).display == "none") {
do these style changes using css in combination with an "active" class or something like that

2021-06-20 11:56 UTC, bmesuere commented on app/assets/javascripts/visualisation_series.js
> +    if (!activeNode.className.match(/^(.* )?active( .*)?$/)) {
use classList instead of a regex

2021-06-20 11:56 UTC, bmesuere commented on app/assets/javascripts/visualisation_series.js
> +            element.className = element.className.replace(" active", "");
Again, classList is a better choice.

You should probably go over the code in this file and refactor things a bit.

2021-06-20 11:56 UTC, bmesuere commented on app/assets/stylesheets/components/card.css.scss
> +.card-subtitle-actions > * {
Not a fan of the wildcard selector in css (but I do agree that it's less bad in combination with the child seletor), try to be more specific is possible.

2021-06-20 11:56 UTC, bmesuere commented on app/helpers/series_helper.rb
> +  def embedded_svg(filename, options = {})
Add documentation. I think it inlines svg?

2021-06-20 13:07 UTC, chvp requested changes

2021-06-20 13:07 UTC, chvp commented on app/views/series/_series.html.erb
> +  <% if current_user&.course_admin?(series.course) || true %>
Same here.

2021-06-20 13:07 UTC, chvp commented on app/views/series/_series.html.erb
> +          <%= embedded_svg("stacked-bar-chart.svg", {class: "mdi svg-icon-btn rotate"}) %>
You can just edit the SVG instead of adding classes like this.

2021-06-20 13:07 UTC, chvp commented on config/routes.rb
> +  # mount ActionCable.server => '/cable'
Refrain from adding unnecessary whitespace changes.

2021-06-20 13:07 UTC, chvp commented on test/models/submission_test.rb
> +    course = create :course
At least make sure that there are some actual submissions in the course/series.

2021-06-20 13:07 UTC, chvp commented on app/assets/stylesheets/models/series.css.scss
> +}
```suggestion
button:hover .svg-icon-btn {
  fill: $text-color;
}
```

2021-06-21 15:04 UTC, rien commented on app/helpers/series_helper.rb
> +  def embedded_svg(filename, options = {})
I think you're referring to the `custom_icon` function in the application helper:
https://github.com/dodona-edu/dodona/blob/ab867e9336a6cc32b994467ddb4aa4ed273b111e/app/helpers/application_helper.rb#L2
Which is able to render SVG's partials placed in [app/views/application/icons/](https://github.com/dodona-edu/dodona/tree/develop/app/views/application/icons).

It also seems simpler and more efficient to use rails' `render partial:` functionality (and pass the `class` as a parameter) instead of reading and parsing a file using Nokogiri (in the past, starting the Nokogiri parser had a very big performance impact).

2021-06-26 17:47 UTC, tibdhond commented on app/assets/javascripts/cumulative_timeseries.ts
> +        this.data.forEach(ex => {
Now using destructuring for this and similar instances.

2021-06-26 17:49 UTC, tibdhond commented on app/assets/javascripts/cumulative_timeseries.ts
> +        let [minDate, maxDate] = d3.extent(data.map(ex => ex.exData).flat()) as Date[];
map(...).flat() has been replaced with flatMap.
However since flatMap seems to be an ES10 addition (while the project lib is set to ES7), the editor will complain about this.

2021-06-26 17:50 UTC, tibdhond commented on app/assets/javascripts/series_graph.ts
> +            .then((r: RawData) => {
'then' replaced by 'await'.
Because of this change, the _init()_ function is now async.

2021-06-26 17:51 UTC, tibdhond commented on app/assets/javascripts/series_graph.ts
> +                d3.select(`${this.selector} *`).remove();
Replaced by `this.container.html("")`

2021-06-26 17:53 UTC, tibdhond commented on app/assets/javascripts/series_graph.ts
> +                if (Object.keys(r.data).length === 0) {
This is something I had forgotten to change after restructuring the data.
Since r.data is an array now this has been replaced by `r.data.length === 0`

2021-06-26 18:04 UTC, tibdhond commented on app/assets/javascripts/stacked_status.ts
> +        });
s replaced by status

2021-06-26 18:06 UTC, tibdhond commented on app/assets/javascripts/stacked_status.ts
> +                .text(`${t}`)
I assume this is about the `${t}`. This is likely a remnant from when this element contained more text.
It has now been changed to be inline.

2021-06-26 18:14 UTC, tibdhond commented on app/assets/javascripts/visualisation_series.js
> +    if (!activeNode.className.match(/^(.* )?active( .*)?$/)) {
Now using `activeNode.classList.contains("active")`

2021-06-26 18:33 UTC, tibdhond commented on app/assets/javascripts/visualisation_series.js
> +    if (getComputedStyle(tabs).display == "none") {
The series card can now receive a new class _stats-active_ which controls whether the visualization related things are shown or not.
As a result these manual style changes have been removed.

2021-06-26 19:44 UTC, tibdhond commented on app/assets/javascripts/visualisation_series.js
> +            element.className = element.className.replace(" active", "");
After a refactor the uses of 'className' have been replaced with 'classList'.
The manual css changes have also been replaced.

2021-06-26 19:48 UTC, tibdhond commented on app/assets/stylesheets/components/card.css.scss
> +.card-subtitle-actions > * {
moved to `.card-subtitle-action a {}`

2021-06-26 20:09 UTC, tibdhond commented on app/helpers/series_helper.rb
> +  def embedded_svg(filename, options = {})
I had been looking for this kind of function, but wasn't able to find it.

The svg icons are now using `custom icon` to be rendered and `embedded_svg` has been removed.
Because of this, the svg files themselves have been moved to app/views/application/icons and renamed to use the .html.erb extention.

2021-06-26 20:16 UTC, tibdhond commented on app/controllers/statistics_controller.rb
> +    # authorize course
Authorization now done on series. Corresponding checks have been moved from _course_policy_ to _series_policy_

2021-06-26 20:26 UTC, tibdhond commented on app/controllers/statistics_controller.rb
> +      ex_data = series.exercises.map { |ex| [ex.id, lan == 'nl' ? ex.name_nl : ex.name_en] }
Didn't know Activity.name was a thing.
Replaced the map with `map {  |ex| [ex.id, ex.name] }` and removed the locale line.

2021-06-26 20:43 UTC, tibdhond commented on app/controllers/statistics_controller.rb
> +      data = result[:value].map { |k, v| { exId: k, exData: v } }
now using snake case

2021-06-26 21:08 UTC, tibdhond commented on app/controllers/statistics_controller.rb
> +  end
All duplicate code has been moved to `series_visualisation` which uses Ruby's `send()` method to call the right function.
The old functions now simply call this function with the right method name (to use with send).

2021-06-26 21:12 UTC, tibdhond commented on app/models/submission.rb
> +  scope :in_time_range, ->(start_date, end_date) { where('submissions.created_at >= ? AND submissions.created_at <= ?', start_date.to_date, end_date.to_date) }
This seems to work on the test data. I'll try testing it on Naos as well later.

2021-06-26 21:17 UTC, tibdhond commented on app/models/submission.rb
> +  scope :only_students, ->(course) { where.not(user: CourseMembership.where(course_id: course.id).where(status: 'course_admin').map(&:user)) }
I assume the `.not` would have to be removed as well?
The scope has been changed to { where(user: course.enrolled_members) }

2021-06-26 21:21 UTC, tibdhond commented on app/views/pages/_test.html.erb
> +<% end %>
removed

2021-06-26 21:38 UTC, tibdhond commented on app/models/submission.rb
> +  def self.violin_matrix(options = {}, base = { until: 0, value: {} })
The _base_ and _in_batches_ parts have been removed, simplifying most the methods quite a bit.

2021-06-26 21:48 UTC, tibdhond commented on app/views/series/_series.html.erb
> +      <% if current_user&.course_admin?(series.course) || true %>
Replaced with the `statistics?` series policy.
The true check has also been moved to there.
The commented authorize has been re-enabled.

2021-06-26 21:48 UTC, tibdhond commented on app/views/series/_series.html.erb
> +  <% if current_user&.course_admin?(series.course) || true %>
also replaced here

2021-06-26 21:49 UTC, tibdhond commented on app/views/series/_series.html.erb
> +          <%= embedded_svg("stacked-bar-chart.svg", {class: "mdi svg-icon-btn rotate"}) %>
As in edit the files directly/manually?
Wouldn't this break the darkmode/lightmode colours?

2021-06-26 21:51 UTC, tibdhond commented on config/routes.rb
> +  # mount ActionCable.server => '/cable'
reverted.

2021-06-26 21:52 UTC, tibdhond commented on app/assets/stylesheets/models/series.css.scss
> +}
implemented this change

2021-06-27 19:07 UTC, tibdhond commented on test/models/submission_test.rb
> +    course = create :course
Tests have been rewritten and now actually test if the data transformation is done correctly.

2021-08-16 15:50 UTC, bmesuere commented
After running locally, some todo's
- [ ] replace "indieningen" by "ingediende oplossingen" or "oplossingen"
- [ ] violin: "aantal indieningen" title looks very similar to Exercise names, maybe move it to the bottom of the axis
- [ ] violin: get rid of border around right statistics, don't repeat "gemiddelde indieningen", larger number, possibly only use  1 decimal
- [ ] violin: tooltip text is not readable in light mode in chrome
- [ ] violin: should dot show average?
- [ ] bar: categories not translated
- [ ] bar: right numbers see violin + problem with font rendering
- [ ] grid: uses different left margin than violin

2021-08-19 09:22 UTC, bmesuere commented
After testing on naos, I found these issues:

- [ ] height is too low for series with 1 exercise (should add top and bottom padding)
- [ ] put tooltip titles in bold
- [ ] heatmap: x-axis becomes unreadable + block spacing is not ok. Be cleverer with the bins?
- [ ] heatmap: sometimes gives server error
- [ ] line graph: should start from 0
- [ ] linen graph: labels are hard to read

2021-08-21 13:16 UTC, pdawyndt commented
- violin chart
  - [ ] cutoff at 20 masks too much for exerises in series 06-10 (with average number of submissions close to 20; sometimes average even goes above 20 and then the white dot is to the right of the 20-mark)
  - [ ] maybe average/standard deviation could be used to choose a smarter upper limit (never below 20 seems good choice)
- status distribution chart
  - [ ] maybe add option to restrict to latest submission to see what status most students are in currently if we look at the chart at a snapshot while students are working on the exercises (we're now looking mostly at the charts post factum)
  - [ ] total number of submissions is lower than number of students that solved the exercise (presumable bug)
- line chart showing users with at least one correct solution
  - [ ] legend is much clearer now
  - [ ] maybe make legend background slightly transparant
  - [ ] maybe add names of exercises to legend
  - [ ] maybe sort exercises in legend according to position of data points
  - [ ] aligning 100% with all course users is not relevant for evaluations/exams; maybe add setting to switch to users that submitted at least one solution for one of the exercises
  - [ ] dates should contain year (at least if not current year)

2021-08-21 16:50 UTC, chvp requested changes
The issue in #2999 should be fixed before this is merged. (Just noting this here so we don't forget.)

2021-08-22 08:28 UTC, bmesuere commented
> * violin chart
>   
>   * cutoff at 20 masks too much for exerises in series 06-10 (with average number of submissions close to 20; sometimes average even goes above 20 and then the white dot is to the right of the 20-mark)

The value is parameterized. I set it to 20 start but can easily be changed.

>   * maybe average/standard deviation could be used to choose a smarter upper limit (never below 20 seems good choice)

I preferred using the same value for all series so they could be compared.

> * status distribution chart
>   * maybe add option to restrict to latest submission to see what status most students are in currently if we look at the chart at a snapshot while students are working on the exercises (we're now looking mostly at the charts post factum)

This is not the goal of the graph. Another "live scoreboard" would be more useful for this.

>   * total number of submissions is lower than number of students that solved the exercise (presumable bug)

Potentially, only submissions before the deadline are taken into account.

> * line chart showing users with at least one correct solution
>   
>   * maybe make legend background slightly transparent

This is set to 90% opacity like the other tooltips

>   * maybe add names of exercises to legend

They are potentially very long so this always looks bad

>   * maybe sort exercises in legend according to position of data points

I explicitly used the exercise order here. This way, you know which percentage maps to which exercise (first, second, third, etc) without having to look at the legend.

>   * aligning 100% with all course users is not relevant for evaluations/exams; maybe add setting to switch to users that submitted at least one solution for one of the exercises

Planned for a next version.

>   * dates should contain year (at least if not current year)

Not sure if relevant. These graphs are only useful for synchronous courses with deadlines in which case you know the year or it doesn't add anything useful.

2021-08-22 13:51 UTC, bmesuere commented
> The issue in #2999 should be fixed before this is merged. (Just noting this here so we don't forget.)

This was fixed. The cause was a double Bootstrap JS import.

2021-08-23 15:06 UTC, chvp approved these changes

2021-08-23 15:06 UTC, chvp commented on config/routes.rb
> +
```suggestion
```

2021-08-23 16:53 UTC, bmesuere requested changes

2021-08-23 16:53 UTC, bmesuere commented on app/assets/stylesheets/components.css.scss
>  @import "components/code_listing.css";
```suggestion
```

2021-08-23 16:53 UTC, bmesuere commented on app/controllers/statistics_controller.rb
> +  def series_visualisation(visualisation)
This should be moved to the private section and renamed to `visualize_series`

2021-08-23 16:53 UTC, bmesuere commented on app/controllers/statistics_controller.rb
> +    authorize series
```suggestion
    series = Series.find(params[:series_id]) if params.key?(:series_id)
    authorize series

    course = series.course
```

2021-08-23 16:53 UTC, bmesuere commented on app/controllers/statistics_controller.rb
> +      render json: { data: data, exercises: ex_data, students: course.enrolled_members.length }
`students` seems a strange name if it is only the count (where exercises does contain actual exercise data)

2021-08-23 16:53 UTC, bmesuere commented on app/models/submission.rb
> +  scope :only_students, ->(course) { where(user: course.enrolled_members) }
`from_students`?

2021-08-23 16:53 UTC, bmesuere commented on app/models/submission.rb
> +    Submission.unscoped.joins <<~HEREDOC
@chvp do we have other joins with heredoc like this in our code? 

Does `least_recent` mean something else than oldest?

This is only used in `first_correct_per_ex_per_user` which is also a bit odd for a scope and is only used once. Maybe this code can be inlined in cumulative time series function.

2021-08-23 16:53 UTC, bmesuere commented on app/models/submission.rb
> +    end
```suggestion
    submissions = submissions.where(id: (latest + 1)..) if latest > 0
    return submissions
```

2021-08-23 16:53 UTC, bmesuere commented on app/models/submission.rb
> +            .group_by { |k, _| k[0] } # group by exercise (key: ex_id, value: [[ex_id, u_id], count])
These and other functions here are hard to read because of the `k`'s, `v`'s and `x'es.

2021-08-23 17:52 UTC, chvp commented on app/models/submission.rb
> +    Submission.unscoped.joins <<~HEREDOC
Yes, `most_recent` is defined a few lines above. Could be inlined I guess, but that would add complexity to that function. Keeping the complexity separate seems better to me.

No opinion on naming, but I do like the consistency with `most_recent`.

2021-08-23 17:52 UTC, chvp commented on app/models/submission.rb
> +  scope :only_students, ->(course) { where(user: course.enrolled_members) }
Sounds good to me.

2021-08-24 12:44 UTC, niknetniko reviewed
- When there is no data, the last graph is a bit weird:
![image](https://user-images.githubusercontent.com/1756811/130618212-37880b96-60e2-446d-a956-aa2cc4351eba.png)
- I would maybe add the short description as a tooltip to the buttons as well

2021-08-24 12:44 UTC, niknetniko commented on config/locales/js/en.yml
> +    violin_desc: This graph shows the distribution of the number of submissions.The larger the zone, the more students submitted that number of solutions.
```suggestion
    violin_desc: This graph shows the distribution of the number of submissions. The larger the zone, the more students submitted that number of solutions.
```

2021-08-24 13:44 UTC, bmesuere approved these changes

2021-08-24 14:10 UTC, niknetniko approved these changes

2021-08-24 14:13 UTC, merged