Create request system for teacher rights
dodona-edu/dodona pull request #2640
Opened 2021-04-24 20:33 UTC by chvp

Still needs tests, documentation update and email system.

- [ ] Tests were added
- [ ] Documentation update can be found at dodona-edu/dodona-edu.github.io#

Closes #2599.

2021-04-25 14:09 UTC, chvp commented
User edit page:
![screenshot_2021-04-25-155732](https://user-images.githubusercontent.com/42220376/115996591-3081c380-a5e0-11eb-8fae-c8dca9349f18.png)

Callout on contact page:
![screenshot_2021-04-25-155740](https://user-images.githubusercontent.com/42220376/115996592-311a5a00-a5e0-11eb-9623-f3a1b3dcad59.png)

Request page:
![screenshot_2021-04-25-160011](https://user-images.githubusercontent.com/42220376/115996594-31b2f080-a5e0-11eb-9753-8f145f2def21.png)

Email sent to admins:
![screenshot_2021-04-25-160042](https://user-images.githubusercontent.com/42220376/115996595-31b2f080-a5e0-11eb-9920-895a74114b43.png)

Overview for admins:
![screenshot_2021-04-25-160105](https://user-images.githubusercontent.com/42220376/115996596-324b8700-a5e0-11eb-91e1-5cc18e003960.png)

Email sent after approval:
![screenshot_2021-04-25-160115](https://user-images.githubusercontent.com/42220376/115996598-32e41d80-a5e0-11eb-8c77-4c114a659f4c.png)

Request page if institution not new:
![screenshot_2021-04-25-160141](https://user-images.githubusercontent.com/42220376/115996599-337cb400-a5e0-11eb-933a-8181990b213f.png)

Overview if no institution given:
![screenshot_2021-04-25-160502](https://user-images.githubusercontent.com/42220376/115996600-34154a80-a5e0-11eb-8a04-b7cd6c99a796.png)

Overview if no institution given but institution has generated name:
![screenshot_2021-04-25-160850](https://user-images.githubusercontent.com/42220376/115996688-98d0a500-a5e0-11eb-925b-cd592206d372.png)

2021-04-25 15:01 UTC, bmesuere requested changes
Good job 👍 This will definitely make (y)our life easier.

2021-04-25 15:01 UTC, bmesuere commented on config/routes.rb
> +    resources :rights_requests, only: %i[index new create] do
edit and show aren't listed here, so those views can be removed?

2021-04-25 15:17 UTC, chvp commented on config/routes.rb
> +    resources :rights_requests, only: %i[index new create] do
Yup, auto-generated by rails, and forgot about the views...

2021-04-25 16:01 UTC, bmesuere requested changes
👍 Tested this on mestra and everything seemed to work as expected (except for emails of course). 2 small suggestions for the form.

2021-04-25 16:25 UTC, chvp commented
Note to self: alsof check that user is staff in happy path test.

2021-04-25 20:01 UTC, chvp commented
Updated form:
![screenshot_2021-04-25-220108](https://user-images.githubusercontent.com/42220376/116007792-c41fb800-a611-11eb-9857-4b489b9ac888.png)

2021-04-25 20:06 UTC, bmesuere approved these changes

2021-04-26 07:43 UTC, niknetniko commented on app/mailers/approved.nl.text.erb
> +Als je verdere vragen hebt mag je ons altijd via dodona@ugent.be contacteren.
Should this e-mail be hardcoded, or could we use the config value? (same in the other languages/mails)

2021-04-26 07:43 UTC, niknetniko commented on app/views/pages/contact.html.erb
> +        <% if current_user&.student? && current_user&.institution.present? %>
We should probably also disable this button if the user already made a request, since the page is inaccessible in that case (or replace the button with "Your request for teacher rights is pending" or something).

It's also not entirely clear to me why do a check on the institution here, but not in the policy.

2021-04-26 07:43 UTC, niknetniko commented on config/locales/models/nl.yml
> +      rights_request: Lesgeversrechten aanvraag
```suggestion
      rights_request: Aanvraag voor lesgeversrechten
```

2021-04-26 08:18 UTC, chvp commented
Disabled button on user profile if request in progress:
![screenshot_2021-04-26-101548](https://user-images.githubusercontent.com/42220376/116051250-aafe2200-a678-11eb-93cb-55537b401308.png)
![screenshot_2021-04-26-101556](https://user-images.githubusercontent.com/42220376/116051253-ab96b880-a678-11eb-95a4-188a34e2d6d6.png)

2021-04-26 08:22 UTC, niknetniko approved these changes

2021-04-26 08:27 UTC, merged