Migrate to Bootstrap 5
dodona-edu/dodona pull request #2700
Opened 2021-05-10 08:37 UTC by bmesuere

This pull request migrates our UI framework to Bootstrap 5.

- [ ] Remove vendored Bootstrap 3
- [ ] Migrate from less to sass for the remaining files and compile assets without errors
- [ ] Add Bootstrap 5 as a dependency and load the code
- [ ] Tweak obvious var name changes and reenable mixins
- [ ] Check if we want to keep the new bootstrap scaling
- [ ] Follow the migration guide for 3 -> 4 and update views
- [ ] Follow the migration guide from 4 -> 5 and update views
- [ ] Check and update all remaining views

A previous analysis of why we made this change can be found in #2692

2021-05-14 17:27 UTC, bmesuere commented
This is ready for review with 2 issues remaining:
- scrollspy is broken on the course page: I will make a last attempt, but switching to a small dedicated library might also be an option
- dark mode is broken: The trick of using string interpolation to import the right file doesn't work with sass. I'll think about a better solution, but worst case we will have to copy the "base" file into both the dark and light theme file. I also didn't test the dark mode colors yet.

2021-05-16 12:30 UTC, bmesuere commented
Dark mode was fixed and a solution for the scrollspy issue can be found in #2718.

2021-05-17 09:36 UTC, niknetniko reviewed
Things I noticed (most of which are very minor and non blocking) when checking the pages (I haven't looked at any code yet):

- [ ] Deprecation warnings in the dark theme (repeated a few times):

```
DEPRECATION WARNING on line 18 of /home/niko/projects/dodona/app/assets/stylesheets/theme/theme-dark.css.scss:
!global assignments won't be able to declare new variables in future versions.
Consider adding `$brand-primary: null` at the top level.
```
- [x] There is no indication that a field is a dropdown in Chrome (e.g. the course edit page):
![image](https://user-images.githubusercontent.com/1756811/118462598-221a5980-b6ff-11eb-8ddf-048b2c656486.png)
- [ ] The question checkbox is no longer aligned (course edit page)
![image](https://user-images.githubusercontent.com/1756811/118462715-45450900-b6ff-11eb-8627-95d1a804d924.png)
- [ ] Buttons are no longer aligned with edit field (course edit page, but also e.g. profile page, scores are fine though)
![image](https://user-images.githubusercontent.com/1756811/118462820-5f7ee700-b6ff-11eb-9348-b6e14e50bc1f.png)
- [ ] Edit labels modal is messy:
![image](https://user-images.githubusercontent.com/1756811/118463070-a240bf00-b6ff-11eb-9497-a6b45df8539b.png)
- [ ] Images in descriptions are different (not aligned, caption is always shown), e.g. the curling exercise (compare with https://dodona.ugent.be/nl/activities/2051796188/):
![image](https://user-images.githubusercontent.com/1756811/118463471-14190880-b700-11eb-9a34-da5ef7a1ca73.png)
- [ ] Code blocks have no more background (same exercise):
![image](https://user-images.githubusercontent.com/1756811/118463577-327f0400-b700-11eb-808e-dfb49a6607b2.png)
- [ ] Evaluation status table is weird
![image](https://user-images.githubusercontent.com/1756811/118463859-87227f00-b700-11eb-94f7-b99b48a1d347.png)
- [x] Clicking grade table tab does not remove underline from evaluation status tab (this does work in production and in other places):
![image](https://user-images.githubusercontent.com/1756811/118464052-b933e100-b700-11eb-86f6-8bb42c3639a3.png)
- [ ] The sidebar is not wide enough:
![image](https://user-images.githubusercontent.com/1756811/118464411-1d56a500-b701-11eb-99fd-b7c34bd325ea.png)
- [ ] Programming language icon is not aligned correctly on programming language edit page:
![image](https://user-images.githubusercontent.com/1756811/118464521-4119eb00-b701-11eb-9b54-b96af279c509.png)
- [ ] This is ugly in dark mode (course edit page):
![image](https://user-images.githubusercontent.com/1756811/118465168-ea60e100-b701-11eb-8a35-2ffd2d3daf99.png)
- [ ] accordions seem broken, the styling and functionality (can't click them), (e.g. in the course description, but also in exercise descriptions):
![image](https://user-images.githubusercontent.com/1756811/118465367-1aa87f80-b702-11eb-8166-ab633f434808.png)
- [ ] Repository page has wrong alignments:
![image](https://user-images.githubusercontent.com/1756811/118466264-f8fbc800-b702-11eb-9eab-917953475b09.png)

2021-05-17 10:05 UTC, chvp commented
Only thing I found that Niko didn't:
![screenshot_2021-05-17-115653](https://user-images.githubusercontent.com/42220376/118471498-1bdcab00-b708-11eb-9ed1-9d1d53ed944f.png)

2021-05-17 10:35 UTC, chvp reviewed
Forgot to do an actual review that can be re-requested, sorry for the spam.

2021-05-17 18:38 UTC, bmesuere commented
- deprecation warning can be ignored because these variables are all defined at a higher level. The !global must be added to escape scoping.
- button alignment is due to default browser font size and bootstrap 5 using rem. We probably want this set to 14px in a future PR.
- sidebar: I didn't change the width, was 240px previously as well. Maybe this also has something to do with your font size? In chrome the overflow ... is applied correctly
- accordions: I fixed the styling (an accordion must have an accordion id), but to make them work, the data attributes need to be changed from data-toggle and data-parent to data-bs-toggle and data-bs-parent. No idea how to proceed here. Run a regex on all course, series and exercise descriptions?

2021-05-18 08:58 UTC, niknetniko requested changes
For non-Python exercises, there is some padding between the status color bar and the other stuff:

![image](https://user-images.githubusercontent.com/1756811/118620974-43924880-b7c6-11eb-922e-909e0b10ec74.png)

2021-05-18 08:58 UTC, niknetniko commented on app/assets/stylesheets/application-dark.css.scss.erb
> +  $development: false;
Should this be `false`?

2021-05-18 08:58 UTC, niknetniko commented on app/assets/stylesheets/application.css.scss.erb
> +  $development: false;
Same here, should this be `false`?

2021-05-18 08:58 UTC, niknetniko commented on app/assets/stylesheets/components/link.css.scss
> +  //height: 1px;
Are these needed?

2021-05-18 13:11 UTC, bmesuere commented on app/assets/stylesheets/application-dark.css.scss.erb
> +  $development: false;
This was set to false for the moment (and maybe the next few weeks) to be able to estimate the effects of the css changes on the "production colors" on naos, mestra and localhost.

2021-05-18 13:14 UTC, niknetniko commented on app/assets/stylesheets/application-dark.css.scss.erb
> +  $development: false;
Makes sense

2021-05-18 19:12 UTC, bmesuere commented
> For non-Python exercises, there is some padding between the status color bar and the other stuff:
> 
> ![image](https://user-images.githubusercontent.com/1756811/118620974-43924880-b7c6-11eb-922e-909e0b10ec74.png)

This is now fixed and deployed on naos.

2021-05-18 20:21 UTC, niknetniko requested changes
While checking on naos, I've noticed two more things:

- The next/previous on reading exercises are now all the way to the left and to the right:
![image](https://user-images.githubusercontent.com/1756811/118717603-900d7080-b826-11eb-9237-4cd70ce6df9c.png)
- The editor (or mark as read) is now always below the page visibility, so you always need to scroll, even if the exercise description is not longer than one page (example https://naos.ugent.be/nl/courses/61/series/645/activities/126856420/ and https://naos.ugent.be/nl/courses/61/series/645/activities/615906596/):
![image](https://user-images.githubusercontent.com/1756811/118717862-e4185500-b826-11eb-8ff3-ec21455f02aa.png)
(screenshot is a bit difficult to make)
This seems to be a consequence of the `height` being set on the `.activity-sidebar .nav`.

2021-05-19 09:36 UTC, niknetniko requested changes
The fix for the sidebar height breaks the stickyness of the sidebar for me.

Some poking around in Chrome suggests this could be fixed by adding something like this to `.activity-sidebar, .series-sidebar` (unless another fix is beter of course):

```scss
position: sticky;
top: $navbar-height + 20px;
```

2021-05-19 09:59 UTC, niknetniko approved these changes

2021-05-19 10:00 UTC, merged