Upgrade checboxes and radios to bootstrap 5
dodona-edu/dodona pull request #2843
Opened 2021-06-10 15:08 UTC by bmesuere

This pull request introduces bootstrap 5 styling for checkboxes and radio buttons. This results in a uniform experience on all platforms. In addition, it enables the use of toggle switches where checkboxes were previously used to enable things.

**Before**
![image](https://user-images.githubusercontent.com/481872/121549441-268c1680-ca0e-11eb-98c5-7ec89317fde9.png)
![image](https://user-images.githubusercontent.com/481872/121549519-39065000-ca0e-11eb-8eb4-87b0e7d0ba7f.png)

**After**
![image](https://user-images.githubusercontent.com/481872/121549650-563b1e80-ca0e-11eb-8d54-c473d2e6df1a.png)
![image](https://user-images.githubusercontent.com/481872/121549789-74088380-ca0e-11eb-9ccc-0d9d643ff4ab.png)

2021-06-11 06:52 UTC, niknetniko approved these changes

2021-06-11 06:52 UTC, niknetniko commented on app/views/courses/_form.html.erb
> +        <div class="form-check <%= "form-switch" unless course.new_record? %>">
Should this be a switch? The reason I'm not 100% sure here is that in most places, the switch is immediate, while here the form has to be saved (and I'm not entirely sure why it's only a switch when it's not a new course).

The md spec [seems to support this](https://material.io/components/switches#behavior):

> When a user toggles a switch, its corresponding action takes effect immediately.

2021-06-11 07:10 UTC, bmesuere commented on app/views/courses/_form.html.erb
> +        <div class="form-check <%= "form-switch" unless course.new_record? %>">
It is a checkbox when creating the course (since it is a form there), but a switch when editing since it is a "mode" that gets enabled. But you are right that this is technically not instant and needs to be saved first.

2021-06-11 07:16 UTC, niknetniko commented on app/views/courses/_form.html.erb
> +        <div class="form-check <%= "form-switch" unless course.new_record? %>">
That does make sense 👍

2021-06-12 07:50 UTC, chvp requested changes
https://mestra.ugent.be/nl/courses/5/submissions/ -> automatic refresh should be a toggle like dark mode
https://mestra.ugent.be/nl/courses/5/series/50/activities/65117396/submissions/ -> most recent correct per user should also be a toggle

2021-06-12 08:40 UTC, bmesuere commented
I wasn't sure about those. They feel more like forms and not a mode, especially the most recent solution one. Therefore, I opted to keep them as checkboxes to not mix the icons (and add a separate setting for them). This is maybe something we can revisit if we implement a better filtering solution?

2021-06-12 09:14 UTC, chvp approved these changes

2021-06-12 10:30 UTC, merged