Add featured courses
dodona-edu/dodona pull request #2849
Opened 2021-06-12 10:58 UTC by bmesuere

This pull request adds the concept of "featured courses" to Dodona which can be used to highlight specific courses such as De Programmeursleerling or the Youtube course and exercises of @deepeebee. In addition this would help avoid confusion caused by copies of those courses.

`featured` is a course flag that can only be set by zeus users. Featured courses are listed in a separated tab on the all courses page and are listed first in the copy course listing.

Closes #2780 

---

- [x] Add featured flag to database
- [ ] Add setting for zeus to admin form
- [ ] Add featured course to the db seed
- [ ] Add tab in courses index
- [ ] Sort featured courses first in the copy course listing

2021-06-12 19:26 UTC, bmesuere commented on app/policies/course_policy.rb
>        %i[name year description visibility registration color teacher institution_id moderated enabled_questions]
@chvp `color` was in the list of permitted attributes here, but I think it shouldn't be?

2021-06-12 19:35 UTC, chvp commented on app/policies/course_policy.rb
>        %i[name year description visibility registration color teacher institution_id moderated enabled_questions]
Indeed, it shouldn't be. This has been a bug since the color feature was introduced: https://github.com/dodona-edu/dodona/commit/ab5081547dbbcfee7ca5b17c82a2424b69268b4a
I can't seem to find the related PR though, to see if any reasoning was given.

2021-06-12 19:37 UTC, bmesuere commented on app/policies/course_policy.rb
>        %i[name year description visibility registration color teacher institution_id moderated enabled_questions]
Ok, I'll move it to the newly added zeus list.

2021-06-12 19:38 UTC, chvp commented on app/policies/course_policy.rb
>        %i[name year description visibility registration color teacher institution_id moderated enabled_questions]
PR is https://github.com/dodona-edu/dodona/pull/415

2021-06-14 08:40 UTC, niknetniko approved these changes

2021-06-14 08:40 UTC, niknetniko commented on app/views/courses/_form.html.erb
> +      <div class="field form-group row">
What's the reasoning behind making this a checkbox, while the questions toggle is a switch? This won't be a real problem since only zeus can see this, but the difference isn't entirely clear to me at first glance:

![image](https://user-images.githubusercontent.com/1756811/121863942-a6f79380-ccfc-11eb-8969-199f4e7f9b3c.png)

2021-06-14 09:01 UTC, bmesuere commented on app/views/courses/_form.html.erb
> +      <div class="field form-group row">
In determining if something should be a toggle or a switch, I ask myself "is this something that can be enabled/disabled" en would it make sense to reformulate the option as such.

My feeling is that the featured flag does not meet that criterium and that it is more like a property. ("enable featured course" doesn't sound right, "enable questions" does).

(The series options are still checkboxes and should probably be toggles, but for that they need to be reformulated in a positive way (show progress instead of hide progress) and this required controller code changes)

2021-06-14 09:14 UTC, niknetniko commented on app/views/courses/_form.html.erb
> +      <div class="field form-group row">
Makes a lot of sense, thanks for the explanation 👍

2021-06-14 09:15 UTC, chvp requested changes

2021-06-14 09:15 UTC, chvp commented on app/views/courses/_form.html.erb
>      <% if current_user.zeus? %>
I think it would be better to use our permission helper instead of a user level check. (Also for the featured checkbox, obviously.) See for example https://github.com/dodona-edu/dodona/blob/develop/app/views/users/_form.html.erb#L21

2021-06-14 09:20 UTC, bmesuere commented on app/views/courses/_form.html.erb
>      <% if current_user.zeus? %>
:+1: I didn't know this existed, will change.

2021-06-14 13:25 UTC, chvp approved these changes

2021-06-14 13:26 UTC, merged