Allow merging of institutions and add secondary providers
dodona-edu/dodona pull request #2906
Opened 2021-07-02 12:27 UTC by chvp

- [x] Tests were added

Closes #2666 and 2667.

2021-07-09 15:26 UTC, bmesuere approved these changes

2021-07-09 15:26 UTC, bmesuere commented on config/locales/views/institutions/en.yml
> +      pick_institution: "Choose other institution"
```suggestion
      pick_institution: "Choose the institution to merge into"
```

2021-07-09 15:26 UTC, bmesuere commented on config/locales/views/institutions/nl.yml
> +      pick_institution: "Kies de andere onderwijsinstelling"
```suggestion
      pick_institution: "Kies de onderwijsinstelling om in samen te voegen"
```

2021-07-09 15:26 UTC, bmesuere commented on config/locales/views/institutions/en.yml
> +        one: "1 user will change institution."
```suggestion
        one: "One user will change institution."
```

2021-07-12 09:43 UTC, niknetniko requested changes

2021-07-12 09:43 UTC, niknetniko commented on app/models/institution.rb
> +    courses.each { |c| c.update(institution: other) }
Should we do this in a transaction? I'm not that familiar with Active Record transactions, and it doesn't seem like there are a lot of ways this could fail, so perhaps it's unnecessary.

2021-07-12 09:43 UTC, niknetniko commented on app/views/institutions/_merge_table.html.erb
> +          <%= link_to institution.name, institution, class: 'nested-link' %>
I would also open this link in a new tab, or was this intentional (with the action which does open a new tab)?

2021-07-12 09:43 UTC, niknetniko commented on app/controllers/institutions_controller.rb
> +      redirect_to institution_url(@other), notice: I18n.t('views.institutions.merge.done')
```suggestion
      redirect_to institution_url(@other), notice: I18n.t('institutions.merge.done')
```
Otherwise this gives translation errors for me (on mestra & locally).

2021-08-02 07:39 UTC, chvp commented on app/models/institution.rb
> +    courses.each { |c| c.update(institution: other) }
Seems unnecessary to me. It shouldn't fail except if we have bigger problems (database connection loss, etc.). In that case, we probably won't be merging institutions. If it somehow fails, a partial migration of the courses to the new institution wouldn't be that big of a problem (same for the other migrated items), IMO.

2021-08-02 08:21 UTC, niknetniko approved these changes

2021-08-02 08:21 UTC, merged