Add icons to all dropdown menus
dodona-edu/dodona pull request #2907
Opened 2021-07-02 15:50 UTC by bmesuere

This pull request adds icons to all dropdown menus.

The commits were cherry-picked from #2903.

Closes #2811

2021-07-03 17:15 UTC, bmesuere commented
@BTWS2 something is wrong with the code in this pull request:
![image](https://user-images.githubusercontent.com/481872/124362008-c49c8680-dc32-11eb-9493-d0db54cace2e.png)

(I also think we don't want icons in the navbar dropdown because of the toggle alignment)

2021-07-03 17:24 UTC, BTWS2 commented
@bmesuere It's ok for me to revert the changes for the user dropdown.

2021-07-03 17:45 UTC, bmesuere commented
I removed the commit that added icons to the navbar menu and fixed the remaining syntax errors in a separate commit.

2021-07-04 19:46 UTC, chvp requested changes

2021-07-04 19:46 UTC, chvp commented on app/views/courses/show.html.erb
> +                  <%= link_to scoresheet_course_url(@course), class: "dropdown-item" do%>
We usually put whitespace after `do`s.

2021-07-05 07:42 UTC, niknetniko approved these changes
Aside from the already requested changes, the current changes look good to me.

(However, despite the title claiming to do so, this PR doesn't add icons to all dropdown menus: the grading wizard also has a dropdown)
![image](https://user-images.githubusercontent.com/1756811/124435064-e30a9b00-dd74-11eb-9cec-4af54fa6e618.png)

2021-07-05 07:53 UTC, BTWS2 commented
@niknetniko Good point, I would suggest:
[mdi-eye](https://iconify.design/icon-sets/mdi/eye.html) Alle scoreonderdelen zichtbaar maken
[mdi-eye-off](https://iconify.design/icon-sets/mdi/eye-off.html) Alle scoreonderdelen verbergen
[mdi-table-row-plus-after](https://iconify.design/icon-sets/mdi/table-row-plus-after.html) Scoreonderdeel toevoegen aan alle oefeningen

2021-07-08 12:05 UTC, chvp approved these changes

2021-07-08 12:08 UTC, niknetniko approved these changes

2021-07-08 12:16 UTC, merged