Re-implement util functions using URL API
dodona-edu/dodona pull request #2954
Opened 2021-08-03 14:58 UTC by TimonDB

This pull request re-implements some util functions. By using the URL API, the code becomes more simplified while maintaining its functionality.

Closes #2614  .

2021-08-04 12:57 UTC, bmesuere requested changes

2021-08-04 12:57 UTC, bmesuere commented on app/assets/javascripts/util.js
>  function getURLParameter(_name, _url) {
Since `name` is no longer overwritten, we can use `name` here instead of `_name`.

2021-08-04 12:57 UTC, bmesuere commented on app/assets/javascripts/util.js
> +    const url = new URL(_url || window.location.href);
```suggestion
    const url = new URL(_url ?? window.location.href);
```

@chvp I think this is never called with an empty string so we can used nullish coalescing here instead of the logical or?

If so, also change in the function below.

2021-08-04 12:57 UTC, bmesuere commented on app/assets/javascripts/util.js
> +    const result = url.searchParams.get(_name);
According to the [docs](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams/get), `get` returns `null` if the parameter isn't found. You can thus return the value directly without the checks in the lines below.

2021-08-04 12:57 UTC, bmesuere commented on app/assets/javascripts/util.js
> +    const result = url.searchParams.getAll(name);
Same as with the other function. getAll will return an empty array when the parameter is not present.

2021-08-04 13:03 UTC, TimonDB commented on app/assets/javascripts/util.js
>  function getURLParameter(_name, _url) {
ah so there is only an underscore before the parameter in case it is overwritten in the function? I was already wondering what the logic behind the underscore was

2021-08-04 13:08 UTC, chvp requested changes
The issue also mentios the `updateURL...` functions. Is there a reason these weren't changed.

2021-08-04 13:08 UTC, chvp commented on app/assets/javascripts/util.js
> +    const url = new URL(_url || window.location.href);
Sound reasonable, if it was called with the empty string it was probably a bug that the `href` was used in that case.

2021-08-04 13:08 UTC, chvp commented on app/assets/javascripts/util.js
>  function getURLParameter(_name, _url) {
If we redefine the variable as `const` we can't use the same variable name (and mutating arguments is generally seen as bad style).

2021-08-04 13:21 UTC, TimonDB commented
> The issue also mentios the `updateURL...` functions. Is there a reason these weren't changed?

@chvp The `updateURL...` functions sometimes have only a pathname as URL argument (e.g. `nl/submissions/53` was one I encountered), this resulted in an error (`Error: Invalid URL`) when trying to create the URL `const url = new URL(_url)`

2021-08-04 13:34 UTC, niknetniko commented
> The `updateURL...` functions sometimes have only a pathname as URL argument (e.g. `nl/submissions/53` was one I encountered), this resulted in an error (`Error: Invalid URL`) when trying to create the URL `const url = new URL(_url)`

Is this used this way in a lot of places? Because if not, it might be worth to update the caller to provide the full URL, allowing us to also update the `updateURL...` functions, which would be nice.

2021-08-04 13:42 UTC, bmesuere requested changes
I also agree with @niknetniko's comment

2021-08-04 13:42 UTC, bmesuere commented on app/assets/javascripts/util.js
> +    return result;
```suggestion
    return url.searchParams.get(name);
```

2021-08-04 13:42 UTC, bmesuere commented on app/assets/javascripts/util.js
>      return result;
```suggestion
    return url.searchParams.getAll(name);
```

2021-08-05 07:26 UTC, chvp commented
The easiest way to fix that there would probably be to add a `base_submissions_url` data attribute in the HTML. This can then be read in the setup function and used in place of the `/submissions/` strings in the javascript file.

2021-08-09 07:28 UTC, bmesuere requested changes
It would be reassuring if some jest tests were added covering those new functions. In addition, it would make sense to "port" these functions to typescript.

@chvp do we already have a file where we can place such helper functions in ts?

2021-08-09 07:29 UTC, chvp commented
> @chvp do we already have a file where we can place such helper functions in ts?

We don't, no.

2021-08-09 10:28 UTC, TimonDB commented on app/assets/javascripts/exercise.js
> +    const to = (_baseSubmissionUrl.substr(0, _baseSubmissionUrl.length - 1)).lastIndexOf("/");
@bmesuere How do I get the general submission/index path? I don't see where I can find it in the codebase

2021-08-09 12:40 UTC, niknetniko commented on app/assets/javascripts/exercise.js
> +    const to = (_baseSubmissionUrl.substr(0, _baseSubmissionUrl.length - 1)).lastIndexOf("/");
In this case it will probably be `submissions_url`. You can find all routes by issuing the command `rails routes` (see the excellent rails guide to see all possible ways to view all existing routes: https://guides.rubyonrails.org/routing.html#listing-existing-routes)

2021-08-09 12:44 UTC, niknetniko requested changes

2021-08-09 12:44 UTC, niknetniko commented on test/javascript/util.test.js
> +    multipleValueUrl = "https://www.dodona.ugent.be/test_functions?param=paramVal1&param=paramVal2&param=paramVal3";
In tests and examples, the convention is to use one of the reserved domains for testing, such as `example.com`. That way the tests can never accidentally use a real service or domain name.

2021-08-09 13:05 UTC, TimonDB commented on test/javascript/util.test.js
> +    multipleValueUrl = "https://www.dodona.ugent.be/test_functions?param=paramVal1&param=paramVal2&param=paramVal3";
I didn't know that, but sounds indeed reasonable. I will adapt it, thanks for the feedback!

2021-08-09 20:23 UTC, chvp approved these changes

2021-08-09 20:23 UTC, chvp commented on app/assets/javascripts/exercise.js
> +function initExerciseShow(exerciseId, programmingLanguage, loggedIn, editorShown, courseId, _deadline, baseSubmissionUrl) {
```suggestion
function initExerciseShow(exerciseId, programmingLanguage, loggedIn, editorShown, courseId, _deadline, baseSubmissionsUrl) {
```

2021-08-09 20:23 UTC, chvp commented on app/assets/javascripts/exercise.js
> +            loadFeedback(baseSubmissionUrl + $(this).data("submission_id"), $(this).data("submission_id"));
```suggestion
            loadFeedback(baseSubmissionsUrl + $(this).data("submission_id"), $(this).data("submission_id"));
```

2021-08-09 20:23 UTC, chvp commented on app/assets/javascripts/exercise.js
> +                    loadFeedback(baseSubmissionUrl + lastSubmission, lastSubmission);
```suggestion
                    loadFeedback(baseSubmissionsUrl + lastSubmission, lastSubmission);
```

2021-08-10 07:31 UTC, niknetniko approved these changes

2021-08-10 08:55 UTC, merged