Align rows in scoresheet
dodona-edu/dodona pull request #2961
Opened 2021-08-04 14:14 UTC by TimonDB

This pull request fixes the misalignment in the scoresheets. By removing the `height` component in the css of `.user-name`, the problem seems to be solved.

Before:
![Screenshot from 2021-08-04 16-03-28](https://user-images.githubusercontent.com/53220653/128196371-2b333644-88a5-4956-9566-fcf4f8bdc521.png)

After:
![Screenshot from 2021-08-04 16-05-09](https://user-images.githubusercontent.com/53220653/128196410-fbb39e00-5cae-40b7-8734-ecde5f4a735b.png)

Closes #2772.

2021-08-04 14:25 UTC, chvp requested changes
So yeah, as mentioned on Slack, grading is now broken:
![screenshot_2021-08-04-162420](https://user-images.githubusercontent.com/42220376/128198419-e2c0a1ed-53b7-45c6-a6f9-4589902263b2.png)

2021-08-10 10:57 UTC, niknetniko requested changes
This breaks the sticky first column (the name) in the evaluation details.
Instead of removing the absolute position of the `.user-name`, it might be fixable by overriding the height of the `user-name` column for either the evaluation details or the grade overview (since both need a different height).

2021-08-10 11:51 UTC, TimonDB commented
> This breaks the sticky first column (the name) in the evaluation details.
> Instead of removing the absolute position of the `.user-name`, it might be fixable by overriding the height of the `user-name` column for either the evaluation details or the grade overview (since both need a different height).

I will look into it. Out of curiosity, what is the purpose of a `sticky-column`?

2021-08-13 07:48 UTC, chvp approved these changes

2021-08-13 07:48 UTC, chvp commented on app/assets/stylesheets/components/table.css.scss
> +#scoresheet-table-wrapper .user-name{
```suggestion
#scoresheet-table-wrapper .user-name {
```

2021-08-13 07:50 UTC, niknetniko approved these changes

2021-08-13 19:37 UTC, bmesuere approved these changes

2021-08-13 19:37 UTC, merged