Update the copy of the right request emails
dodona-edu/dodona pull request #2963
Opened 2021-08-04 16:36 UTC by bmesuere

This pull request updates the copy of the right request emails.

The text is now a bit more customer focussed since this is one of the first contacts we have with teachers. In addition, I added links to the demo video and to our twitter and facebook accounts (in Dutch only).

@chvp if you're not ok with your name being in the emails, just let me know and I'll replace it with mine.

2021-08-04 16:45 UTC, chvp requested changes
No personalized name for the reject?

2021-08-04 16:45 UTC, chvp commented on app/views/rights_request_mailer/approved.en.html.erb
> +    <p>Hi <%= @request.user.first_name %>,</p>
`first_name` can sometimes be empty, so I'd add an `||` here with the full name.

2021-08-04 16:45 UTC, chvp commented on app/views/rights_request_mailer/approved.nl.text.erb
> +Goed nieuws! We hebben je Dodona-account lesgeversrechten gegeven. Je kan nu cursussen aanmaken en zelf oefeningen aan Dodona toevoegen.
The few people who see the plaintext version will probably appreciate it if we wrap this properly.

2021-08-05 06:43 UTC, niknetniko requested changes

2021-08-05 06:43 UTC, niknetniko commented on app/views/rights_request_mailer/approved.nl.html.erb
> +        ps. Volg ons snel op <a href="https://twitter.com/DodonaEdu">Twitter</a> of <a href="https://facebook.com/DodonaEdu">Facebook</a> en wees als eerste op de hoogte van onze nieuwste functies.
```suggestion
        PS Volg ons snel op <a href="https://twitter.com/DodonaEdu">Twitter</a> of <a href="https://facebook.com/DodonaEdu">Facebook</a> en wees als eerste op de hoogte van onze nieuwste functies.
```

2021-08-05 06:43 UTC, niknetniko commented on app/views/rights_request_mailer/approved.nl.text.erb
> +ps. Volg ons snel op Twitter (https://twitter.com/DodonaEdu) of Facebook
```suggestion
PS Volg ons snel op Twitter (https://twitter.com/DodonaEdu) of Facebook
```

2021-08-05 08:53 UTC, niknetniko approved these changes

2021-08-05 08:57 UTC, merged