Add `Total Score` and `Total Max` to csv grade report
dodona-edu/dodona pull request #2977
Opened 2021-08-10 13:53 UTC by TimonDB

This pull request adds the `Total Score` and `Total Max` per student to the csv grade report.

Closes #2816.

2021-08-11 09:12 UTC, chvp requested changes
Can you also add some tests/asserts to make sure that the resulting data in the CSV is correct?

2021-08-11 14:07 UTC, bmesuere requested changes

2021-08-11 14:07 UTC, bmesuere commented on app/models/evaluation.rb
>          row = [user.full_name, user.email]
Merge this into line 125 and set the first 4 fields at once.

2021-08-12 08:16 UTC, chvp approved these changes

2021-08-12 09:06 UTC, niknetniko approved these changes

2021-08-12 09:08 UTC, bmesuere approved these changes

2021-08-12 09:08 UTC, merged