Add iCal link for syncing deadlines with external calendar
dodona-edu/dodona pull request #2979
Opened 2021-08-11 11:42 UTC by TimonDB

This pull request adds an iCal link for syncing the deadlines of a course with an external calendar.

Closes #2596.

2021-08-11 14:26 UTC, bmesuere requested changes

2021-08-11 14:26 UTC, bmesuere commented on Gemfile
> +gem "icalendar", "~> 2.7"
This seems like a good gem with plenty of users 👍 
We have the habit of placing a little comment in the gemfile mentioning where the specific gem is used.

2021-08-11 14:26 UTC, bmesuere commented on app/controllers/courses_controller.rb
> +    @series = Series.where(course_id: @course.id)
We only want public series to show up so this needs to be filtered.

2021-08-11 14:26 UTC, bmesuere commented on app/controllers/courses_controller.rb
> +        cal.x_wr_calname = 'Course deadlines'
Use the actual course name.

2021-08-11 14:26 UTC, bmesuere commented on app/controllers/courses_controller.rb
> +    respond_to do |format|
@chvp do we need a format block here if we always want to respond with the same response?

2021-08-11 14:26 UTC, bmesuere commented on app/controllers/courses_controller.rb
> +            e.description = serie.description
I would not set the description (since this might expose semi-hidden data). Instead, the url field can be used to link to the specific series.

2021-08-11 14:26 UTC, bmesuere commented on app/controllers/courses_controller.rb
> +            e.dtstart = serie.deadline
Are the timezones ok if you set the date like this? The icalendar docs use Icalendar::Values::DateTime.

2021-08-11 14:26 UTC, bmesuere commented on app/controllers/courses_controller.rb
> +        render plain: cal.to_ical
You will need to look into the ical spec, but it might be needed to use `send_data` instead in combination with a specific type, the attachment flag and a filename ending in ics.

2021-08-11 14:26 UTC, bmesuere commented on app/policies/course_policy.rb
> +    course_admin?
The ical link will be used unauthenticated, so should always work.

2021-08-11 14:26 UTC, bmesuere commented on app/views/courses/ical.html.erb
> +<%= render partial: 'navbar_links' %>
A view is not needed because you specifically call render (or send_data).

2021-08-11 15:35 UTC, TimonDB commented on app/controllers/courses_controller.rb
> +    @series = Series.where(course_id: @course.id)
@bmesuere is a serie public when its `activities_visible` property is set to True?

2021-08-12 09:15 UTC, TimonDB commented on app/policies/course_policy.rb
> +    course_admin?
Does this mean that the function `def ical?`  is unnecessary?

2021-08-12 09:18 UTC, bmesuere commented on app/policies/course_policy.rb
> +    course_admin?
no, for now simply put `true` here. We can later discuss if we want to allow ical links for completely hidden courses.

2021-08-12 09:20 UTC, chvp commented on app/controllers/courses_controller.rb
> +    respond_to do |format|
Should not be necessary, no.

2021-08-12 09:27 UTC, chvp commented on app/controllers/courses_controller.rb
> +    @series = Series.where(course_id: @course.id, visibility: :open)
There is no need for the `@` in `@series`, since there is no view.

2021-08-12 09:27 UTC, chvp commented on app/controllers/courses_controller.rb
> +        e.description = series_url(serie)
There is a `url` field in the ICS spec, so it might be better to use that one. A series also has a description, but I'm not sure we want to add that here (since it can contain HTML/markdown).

2021-08-12 09:30 UTC, TimonDB commented on app/views/courses/show.html.erb
> +                  <i class="mdi mdi-calendar-clock mdi-18"></i>Export course deadlines
This has to be cleaned up (proper translation), but to demonstrate, I just hardcoded the text

2021-08-12 09:31 UTC, chvp commented on app/controllers/courses_controller.rb
> +        e.dtend = serie.deadline
[The spec](https://datatracker.ietf.org/doc/html/rfc5545#section-3.8.2.2) says the following: 
```
      The value type
      of this property MUST be the same as the "DTSTART" property, and
      its value MUST be later in time than the value of the "DTSTART"
      property.  Furthermore, this property MUST be specified as a date
      with local time if and only if the "DTSTART" property is also
      specified as a date with local time.
```
So this will produce an invalid file. Substracting a second or minute from the start seems like the best option to avoid this, I think.

2021-08-12 09:44 UTC, chvp commented on app/controllers/courses_controller.rb
> +        e.dtend = serie.deadline
The spec also mentions a [duration](https://datatracker.ietf.org/doc/html/rfc5545#section-3.8.2.5) which can be used in place of the `end`. Durations must be positive, but I can't immediately find whether they consider 0 a positive number or not.

2021-08-12 09:58 UTC, TimonDB commented on app/controllers/courses_controller.rb
> +    @series = Series.where(course_id: @course.id, visibility: :open)
ah yes, I will adapt it. Btw, what is the best option to use in this case: `Series.where(...)` or `@course.series.where(...)`?

2021-08-12 10:19 UTC, chvp commented on app/controllers/courses_controller.rb
> +    @series = Series.where(course_id: @course.id, visibility: :open)
I have a slight preference for the latter, but it's not a strong one. It reads more natural to me.

2021-08-12 10:19 UTC, TimonDB commented on app/controllers/courses_controller.rb
> +        e.dtend = serie.deadline
Since most calendars only show the hour and minutes of the event, would it not be better to add a second the end? This way, the start time and end time will both be truncated to the correct time

2021-08-12 10:24 UTC, TimonDB commented on app/controllers/courses_controller.rb
> +        e.dtend = serie.deadline
For example: it seems like my calendar app users `floor()` to display the start time, resulting in 11:59 instead of 12:00
![Screenshot from 2021-08-12 12-20-32](https://user-images.githubusercontent.com/53220653/129181287-acf84cb1-250e-405f-a2a0-53bde81b387f.png)

2021-08-12 11:06 UTC, chvp commented on app/controllers/courses_controller.rb
> +        e.dtend = serie.deadline
Yeah, makes sense.

2021-08-12 11:36 UTC, TimonDB commented on app/controllers/courses_controller.rb
> +        e.description = series_url(serie)
Maybe we can just add a short message like `"Deadline for #{serie.name} of course #{@course.name}"` instead of the serie's description?

2021-08-12 11:43 UTC, chvp commented on app/controllers/courses_controller.rb
> +        e.description = series_url(serie)
Sounds good to me.

2021-08-16 12:12 UTC, TimonDB commented on app/controllers/courses_controller.rb
> +            e.dtstart = serie.deadline
I have set the start and end time of the event in their respective UTC time, which is indicated in the .ics file by a `'Z'` at the end of `dtstart` and `dtend`. This way, all calendar apps should in theory show these start and end times correctly according to the user's time zone

2021-08-16 12:31 UTC, chvp requested changes
This looks good :+1: 
This still needs some tests, and we need to figure out what we do for closed courses. There's no real secret information in the exported ICS files, but I can imagine that some teachers might be hesitant in allowing this without any form of authentication.

2021-08-16 12:31 UTC, chvp commented on config/locales/views/courses/en.yml
> +      download_deadlines: "Export course deadlines"
This somehow needs to mention a calendar, I think. Right now I don't think users will really know what this means.

2021-08-17 07:49 UTC, TimonDB commented on config/locales/views/courses/en.yml
> +      download_deadlines: "Export course deadlines"
Fair point. Maybe "Export course deadlines for external calendar" is more clarifying?

2021-08-18 16:17 UTC, bmesuere commented
I think this needs another UI solution. If you click the link right now, a file is downloaded which can be imported in a calendar application. However, this is not what we want because this will cause a 1-time import of the deadlines. We want to expose actual link to the user so he can add the feed instead. (Sorry I previously pushed for the download stuff to be added in the controller as this doesn't seem to be the way to go after all)

2021-08-18 19:27 UTC, TimonDB commented
> I think this needs another UI solution. If you click the link right now, a file is downloaded which can be imported in a calendar application. However, this is not what we want because this will cause a 1-time import of the deadlines. We want to expose actual link to the user so he can add the feed instead. (Sorry I previously pushed for the download stuff to be added in the controller as this doesn't seem to be the way to go after all)

So if I understand correctly, we want to create a [webcal link](https://toasterlovin.com/rails-webcal-links-with-icalendar-gem/) that a user can click to subscribe to the calendar of a specific course? And the user's calendar app will then periodically fetch new events?

2021-08-19 08:13 UTC, chvp commented
A webcal link seems like a good mechanism :+1:

2021-08-23 09:56 UTC, TimonDB commented
When adding the course calendar to my Google Calendar using the URL (e.g. http://dodona.localhost:3000/nl/courses/3/ical), the deadlines don't seem to be imported. The [website](https://toasterlovin.com/rails-webcal-links-with-icalendar-gem/) I used as a guideline states the following:

> Your controller needs to be unauthenticated, or else the user's calendar app won't be able to access the calendar. So, if your `ApplicationController` is authenticated, your `CalendarsController` will probably need to inherit directly from `ActionController::Base` to avoid authentication.

Could this in our case also be the reason why the deadlines don't show up on Google Calendar?

2021-08-23 10:01 UTC, bmesuere commented
The policy is set to unauthenticated access. You can easily test this by loading the url in a separate browser or in private mode. Just to be sure, did you try to add the localhost url to google calendar? Because that will not work since it's only a local web server...

2021-08-23 10:03 UTC, TimonDB commented
> The policy is set to unauthenticated access. You can easily test this by loading the url in a separate browser or in private mode. Just to be sure, did you try to add the localhost url to google calendar? Because that will not work since it's only a local web server...

Ah yes, I indeed tried to add the localhost url, not my smartest move. That explains why it doesn't work

2021-08-24 07:37 UTC, chvp reviewed
Looks good, but translation strings still need to be updated.

2021-08-24 07:37 UTC, chvp commented on config/locales/views/courses/en.yml
> +      download_deadlines: "Export course deadlines"
"Add course to calendar", maybe?

2021-08-24 11:45 UTC, bmesuere commented
- Is it possible to add an extra (bootstrap) tooltip to this menu item that gives a little more information? Something like: Add this link to your calendar application to show the course deadlines in your calendar
- For now, I would limit the menu item to only be visible to course admins because we will probably need to check if the updates work

2021-08-25 11:52 UTC, chvp approved these changes

2021-08-28 12:43 UTC, bmesuere commented
It is now 24+ hours later and the deadline was still not updated in my google calendar.

2021-08-28 16:27 UTC, bmesuere commented
It was now updated so this seems to work.

2021-08-28 16:32 UTC, bmesuere approved these changes

2021-08-28 16:38 UTC, merged