Runtime error link switches to correct tab
dodona-edu/dodona pull request #2993
Opened 2021-08-17 09:54 UTC by TimonDB

This pull request fixes the Runtime error tab link. Explanation of the fix: The nav-tab with `href="#code"` was searched. However, the two tabs had `href="#tab-corectheid-0"` and `href="#tab-code-1"`, so the search delivered an empty result. Instead, searching for `code` in the href returns an index greater than zero if `code` is present in the href, and -1 otherwise. Filtering on this condition delivers the correct tab.

Closes #2992.

2021-08-17 14:33 UTC, chvp commented on app/assets/javascripts/submission.js
> +                return $(this).attr("href").indexOf(tab) > 0;
```suggestion
                return $(this).attr("href").indexOf(`#tab-${tab}`) === 0;
```
I think this makes more sense, since the word `code` will probably show up in other tab id's, which is the most common use of this code.

2021-08-17 15:34 UTC, chvp approved these changes

2021-08-18 16:09 UTC, bmesuere requested changes

2021-08-18 16:09 UTC, bmesuere commented on app/assets/javascripts/submission.js
> +                return $(this).attr("href").indexOf(`#tab-${tab}`) === 0;
```suggestion
                return $(this).attr("href").startsWith(`#tab-${tab}`);
```

2021-08-18 16:55 UTC, bmesuere approved these changes

2021-08-18 16:55 UTC, merged