Use SimpleLightbox instead of Strip as lightbox
dodona-edu/dodona pull request #2996
Opened 2021-08-17 14:28 UTC by TimonDB

This pull request migrates away from Strip and uses SimpleLightbox instead.

TODO:
- [ ] Cleanup code
- [ ] Add copyrights
- [ ] Test if it correctly renders images on all pages
- [ ] Videos can also be displayed in the lightbox
- [ ] Remove the Split lightbox

Closes #2720.

2021-08-18 13:08 UTC, niknetniko reviewed
I haven't run it locally yet, but:

- I think we should unvendor this and include it as a yarn dependency instead of adding the files to our repo. The [docs](https://dbrekalo.github.io/simpleLightbox/) seem to indicate this is possible (and if not possible, we perhaps need to look at a different lightbox implementation).
- We'll need to localize the next/previous buttons (see `closeBtnCaption`, etc.)
- Check if MathJax works in the captions out of the box. If not, we probably need to hook it in, like we did with Strip. The callback `beforeSetContent` seems like a good place to start.

2021-08-19 13:06 UTC, TimonDB commented
@niknetniko What do you mean by "We'll need to localize the next/previous buttons"?

2021-08-19 13:09 UTC, niknetniko commented
> @niknetniko What do you mean by "We'll need to localize the next/previous buttons"?

The [docs](https://dbrekalo.github.io/simpleLightbox/) mention these strings, which I assume are only available in English by default:

```
// customize / localize controls captions
closeBtnCaption: 'Close',
nextBtnCaption: 'Next',
prevBtnCaption: 'Previous',
loadingCaption: 'Loading...',
```

These are displayed on hover:
![image](https://user-images.githubusercontent.com/1756811/130073924-9e8baf7d-e6c8-4832-b085-4bfb8059519a.png)

(Unless we don't display the controls, in which case this isn't really needed).

2021-08-23 09:27 UTC, TimonDB commented
When trying to hook in MathJax to check for math in the captions using the `beforeContentSet` callback, this didn't seem to work as this is probably executed before the content is created. So instead I searched for another lightbox implementation that does have a `onShow` callback to hook MathJax. With [GLightbox](https://biati-digital.github.io/glightbox/#), it all seems to work fine, so if OK for everyone, I think it is better to use this implementation

2021-08-23 11:21 UTC, niknetniko requested changes
Glightbox looks good, and is MIT licensed 👍

The code looks good, just two minor UI things.

2021-08-23 11:21 UTC, niknetniko commented on app/assets/javascripts/exercise.js
> +            title: altText,
Using title here results in a bit of unnecessary padding:
![image](https://user-images.githubusercontent.com/1756811/130437243-02af0e08-0823-4d70-942e-6ec1d37a1dd9.png)

- I think we could either use `description` (and increase the description's font size a bit) or remove the padding with css.
- Additionally, in dark mode, we want to make this caption background black, with white text. Or, if that's difficult to do for only dark mode, always make the background black and text white, like the current lightbox implementation.

2021-08-23 14:25 UTC, niknetniko approved these changes

2021-08-23 14:54 UTC, chvp approved these changes

2021-08-24 12:17 UTC, bmesuere requested changes

2021-08-24 12:17 UTC, bmesuere commented on app/assets/javascripts/exercise.js
> +    });
Is there a reason why you don't pass `content` directly to the constructor?

2021-08-24 12:17 UTC, bmesuere commented on app/assets/stylesheets/libraries/glightbox.css.scss
> +}
```suggestion
}

```

2021-08-24 12:17 UTC, bmesuere commented on vendor/assets/javascripts/vendor.js
> -//=require strip/strip.pkgd.min.js
This was the last remaining vendored file. The file is now empty so this, the parent directory and the require in app/assets/javascripts/application.js could be removed.

@chvp What do you think? We will probably never add new vendored files here because they use sprockets instead of webpacker.

2021-08-24 12:22 UTC, chvp commented on vendor/assets/javascripts/vendor.js
> -//=require strip/strip.pkgd.min.js
Agreed.

2021-08-24 12:34 UTC, TimonDB commented on app/assets/javascripts/exercise.js
> +    });
Not really, I didn't know you could directly pass `content`

2021-08-24 13:15 UTC, bmesuere approved these changes

2021-08-24 13:15 UTC, merged