Add student label to evaluation interface
dodona-edu/dodona pull request #3012
Opened 2021-08-23 15:28 UTC by TimonDB

This pull request shows the student label in the evaluation overview.

Before:
![Screenshot from 2021-08-23 17-22-47](https://user-images.githubusercontent.com/53220653/130473784-ac69513b-e30e-4851-bfc0-b5edd2af5733.png)

After:
![Screenshot from 2021-08-23 17-22-15](https://user-images.githubusercontent.com/53220653/130473804-76ad6004-fbef-493a-8308-4f41a9c2b4bf.png)

Closes #2676.

2021-08-23 16:18 UTC, TimonDB commented
Someone who knows why the system test keeps failing?

2021-08-23 16:20 UTC, bmesuere commented
```
      ActionView::Template::Error: undefined local variable or method `users_labels' for #<ActionView::Base:0x00000000028410>
      Did you mean?  users_url
          app/views/feedbacks/_feedback_actions.html.erb:111
          app/views/feedbacks/show.js.erb:1
          app/controllers/scores_controller.rb:40:in `block (2 levels) in destroy'
          app/controllers/scores_controller.rb:39:in `destroy'
      # app/views/feedbacks/_feedback_actions.html.erb:111
      # app/views/feedbacks/show.js.erb:1
      # app/controllers/scores_controller.rb:40
      # app/controllers/scores_controller.rb:39
      # app/controllers/application_controller.rb:170
```

2021-08-24 07:47 UTC, chvp requested changes
Not a huge fan of the stacked labels. What's the issue with showing them one after another horizontally?

I'm also pretty sure we use an orange hue for the labels elsewhere, so I would use that same color here.

2021-08-24 08:30 UTC, TimonDB commented
> Not a huge fan of the stacked labels. What's the issue with showing them one after another horizontally?

Showing them horizontally can cause the student's name to be truncated quickly as shown in the screenshot... Maybe it can be checked how many labels there are; (1) in case of one label, it is shown next to the name. (2) if more than 1 label, it is shown beneath the name? Or we can always show them beneath the name
![Screenshot from 2021-08-24 10-17-33](https://user-images.githubusercontent.com/53220653/130583700-9151ff83-c865-4cc1-8ee3-ed97f43c002e.png)

2021-08-24 08:52 UTC, bmesuere commented
I'll submit another pull request today which reworks the label style. Maybe put this one on hold until that lands.

2021-08-25 14:24 UTC, bmesuere commented
You can rebase this on develop which now includes the redesigned labels.

2021-08-30 12:04 UTC, chvp approved these changes

2021-08-30 12:04 UTC, chvp commented on app/controllers/feedbacks_controller.rb
> +                             .map { |m| m.course_label }
```suggestion
                             .course_labels
```

2021-08-30 12:25 UTC, merged