Provide correct user URL in submissions.json
dodona-edu/dodona pull request #3015
Opened 2021-08-24 09:34 UTC by TimonDB

This pull request provides the correct user URL in the submissions json. The `user/:id` URL was provided, however, a course admin can only view a user profile via the `courses/:id/members/:id` URL.

Closes #2732.

2021-08-24 13:18 UTC, niknetniko requested changes

2021-08-24 13:18 UTC, niknetniko commented on app/controllers/course_members_controller.rb
> +    @users_lables = @course.course_memberships
```suggestion
    @users_labels = @course.course_memberships
```

2021-08-24 13:18 UTC, niknetniko commented on app/views/course_members/show.json.jbuilder
> +json.labels @users_lables[@user], :name
```suggestion
json.labels @users_labels[@user], :name
```

2021-08-24 13:18 UTC, niknetniko commented on app/views/submissions/_submission_basic.json.jbuilder
> +json.user course_member_url(course_id: submission.course, id: submission.user.id, format: :json) if submission.course
Should we provide the `user_url` if there is no course attached to the submission? This might be useful if you are getting your own submissions, but not sure if that happens.

2021-08-24 13:38 UTC, chvp commented on app/views/submissions/_submission_basic.json.jbuilder
> +json.user course_member_url(course_id: submission.course, id: submission.user.id, format: :json) if submission.course
That is how it is done in the HTML, so that seems like the best option in the JSON as well.

2021-08-24 13:38 UTC, chvp commented on app/views/course_members/show.json.jbuilder
> +json.labels @users_lables[@user], :name
Should probably be tested, if this wasn't caught by the tests already.

2021-08-24 13:39 UTC, chvp commented on app/views/course_members/show.json.jbuilder
> +json.labels @users_lables[@user], :name
Ah, never mind, didn't see the comment above yet.

2021-08-24 17:47 UTC, niknetniko approved these changes

2021-08-24 18:09 UTC, bmesuere approved these changes

2021-08-25 07:41 UTC, chvp requested changes

2021-08-25 07:41 UTC, chvp commented on app/controllers/course_members_controller.rb
> +                           .to_h
It feels a bit wasteful to load all user -> course label mappings to show a single user. The HTML version of this page doesn't need this, so you can look there how the course labels are loaded for a single user. Probably move that here, since it can be shared between the json and html views.

2021-08-25 11:57 UTC, chvp requested changes

2021-08-25 11:57 UTC, chvp commented on app/views/course_members/index.json.jbuilder
>    json.url course_member_url(cm.course, cm.user, format: :json)
We usually extract the common items between the index and the show to a partial.

2021-08-25 11:59 UTC, chvp commented on app/views/course_members/index.json.jbuilder
>    json.url course_member_url(cm.course, cm.user, format: :json)
There are slight differences between the data per user in `index` and in `show`, but I think those differences are not necessary, and can be removed.

2021-08-25 13:14 UTC, chvp approved these changes

2021-08-25 14:22 UTC, merged