Fix searching users using labels
dodona-edu/dodona pull request #3056
Opened 2021-08-31 14:24 UTC by TimonDB

This pull request enables searching users using the course labels. At the moment, searching users via the course labels seems to be completely broken, on every page. This PR tries to fix this, but I'm not sure it is completely OK now.

Closes #2524.

2021-09-01 14:17 UTC, chvp commented on app/assets/javascripts/util.js
> +    const url = new URL(decodeURI(_url), window.location.origin);
I'm not sure if a full decodeURI is the way to go. What happens if e.g. a label contains a character that is usually percent-encoded?

2021-09-01 14:24 UTC, TimonDB commented on app/assets/javascripts/util.js
> +    const url = new URL(decodeURI(_url), window.location.origin);
hmmm fair point, didn't think of that... But maybe we can use `_url.replace("%5B%5D", "[]")` to get the brackets back into the url string? That might be a simple solution for this issue, I only think of that now

2021-09-01 14:27 UTC, chvp commented on app/assets/javascripts/util.js
> +    const url = new URL(decodeURI(_url), window.location.origin);
A replace sounds fine to me.

2021-09-01 20:52 UTC, bmesuere requested changes

2021-09-01 20:52 UTC, bmesuere commented on app/assets/javascripts/util.js
> +    const url = new URL(_url.split("%5B%5D").join("[]"), window.location.origin);
Use replaceAll here

2021-09-02 07:17 UTC, TimonDB commented on app/assets/javascripts/util.js
> +    const url = new URL(_url.split("%5B%5D").join("[]"), window.location.origin);
I did try to use replaceAll, but that gives an error: 
![Screenshot from 2021-09-02 09-15-02](https://user-images.githubusercontent.com/53220653/131799633-20637524-c9cb-4128-bc25-fe709ea0d859.png)

2021-09-02 07:36 UTC, chvp commented on app/assets/javascripts/util.js
> +    const url = new URL(_url.split("%5B%5D").join("[]"), window.location.origin);
Your checker is probably just confused about the type. This is not typescript, so it shouldn't give any linting errors. The function [does exist](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replaceAll), so it should work.

2021-09-02 08:26 UTC, chvp requested changes
This pull request also seems to contain the changes for #3058. Can you remove those?

2021-09-02 08:46 UTC, chvp approved these changes

2021-09-02 10:06 UTC, bmesuere approved these changes

2021-09-02 10:07 UTC, merged