Add 'csv' test format
dodona-edu/dodona pull request #3065
Opened 2021-09-02 15:10 UTC by inteon

This pull request

diff identical:
![image](https://user-images.githubusercontent.com/42113979/131868126-d9487ec1-4663-42bb-835e-14b2896ddd8e.png)
diff row missing & wrong column name:
![image](https://user-images.githubusercontent.com/42113979/131868308-ff739470-8606-4ea4-8335-af2627d522e9.png)
diff too many rows:
![image](https://user-images.githubusercontent.com/42113979/131868459-2c6292ae-fc63-42c9-8369-9e38ca2beea9.png)
diff too many rows (unified):
![image](https://user-images.githubusercontent.com/42113979/131868503-6c097bec-d435-4cd4-a10e-1c1279ec69c8.png)
diff wrong column:
![image](https://user-images.githubusercontent.com/42113979/131868730-52fcc3ef-2895-48f2-a896-65dc0ef74a14.png)
diff wrong column (unified):
![image](https://user-images.githubusercontent.com/42113979/131868770-dbe18f9f-f0bd-447f-91f3-db9e7a3d61b4.png)

- [ ] Tests were added
- [ ] Documentation update can be found at dodona-edu/dodona-edu.github.io#

2021-09-02 15:19 UTC, thepieterdc commented on app/assets/stylesheets/models/submissions.css.scss
> +      width: 0px; /* minimize the width */
Unit is not required if amount is 0
```suggestion
      width: 0; /* minimize the width */
```

2021-09-02 15:19 UTC, thepieterdc commented on app/helpers/renderers/feedback_table_renderer.rb
> +      end
Could get rid of the duplicated `if`-statement everywhere if you make a function `differ(t)` that returns either the `LCSCsvDiffer` or `LCSHtmlDiffer`.

2021-09-02 15:19 UTC, thepieterdc commented on public/schemas/judge_output.json
> +      ]
Indicate the default value here in the description

2021-09-02 15:19 UTC, thepieterdc commented on app/helpers/renderers/lcs_csv_differ.rb
> +              end
Can oneline this with `map`.

2021-09-02 15:46 UTC, pdawyndt commented
Is there support for large tables (say > 20 rows, > 10 colums). We might need some specific strategies to handle those:

- specific handling if number of rows differs, e.g. explicitly show the number of rows (might be useful to always report the number of rows)
- specific handling if number of cols differs, e.g. explicitly show the number of cols (might be useful to always report the number of cols)
- show only selection of rows, e.g. always show first few rows (irrespective if they are correct or not), and only show a limited number of wrong rows with indications where rows have been left out and where rows are situated (e.g. row numbers)
- show only some columns: some good thinking needed here

2021-09-02 16:00 UTC, inteon commented
> Is there support for large tables (say > 20 rows, > 10 colums). We might need some specific strategies to handle those:
> 
> * specific handling if number of rows differs, e.g. explicitly show the number of rows (might be useful to always report the number of rows)
> * specific handling if number of cols differs, e.g. explicitly show the number of cols (might be useful to always report the number of cols)
> * show only selection of rows, e.g. always show first few rows (irrespective if they are correct or not), and only show a limited number of wrong rows with indications where rows have been left out and where rows are situated (e.g. row numbers)
> * show only some columns: some good thinking needed here

Currently, the column problem is mostly solved by horizontal scrolling:
![image](https://user-images.githubusercontent.com/42113979/131877246-bf3dcb3a-ce95-4a9b-b288-f42203785a48.png)

Large number of rows are just displayed as-is, and if there are more than 100 row, a simplified view is generated to reduce compute time (@bmesuere).

2021-09-02 16:48 UTC, BTWS2 commented
> Is there support for large tables (say > 20 rows, > 10 colums, possibly lengthy content). We might need some specific strategies to handle those:
> 
> * specific handling if number of rows differs, e.g. explicitly show the number of rows (might be useful to always report the number of rows)
> * specific handling if number of cols differs, e.g. explicitly show the number of cols (might be useful to always report the number of cols)

In the new SQL judge (in development by @inteon) differences between row en column counts are shown (if the counts match, there is no warning):
![image](https://user-images.githubusercontent.com/56451049/131881130-ea1deed6-35c7-4877-b35a-890b6fef3302.png)


> * show only selection of rows, e.g. always show first few rows (irrespective if they are correct or not), and only show a limited number of wrong rows with indications where rows have been left out and where rows are situated (e.g. row numbers)
> * show only some columns: some good thinking needed here

We have to assume students don't have access to the full database/dataset. I prefer outputting all rows/columns (limited to 100).

> * add ellipsis to lengthy fields
> * may be easier (in some cases) if diffed tables are not shown side-by-side, but unified; but also here there are some options, e.g. unify per cell
> 
> Some inspiration:
> 
> * [daff](https://github.com/paulfitz/daff) (got this one from here [hacker news](https://news.ycombinator.com/item?id=17924798)); Ruby bindings and supports Sqlite format

I find it difficult to see the difference when two tables are unified, I prefer the split view for tables. However, I have to admit daff manages to clearly show the differences in a unified table. 

The output of the student and solution may be shown in a html table in a pop-up (as is, without diff), similar to the Python Tutor pop-up ([example in jsfiddle](https://jsfiddle.net/vxktcn4L/)). This may be especially useful for large datasets, because we have to assume students don't have access to the full dataset.
- Sticky header with types
- Adaptive lay-out with horizontal and vertical scrollbars (when needed). Students sometimes use Dodona in split screen with their IDE.

![image](https://user-images.githubusercontent.com/56451049/131882193-d8feac3a-af80-4160-a88b-ad4e671a6ea4.png)

2021-09-03 08:30 UTC, inteon commented
Just did some experimentation with the daff online example:
- In most cases the tool yields identical results to this current diff implementation.
- The main improvement of daff over this implementation is the situation where there is a difference in the number of columns and number of rows; in this case daff will better match the columns & rows because it uses the header values to match columns. This is something that we can add too.
- In my opinion, fixing the row/column order should be the responsibility of the judge. This way we can also better adhere to the way the text-base compare works.

I think this current implementation should already be a good baseline for diffing tables.
I propose we implement this feature throughout multiple PRs & limit the scope of this PR to:
- adding format option in judge json output
- adding simple html + csv for table compare
- adding simple differ implementation

Follow-up PRs can include:
- adding sub-headers (eg. datatype in sql)
- updating layout: sticky columns & headers
- adding ellipsis to lengthy fields (maybe expand contents on click)
- adding a popup for better full-screen viewing
- updating the differ implementation

2021-09-09 07:54 UTC, bmesuere requested changes
I think this can be a valuable addition to Dodona. Not only for the sql judge, but also for other judges. Next to comments I left on the code, I have these general remarks:

- Expand the initial post of the pull request and add more info about the changes and design choices you made. Slightly change the wording of the title as well: this is more about adding a new diffing and display strategy for csv-based output, not about the tests itself.
- Add tests
- As I already said on slack, this is the most performance critical part of Dodona. This code is executed on the webserver (of which we only have one) and handles user-generated content. This can crash the Dodona website. In fact, the few times we had issues, they were all related to the performance of generating the feedback table. I would like you to do a few timings on large test output (e.g., 1000 tests, each with 100+ lines; a user generating 1000+ columns; etc).

2021-09-09 07:54 UTC, bmesuere commented on app/assets/stylesheets/models/submissions.css.scss
> +      width: 0; /* minimize the width */
why is this needed? (I mostly concerned with breaking existing things)

2021-09-09 07:54 UTC, bmesuere commented on app/assets/stylesheets/models/submissions.css.scss
> +      content: " "; /* make sure the line-height is respected */
seems a bit hackish to me

2021-09-09 07:54 UTC, bmesuere commented on app/assets/stylesheets/models/submissions.css.scss
> +  }
Are these table? If so, is there a reason to use inline-block instead of inline-table?

2021-09-09 07:54 UTC, bmesuere commented on app/helpers/renderers/feedback_table_renderer.rb
> +      LCSCsvDiffer
The naming is inconsistent with `LCSHtmlDiffer`. The html part there refers to the output format of the diff, not the input. Although the CSV differ also uses LCS (if I understand right), maybe CSVDiffer is a better name?

2021-09-09 07:54 UTC, bmesuere commented on app/helpers/renderers/lcs_csv_differ.rb
> +  def self.render_accepted(builder, generated)
Why do we need a class method here? The old differ didn't need one.

2021-09-09 07:54 UTC, bmesuere commented on app/helpers/renderers/lcs_csv_differ.rb
> +class LCSCsvDiffer
Would we benefit from making a super class and somehow forcing the used functions to be present? Ruby isn't statically typed so abstract methods don't exist, but we can raise errors in base class or use a module to achieve something similar.

2021-09-09 07:54 UTC, bmesuere commented on app/helpers/renderers/lcs_csv_differ.rb
> +    @expected ||= ''
duplicate code, so extract to separate function?

2021-09-09 07:54 UTC, bmesuere commented on app/helpers/renderers/lcs_csv_differ.rb
> +              end
I find it hard to understand this, especially lines 59 and 60, but this could be me. Can you maybe add some comments? You can add newlines in the chained calls and add comments at the end of the line.

2021-09-09 07:54 UTC, bmesuere commented on app/helpers/renderers/lcs_csv_differ.rb
> +    @diff = unless @simplified_table
What happens in the other case?

2021-09-09 07:54 UTC, bmesuere commented on public/schemas/judge_output.json
> +      "description": "Indicates how to show the test output (defaults to 'text').",
```suggestion
      "description": "Indicates how to diff and show the test output (defaults to 'text').",
```

2021-09-09 07:54 UTC, bmesuere commented on public/schemas/partial_output.json
> +      "description": "Indicates how to show the test output (defaults to 'text').",
```suggestion
      "description": "Indicates how to diff and show the test output (defaults to 'text').",
```

2021-09-09 08:31 UTC, inteon commented on app/assets/stylesheets/models/submissions.css.scss
> +  }
`inline-table` breaks the horizontal scrolling; `inline-block` is the only display option that worked for me.

2021-09-09 08:34 UTC, inteon commented on app/helpers/renderers/lcs_csv_differ.rb
> +  def self.render_accepted(builder, generated)
The `render_accepted` logic is different for the csv and text output; I moved that logic from `feedback_table_renderer.rb` to `lcs_csv_differ.rb` and `lcs_html_differ.rb` so both can have a different implementation.

2021-09-09 08:35 UTC, inteon commented on app/assets/stylesheets/models/submissions.css.scss
> +      width: 0; /* minimize the width */
I'll remove that line, seems to have no effect anymore.

2021-09-09 08:39 UTC, inteon commented on app/assets/stylesheets/models/submissions.css.scss
> +      content: " "; /* make sure the line-height is respected */
In the current implementation; the diff table always has at least some text on each row. This csv diff however, uses 2 tables (1 left and 2 right) and now it is possible to have rows that are totally empty. This hack makes sure that such an empty row has the correct height.

I'll have a 2nd look and try to simplify this bit of css.

2021-09-09 08:41 UTC, inteon commented on app/helpers/renderers/feedback_table_renderer.rb
> +      LCSCsvDiffer
It seems like we can only fix this by renaming `LCSHtmlDiffer` right?
What do you think about `TextDiff` and `CSVDiff`?

2021-09-09 08:57 UTC, inteon commented on app/helpers/renderers/lcs_csv_differ.rb
> +    @diff = unless @simplified_table
a simplified table is shown instead (much like the text table)
This table does no diffing and combines all column content (newlines instead of rows)

2021-09-09 12:56 UTC, inteon commented on app/helpers/renderers/lcs_csv_differ.rb
> +class LCSCsvDiffer
The interface would be simple:
```
.new(generated, expected)
.unified
.split
.render_accepted(builder, generated)
```

2021-09-09 14:14 UTC, inteon commented on app/helpers/renderers/lcs_csv_differ.rb
> +    @expected ||= ''
fixed this using lambda function

2021-09-10 12:32 UTC, bmesuere commented on app/helpers/renderers/lcs_csv_differ.rb
> +  def self.render_accepted(builder, generated)
But why use a class method and not an instance method as with the rest of the methods in this file?

2021-09-10 12:33 UTC, bmesuere commented on app/helpers/renderers/feedback_table_renderer.rb
> +      LCSCsvDiffer
@chvp What do you think? Rename to `LineDiffer`/`TextDiffer` and `CsvDiffer`?

2021-09-10 12:37 UTC, bmesuere commented on app/helpers/renderers/lcs_csv_differ.rb
> +    @expected ||= ''
This is not a common construct in our code base and unless I'm missing something has no advantages over using a real method. In fact, in the face of testability a separate method is preferred.

2021-09-10 12:40 UTC, chvp commented on app/helpers/renderers/feedback_table_renderer.rb
> +      LCSCsvDiffer
`TextDiffer` and `CsvDiffer` seem fine to me.

2021-09-10 12:53 UTC, inteon commented on app/helpers/renderers/lcs_csv_differ.rb
> +  def self.render_accepted(builder, generated)
because in case of an accept, there will be no instance created of the class (the constructor runs code specific to a non-accepted situation)

2021-09-10 13:12 UTC, chvp requested changes

2021-09-10 13:12 UTC, chvp commented on app/helpers/renderers/diff_csv.rb
> +      builder << Array.new(@combined_headers.length) { |i| @gen_header_indices.index(i) }.map { |idx| idx.nil? ? '<td></td>' : %(<td class="del">#{CGI.escape_html gen_cols[idx]}</td>) }.join
This can still create a **lot** of HTML elements. Too many HTML elements on a page can noticeably slow down browsers. The text differ takes special care to do this with only a few elements. This is probably harder here if you still want this feedback to look somewhat good, but we might have to abandon that in extreme cases.

2021-09-10 13:12 UTC, chvp commented on app/helpers/renderers/diff_csv.rb
> +      build_table = lambda { |headers, is_old, cls, icon_cls, title|
Again, move this to a separate function.

2021-09-10 13:12 UTC, chvp commented on app/helpers/renderers/diff_csv.rb
> +              method(is_old ? :simple_old_row : :simple_new_row).call(builder)
Just use an if statement instead of adding extra indirection. (Same below.)

2021-09-10 13:12 UTC, chvp commented on app/helpers/renderers/diff_csv.rb
> +      builder << Array.new(@combined_headers.length) { |i| @gen_header_indices.index(i) }.map { |idx| idx.nil? ? '<td></td>' : %(<td class="del">#{CGI.escape_html gen_cols[idx]}</td>) }.join
This is also a pretty long line. Use `.<call> do |arg| ... end` syntax to split this over multiple lines.

2021-09-10 13:34 UTC, inteon commented on app/helpers/renderers/diff_csv.rb
> +    extract_headers = lambda { |text|
I'm not sure if we can make Diff::LCS.sdiff work on a table, now I use the function on the lines first and then parse and apply sdiff on the columns.

2021-09-10 13:37 UTC, chvp commented on app/helpers/renderers/diff_csv.rb
> +    extract_headers = lambda { |text|
I'm pretty sure the LCS differ should be able to handle that.

2021-09-10 13:39 UTC, chvp commented on app/helpers/renderers/diff_csv.rb
> +    extract_headers = lambda { |text|
See for example this output:
```
irb(main):003:0> Diff::LCS.sdiff [[:a, :b], [:d, :e]], [[:a, :b, :c], [:d, :e]]
=> [#<Diff::LCS::ContextChange: ["!", [0, [:a, :b]], [0, [:a, :b, :c]]]>, #<Diff::LCS::ContextChange: ["=", [1, [:d, :e]], [1, [:d, :e]]]>]
```

2021-09-10 13:52 UTC, inteon commented on app/helpers/renderers/diff_csv.rb
> +      builder << Array.new(@combined_headers.length) { |i| @gen_header_indices.index(i) }.map { |idx| idx.nil? ? '<td></td>' : %(<td class="del">#{CGI.escape_html gen_cols[idx]}</td>) }.join
It should 'only' create 1 element per column. Will first try some other changes to improve performance.

2021-09-10 14:01 UTC, inteon commented on app/helpers/renderers/diff_csv.rb
> +    extract_headers = lambda { |text|
ok, cool; I'll try that

2021-09-10 14:37 UTC, inteon commented on app/helpers/renderers/diff_csv.rb
> +    extract_headers = lambda { |text|
Seems to work, thank you for the improvement!

2021-09-10 17:53 UTC, inteon commented
I updated the code as requested, below are the timing results of some requests on my local computer:
```
CsvDiffer - 32 cols 1000 rows
501.2ms | Allocations: 608735
486.6ms | Allocations: 556962
526.4ms | Allocations: 556948
399.3ms | Allocations: 556942
649.3ms | Allocations: 556941
424.6ms | Allocations: 556947
502.2ms | Allocations: 556945
405.6ms | Allocations: 556945

TextDiffer - 32 cols 1000 rows
241.5ms | Allocations: 143148
174.0ms | Allocations: 94615
283.1ms | Allocations: 94610
376.1ms | Allocations: 94607
176.9ms | Allocations: 94608
161.0ms | Allocations: 94606
  
CsvDiffer - 32 cols 100 rows
111.8ms | Allocations: 145770
63.4ms | Allocations: 96886
74.9ms | Allocations: 96882
76.6ms | Allocations: 96877
40.7ms | Allocations: 96877
49.2ms | Allocations: 96877
40.5ms | Allocations: 96881

TextDiffer - 32 cols 100 rows
69.2ms | Allocations: 66493
19.7ms | Allocations: 18007
23.3ms | Allocations: 17996
53.6ms | Allocations: 18000
19.9ms | Allocations: 17993
24.2ms | Allocations: 18000
31.3ms | Allocations: 17996
18.2ms | Allocations: 18000
18.0ms | Allocations: 17993

CsvDiffer - 100 cols 100 rows
135.4ms | Allocations: 301609
191.0ms | Allocations: 252706
204.2ms | Allocations: 252698
91.0ms | Allocations: 252708
85.4ms | Allocations: 252710
85.7ms | Allocations: 252717
96.8ms | Allocations: 252724

TextDiffer - 100 cols 100 rows
73.6ms | Allocations: 72305
21.8ms | Allocations: 23818
36.3ms | Allocations: 23804
24.5ms | Allocations: 23811
25.8ms | Allocations: 23804
38.0ms | Allocations: 23814
23.8ms | Allocations: 23811
22.6ms | Allocations: 23811
```
It seems like the CsvDiffer is slower than the TextDiffer; it also does a lot more allocations (I guess this is due to the extra csv-decode step).

2021-09-11 06:52 UTC, chvp commented
Is this always one table or multiple?

2021-09-11 07:45 UTC, inteon commented
> Is this always one table or multiple?

This is 1 big table (as described eg. 1000 rows and 32 cols) and 1 small table (probably negligible).
The output was initially generated by the sql judge eg.:
![image](https://user-images.githubusercontent.com/42113979/132940605-bb9e9be9-a2d7-4df5-ab63-16a6019e1a45.png)
![image](https://user-images.githubusercontent.com/42113979/132940619-fbafa515-8df4-49d1-8145-6deed21c9d36.png)

2021-09-11 07:53 UTC, bmesuere commented
Can you retest with multiple tables/tests in the same result? We have no control over how many tests a teacher might include in their exercise (we recently had someone using 5000 tests).

The timing is for the entire feedback set. Part of that is a fixed cost, part of it will scale with the number of tests. It would be interesting to see how it scales.

2021-09-13 14:32 UTC, inteon commented
I added an extra constraint, now the constraints are:
- if more than 20 columns > use text rendering instead of csv rendering
- if more than 100 rows > use simplified csv rending

This results in the following benchmarks:
```
ALL: 6 chars per field, 50 tables (rows x columns)

100 x 100 -> (text fallback)
Duration: 635.1ms | Allocations: 299391
Duration: 577.8ms | Allocations: 251725
Duration: 602.0ms | Allocations: 251720
Duration: 553.1ms | Allocations: 251727
500 x 20  -> (simplified view)
Duration: 1214.1ms | Allocations: 1715646
Duration: 1051.4ms | Allocations: 1668200
Duration: 1187.4ms | Allocations: 1668202
Duration: 1200.1ms | Allocations: 1668200
Duration: 1237.9ms | Allocations: 1668197
100 x 20  -> (no fallback)
Duration: 1405.0ms | Allocations: 3819983
Duration: 1185.6ms | Allocations: 3773643
Duration: 1383.5ms | Allocations: 3772518
Duration: 1473.9ms | Allocations: 3826372
Duration: 1253.0ms | Allocations: 3772573
1000 x 3    -> (simplified)
Duration: 609.9ms | Allocations: 1368229
Duration: 788.6ms | Allocations: 1320804
Duration: 678.4ms | Allocations: 1320797
Duration: 658.1ms | Allocations: 1320805
3    x 1000 -> (text fallback)
Duration: 195.4ms | Allocations: 152149
Duration: 233.6ms | Allocations: 104550
Duration: 132.3ms | Allocations: 104543
Duration: 144.0ms | Allocations: 104539
```

2021-09-15 14:39 UTC, bmesuere requested changes
The code is already much improved 👍 

I left some comments, but as a general remark I am still missing more comments. For each of the functions, it should be clear what the function does and what the format of the input and output is.

I also took the liberty to rewrite the start post of the pull request a bit.

2021-09-15 14:39 UTC, bmesuere commented on app/helpers/renderers/csv_differ.rb
> +    first_line, = raw.lstrip.split("\n", 2)
```suggestion
    first_line = raw.lstrip.lines.first
```

2021-09-15 14:39 UTC, bmesuere commented on app/helpers/renderers/csv_differ.rb
> +  def self.usable?(raw)
```suggestion
  def self.limited_columns?(raw)
```

2021-09-15 14:39 UTC, bmesuere commented on app/helpers/renderers/feedback_table_renderer.rb
> +    if t[:format] == 'csv' && CsvDiffer.usable?(t[:generated]) && CsvDiffer.usable?(t[:expected])
```suggestion
    if t[:format] == 'csv' && CsvDiffer.limited_columns?(t[:generated]) && CsvDiffer.limited_columns?(t[:expected])
```

2021-09-15 14:39 UTC, bmesuere commented on app/helpers/renderers/csv_differ.rb
> +          builder << @combined_headers.join
I think this is user input and needs to be escaped?

2021-09-15 14:39 UTC, bmesuere commented on app/helpers/renderers/csv_differ.rb
> +  end
These functions look very similar, can they be combined?

2021-09-15 14:39 UTC, bmesuere commented on app/helpers/renderers/csv_differ.rb
> +  def split_build_table(builder, headers, is_old)
what is the meaning of `is_old`? Is this really the best name?

2021-09-15 14:47 UTC, inteon commented on app/helpers/renderers/csv_differ.rb
> +          builder << @combined_headers.join
@combined_headers is escaped already:
https://github.com/dodona-edu/dodona/pull/3065/files#diff-92f0d0cfac0130a6a7673e9ce05d27033bebb84e9428a7aa354a74e3430c46f9R294-R337

2021-09-15 15:24 UTC, inteon commented on app/helpers/renderers/csv_differ.rb
> +  end
yes, done

2021-09-15 15:26 UTC, inteon commented on app/helpers/renderers/csv_differ.rb
> +  def split_build_table(builder, headers, is_old)
changed it to `is_generated_output`

2021-09-15 16:35 UTC, bmesuere approved these changes

2021-09-16 07:35 UTC, chvp approved these changes

2021-09-16 07:35 UTC, merged