Implement OIDC identity provider
dodona-edu/dodona pull request #3079
Opened 2021-09-09 09:21 UTC by thepieterdc

This pull request implements OIDC as an identity provider. The first use case is the Flemish government, documentation is available at https://authenticatie.vlaanderen.be/docs/beveiligen-van-toepassingen/integratie-methoden/oidc/technische-info/discovery-url/.

:exclamation: If you receive an `OpenIDConnect::Discovery::DiscoveryFailed` exception, this can be because of a present or absent trailing slash (`/`) in the issuer value. Some issuers include this, others don't. 

## Setup test
Add a new provider with the following settings:
```
irb(main):001:0> Provider::Oidc.create!(client_id: 'the-client-id', issuer: 'https://authenticatie-ti.vlaanderen.be/op')
```

## Setup production
Add a new provider with the following settings:
```
irb(main):001:0> Provider::Oidc.create!(client_id: 'the-client-id', issuer: 'https://authenticatie.vlaanderen.be/op')
```

## Displaying a provider in the frontend
Similar to `LTI` and `SAML`, the `provider` must be passed along in the request:
```ruby
 <%= link_to omniauth_authorize_path(:user, Provider::Oidc.sym, provider: provider_comes_here) do %>
Sign in!
<% end %>
```

## Testing
To test this, create a provider with the following settings. This issuer has whitelisted the callbacks for both `dodona.localhost:3000`, `mestra.ugent.be`, `naos.ugent.be` and `dodona.ugent.be`.
```ruby
irb(main):001:0> Provider::Oidc.create!(client_id: '4v22yzEh92pcRylWfEsXe1wtMlgQgE9x', issuer: 'https://dodona-oidc-test.eu.auth0.com/')
```

Closes #3022

2021-09-09 09:31 UTC, bmesuere commented on lib/OIDC/auth/settings.rb
> +          response_type: :id_token,
```suggestion
          response_type: :code,
```

2021-09-09 09:36 UTC, bmesuere commented on lib/OIDC/auth/settings.rb
> +            redirect_uri: "https://#{Rails.configuration.default_host}/users/auth/oidc/callback"
```suggestion
            redirect_uri: "https://#{Rails.configuration.default_host}/users/auth/vla/callback"
```

2021-09-22 12:20 UTC, bmesuere requested changes
When the callback url is triggered, we to use the correct settings to proceed. For this, we need to know which provider to use. A mechanism was implemented that can extract the provider id from the returned state, however it doesn't seem to be correctly set in the first place.

2021-09-22 12:20 UTC, bmesuere commented on lib/LTI/jwk.rb
> +    def get_jwks_content(uri)
I'm not sure why, but by fixing this typo, one of the tests fails: 
```
      SocketError: getaddrinfo: Name or service not known (stark.name:80)
          lib/LTI/jwk.rb:29:in `get_jwks_content'
          lib/LTI/jwk.rb:22:in `parse_jwks_uri'
          lib/LTI/messages.rb:14:in `parse_message'
          app/controllers/concerns/set_lti_message.rb:11:in `set_lti_message'
      # lib/LTI/jwk.rb:29
      # lib/LTI/jwk.rb:22
      # lib/LTI/messages.rb:14
      # app/controllers/concerns/set_lti_message.rb:11
      # test/controllers/lti_controller_test.rb:24
```

This error is because we try to fetch key urls from an auto-generated address which of course fails. This can probably be fixed by stubbing the call, but I don't know why it passed in the first place.

2021-09-22 12:20 UTC, bmesuere commented on lib/LTI/jwk.rb
> +    def get_jwks_content(uri)
I fixed this. The reason was that this call was in fact stubbed, but only for the wrongly spelled name.

2021-09-22 23:02 UTC, thepieterdc commented
> When the callback url is triggered, we to use the correct settings to proceed. For this, we need to know which provider to use. A mechanism was implemented that can extract the provider id from the returned state, however it doesn't seem to be correctly set in the first place.

Should be fixed in https://github.com/dodona-edu/dodona/pull/3079/commits/68a1a4d68790e237a983ecbccde5946e85848eb8

2021-09-23 09:05 UTC, bmesuere commented on lib/OIDC/auth/setup.rb
> +          parsed = state[1].to_i
```suggestion
          parsed = state[0].to_i
```

2021-10-02 10:52 UTC, chvp reviewed
Code looks good, thanks a lot :+1: 

(I obviously wasn't able to test the functionality.)

2021-10-02 10:52 UTC, chvp commented on lib/OIDC/auth/strategy.rb
> +        @user_info = ::OpenIDConnect::ResponseObject::UserInfo.new(decoded)
This is specific to the Vlaamse Overheid, right? I feel like that should at least be noted in a comment that this will have to be extracted/changed when we add another OIDC provider.

2021-10-02 11:55 UTC, thepieterdc commented on lib/OIDC/auth/strategy.rb
> +        @user_info = ::OpenIDConnect::ResponseObject::UserInfo.new(decoded)
It is indeed. Will do so

2021-10-03 10:19 UTC, bmesuere requested changes

2021-10-03 10:19 UTC, bmesuere commented on lib/OIDC/auth/settings.rb
> +          scope: [:openid, :profile]
Don't we also need the `vo` scope for things like email?

2021-10-03 10:19 UTC, bmesuere commented on lib/OIDC/auth/settings.rb
> +          state: lambda { format("%d-%s", provider.id, SecureRandom::hex(16)) }
Add comment about encoding the provider id in the state to be able to retrieve it later at callback time.

2021-10-03 10:19 UTC, bmesuere commented on lib/OIDC/auth/strategy.rb
> +        @client ||= ::OIDC::Client.new(client_options.merge(audience: options.issuer))
In the end, was the audience returned by VO according to the spec or did you make changes to it? If yes, can you add a comment explaining what was the default and what you changed?

2021-10-03 10:19 UTC, bmesuere commented on lib/OIDC/auth/strategy.rb
> +        decoded["email"] = decoded["vo_email"]
Related to my previous question, is the vo_email field present also if we don't request the scope?

2021-10-03 10:19 UTC, bmesuere commented on lib/OIDC/client.rb
> +    def authorization_code=(code)
This was monkey patched from the library? If yes, add a comment about why + changes.

2021-10-03 10:25 UTC, thepieterdc commented on lib/OIDC/auth/settings.rb
> +          scope: [:openid, :profile]
Indeed, done :)

2021-10-03 18:27 UTC, thepieterdc commented on lib/OIDC/auth/strategy.rb
> +        decoded["email"] = decoded["vo_email"]
It is not, we will need to change this when implementing other OIDC providers. My proposal is to not abstract this logic away just yet, but wait until we in fact require additional OIDC providers. This way we can extract everything Vlaamse Overheid-specific at once.

2021-10-03 18:28 UTC, thepieterdc commented on lib/OIDC/client.rb
> +    def authorization_code=(code)
Not really monkey patched (as in, a change to the underlying library should/will not affect us), just a different client was injected.

2021-10-04 08:09 UTC, bmesuere approved these changes
👍 great work!

2021-10-04 10:12 UTC, merged