Series graph html legends
dodona-edu/dodona pull request #3125
Opened 2021-09-21 14:57 UTC by tibdhond

The visualisation legends have been rewritten into html (instead of svg). Several styling attributes have been moved to the stylesheet. I also used the opportunity to give the colour boxes rounded colours since I feel like it looks a bit better.

![image](https://user-images.githubusercontent.com/32074366/134194250-545a3478-200e-4f2e-9028-8fc698fc439c.png)

![image](https://user-images.githubusercontent.com/32074366/134194494-a3024982-5fec-4ba3-ab1e-536a74f24aec.png)

Closes #3019 .

2021-10-02 10:57 UTC, chvp reviewed
Can we not generate the legends in the template files now? Or would that make coloring the indicators too complex?

2021-10-03 09:57 UTC, bmesuere requested changes
Text reflow with many items/narrow screens (one of the main reasons of this PR) isn't fixed.

![image](https://user-images.githubusercontent.com/481872/135748702-a90e7351-693d-49f0-bc61-12d092978b5b.png)

The squares should always be square, only the labels should shrink.

2021-10-03 17:59 UTC, tibdhond commented
@chvp For the stacked status graph this is probably possible, but it'll probably be a lot harder to for the cumulative graph since the amount of legend items can vary.  I'm not sure if there's an easy/elegant fix for this using ruby/css.

2021-10-03 18:01 UTC, bmesuere commented
> @chvp For the stacked status graph this is probably possible, but it'll probably be a lot harder to for the cumulative graph since the amount of legend items can vary. I'm not sure if there's an easy/elegant fix for this using ruby/css.

I'm ok with doing this in JS

2021-10-03 18:09 UTC, tibdhond commented
A 'flex-wrap' seems to have fixed both the text and the square issue, but I also added a 'min-width' to the boxes for good measure.

2021-10-04 13:09 UTC, bmesuere approved these changes

2021-10-04 13:09 UTC, bmesuere commented on app/assets/stylesheets/components/visualisations.css.scss
> +  flex-wrap: wrap;
```suggestion
  flex-wrap: wrap;
  overflow: hidden;
```

2021-10-04 13:09 UTC, bmesuere commented on app/assets/stylesheets/components/visualisations.css.scss
> +      min-width: 15px;
```suggestion
```

2021-10-04 13:20 UTC, merged