Add warning icon when question has newer submission
dodona-edu/dodona pull request #3136
Opened 2021-09-29 16:27 UTC by chvp

![screenshot_2021-09-29-182354](https://user-images.githubusercontent.com/42220376/135310095-20c222b6-6fbc-4f12-9f5c-00b735cb4fc7.png)

- [ ] Tests were added
- [ ] Documentation update can be found at dodona-edu/dodona-edu.github.io#

Closes #2540 .

2021-09-29 16:51 UTC, niknetniko commented
Do we want to show this (with the current wording) to the students themselves?

2021-09-29 16:56 UTC, pdawyndt commented
Would be handy if the warning also links to the other submissions of the student for this exercise. Why not show the number of upstream and downstream submissions as we also do in evaluations?

2021-09-29 17:05 UTC, chvp commented
> Would be handy if the warning also links to the other submissions of the student for this exercise. Why not show the number of upstream and downstream submissions as we also do in evaluations?

There is no room for this in the annotation interface. It's also far too involved for the usecase (which is a quick check that the student hasn't fixed their own problem already).

> Do we want to show this (with the current wording) to the students themselves?

Right, forgot that students will also see this when picking the wording. Showing to students doesn't seem like a problem to me (might remind them to mark their own question as answered), but wording should obviously be changed to accommodate that. Problem is that we don't have easy access to the user type in the location where we pick the translation, so it's preferable to come up with something generic that works for both.

2021-09-30 07:24 UTC, chvp commented
I tweaked the wording so that it works for both students and teachers.

2021-09-30 07:59 UTC, niknetniko requested changes

2021-09-30 07:59 UTC, niknetniko commented on app/models/question.rb
> +    Submission.where(id: (id + 1).., exercise_id: submission.exercise_id, course_id: course_id, user_id: submission.user_id).first
```suggestion
    Submission.where(id: (submission.id + 1).., exercise_id: submission.exercise_id, course_id: course_id, user_id: submission.user_id).first
```
If I understand correctly.

2021-09-30 08:11 UTC, niknetniko approved these changes

2021-10-02 12:16 UTC, bmesuere requested changes
- hasWarning and warningUrl are implemented in a generic way in the Annotation class (which is good), but the tooltip title is very specific. Is there a reason for this?
- Can we use the bootstrap (popper) tooltip instead of the title attribute (which can take a while to show up).
- I'm not sure about the size of the icon. There is a big contrast in size and color with the gray small text. Maybe mdi-12 is more appropriate here? Or a blue info icon because there is nothing actually wrong?
- Do we also want to show this warning for completed questions? Or only for open questions?

Regarding the remark of @pdawyndt: I have been thinking about something like this when I was working on the redesign. The idea was to show some kind of timeline at the top of the submissions since there we only use the left side of the page to show the status. However, I haven't come up with a good design yet.

2021-10-02 12:16 UTC, bmesuere commented on config/locales/js/en.yml
> +      has_newer_submission: There is a newer solution since this question. Click here to go to their newest submission.
```suggestion
      has_newer_submission: There was a newer submission since this question. Click here to go to the latest submission.
```

2021-10-02 15:29 UTC, chvp commented
> * hasWarning and warningUrl are implemented in a generic way in the Annotation class (which is good), but the tooltip title is very specific. Is there a reason for this?

Other code in this file does this as well. We could get the warning text in the same way as the URL, but like for the other code it feels to me like a bridge we should cross once it's necessary.

> * Can we use the bootstrap (popper) tooltip instead of the title attribute (which can take a while to show up).

Sure, I'll change this.

> * I'm not sure about the size of the icon. There is a big contrast in size and color with the gray small text. Maybe mdi-12 is more appropriate here? Or a blue info icon because there is nothing actually wrong?

I'll change it to a blue info icon.

> * Do we also want to show this warning for completed questions? Or only for open questions?

Especially with the icon change it doesn't feel like it does any harm to show it for completed questions as well.

2021-10-02 18:13 UTC, bmesuere approved these changes
Looks good! Do you have a screenshot to update the PR start?

2021-10-02 18:18 UTC, merged

2021-10-02 19:23 UTC, pdawyndt commented
Some iDeal for a submission history in #925