Finalize the heatmap in the series visualization
dodona-edu/dodona pull request #3166
Opened 2021-10-14 20:00 UTC by tibdhond

This pull request hopes to finalize the timeseries graph. 
The graph now uses a custom binning system that can handle anywhere from bins per 5 minutes to bins per 4 weeks (and can easily be expanded).

![image](https://user-images.githubusercontent.com/32074366/143420548-37952f59-2d8b-48cd-a3fe-d19107ae8923.png)![image](https://user-images.githubusercontent.com/32074366/143421123-435f099a-81f5-4f8e-8ae6-bfb7fd8ea170.png)

Closes #3017 .

2021-10-30 17:32 UTC, tibdhond commented
- The issue with the tooltip numbers has been fixed.
- The range detection was working as intended, the configuration just wasn't broad enough. It has been expanded to also look for bin steps of 5, 10 and 30 minutes.
- Can't reproduce the not enough data bug on Naos.
- There was an error in the aligning part causing the first bins to be empty. This has been fixed.
- A first attempt at displaying the bin size has been added. Screenshots at the top of the page have been updated.
- Datetime formatting has been improved

2021-11-08 15:21 UTC, bmesuere requested changes
It seems that the functional issues are indeed fixed 👍 
Some additional suggestions:
- The legend now reads "1x[x] = 15 minutes". I would remove the "1x" and "=", and make the square white with only the outline border shown. If we don't do the below suggestion, it could probably be moved to the bottom left corner to the left of the tick marks.
- Would it be useful to add a legend mapping the color intensity to values? In don't think we really need this, so I wouldn't to this for now.
- The ticks are much improved!
- Tooltip suggestions:
  - Do we need the "van: " and "tot: "? A dash between the two values is shorter. If we keep them, they shouldn't be in bold but the values should.
  - For shorter intervals (e.g. 15 minutes), the day isn't mentioned. Suggestion: **Van:** 14:00 **Tot:** 14:15 -> **14:00 - 14:15** op woensdag 6 september.
  - 1 day: this has a "ingediende oplossingen op" prefix that's redundant
  - 1 week/2 weeks: **Maandag 2 januari - 16 januari**
  - Pluralization for the submissions e.g. "1 oplossingen"
-  Sometimes, submissions from (1 interval) after the deadline are taken into account. You can see this clearly on naos in course 3, week 12
- how does it look if we add a border (in a light-ish blue?) to the squares? The ones with low values are hard to see now in light mode on my screen

2021-11-09 17:01 UTC, tibdhond commented
Feedback has been processed, screenshots at the top of the page have been updated accordingly.

2021-11-10 09:59 UTC, chvp requested changes

2021-11-10 09:59 UTC, chvp commented on app/assets/javascripts/visualisations/timeseries.ts
> +            this.y.bandwidth()*1.5,
```suggestion
            this.y.bandwidth() * 1.5,
```

2021-11-10 09:59 UTC, chvp commented on app/assets/javascripts/visualisations/timeseries.ts
> +            .attr("transform", `translate(0, ${this.innerHeight-this.y.bandwidth()/2})`)
```suggestion
            .attr("transform", `translate(0, ${this.innerHeight-this.y.bandwidth() / 2})`)
```

2021-11-10 09:59 UTC, chvp commented on app/assets/javascripts/visualisations/timeseries.ts
> +        const unitTl = I18n.t("time.time_units");
Not clear what `Tl` means.

2021-11-10 09:59 UTC, chvp commented on app/assets/javascripts/visualisations/timeseries.ts
> +                <br>${on} ${dateFormat(d.date)}<br>
This makes days in Dutch capitalized, which should not be the case.

2021-11-10 09:59 UTC, chvp commented on config/locales/defaults/en.yml
> +    time_units:
```suggestion
    units:
```

2021-11-18 15:57 UTC, chvp requested changes
Please add whitespace around all mathematical operators for consistency with our codebase. I only noted a few in the previous review, but there are others still.

2021-11-18 15:57 UTC, chvp commented on app/assets/javascripts/visualisations/timeseries.ts
> +                <br>${on} ${dateFormat(d.date)}<br>
Just changing the casing in the translation strings is not good enough. In the other string the day is the first element of a sentence, so should be capitalised in that case.

2021-11-21 15:31 UTC, tibdhond commented
All of the spacing issues should have been fixed now.
The tooltip dates are now capitalized if they are the first word in the sentence.

2021-11-22 11:30 UTC, bmesuere commented
I would also reduce the size of the square in the legend some more to make it less prominent.

2021-11-22 11:30 UTC, bmesuere reviewed
I would also reduce the size of the square in the legend some more to make it less prominent.

2021-11-25 10:07 UTC, tibdhond commented
The box in the legend is now shrunk by two thirds.
I was also wondering if using the status icons in the tooltip would give added value (in addition to the textualstatus )?

2021-11-30 13:04 UTC, bmesuere commented
> The box in the legend is now shrunk by two thirds (screenshots updated accordingly). I was also wondering if using the status icons in the tooltip would give added value (in addition to the textualstatus )?

This is hard to say without trying, so maybe create a mockup and compare screenshots of the 2 versions?

2021-11-30 15:29 UTC, tibdhond commented
Tooltip with and without the statusicons.
I personally think it looks a lot better with the icons, it breaks up the wall of text a bit.

![image](https://user-images.githubusercontent.com/32074366/144076349-f1af840d-5997-44bc-be55-330a31a83c84.png)
![image](https://user-images.githubusercontent.com/32074366/144076594-cf0e18cb-5d78-4664-8015-7a10dfb2d14e.png)

2021-12-01 13:10 UTC, chvp reviewed
Code looks good to me. I quite like the icons in the tooltip.

2021-12-01 13:10 UTC, chvp commented on config/locales/defaults/nl.yml
> +    day_names: ["zondag", "maandag", "dinsdag", "woensdag", "donderdag", "vrijdag", "zaterdag"]
Is this used anywhere else? Because if so this will have an impact in those places as well, which we do not necessarily want.

2021-12-01 13:19 UTC, tibdhond commented on config/locales/defaults/nl.yml
> +    day_names: ["zondag", "maandag", "dinsdag", "woensdag", "donderdag", "vrijdag", "zaterdag"]
A global search for `day_names` (in vscode) only returns hits in `series_graph.ts` and the translation files, so I would assume it's not used anywhere else.

2021-12-01 13:20 UTC, chvp commented on config/locales/defaults/nl.yml
> +    day_names: ["zondag", "maandag", "dinsdag", "woensdag", "donderdag", "vrijdag", "zaterdag"]
Okay.

2021-12-12 16:19 UTC, bmesuere requested changes
Sorry for the delay in reviewing. Right now, everything in the tooltip is in bold which defies the purpose. How about in the example below but the following things in bold:
- 23:35 - 24:40
- 51 oplossingen
- 17, 9, ... (so only the numbers for the detailed part)
![image](https://user-images.githubusercontent.com/481872/145720283-9c94a2a0-cb68-4452-b3dd-15a9e92ff16b.png)


I do like the icons!

2021-12-12 18:23 UTC, tibdhond commented
Everything in the tooltip being bold was a bug caused by a missing closing tag.
Nevertheless, changes have been made as per the suggestion:
![image](https://user-images.githubusercontent.com/32074366/145724644-e8e3cd5e-1eb6-47f8-ad1d-00cb6c1e5ad7.png)

2021-12-12 18:49 UTC, bmesuere approved these changes

2021-12-13 08:37 UTC, chvp approved these changes

2021-12-13 08:37 UTC, merged