Add mailto and tooltip
dodona-edu/dodona pull request #3203
Opened 2021-11-13 19:31 UTC by BTWS2

![image](https://user-images.githubusercontent.com/56451049/141656570-276da2d3-1519-401b-aa52-287e0b96f8f5.png)
![image](https://user-images.githubusercontent.com/56451049/141656577-0416d8cf-6804-400b-92dd-19308432f0bf.png)

Closes #3201.

2021-11-14 16:14 UTC, bmesuere approved these changes
Not sure if the tooltip is needed, but ok for me.

Thanks!

2021-11-14 16:22 UTC, niknetniko approved these changes

2021-11-14 17:18 UTC, chvp requested changes
Like the issue asks, I would also add this to the user profile. For the Dodona admins, this can be useful as well.

2021-11-15 08:23 UTC, chvp requested changes
Right now, the emailaddress is also colored as a link. Personally I think this is a bit too attention-grabbing.

2021-11-15 08:23 UTC, chvp commented on app/views/course_members/_members_table.html.erb
> +        <td><span title="<%= t '.send_mail' %>"><%= mail_to(user.email) %><span></td>
The extra span isn't required. You can use the [`html_options` argument of `mail_to`](https://api.rubyonrails.org/classes/ActionView/Helpers/UrlHelper.html#method-i-mail_to) to set the title. `mail_to` also supports a `name` argument, which we can use as well.

2021-11-15 13:03 UTC, chvp commented on app/views/users/show.html.erb
> +            <%= current_user.admin? ? mail_to(@user.email) : @user.email %>
`admin?` also includes staff. `zeus?` should be used.

2021-11-15 13:14 UTC, bmesuere commented
> Right now, the emailaddress is also colored as a link. Personally I think this is a bit too attention-grabbing, especially on the profile pages. @bmesuere opinions?

If it is a link, it should look like a link? I don't have a problem with the current styling because the profile page isn't used that much.

2021-11-18 15:51 UTC, chvp requested changes
Could you rebase on latest develop when making changes? That way the checks will run for your changes.

2021-11-18 15:51 UTC, chvp commented on app/views/course_members/_members_table.html.erb
> +        <td><%= mail_to(user.email, nil, {title: t('.send_mail'), class: 'text-muted'}) %></td>
We can fill in this `nil` argument, we have the name of the user (here and in the other instances). I would also not add the text-muted class here since the link works visually in our tables.

2021-11-19 13:59 UTC, BTWS2 commented on app/views/course_members/_members_table.html.erb
> +        <td><%= mail_to(user.email, nil, {title: t('.send_mail'), class: 'text-muted'}) %></td>
I replaced `nil` with the user email. I would like to continue displaying the e-mail, because not everyone has their mailto client configured properly. I removed text-muted.

2021-11-19 15:52 UTC, BTWS2 commented
I had some trouble with the rebase because of multiple laptops, but it should be ok now.

2021-11-19 17:09 UTC, chvp commented on app/views/course_members/_members_table.html.erb
> +        <td><%= mail_to(user.email, nil, {title: t('.send_mail'), class: 'text-muted'}) %></td>
I did not realize filling in the argument would change the shown content of the `a`. In that case, leaving it empty seems like the better option. I'll change this, approve and merge.

2021-11-19 17:09 UTC, chvp approved these changes

2021-11-19 17:20 UTC, merged