Visualisation time scope control
dodona-edu/dodona pull request #3204
Opened 2021-11-14 20:14 UTC by tibdhond

This pull request

Gives the user control over the time scope of the visualisation on the course page.
It's not completely finished, but is in a state where it could be reviewed.

Closes # .

2021-11-18 16:23 UTC, chvp requested changes
I was trying to test this on naos, but the filtering doesn't seem to work correctly. I tried to apply bounds to [this series](https://naos.ugent.be/en/courses/3/#series-264-second-evaluation-group-1) to zoom in on the day of the evaluation, but got a "no data" message (even though there should have been data, when looking at the submission list).

2021-11-20 16:57 UTC, tibdhond commented
The bug seems fixed, however the initialization of the date picker doesn't seem to be on point yet. This is mostly because it's hard to find a good date to initialize on (especially for the graphs that don't use the timestamps). For now I'll leave it like this until we decide whether to keep the time scope for the non-timestamp graphs.

2022-01-10 13:49 UTC, bmesuere commented
@tibdhond can you rebase this?

2022-01-15 17:08 UTC, tibdhond commented
I moved the time scoping the the frontend. This has several advantages, but one disadvantage:
\+ No need for sanitation
\+ Data fetching is easier (since the before parts doesn't have to be calculated, D3 easily takes care of that)
\+ Date pickers are easier to configure
\- Sometimes, more data than necessary is sent to the frontend

This raises two possible ways how we can use the time scoping:

- Keep things as they are and send a request to the backend every time 'apply' is pressed (and keep the data up to date)
- Apply the scoping on previously fetched data (but potentiality miss out on new submissions)

2022-01-17 09:53 UTC, chvp requested changes

2022-01-17 09:53 UTC, chvp commented on app/assets/javascripts/visualisations/series_graph.ts
> +
This feels like it should be solved by inheritance instead of an `if` statement.

2022-01-17 09:53 UTC, chvp commented on app/policies/series_policy.rb
> +    course_admin? || true
```suggestion
    course_admin?
```

2022-01-17 10:22 UTC, tibdhond commented on app/assets/javascripts/visualisations/series_graph.ts
> +
While I do agree that this does seem like an inheritance thing, I feel like it would complicate things a bit. We would either have to:
- Duplicate everything inside the if to both the cumulative graph and heatmap (and any future graph that uses the datepickers)
- Use mixins (which might impact execution of 'super' methods/calls)
- Create a more complex hierarchy (something like: SeriesGraph > ExerciseGraph > TimeExerciseGraph > Heatmap + SeriesGraph > TimeGraph > Cumulative)
- Decouple the heatmap from its ExerciseGraph super class, copy any code inside that super class to the heatmap and make a common super class between the heatmap and the cumulative graph

2022-01-17 10:58 UTC, tibdhond commented on app/assets/javascripts/visualisations/series_graph.ts
> +
Moved some things around. The initialization of the time pickers has now been put in a function which is called from the heatmap init and cumulative init.

2022-01-17 15:37 UTC, bmesuere requested changes
In chrome, the pickers are full width instead of inline:
![image](https://user-images.githubusercontent.com/481872/149798591-b43269b5-6b44-46ce-9406-1fede79922d6.png)

The ticks seem to show the end time of the interval? Is there a reason for this? The start seems more intuitive to me.

If I load the graph for for course 3, exam group 6 on naos and select 15h as starting time, the first block of the graph seems bugged:
![image](https://user-images.githubusercontent.com/481872/149799003-3ad461bb-aae8-4be5-b471-d08604ca8c31.png)

2022-01-17 17:40 UTC, tibdhond commented
@bmesuere 
> In chrome, the pickers are full width instead of inline:

This is probably due to the style sheets not being compiled anymore (issue #3289). Not much I can do about this until this issue is fixed.

> The ticks seem to show the end time of the interval? Is there a reason for this? The start seems more intuitive to me.

I had changed this to make it consistent with the cumulative graph, but in hindsight this wasn't necessary. It has been switched back now.

> If I load the graph for for course 3, exam group 6 on naos and select 15h as starting time, the first block of the graph seems bugged:

The old data wasn't discarded on updates. This should be fixed now.

2022-01-18 08:40 UTC, chvp approved these changes
Code looks good. The styling of the pickers was indeed due to #3289 (clearing the cache and recompiling the assets on naos fixed it). Not sure about the UI (it's just two time pickers and a button, without ever making it clear what the pickers and button are for), but I'll let @bmesuere comment on that.

2022-01-18 17:34 UTC, bmesuere reviewed
I agree, this probably looks better if you use the `calendar-start` and `calendar-end` icons. You could leave out the button and update automatically if any of the two fields are changed.

2022-01-20 14:59 UTC, bmesuere approved these changes

2022-01-20 14:59 UTC, bmesuere commented
can I merge this, @tibdhond ?

2022-01-20 17:29 UTC, tibdhond commented
Looks good to me.

2022-01-20 17:29 UTC, merged