Add copy to clipboard button for submission link
dodona-edu/dodona pull request #3215
Opened 2021-11-20 21:02 UTC by BTWS2

The button works, but only copies the submission id, not the full link. How do I get the full link?

![image](https://user-images.githubusercontent.com/56451049/142740390-6f1145a4-f1b6-409f-af65-c920f0e9bab3.png)

- [ ] Documentation update can be found at dodona-edu/dodona-edu.github.io#

Closes #2213.

2021-11-22 07:42 UTC, chvp requested changes
I'm not sure I agree with this placing. Even though there is a tooltip, this will not be obviously a button. Since this has been requested independently by a number of teachers, we need this to be a lot more discoverable, IMO.

2021-11-22 07:42 UTC, chvp commented on app/views/submissions/_description.html.erb
> +        <button class="btn btn-icon" data-clipboard-text="<%= 'https://' + request.domain.to_s + submission_path(submission.id).to_s %>" title="<%= t "submissions.show.copy_submission_link" %>">
```suggestion
        <button class="btn btn-icon" data-clipboard-text="<%= submission_url(submission.id) %>" title="<%= t "submissions.show.copy_submission_link" %>">
```

2021-11-22 11:36 UTC, bmesuere reviewed
I agree that we need a better solution for this than the current proposal. The entire result area must be taken into account. For now, I/we don't have time to design this.

2022-04-16 17:56 UTC, bmesuere commented
This was mostly solved by adding clickable and linkable submission numbers to the ui in the previous release.

2022-04-16 17:56 UTC, closed without merging