Update readme to improve setup script for new users
dodona-edu/dodona pull request #3273
Opened 2022-01-05 13:21 UTC by jorg-vr

This pull request edits the readme file.

The changes reflect the information I lacked to setup dodona.

This includes explicitly specifying some basic requirements such as `yarn`, `ruby` and `node`

I also updated the part on `Evaluating exercises locally`

2022-01-05 13:30 UTC, bmesuere approved these changes

2022-01-05 13:56 UTC, niknetniko commented on README.md
> +5. install correct `node` version using `nvm` and [yarn](https://yarnpkg.com/)
```suggestion
5. Install the correct `node` version using `nvm` and [yarn](https://yarnpkg.com/)
```

2022-01-05 13:56 UTC, niknetniko commented on README.md
> +4. Install correct `ruby` version using [RVM](https://rvm.io/) and install `rails`
```suggestion
4. Install the correct `ruby` version using [RVM](https://rvm.io/) and install `rails`
```

2022-01-05 14:43 UTC, rien commented on README.md
> +    CREATE DATABASE `dodona_test-N`;
I don't think this is needed, since rails will drop and create these databases itself when you do `rails db:setup` (that was the reason this was omitted initially, I think).

2022-01-05 14:50 UTC, jorg-vr commented on README.md
> +    CREATE DATABASE `dodona_test-N`;
I had issues with the following statements (Granting users access to non existing databases)
This is why I created those statements
But in the end I also had to change the other sql lines as well to fix my issues, so I am not sure if the create database lines where actually needed

2022-01-05 14:52 UTC, chvp requested changes

2022-01-05 14:52 UTC, chvp commented on README.md
> +4. Install the correct `ruby` version using [RVM](https://rvm.io/) and install `rails`
Installing `rails` should not be required. The `rails` gem from the `bundle install` below should be used.

2022-01-05 14:52 UTC, chvp commented on README.md
> +2. run `docker pull dodona/dodona-python`
```suggestion
2. Run `docker pull dodona/dodona-python`
```

2022-01-05 15:01 UTC, rien commented on README.md
> +    CREATE DATABASE `dodona_test-N`;
Probably because the `@'localhost'` part was missing. I've tested this locally and performing a `GRANT` statement on a non-existing database should work.

2022-01-10 09:20 UTC, chvp approved these changes

2022-01-10 12:41 UTC, merged