Rights request: Show correct error message when motivation is not filled out
dodona-edu/dodona pull request #3274
Opened 2022-01-05 16:21 UTC by jorg-vr

This pull request fixes a bug where the user was shown misleading information when he hadn't filled out a motivation message.

Right now the following message is shown:
![image](https://user-images.githubusercontent.com/21177904/148251156-774c405d-4cac-4e36-8323-8af2dcb24c58.png)

The error message saying you already applied still appears when it should:
![image](https://user-images.githubusercontent.com/21177904/148251732-3dbb16e5-453f-49f8-9d58-871274278828.png)

Closes #3124 .

2022-01-05 16:46 UTC, bmesuere requested changes

2022-01-05 16:46 UTC, bmesuere commented on app/views/rights_requests/new.html.erb
> +        <% if policy(RightsRequest).create? or current_user&.rights_request.errors.any?%>
It seems strange get the rights_request from the current user. You should be able to access it through `@rights_request`. 

In addition, we always add a space before the `%>`. Our linter doesn't check for this in erb files :(

2022-01-06 12:46 UTC, bmesuere approved these changes

2022-01-06 14:20 UTC, niknetniko requested changes

2022-01-06 14:20 UTC, niknetniko commented on app/views/rights_requests/new.html.erb
> +        <% if policy(RightsRequest).create? or @rights_request.errors.any? %>
```suggestion
        <% if policy(RightsRequest).create? || @rights_request.errors.any? %>
```

I think we generally prefer `&&` and `||` over `and` and `or`, as those last ones have some non obvious precedence rules.

2022-01-06 14:20 UTC, niknetniko commented on app/views/rights_requests/new.html.erb
> +        <% if policy(RightsRequest).create?  or @rights_request.errors.any? %>
```suggestion
        <% if policy(RightsRequest).create?  || @rights_request.errors.any? %>
```

2022-01-06 14:25 UTC, jorg-vr commented on app/views/rights_requests/new.html.erb
> +        <% if policy(RightsRequest).create? or @rights_request.errors.any? %>
Thanks for the feedback, learned something new now by looking it up :)

2022-01-06 14:51 UTC, niknetniko approved these changes

2022-01-06 14:56 UTC, merged

2022-01-09 14:08 UTC, chvp commented
I'm not sure this is the correct fix. I feel like the policy's `create?` should not return false.