Sort copy courses list to show own courses first
dodona-edu/dodona pull request #3277
Opened 2022-01-06 12:31 UTC by jorg-vr

This pull request changes the order a user sees the course list when he wants to copy a course. Now their own courses are displayed first. Original order is kept as secondary ordering.

![image](https://user-images.githubusercontent.com/21177904/148382910-6ce9a5e5-94a6-44cb-801e-592b19201324.png)

Closes #1661.
Closes #3049.

2022-01-06 12:53 UTC, bmesuere requested changes
In this implementation, it isn't really clear why some courses are sorted first. It would be clearer if the ones where the user is admin have an additional icon as is done in the general course listing: 

![image](https://user-images.githubusercontent.com/481872/148385567-912cfd40-6235-4f8e-a3c6-1dbea461a4bb.png)

I'm not sure about the way the sorting is done (do we already require will_paginate/array in other pages?). Is this done at the ruby side or using a query?

2022-01-06 14:54 UTC, jorg-vr commented
I have added the Icon
![image](https://user-images.githubusercontent.com/21177904/148399427-958ae388-6a88-4792-85ec-6bbc86e69bdc.png)

@bmesuere  `require 'will_paginate/array'` is not used anywhere else in the code base
This was needed because `sort_by` returns an array instead of an `Active Record Relation`
sort_by preforms the sort in ruby, not in a database query

The query order/reorder does not support custom functions like `current_user.course_admin?(course)`, which is why I chose `sort_by`
I could write a database statement with the same result, but that would be rewriting the functionality of `current_user.course_admin?(course)` which could lead to two differing implementations in the future

Other option is using two or three separate select statements as in #3049 (but merge them instead of duplicating the listing code as @chvp  suggested)

2022-01-07 08:15 UTC, jorg-vr commented
Updated code `sort_by` to a `select` and `reject` statement to move the filtering logic to the database and also reduce complexity

`require 'will_paginate/array'` is still needed

2022-01-07 08:24 UTC, jorg-vr commented
By using `concat` instead of `+` I removed the need for `require 'will_paginate/array'`

2022-01-09 10:54 UTC, bmesuere approved these changes
Ok for me if it is for @chvp 

We generally try to keep the PR start post up to date before merging so it reflects the state of what is being merged. This usually means updating the screenshots to the final version.

2022-01-10 09:21 UTC, chvp approved these changes

2022-01-10 09:47 UTC, niknetniko approved these changes

2022-01-10 12:43 UTC, merged