Add external URL to machine annotations
dodona-edu/dodona pull request #3278
Opened 2022-01-06 13:04 UTC by jorg-vr

This pull request is a work in progress: 
Will add more info later on in the process.

- [ ] Tests were added
- [ ] Documentation update can be found at dodona-edu/dodona-edu.github.io#

Related to #2845 .

2022-01-09 10:58 UTC, bmesuere reviewed
We generally use "draft pull requests" instead of a WIP label. This prevents the PR from accidentally being merged (and doesn't trigger the automatic review request).

2022-01-12 16:37 UTC, niknetniko requested changes
We probably also want to add this to the full format, in `public/schemas/judge_output.json`.

2022-01-12 17:19 UTC, bmesuere approved these changes
I agree with @niknetniko his comment, but looks good otherwise.

2022-01-13 08:16 UTC, niknetniko approved these changes

2022-01-13 08:22 UTC, merged