Mark score item as busy before delay, to let page wait until delay finish
dodona-edu/dodona pull request #3287
Opened 2022-01-11 08:44 UTC by jorg-vr

This pull request fixes the issue that a user can go to the next exercise before the scores are saved.

Closes #3212.

2022-01-11 10:22 UTC, niknetniko requested changes

2022-01-11 10:22 UTC, niknetniko commented on app/assets/javascripts/feedback/score.ts
> +            this.markBusy();
This seems to break the case where you use the up/down buttons of the form field, since those buttons immediately trigger the `change` event. This is the reason why we only call `visualiseUpdating` here: we apply visuals to ensure the user is aware we know a change has occurred, but we cannot disable the input yet, since the user might want to make further changes.

I think a potential solution worth investigating is moving the line `this.parent.registerUpdating(this.scoreItemId);` from `markBusy` to `visualiseUpdating`. There is code to make sure if you press 'Next', it will wait for the updating score items to complete.

2022-01-12 08:53 UTC, jorg-vr commented on app/assets/javascripts/feedback/score.ts
> +            this.markBusy();
Tried your solution and this also fixed the the `next` button issue, but the issue with being able to press the up and down buttons while updating remained (on slow internet)

Fixed that by disabling those as well in the `disableInputs` method. Now everything works as expected in my tests

2022-01-12 08:59 UTC, jorg-vr commented on app/assets/javascripts/feedback/score.ts
> +            this.markBusy();
good to know is that the `change` event only triggers after the input looses focus, so I think at this point we can safely disable all inputs

2022-01-12 09:02 UTC, jorg-vr commented on app/assets/javascripts/feedback/score.ts
> +            this.markBusy();
Ah wait I get what you mean with up/won buttons, will change

2022-01-12 09:20 UTC, jorg-vr commented on app/assets/javascripts/feedback/score.ts
> +            this.markBusy();
Ok applied your feedback now

2022-01-12 10:20 UTC, niknetniko approved these changes

2022-01-12 16:11 UTC, chvp approved these changes

2022-01-12 17:12 UTC, bmesuere approved these changes

2022-01-13 08:13 UTC, merged