Make cloning git repository asynchronous
dodona-edu/dodona pull request #3295
Opened 2022-01-14 10:43 UTC by jorg-vr

This pull request

- [ ] Tests were added
- [ ] Documentation update can be found at dodona-edu/dodona-edu.github.io#

Closes # .

2022-01-16 15:47 UTC, bmesuere requested changes
I added a suggestion to rephrase the message to the user (to be adapted/translated for the other string if ok).

You have added the job to the git_clone queue, but no workers are watching this queue. Option 1 is to add this queue to the current workers in the config/deploy files, option 2 is to reuse an existing queue. @chvp is better placed to decide which option is best.

2022-01-16 15:47 UTC, bmesuere commented on config/locales/views/judges/en.yml
> +      clone_incomplete: "Cloning in progress. It can take a few minutes before the judge is uploaded to the server and ready for use."
```suggestion
      clone_incomplete: "We are adding your judge to Dodona. This can take up to five minutes."
```

2022-01-17 08:15 UTC, chvp commented
I think using the same queue as the one used for reprocessing the repositories makes the most sense. This is currently the default queue, but we might want to make this a named queue also (in light of efforts related to #3299).

2022-01-17 09:34 UTC, jorg-vr commented
I updated the translations and added a 'git' queue for cloning and reprocessing repositories

2022-01-17 15:46 UTC, bmesuere requested changes
Some more minor text suggestions. We try to avoid u/uw in communicating with users. Right now, the additional message is shown as callout on the top of the page, right under the "success" message which is styled differently. I would maybe move the message to inside the card (e.g., right side).

2022-01-17 15:46 UTC, bmesuere commented on config/locales/views/judges/en.yml
> +      clone_incomplete: "We are adding your judge to Dodona. This can take up to five minutes."
```suggestion
      clone_incomplete: "We are now adding your judge to Dodona. It can take up to five minutes until it becomes available."
```

2022-01-17 15:46 UTC, bmesuere commented on config/locales/views/judges/nl.yml
> +      clone_incomplete: "Wij zijn uw judge aan het toevoegen aan Dodona. Dit kan tot 5 minuten duren."
```suggestion
      clone_incomplete: "We zijn je judge nu aan het toevoegen aan Dodona. Het kan tot 5 minuten duren eer hij beschikbaar is."
```

2022-01-17 15:46 UTC, bmesuere commented on config/locales/views/repositories/en.yml
> +      clone_incomplete: "We are adding your repository to Dodona. This can take up to five minutes."
```suggestion
      clone_incomplete: "We are now adding your repository to Dodona. It can take up to five minutes until your exercises show up."
```

2022-01-17 15:46 UTC, bmesuere commented on config/locales/views/repositories/nl.yml
> +      clone_incomplete: "Wij zijn uw repository aan het toevoegen aan Dodona. Dit kan tot 5 minuten duren."
```suggestion
      clone_incomplete: "We zijn je repository nu aan het toevoegen aan Dodona. Het kan tot 5 minuten duren eer je oefeningen beschikbaar zijn."
```

2022-01-18 08:54 UTC, chvp requested changes

2022-01-18 08:54 UTC, chvp commented on app/models/concerns/gitable.rb
> +    out != ''
Not sure about this (for two reasons). First of, I'd use Ruby's builtin File listing instead of shelling out. Also, just checking that there are files is not sufficient for knowing if the checkout finished, since it happens quite often that people add empty repositories to Dodona (sometimes even without commits).

2022-01-18 08:58 UTC, jorg-vr commented on app/models/concerns/gitable.rb
> +    out != ''
Wasn't sure how often that would happen, that does indeed break things

The only other option I can think of is adding a state field to both the judge and the repository table which is set to complete after the run (As I don't think were able to add such a field to `gitable`)

2022-01-18 09:03 UTC, chvp commented on app/models/concerns/gitable.rb
> +    out != ''
You could technically check the delayed jobs table, but I don't think that would be a cleaner solution than just keeping an extra field.

2022-01-18 17:00 UTC, chvp requested changes

2022-01-18 17:00 UTC, chvp commented on db/migrate/20220118102649_add_status_to_judges.rb
> +    add_column :judges, :status, :integer
This column should probably be `null: false` and initialised to complete for any existing repositories/judges?

2022-01-18 17:00 UTC, chvp commented on app/models/concerns/gitable.rb
> +    enum status: { unknown: 0, 'clone queued': 1, cloning: 2, 'clone complete': 3, 'clone failed': 4 }
Is the `unknown` status required? It doesn't seem used, and I feel like we have a sensible default for existing `Gitable`s? Also maybe `clone_status` as the field name and remove the spaces in the names, just to tighten things up a bit? Although I don't feel too strongly about this.

2022-01-18 17:27 UTC, bmesuere approved these changes
Except for the comment from @chvp, this looks good 👍

2022-01-18 17:41 UTC, niknetniko commented on config/locales/views/judges/nl.yml
> +      clone_failed: "Het clonen van de judge is mislukt. Kijk na of Dodona lees en schrijf rechten heeft op jouw judge."
```suggestion
      clone_failed: "Het clonen van de judge is mislukt. Kijk na of Dodona lees- en schrijfrechten heeft op jouw judge."
```

2022-01-18 17:41 UTC, niknetniko commented on app/models/concerns/gitable.rb
> +    enum status: { unknown: 0, 'clone queued': 1, cloning: 2, 'clone complete': 3, 'clone failed': 4 }
Perhaps also useful to add the `_prefix: :clone` option, which will prefix all helper methods with `clone`. This will then result in the `judge.clone_failed?`, `judge.clone_completed?`, etc. methods, instead of `judge.failed?` and `judge.completed?` if I understand correctly how it works.

If we were to use the `prefix` option, you wouldn't need to define `clone_failed?` yourself anymore (on line 53 of this file).

2022-01-18 17:41 UTC, niknetniko commented on config/locales/views/repositories/nl.yml
> +      clone_failed: "Het clonen van de repository is mislukt. Kijk na of Dodona lees en schrijf rechten heeft op jouw repository."
```suggestion
      clone_failed: "Het clonen van de repository is mislukt. Kijk na of Dodona lees- en schrijfrechten heeft op jouw repository."
```

2022-01-18 17:42 UTC, niknetniko commented on app/models/concerns/gitable.rb
> +    enum status: { unknown: 0, 'clone queued': 1, cloning: 2, 'clone complete': 3, 'clone failed': 4 }
Perhaps also useful to add the `_prefix: :clone` option, which will prefix all helper methods with `clone`. This will then result in the `judge.clone_failed?`, `judge.clone_completed?`, etc. methods, instead of `judge.failed?` and `judge.completed?` if I understand correctly how it works.

If we were to use the `prefix` option, you wouldn't need to define `clone_failed?` yourself anymore (on line 53 of this file).

2022-01-19 10:34 UTC, niknetniko approved these changes

2022-01-19 17:32 UTC, chvp commented on db/migrate/20220118102649_add_clone_status_to_judges.rb
> +    add_column :judges, :clone_status, :integer, null: false, default: 3
I wonder whether it would be a good idea to add an extra statement after this changing the default to 1. The application code already handles this, but it makes more sense for resulting default to be the initial state I think.

2022-01-19 18:16 UTC, pdawyndt commented
“lees- en schrijfrechten”

2022-01-21 21:25 UTC, chvp approved these changes

2022-01-24 10:19 UTC, merged