add line blur on hover
dodona-edu/dodona pull request #3300
Opened 2022-01-16 00:35 UTC by tibdhond

When hovering over a legend item, every line except the one corresponding to the item will be blurred.
This should greatly assist in identifying the correct line for each exercise.

![Peek 2022-01-16 01-26](https://user-images.githubusercontent.com/32074366/149642530-583bc40c-7072-4aa4-ba0b-a0d6bf9eb7f2.gif)

2022-01-16 15:29 UTC, bmesuere requested changes
This is a great improvement :+1:

2022-01-16 15:29 UTC, bmesuere commented on app/assets/javascripts/visualisations/cumulative_timeseries.ts
> +                lines.style("opacity", 0.2);
You don't need the complicated css selector here (nor the data attribute added before). The d3-way to do this is to use a function accessing the data ("d"), with a conditional operator returning 0.2 or 1.

2022-01-16 22:41 UTC, tibdhond commented on app/assets/javascripts/visualisations/cumulative_timeseries.ts
> +                lines.style("opacity", 0.2);
should be better now

2022-01-17 07:27 UTC, bmesuere approved these changes

2022-01-17 08:11 UTC, chvp approved these changes

2022-01-17 09:10 UTC, merged