Store last seen and last sign in in the database
dodona-edu/dodona pull request #3328
Opened 2022-01-24 15:06 UTC by jorg-vr

This pull request

- [ ] Tests were added
- [ ] Documentation update can be found at dodona-edu/dodona-edu.github.io#

Closes #3296  .

2022-01-24 16:02 UTC, bmesuere requested changes
I would add an index on `seen_at` since we will query this often for secondary statistics.

2022-01-24 16:02 UTC, bmesuere commented on app/controllers/application_controller.rb
> +  after_action :set_user_seen_at, if: :current_user
I would also skip this for `remote_request?` calls.

2022-01-25 08:44 UTC, jorg-vr commented
@bmesuere I have added the index but I am not 100% sure that it is a good idea. The field is updated very often, each update being slowed down by also having to update the index. 
While the added benefit only applies for our analysis requests, which will probably only happen infrequently.
So overall our database might be slowed down instead of sped up by this index

2022-01-25 10:15 UTC, bmesuere commented
@jorg-vr you are right. In addition, we will query this on elysium so the select will have no impact on the production database. We could always add an index later.

2022-01-25 16:14 UTC, niknetniko approved these changes

2022-01-26 13:06 UTC, bmesuere approved these changes
We can monitor the number of update queries in datadog and add a timeout if needed.

2022-01-26 13:24 UTC, merged