Merge complex institutions with overlapping users
dodona-edu/dodona pull request #3331
Opened 2022-01-28 13:29 UTC by jorg-vr

This pull request builds upon #3327  but is split off to keep the individual pull request manageable

- [ ] Tests were added
- [ ] Documentation update can be found at dodona-edu/dodona-edu.github.io#

Closes # .

2022-02-01 15:15 UTC, bmesuere requested changes
Right now, we already offer an institution merge on the website but this sometimes fails due to overlapping users. Since this PR provides a way to merge these institutions semi-automatically, it would be nice if the command that is needed for this is printed along with the error message that is shown when the automatic merge fails.

I'm thinking about a way on how to test this with actual data without risking data loss. The only way I can think of is copying some problematic data from the production environment to naos but this might be a lot of work (this is why #2866 would be nice).

The code itself looks ok.

2022-02-01 15:15 UTC, bmesuere commented on app/models/submission.rb
> +    AfterCommitEverywhere.after_commit do
maybe add a little comment here

2022-02-02 09:39 UTC, chvp requested changes

2022-02-02 09:39 UTC, chvp commented on app/runners/merge_institutions.rb
> +class MergeInstitutions
I'm not sure `app/runners/` is the correct location for this. `app/runners` is currently for everything related to the running of submissions, which this is unrelated to.

2022-02-02 13:29 UTC, bmesuere commented on app/runners/merge_institutions.rb
> +class MergeInstitutions
You're right, I missed the file path of this one. Since its strictly related to the rake task, was there a specific reason for not putting it in that same file?

2022-02-02 13:32 UTC, jorg-vr commented on app/runners/merge_institutions.rb
> +class MergeInstitutions
It imports from MergeUsers. Was not sure if rake tasks importing classes from other rake tasks is really the way to go.
It should probably be moved to a different folder?

2022-02-02 13:34 UTC, chvp commented on app/runners/merge_institutions.rb
> +class MergeInstitutions
Are `.rb` files allowed in `lib/tasks`. Or does that conceptually not make sense? Otherwise, storing them alongside the tasks seems fine to me.

2022-02-02 13:36 UTC, bmesuere commented on app/runners/merge_institutions.rb
> +class MergeInstitutions
maybe in a separate subdirectory in lib/tasks?

2022-02-03 09:01 UTC, chvp approved these changes

2022-02-03 09:21 UTC, niknetniko approved these changes

2022-02-03 11:41 UTC, bmesuere approved these changes
Looking forward to merge some problematic institutions :)

2022-02-03 14:25 UTC, merged