Change sort order for students with teacher rights
dodona-edu/dodona pull request #3338
Opened 2022-02-02 20:05 UTC by BTWS2

This pull request closes #3107.

For reference:
`enum permission: { student: 0, staff: 1, zeus: 2 }`
`enum status: { pending: 0, course_admin: 1, student: 2, unsubscribed: 3 }`

Examples:
![image](https://user-images.githubusercontent.com/56451049/152227488-42e97a7c-7c32-4d2a-8097-d1ec2d0ba819.png)
![image](https://user-images.githubusercontent.com/56451049/152227602-2c34eb45-39d4-47b5-9d43-511b0e1a55fb.png)

2022-02-03 09:18 UTC, chvp approved these changes

2022-02-03 09:19 UTC, niknetniko approved these changes

2022-02-03 18:53 UTC, bmesuere requested changes
The first screenshot looks strange. Zeus is listed second but isn't a course admin and has no warning. This is probably because we don't add the warning for zeus. This is not strictly needed, but if we sort it this way, I would add the warning for that class as well.

2022-02-04 08:57 UTC, chvp commented on app/views/course_members/_members_table.html.erb
> +          <% elsif user.staff? || user.zeus? %>
```suggestion
          <% elsif user.admin? %>
```

2022-02-04 13:22 UTC, bmesuere approved these changes

2022-02-04 13:22 UTC, merged