Papyros integration
dodona-edu/dodona pull request #3401
Opened 2022-02-16 10:39 UTC by winniederidder

This pull request integrates Papyros into Dodona to allow users to write and run code within their browser.

Papyros makes use of WebWorkers, requiring SharedArrayBuffers to communicate. Enabling this feature in the browser requires specific HTTP headers to be set on resources used in the pages where this feature is enabled. Examples of such resources are /packs and /assets. For production/staging, these headers must be enabled on the server. In development, this can be taken care of with configuration in config/development.rb .
Some HTTP headers must also be added to responses concerning exercises and their description to allow the iframes to load everything correctly and securely.

- [ ] Tests were added
- [ ] Documentation update can be found at dodona-edu/dodona-edu.github.io#

Closes #3232  .

2022-02-20 22:32 UTC, winniederidder commented
Current visuals of the integration:
![Uploading papyros-integration-v1.PNG…]()

2022-02-22 16:43 UTC, bmesuere requested changes
I would move the papyros initialization to a separate function instead of integrating it in initExerciseShow because we won't always run this code.

Layout:
- The button to trigger papyros should not be a floating action button. What about something like https://cdn.phpjabbers.com/files/frees/sliding-contact-form.jpg? (I wouldn't show the button when expanded)
- I wouldn't use "Papyros" branding in the editor. The title should be something like "Run Python code in your browser" so it's clear what this is. Maybe add a BETA label?
- The help text should be bigger, especially since it's still in beta. Tweak the text so it's more aimed at something younger children can understand. Link them to the contact form instead of just saying to contact us. The margin should be in line with the rest of the page. The top needs a bit more spacing.
- Run and stop buttons feel a bit off here design-wise. I don't have a clear suggestion at this time.
- The vertical alignment for "waiting for input" if off.
- It's not really clear what the output area is when you load the page now that the title is gone. Maybe add a "your output will appear here" placeholder?
- The output area is too prominent compared to the editor itself. What about reducing the height a bit + increase the height of the editor area by giving it the leftover vertical space instead of a fixed height?
- The copy button at the bottom isn't clear. There is enough space so at least include a label

@rien can you check the CSP header changes?

2022-02-22 16:43 UTC, bmesuere commented on app/assets/javascripts/exercise.js
> +import { InputMode, Papyros, plFromString } from "@dodona/papyros";
`plFromString` seems like this should be a static function under Papyros or something instead of a separate export since it is not useful outside this context.

2022-02-22 16:43 UTC, bmesuere commented on app/assets/javascripts/exercise.js
> +    let launched = false;
rename to something useful, probably papyrosLaunched or papyrosActive?

2022-02-22 16:43 UTC, bmesuere commented on app/assets/javascripts/exercise.js
> +        } catch (e) {
Error handling for flow control is bad style. But part of this will probably be fixed by conditionally calling the papyros initialisation from ruby-land

2022-02-22 16:43 UTC, bmesuere commented on app/assets/stylesheets/components/offcanvas.css.scss
> +    width: 700px;
I would prefer overriding the bootstrap variable for this (https://getbootstrap.com/docs/5.1/components/offcanvas/#variables).

2022-02-22 16:43 UTC, bmesuere commented on app/controllers/activities_controller.rb
> +  def isw
this needs a better name

2022-02-22 16:43 UTC, bmesuere commented on app/controllers/activities_controller.rb
> +    send_file(Rails.root.join('node_modules', '@dodona', 'papyros', 'dist', 'inputServiceWorker.js'),
This feels very ugly. In theory, the node_modules directory shouldn't even be available at runtime.

2022-02-22 16:43 UTC, bmesuere commented on app/views/activities/show.html.erb
> +
Move this code to a partial since there's a chance is will be reused on other pages such as grading.

2022-02-22 16:43 UTC, bmesuere commented on config/initializers/content_security_policy.rb
> +                         'http://localhost:3035', 'ws://localhost:3035',
why is localhost used here?

2022-02-22 18:21 UTC, winniederidder commented on app/controllers/activities_controller.rb
> +    send_file(Rails.root.join('node_modules', '@dodona', 'papyros', 'dist', 'inputServiceWorker.js'),
That is correct. A possible solution might be as follows:
I could try to make Papyros search for the serviceworker at a given path (using configureInput). We could then move the isw-path to a different controller (pages is probably not the most appropriate, but something like that) and give it a suitable name (something related to service_worker). Finally, I could add an installation script that copies the default service worker to a given path (such as the public directory or from wherever the application wants to serve the service worker if it doesn't provide one themselves).

2022-02-22 18:22 UTC, winniederidder commented on config/initializers/content_security_policy.rb
> +                         'http://localhost:3035', 'ws://localhost:3035',
Localhost was already present before this PR. I believe it has to do with the webpack-dev-server, as mentioned in the comment above. Someone else might be able to shed more light on this specifically (@rien , @jorg-vr ?)

2022-02-22 18:39 UTC, winniederidder commented on app/controllers/activities_controller.rb
> +  def isw
> I would move the papyros initialization to a separate function instead of integrating it in initExerciseShow because we won't always run this code.
> 

That method won't always be called, because you mentioned e.g. using it in the Grading page? Would a separate method that can be given an editor argument (in case of an exercise page) work then? Being able to access the ace-editor adds useful functionality which I would like to preserve.

> Layout:

> * Run and stop buttons feel a bit off here design-wise. I don't have a clear suggestion at this time.

I could move the buttons away from the status bar and put them elsewhere (similar to [futurecoder](https://futurecoder.io/course/#ide) or [Codecademy](https://i0.wp.com/learn.onemonth.com/wp-content/uploads/2019/05/image1.png?resize=1030%2C532&ssl=1)). [This issue](https://github.com/dodona-edu/papyros/issues/36) also describes the addition of keybinds which can replace the buttons, but students might prefer also having physical buttons in a good location.


> * It's not really clear what the output area is when you load the page now that the title is gone. Maybe add a "your output will appear here" placeholder?

The title attribute is used (shown when the user hovers over the output field). We can also add a title ourselves above the respective div, or go back to the placeholder.

> * The copy button at the bottom isn't clear. There is enough space so at least include a label

Is a floating action button okay here, or should the button style itself also be changed?

2022-02-22 18:40 UTC, winniederidder commented
> I would move the papyros initialization to a separate function instead of integrating it in initExerciseShow because we won't always run this code.
> 

That method won't always be called, because you mentioned e.g. using it in the Grading page? Would a separate method that can be given an editor argument (in case of an exercise page) work then? Being able to access the ace-editor adds useful functionality which I would like to preserve.

> Layout:

> * Run and stop buttons feel a bit off here design-wise. I don't have a clear suggestion at this time.

I could move the buttons away from the status bar and put them elsewhere (similar to [futurecoder](https://futurecoder.io/course/#ide) or [Codecademy](https://i0.wp.com/learn.onemonth.com/wp-content/uploads/2019/05/image1.png?resize=1030%2C532&ssl=1)). [This issue](https://github.com/dodona-edu/papyros/issues/36) also describes the addition of keybinds which can replace the buttons, but students might prefer also having physical buttons in a good location.


> * It's not really clear what the output area is when you load the page now that the title is gone. Maybe add a "your output will appear here" placeholder?

The title attribute is used (shown when the user hovers over the output field). We can also add a title ourselves above the respective div, or go back to the placeholder.

> * The copy button at the bottom isn't clear. There is enough space so at least include a label

Is a floating action button okay here, or should the button style itself also be changed?

2022-02-27 23:16 UTC, winniederidder commented
Some late screenshots:
Button to show Papyros
![papyros-button](https://user-images.githubusercontent.com/53743234/155904118-33b3d6ca-24f5-48d1-81b6-3342d1ea2c85.png)
Current layout with new button, beta label, ...
![papyros-shown](https://user-images.githubusercontent.com/53743234/155904119-5e19ad25-0813-4e3f-ba03-0d2cc23bc834.PNG)

2022-03-01 14:52 UTC, closed without merging

2022-03-01 14:53 UTC, winniederidder commented
Closed in favor of #3453