Don't fetch first and last submission for timeseries if none are present
dodona-edu/dodona pull request #3403
Opened 2022-02-16 13:57 UTC by jorg-vr

This pull request fixes a bug when timeseries tried to fetch the first and last submission when none are present.

Now a message is shown explaining that no data is availlable:
![image](https://user-images.githubusercontent.com/21177904/154279189-6e306ee8-06a0-4856-8e32-1bb267618006.png)

Closes #3367 .

2022-02-17 16:04 UTC, chvp requested changes
With small bugfixes like this, I always try to add a simple test covering the wrong behaviour. Just to make sure we don't regress later.

2022-02-17 16:04 UTC, chvp commented on app/models/submission.rb
> +    last_sub = submissions.present? ? submissions.most_recent.first.created_at : nil
I feel like `.any?` instead of `.present?` makes more sense semantically?

2022-02-18 14:30 UTC, chvp approved these changes

2022-02-19 13:54 UTC, bmesuere approved these changes

2022-02-19 16:04 UTC, niknetniko approved these changes

2022-02-21 08:05 UTC, merged