Clear scores when an other submission is selected to grade
dodona-edu/dodona pull request #3405
Opened 2022-02-17 12:39 UTC by jorg-vr

This pull request clears the scores when an other submission is selected to grade.

![Peek 2022-02-17 13-37](https://user-images.githubusercontent.com/21177904/154483546-7127a9bf-a2d0-4949-ad12-22fe7bf5facb.gif)

- [x] Tests were added

Closes #3344 .

2022-02-17 12:50 UTC, niknetniko requested changes

2022-02-17 12:50 UTC, niknetniko commented on db/seeds.rb
> +          (1..rand(10)).each do
Wouldn't this create no submissions if `rand` returns 0?

2022-02-17 12:52 UTC, jorg-vr commented on app/controllers/feedbacks_controller.rb
> +    @feedback.scores.each { |s| s.destroy } if attrs['submission_id'].present? && attrs['submission_id'] != @feedback.submission_id
Good idea, will edit :)

2022-02-17 12:54 UTC, jorg-vr commented on db/seeds.rb
> +          (1..rand(10)).each do
could happen, although that is not really an issue. The random is meant to create some variability in the amount of submissions. But will update to `rand(1,10)`

2022-02-17 15:41 UTC, niknetniko approved these changes
:+1: (apart from Rubocop's complaint)

2022-02-17 16:05 UTC, chvp approved these changes

2022-02-19 13:51 UTC, bmesuere approved these changes
I suppose this will also fix the issue reported in [this comment](https://github.com/dodona-edu/dodona/discussions/3400#discussioncomment-2187874)?

2022-02-19 13:51 UTC, bmesuere commented on db/seeds.rb
> +          (1..rand(1..10)).each do
Do we really need this many submissions? I know this seems like a small number, but they quickly add up, especially in nested loops. After a while our tests and db seeds (and thus mestra deploys) become painfully slow.

2022-02-19 13:51 UTC, bmesuere commented on db/seeds.rb
> +                              created_at: (Time.now - 1.day).beginning_of_day + 6.hour + rand(0..540).minutes + rand(0..540).minutes,
What is the goal if this construction? If there is a specific reason for this time range, maybe add a comment with the explanation.

Next to that, it can be cleaned up. The 6.hours and double rand can be replace by a single rand. The first part can probably be replaced by something like Date.yesterday or 1.day.ago.

2022-02-21 08:44 UTC, jorg-vr commented on db/seeds.rb
> +          (1..rand(1..10)).each do
Created a separate course for visualizations. Because yes we need so many for decent graphs and testing features with multiple submission per student for example, but no need to have it in every course

2022-02-21 08:46 UTC, jorg-vr commented on db/seeds.rb
> +                              created_at: (Time.now - 1.day).beginning_of_day + 6.hour + rand(0..540).minutes + rand(0..540).minutes,
I improved the date and added a comment for the other part. Using two rands creates a bell curve, so it is not the same result as a single rand

2022-02-21 08:47 UTC, merged