Improve labeling of time periods on cumulative plot
dodona-edu/dodona pull request #3407
Opened 2022-02-18 09:46 UTC by jorg-vr

This pull request removes the start time from the tooltip of the cumulative plot as it incorrectly indicates some kind of binning behavior, which is not what the graph represents.

The capitalization of dates in the tooltip has also changed to follow behavior as specified by I18n.

![image](https://user-images.githubusercontent.com/21177904/154923200-b99ea52f-df74-4aa3-b17a-8fde0d75785e.png)
![image](https://user-images.githubusercontent.com/21177904/154923175-75da7ff4-66db-4cc5-a101-f6b32e64e1f9.png)

I also fixed a bug that scaling is reset when the date range is changed.

Closes #3348 .

2022-02-18 09:48 UTC, chvp commented
As I mentioned on Slack, I think removing the start time makes more sense. The values in the graph are calculations at fixed points in time, not in intervals.

2022-02-18 10:18 UTC, jorg-vr commented
Updated the behavior, it is indeed much more logical this way :)

2022-02-19 14:11 UTC, bmesuere requested changes
The tooltip look a lot clearer 👍 
Sorry for nitpicking!

2022-02-19 14:11 UTC, bmesuere commented on app/assets/javascripts/visualisations/cumulative_timeseries.ts
> +        message += "</b>";
I would prefer that the opening b-tag is also added here (so something like `message = "<b>" + message + "</b>"` to reduce the change to generate invalid html by some future change.

2022-02-19 14:11 UTC, bmesuere commented on app/assets/javascripts/visualisations/cumulative_timeseries.ts
> +        message += capitalize(weekDay(date));
The first letter of days and months is only capitalized in English and not in Dutch. In addition, the capitalize function is added twice in the graph files, so maybe the fixed version that checks the current language can me moved to the super class.

2022-02-21 09:16 UTC, jorg-vr commented on app/assets/javascripts/visualisations/cumulative_timeseries.ts
> +        message += capitalize(weekDay(date));
I just removed the function as the behavior of I18n was already correct

2022-02-21 09:24 UTC, bmesuere approved these changes

2022-02-21 09:29 UTC, merged