Add papyros dependency
dodona-edu/dodona pull request #3453
Opened 2022-03-01 14:32 UTC by winniederidder

Temporary to clean up the PR

2022-03-01 14:52 UTC, winniederidder commented
Layout:

Button to show Papyros, shown on permitted exercise pages
![papyros-button](https://user-images.githubusercontent.com/53743234/155904118-33b3d6ca-24f5-48d1-81b6-3342d1ea2c85.png)
Current layout with new button, beta label, ...
![papyros-shown](https://user-images.githubusercontent.com/53743234/155904119-5e19ad25-0813-4e3f-ba03-0d2cc23bc834.PNG)

2022-03-03 09:42 UTC, bmesuere requested changes
@rien kan you check the policy stuff?

2022-03-03 09:42 UTC, bmesuere commented on app/assets/javascripts/coding_scratchpad.js
> +function initCodingScratchpad(programmingLanguage, editor = undefined) {
what are you trying to solve with `editor = undefined`? Default parameters are used if no value or undefined is passed, so this seems like a no-op.

2022-03-03 09:42 UTC, bmesuere commented on app/assets/javascripts/coding_scratchpad.js
> +                    parentElementId: "papyros-editor-wrapper",
these id strings should probably be consts.

2022-03-03 09:42 UTC, bmesuere commented on app/assets/javascripts/coding_scratchpad.js
> +        $("#papyros-offcanvas-show-btn").on("click", async function () {
we are deprecating the use of jquery in Dodona, so new code should use a native equivalent.

2022-03-03 09:42 UTC, bmesuere commented on app/assets/javascripts/coding_scratchpad.js
> +                await papyros.configureInput(false, "http://dodona.localhost:3000/", "inputServiceWorker.js");
why is there a local host reference here?

2022-03-03 09:42 UTC, bmesuere commented on app/assets/javascripts/exercise.js
> +        initCodingScratchpad(programmingLanguage, editor);
This line should probably be called from an erb/ruby page instead of including it here. In fact, it is already added as a separate pack, so including it here at the top of the file will including it twice in our assets.

2022-03-03 09:42 UTC, bmesuere commented on app/assets/stylesheets/bootstrap_variable_overrides.css.scss
> +$offcanvas-horizontal-width: 700px;
the offcanvas seems to have a white left border. This is not the case with the examples on the bootstrap website.

2022-03-03 09:42 UTC, bmesuere commented on app/assets/stylesheets/components/offcanvas.css.scss
> +.offcanvas-show-btn {
rename the file to papyros/scratchpad instead of offcanvas.

2022-03-03 09:42 UTC, bmesuere commented on app/assets/stylesheets/libraries/coding_scratchpad.css.scss
> +.margin-bottom-11 {
If these styles are added to the libraries folder, they should probably be prefixed or scoped since margin-bottom and beta-label are quite generic in name.

2022-03-03 09:42 UTC, bmesuere commented on app/assets/stylesheets/components/offcanvas.css.scss
> +    top: 50%;
I prefer it a bit lower on the page, eg bottom: 100px

2022-03-03 09:42 UTC, bmesuere commented on app/assets/stylesheets/libraries/coding_scratchpad.css.scss
> +.beta-label {
I prefer a more muted approach, e.g. BETA in superscript just to the right of the title.

2022-03-03 09:42 UTC, bmesuere commented on app/assets/stylesheets/libraries/coding_scratchpad.css.scss
> +    color: white;
If still needed, replace with existing scss variables

2022-03-03 09:42 UTC, bmesuere commented on app/controllers/activities_controller.rb
> +    send_file(Rails.root.join('app/assets/javascripts/inputServiceWorker.js'),
the files in app/assets are processed through webpack/sprockets/... for serving in production. It is not ok to reference it directly like this in the ruby code.

2022-03-03 09:42 UTC, bmesuere commented on app/models/exercise.rb
> +
In my opinion, loading the scratchpad (or not) should not be part of the model, so remove this code.

2022-03-03 09:42 UTC, bmesuere commented on app/views/activities/_coding_scratchpad.html.erb
> +    <div class="papyros-info">
There is still too little margin/padding. The info button almost sticks to the menu bar and the left margin is only half of that of the rest of the content.

2022-03-03 09:42 UTC, bmesuere commented on app/views/activities/_coding_scratchpad.html.erb
> +        <button class="btn with-text btn-primary btn-fab-extended">
The added text is better, but we still have a mix of 3 buttons (4 of you count enter) each in a different color and 3 in a different style. Can we add the copy button to the right of the stop button?

2022-03-03 09:42 UTC, bmesuere commented on app/views/activities/show.html.erb
> +          <% if @activity.scratchpad? %>
explicitly check for python here (instead of in the model). In a first version, this check will probably include some user id's as well.

2022-03-03 09:42 UTC, bmesuere commented on app/views/activities/_coding_scratchpad.html.erb
> +</div>
The javascript initialization of the scratchpad should happen here.

2022-03-03 09:42 UTC, bmesuere commented on app/views/activities/show.html.erb
> +          <% end %>
These elements don't follow the flow of the page, but are inserted at a very specific place (i.e. in the tab content). Why not add them at the bottom of this file?

2022-03-03 19:53 UTC, winniederidder commented on app/assets/javascripts/inputServiceWorker.js
> +!function(e,t){"object"==typeof exports&&"object"==typeof module?module.exports=t():"function"==typeof define&&define.amd?define([],t):"object"==typeof exports?exports.Papyros=t():e.Papyros=t()}(self
This is the default service worker from Papyros, as we do not provide one within Dodona. It is built using Webpack and copied from node_modules/@dodona/papyros/dist. I picked a location in our assets directory that seemed appropriate, but it must be somewhere where we can find and serve it, without having to resort to node_modules directly.

2022-03-03 19:57 UTC, winniederidder commented on app/assets/javascripts/coding_scratchpad.js
> +import { InputMode, Papyros } from "@dodona/papyros";
I followed the style I found in exercise.js, where I initially implemented my solution. All files there were in JavaScript, so I stuck to that. I will migrate it.

2022-03-03 20:01 UTC, winniederidder commented on app/assets/javascripts/coding_scratchpad.js
> +function initCodingScratchpad(programmingLanguage, editor = undefined) {
This is to make it clear that the editor argument is optional. Otherwise, a reader of the code might think that both arguments are always required. When migrating to TypeScript, I will be able to use editor? instead.

2022-03-03 20:03 UTC, winniederidder commented on app/assets/javascripts/coding_scratchpad.js
> +                await papyros.configureInput(false, "http://dodona.localhost:3000/", "inputServiceWorker.js");
An artefact from testing, this should indeed become a dynamic url.

2022-03-03 20:04 UTC, winniederidder commented on app/assets/javascripts/exercise.js
> +        initCodingScratchpad(programmingLanguage, editor);
How do I obtain a reference to the editor then? This editor is scoped within that function, so it must be called from there. Is there a different way to get this required reference?

2022-03-03 20:09 UTC, winniederidder commented on app/views/activities/_coding_scratchpad.html.erb
> +</div>
As mentioned in an earlier comment, having access to the ace editor (when it exists) is quite useful. Currently, it is locally scoped inside exercise.js. Should I instantiate a separate instace of it using ace.edit on the submission field if it exists within the page, or what is your preferred approach?

2022-03-03 20:34 UTC, bmesuere commented on app/assets/javascripts/inputServiceWorker.js
> +!function(e,t){"object"==typeof exports&&"object"==typeof module?module.exports=t():"function"==typeof define&&define.amd?define([],t):"object"==typeof exports?exports.Papyros=t():e.Papyros=t()}(self
This is definitely not ok.
- The way this file is accessed from the controller is not ok
- It will not be automatically updated when we update papyros 
- it is not clear what this file is doing. Especially because a service worker can break the rest of Dodona and will be hard to fix if that's the case.

If there isn't an acceptable way to fix these issues, I once again propose not using the service worker route.

2022-03-03 20:36 UTC, bmesuere commented on app/assets/javascripts/exercise.js
> +        initCodingScratchpad(programmingLanguage, editor);
This is why we have a global dodona object

2022-03-03 20:52 UTC, winniederidder commented on app/assets/javascripts/inputServiceWorker.js
> +!function(e,t){"object"==typeof exports&&"object"==typeof module?module.exports=t():"function"==typeof define&&define.amd?define([],t):"object"==typeof exports?exports.Papyros=t():e.Papyros=t()}(self
It is stored within the assets folder. I think assets are served automatically somehow but my Rails knowledge is rather limited. In theory, the ActivitiesController method is not required as it can be served like a stylesheet and does not need any modification. 

Automatic updating is indeed not done. This is also mentioned in the Papyros-README where users will need to manually copy this file from the dist folder if they do not provide a service worker themselves. However, at this point the file is stable so this will rarely be an issue.
What the file is doing, is described in that README as well. It appends headers to requests that belong to the scope of the service worker, which can be made even smaller by giving it its own directory (so it should be moved a bit). It also handles the specific input urls which are not used by standard applications and thus do not interfere. The added HTTP headers to other parts of Dodona should ensure everything keeps working, as is mentioned in the README in Papyros. It is simply built by webpack and thus turned into rather ugly JavaScript, similar to how e.g. bootstrap.min.js or other minified JS files work. 

So, the first issue should be resolvable by serving it as a normal asset.
The other issues I explained above.

If this is not sufficient, we could make our own service worker importing the functionality provided within Papyros. This will ensure automatic updating when installing a new version, as it will be re-bundled. It will be more clear what it does, as programmers don't see the uglified code. It will need a bundling step to make it accessible in the way it is now, so this will perhaps require some more delving in the assets pipeline.

2022-03-03 20:57 UTC, winniederidder commented on app/assets/javascripts/exercise.js
> +        initCodingScratchpad(programmingLanguage, editor);
I should add the editor to the global object then within initExerciseShow? Do we not risk a race condition if the scratchpad is initialized before initExerciseShow is called? Alternatively, an old instance of the editor might be present when switching between exercises, which could also cause problems. Are there guarantees on the order of code executed?

2022-03-04 16:31 UTC, winniederidder commented on app/controllers/activities_controller.rb
> +    send_file(Rails.root.join('app/assets/javascripts/inputServiceWorker.js'),
Am I allowed to reference app/assets/builds?

2022-03-04 20:51 UTC, winniederidder commented on app/assets/javascripts/inputServiceWorker.js
> +!function(e,t){"object"==typeof exports&&"object"==typeof module?module.exports=t():"function"==typeof define&&define.amd?define([],t):"object"==typeof exports?exports.Papyros=t():e.Papyros=t()}(self
To add to this, the service worker cannot be hosted within /assets as Rails disables these requests. We can give it its own secluded folder (e.g. /serviceworker/) to still limit the requests intercepted by the service worker (instead of putting it at the root, where 'normal' service workers tend to operate.

2022-03-13 16:05 UTC, bmesuere requested changes
Code-wise, this is a great step forward 👍 

Regarding the service worker: This can only be merged with the service worker if each of these points are fixed:
- [ ] The service worker code is readable and not minimized
- [ ] The service worker file is called correctly instead of referencing the file from assets (e.g. add it to the packs so it's processed by webpack and sprockets.
- [ ] There is a clear upgrade path
- [ ] The service worker is registered using a `scope` so its impact is as minimal as possible

Regarding the UI/flow:
- New copy button location is an improvement but I would make it gray/neutral instead of green
- The button doesn't seem to copy the code to the ACE editor
- If papyros is triggered for a second time, the code in the papyros editor is overwritten by that in the ACE editor. In case of such conflict: ask the user if he wants the code replaced.
- Increase the height of the papyros editor to take up everything that isn't used by the other UI elements.
- The UI text can still use some work. I'll try to do a few suggestions later.

2022-03-13 16:28 UTC, winniederidder commented
> * The button doesn't seem to copy the code to the ACE editor

A standard copy button seems to be more logical. If we copy only to the editor, it sounds more logical to just submit it immediately. Copying to the clipboard allows the user to do with it as they please, such as pasting in a file or in the editor to submit. Are you certain you want it to just paste the code into the editor?

2022-03-14 19:53 UTC, winniederidder commented
> Regarding the service worker: This can only be merged with the service worker if each of these points are fixed:
> 
> * [ ]  The service worker code is readable and not minimized
> * [ ]  The service worker file is called correctly instead of referencing the file from assets (e.g. add it to the packs so it's processed by webpack and sprockets.
> * [ ]  There is a clear upgrade path
> * [ ]  The service worker is registered using a `scope` so its impact is as minimal as possible
> 

There is now a file called inputServiceWorker.ts in app/assets/javascripts/packs which is built by webpack and processed as requested. The upgrade path is automatic as the core functionality is mported from @dodona/papyros so that will be updated automatically when upgrading versions.
Regarding scope and serving:
When registering a service worker, it becomes active on the path it was registered on. In our ideal case, that is /assets/ as it is served as e.g. /assets/inputServiceWorker.js. It is therefore only able to intercept requests originating from that location. Activities within Dodona are hosted in different locations, such as /activities/:id, /courses/:cid/activities/:aid and /courses/:cid/series/:sid/activities/:aid. Requests happening within these pages cannot be intercepted, as they are outside the scope of the service worker. As implemented earlier, the solution is to host the service worker within the scope of the specific page, using new routes in config/routes.rb leading to ActivitiesController#isw. This controller now uses the application's assets to serve this file, which is hopefully ok. Redirecting to the actual URL using javascript_path is forbidden by the browser (scripts may not be served under redirects for security reasons). These new routes then host the serviceworker under e.g. /activities/:id/inputServiceWorker.js, alllowing requests to be intercepted only within this specific page.

2022-03-15 12:46 UTC, winniederidder commented
Updated layout following given suggestions:
![scratchpad-integration](https://user-images.githubusercontent.com/53743234/158380626-c0c07a4d-a1f3-48f8-819d-5eb9c31d320d.PNG)

2022-03-23 13:21 UTC, bmesuere commented
> > Regarding the service worker: This can only be merged with the service worker if each of these points are fixed:
> > 
> > * [ ]   The service worker code is readable and not minimized
> > * [ ]   The service worker file is called correctly instead of referencing the file from assets (e.g. add it to the packs so it's processed by webpack and sprockets.
> > * [ ]   There is a clear upgrade path
> > * [ ]   The service worker is registered using a `scope` so its impact is as minimal as possible
> 
> There is now a file called inputServiceWorker.ts in app/assets/javascripts/packs which is built by webpack and processed as requested. The upgrade path is automatic as the core functionality is mported from @dodona/papyros so that will be updated automatically when upgrading versions. Regarding scope and serving: When registering a service worker, it becomes active on the path it was registered on. In our ideal case, that is /assets/ as it is served as e.g. /assets/inputServiceWorker.js. It is therefore only able to intercept requests originating from that location. Activities within Dodona are hosted in different locations, such as /activities/:id, /courses/:cid/activities/:aid and /courses/:cid/series/:sid/activities/:aid. Requests happening within these pages cannot be intercepted, as they are outside the scope of the service worker. As implemented earlier, the solution is to host the service worker within the scope of the specific page, using new routes in config/routes.rb leading to ActivitiesController#isw. This controller now uses the application's assets to serve this file, which is hopefully ok. Redirecting to the actual URL using javascript_path is forbidden by the browser (scripts may not be served under redirects for security reasons). These new routes then host the serviceworker under e.g. /activities/:id/inputServiceWorker.js, alllowing requests to be intercepted only within this specific page.

I don't think there's a need for this additional path unless I'm entirely mistaken how this works. We use the service worker to intercept "fake" requests to handle input, right? So we can choose whichever path we use for those fake requests as long as we can intercept them? Using the `scope` during registration, we can further restrict the scope of the service worker. So isn't it possible to send the fake requests to /assets/fake-papyros-request and limit the scope to that? This way the SW will be guaranteed to have no unwanted impact.

2022-03-23 13:23 UTC, bmesuere commented
@chvp @rien @niknetniko @jorg-vr can you review this as well?

2022-03-23 13:57 UTC, rien commented on app/javascript/packs/inputServiceWorker.ts
> +import { InputWorker } from "@dodona/papyros/dist/workers/input/InputWorker";
Since `InputWorker` is exported in [papyros' `Libary.ts`](https://github.com/dodona-edu/papyros/blob/main/src/Library.ts), you should be able to change this to:
```suggestion
import { InputWorker } from "@dodona/papyros";
```

2022-03-23 13:57 UTC, rien commented on app/views/activities/_coding_scratchpad.html.erb
> +            "<%= @activity.programming_language&.name %>"
Since this is Javascript, you should probably use [`escape_javascript`](https://api.rubyonrails.org/classes/ActionView/Helpers/JavaScriptHelper.html#method-i-escape_javascript), just in case.

2022-03-23 13:57 UTC, rien commented on config/initializers/content_security_policy.rb
> +      'https://cdn.jsdelivr.net/pyodide/', 'https://pypi.org/pypi/', 'https://files.pythonhosted.org/packages/'
Allowing full access to pypi and python packages is maybe a lot to allow application-wide. Maybe this should be set more specific on the page where this could be allowed?

Is full access to pypi needed and desired? Not all python packages are available inside the python judge.

2022-03-23 13:57 UTC, rien commented on app/controllers/activities_controller.rb
> +  def isw
This name isn't very descriptive. Maybe this could be changed to `input_service_worker`?

2022-03-23 14:17 UTC, jorg-vr commented on app/views/activities/_coding_scratchpad.html.erb
> +            "<%= @activity.programming_language&.name %>"
Could you provide the isw asset path here as an argument `"<%= asset_path("inputServiceWorker.js") %>"`
and use something like `await papyros.configureInput(location.host, isw_path, false);` in the papyros launch?

I think this would avoid the need for a custom path to the asset.
But maybe you have already tried this.

2022-03-24 08:18 UTC, winniederidder commented
> I don't think there's a need for this additional path unless I'm entirely mistaken how this works. We use the service worker to intercept "fake" requests to handle input, right? So we can choose whichever path we use for those fake requests as long as we can intercept them? Using the `scope` during registration, we can further restrict the scope of the service worker. So isn't it possible to send the fake requests to /assets/fake-papyros-request and limit the scope to that? This way the SW will be guaranteed to have no unwanted impact.

Sadly, this is not doable. The scope on the service worker tells the worker from which origins it can intercept requests. This scope is relative to where the service worker is hosted. If it is hosted under /assets, it can only intercept requests originating from /assets. Since our requests come from the exercise page to /assets, it is unable to change them. This is why I need to resolve the worker from a local scope /exercise/:id/serviceworker so it can intercept requests originating from /exercise/:id

2022-03-24 08:23 UTC, winniederidder commented on config/environments/development.rb
> +class AssetHeaders
The headers served with the exercise pages to support SharedArrayBuffers (COEP/CORP) cause a mismatch between origins when fetching assets inside an iframe, causing the sandboxed origin to not be allowed to fetch e.g. stylesheets anymore (as origins are isolated). The cross-origin headers allow the sandboxed host to still fetch these. These will indeed be needed in other environments as well.

2022-03-24 08:25 UTC, winniederidder commented on app/views/activities/_coding_scratchpad.html.erb
> +            "<%= @activity.programming_language&.name %>"
The custom path is required because of reasons I described in my reply to Bart, which you can find below.

2022-03-24 08:27 UTC, winniederidder commented on config/locales/js/en.yml
> +      copy_code: Copy
That will cause the button to be quite big. I agree "Copy" isn't ideal.

2022-03-24 08:36 UTC, rien commented on app/javascript/packs/inputServiceWorker.ts
> +import { InputWorker } from "@dodona/papyros/dist/workers/input/InputWorker";
Ah, sad. Maybe it is a good idea to mention the reason for this type of import in a comment then?

2022-03-24 11:20 UTC, winniederidder commented on app/javascript/packs/inputServiceWorker.ts
> +import { InputWorker } from "@dodona/papyros/dist/workers/input/InputWorker";
The comment indeed does not mention this specific issue, only that I specifically import the worker. I'll update it to be more clear.

2022-03-24 12:40 UTC, chvp approved these changes
No additional comments except for a few small nits.

2022-03-24 12:40 UTC, chvp commented on config/environments/development.rb
> +class AssetHeaders
In other environments these headers will be set by Apache, I assume? Then this will need a matching PR in the dodona-ansible repo.

2022-03-24 12:40 UTC, chvp commented on config/environments/development.rb
> +      #response[1]['Cross-Origin-Embedder-Policy'] = 'require-corp'
Remove the commented out code.

2022-03-24 12:40 UTC, chvp commented on config/environments/development.rb
> +     # 'Cross-Origin-Embedder-Policy' => 'require-corp',
Same here.

2022-03-24 12:40 UTC, chvp commented on config/initializers/content_security_policy.rb
> +
Remove trailing whitespace.

2022-03-25 14:32 UTC, winniederidder commented on config/locales/js/en.yml
> +      copy_code: Copy
Changed it to "Copy to Dodona" but layout-wise this isn't ideal. @bmesuere thoughts?

2022-04-02 13:44 UTC, chvp commented
The sideways "Begin met coderen" looks a little weird to me. Also, toggling to batch input doesn't seem to work for me on Naos. Not sure if this is due to deployment issues or otherwise.

2022-04-02 13:53 UTC, winniederidder commented
> The sideways "Begin met coderen" looks a little weird to me. Also, toggling to batch input doesn't seem to work for me on Naos. Not sure if this is due to deployment issues or otherwise.

"Start coding" doesn't seem to have a better translation, but suggestions are welcome. Regarding the switch, a fix will be pushed very soon, it's not deployment related.

2022-04-14 12:52 UTC, bmesuere requested changes
I did this review together with @chvp 

- Please tweak the padding of the buttons to use `px-3 py-1` and remove `border-2`. The inset can probably also be removed. 
- Add additional margin to the left-most button (so the total is equivalent to `m-2`) + add the same margin to the right of the status text on the right. 
- Use cursor not-allowed instead of wait where appropriate.
- Set the bg color of the copy button to gray-300
- the line input text has a smaller bottom margin than the text area which causes the toggle text to stick to the input. Add a bit margin here.
- close papyros after clicking the copy button
- can you move the "do you want to update your scratchpad code" prompt to after expanding the sidebar?
- non-interactive input is broken on naos (both chrome and firefox)
   <img width="1911" alt="image" src="https://user-images.githubusercontent.com/481872/163391486-8a1ec66c-fff7-470c-bff3-7165fdd839f2.png">

Regarding the scope of the service worker: you are correct. The scope seems to filter on the origin/initiator and not the destination. Can you point me to the lines of code where your own request filtering is done?

2022-04-14 12:52 UTC, bmesuere commented on config/locales/views/activities/nl.yml
> +      experimental_feature_html: Deze experimentele toepassing laat je toe om code te schrijven en uit te voeren in je browser, zodat je meteen kan beginnen. Suggesties en problemen kan je melden bij
```suggestion
      experimental_feature_html: In dit venster kan je Python-code uitvoeren zonder iets te moeten installeren. De code die je hier schrijft wordt <b>niet</b> automatisch ingediend in Dodona. Deze functie is nog in volle ontwikkeling. We horen graag je suggesties en problemen via <a href="%{url}">het contactformulier</a>.
```

2022-04-14 12:52 UTC, bmesuere commented on config/locales/views/activities/en.yml
> +      experimental_feature_html: This experimental feature lets you write and run code in your browser to get you started immediately. Please report any suggestions and issues to <a href="%{url}">tea
```suggestion
      experimental_feature_html: This window allows you to run Python code without installing a thing. The code you write here is <b>not</b> automatically submitted to Dodona. This feature is still in full development, so we're happy to hear about your suggestions and issues using <a href="%{url}">the contact form</a>. 
```

2022-04-14 12:52 UTC, bmesuere commented on app/assets/stylesheets/components/scratchpad.css.scss
> +    width: fit-content;
```suggestion
    white-space: nowrap;
```

2022-04-14 12:52 UTC, bmesuere commented on config/locales/js/nl.yml
> +      overwrite_code: Wil je de code in het kladblok overschrijven met je huidige oplossing?
```suggestion
      overwrite_code: Wil je de code in het kladblok overschrijven met je laatste aanpassingen?
```

2022-04-14 12:52 UTC, bmesuere commented on config/locales/js/en.yml
> +      overwrite_code: Do you want to overwrite the code in the scratchpad with your current solution?
```suggestion
      overwrite_code: Do you want to overwrite the code in the scratchpad with your latest changes?
```

2022-04-14 12:52 UTC, bmesuere commented on config/locales/views/activities/nl.yml
> +      start_coding: Begin met coderen
```suggestion
      start_coding: Code uitvoeren
```
In the future, we would use "Kladblok" and "Scratchpad" as label text + add some kind of run icon.

2022-04-15 12:20 UTC, winniederidder commented on app/assets/stylesheets/components/scratchpad.css.scss
> +    color: $header-fg;
Display:flex causes the height of the header to be slightly smaller than navbar-height. Maybe it is best to remove this close button, as clicking anywhere off the offcanvas closes it too so the button is quite redundant? Then we can remove the flex parts (such as the flex-spacer, display-flex and the button itself)

2022-04-15 14:09 UTC, winniederidder commented
> I did this review together with @chvp
> 
> * Please tweak the padding of the buttons to use `px-3 py-1` and remove `border-2`. The inset can probably also be removed.
> * Add additional margin to the left-most button (so the total is equivalent to `m-2`) + add the same margin to the right of the status text on the right.
> * Use cursor not-allowed instead of wait where appropriate.
> * Set the bg color of the copy button to gray-300
> * the line input text has a smaller bottom margin than the text area which causes the toggle text to stick to the input. Add a bit margin here.
A PR for styling was opened at [Papyros](https://github.com/dodona-edu/papyros/pull/117)

> * non-interactive input is broken on naos (both chrome and firefox)
>   <img alt="image" width="1911" src="https://user-images.githubusercontent.com/481872/163391486-8a1ec66c-fff7-470c-bff3-7165fdd839f2.png">

This is unrelated to the browser but related to [comsync](https://github.com/alexmojaki/comsync/issues/3), I patched it until a proper fix is implemented there.

> Regarding the scope of the service worker: you are correct. The scope seems to filter on the origin/initiator and not the destination. Can you point me to the lines of code where your own request filtering is done?

Dodona's service worker is located [here](https://github.com/dodona-edu/dodona/blob/papyros-integration-v2/app/javascript/packs/inputServiceWorker.ts). It uses the [InputWorker](https://github.com/dodona-edu/papyros/blob/main/src/workers/input/InputWorker.ts) provided by Papyros. Since a hostname is not provided by Dodona to limit the impact of the service worker, this boils down to simply using the serviceWorkerFetchListener provided by sync-message defined [here](https://github.com/alexmojaki/sync-message/blob/master/lib/index.ts) where the current implementation only affects urls containing "__SyncMessageServiceWorkerInput__" for reading and writing.

2022-04-17 13:13 UTC, bmesuere reviewed
Would it be possible to add/duplicate the intervention check to the pack in dodona?
e.g. instead of 
```
    if (!await inputHandler.handleInputRequest(event)) {
        return;
    }
```
something like 
```
    if (/* check if url contains SyncMessageServiceWorkerInput*/) {
        inputHandler.handleInputRequest(event);
    } else {
        return;
    }
```

This way, a broken papyros package can't break dodona requests.

2022-04-18 13:06 UTC, winniederidder commented
> Would it be possible to add/duplicate the intervention check to the pack in dodona? e.g. instead of
> 
> ```
>     if (!await inputHandler.handleInputRequest(event)) {
>         return;
>     }
> ```
> 
> something like
> 
> ```
>     if (/* check if url contains SyncMessageServiceWorkerInput*/) {
>         inputHandler.handleInputRequest(event);
>     } else {
>         return;
>     }
> ```
> 
> This way, a broken papyros package can't break dodona requests.

We exposed the filter in sync-message, which is now explicitly added in the Dodona service worker to help with this.

2022-04-18 13:21 UTC, bmesuere commented
@winniederidder Thank you for the update, but it doesn't fix the concern I have. Instead, it even makes it more visible. I'll try to explain: if due to a bug or misconfiguration the sync-message library always returns true for the call we do know, all legitimate Dodona requests could fail which is a major problem. What I would like here is a check in code that we own (i.e. in the pack file) that limits the number of requests that we hand over to the library so that worst case, when something breaks, only papyros stops working. Note that this additional check must not be the exact same one that happens in the library as long as it limits the scope of impact enough.

2022-04-18 13:28 UTC, winniederidder commented
> @winniederidder Thank you for the update, but it doesn't fix the concern I have. Instead, it even makes it more visible. I'll try to explain: if due to a bug or misconfiguration the sync-message library always returns true for the call we do know, all legitimate Dodona requests could fail which is a major problem. What I would like here is a check in code that we own (i.e. in the pack file) that limits the number of requests that we hand over to the library so that worst case, when something breaks, only papyros stops working. Note that this additional check must not be the exact same one that happens in the library as long as it limits the scope of impact enough.

Using the BASE_URL_SUFFIX in the test from the library would then also be risky in this sense. I could copy the value of the this suffix from the library into this file so it is fully under our control.

2022-04-18 16:17 UTC, bmesuere requested changes
Two more minor issues:
- The copy to dodona button should have black text instead of white
- Clicking that button correctly copies the code to Dodona, but the "Submit" tab isn't set to active (e.g. if you were on the feedback tab when opening the scratchpad, I would expect it to switch back to submit when the code is copied to show you the change)

Can you also make sure the latest (working) version is deployed at papyros.dodona.be? We will use it in a demo tomorrow.

2022-04-18 17:23 UTC, winniederidder commented
> * Clicking that button correctly copies the code to Dodona, but the "Submit" tab isn't set to active (e.g. if you were on the feedback tab when opening the scratchpad, I would expect it to switch back to submit when the code is copied to show you the change)

Do we want to scroll the submit panel into view? I experimented a bit with scrolling to #handin or #activity-handin-link but neither yielded a simple and reliable scrolling behaviour. I'll look into it more if this is something you want added.

2022-04-19 09:05 UTC, niknetniko approved these changes

2022-04-20 18:24 UTC, bmesuere commented
Report by @pdawyndt 

The "Run your code" offcanvas-button always seems to trigger a horizontal scrollbar, that disappears as soon as Papyros is brought on canvas. Try to avoid this horizontal scrollbar if not needed.

Example: https://naos.ugent.be/en/courses/56/series/591/activities/203584369/

![image](https://user-images.githubusercontent.com/5736113/164295783-286537ab-71ea-425e-858b-c4708b57ad8d.png)

![image](https://user-images.githubusercontent.com/5736113/164295832-2cc758f6-26b1-4e8d-aef6-c917d65a7996.png)

2022-04-21 22:38 UTC, winniederidder commented
Update to properly support dark mode in Papyros:
![dodona-dark-mode](https://user-images.githubusercontent.com/53743234/164562800-179c7edf-4eeb-4538-bc3c-799737f787ca.PNG)

2022-04-21 22:53 UTC, winniederidder commented
> Report by @pdawyndt
> 
> The "Run your code" offcanvas-button always seems to trigger a horizontal scrollbar, that disappears as soon as Papyros is brought on canvas. Try to avoid this horizontal scrollbar if not needed.
> 
> Example: https://naos.ugent.be/en/courses/56/series/591/activities/203584369/
> 
> ![image](https://user-images.githubusercontent.com/5736113/164295783-286537ab-71ea-425e-858b-c4708b57ad8d.png)
> 
> ![image](https://user-images.githubusercontent.com/5736113/164295832-2cc758f6-26b1-4e8d-aef6-c917d65a7996.png)

I do not get a horizontal scrollbar when opening the Manhattan Python exercise in development locally:
![no-scrollbar](https://user-images.githubusercontent.com/53743234/164563192-723964fc-d47c-4da7-8020-3982a5c43e9c.PNG)

It might have to do with the button being filled in first, affecting the page width, before being rotated.

2022-04-24 07:20 UTC, bmesuere requested changes
Alright, dark mode looks good! Two (small) remaining issues:
- the vertical button to open the scratchpad in dark mode doesn't look like a button because it's missing a border. I suggesting adding border-color hairline gray (it's a existing var) and border-bottom 0
- the tests are still failing

2022-04-24 17:10 UTC, bmesuere commented on test/application_system_test_case.rb
> +  config.default_max_wait_time = 20
Why is this necessary? The value of 10 was there with a reason to keep the total runtime of these tests acceptable. These tests have increased it from 2.5 to 3.5 minutes.

2022-04-24 17:34 UTC, winniederidder commented on test/application_system_test_case.rb
> +  config.default_max_wait_time = 20
Pyodide intialization takes a while, so running a piece of code and expecting output to show up takes a while. The find methods take their waiting time from the capybara config and it doesn't seem to be possible to update the config for this test file only. This system test probably also takes longer because separate pages are loaded per test.  I can try to do it all on the same page instead and make the waits longer only when required.

2022-04-24 17:56 UTC, bmesuere commented on test/application_system_test_case.rb
> +  config.default_max_wait_time = 20
you can set it for checks where it fails: https://blog.tomoyukikashiro.me/post/things-to-be-aware-of-when-change-capybara_default_wait_time/

2022-04-24 18:24 UTC, winniederidder commented on test/application_system_test_case.rb
> +  config.default_max_wait_time = 20
Does the minitest-suite we use support test nesting? Something similar to Jest using 'describe' and 'it'-blocks, as now I combined all tests into a big one separated by comment lines to prevent having to load Pyodide from scratch multiple times.

2022-04-25 08:02 UTC, bmesuere approved these changes

2022-04-25 08:02 UTC, merged