Number submissions by user, exercise and course
dodona-edu/dodona pull request #3485
Opened 2022-03-17 12:34 UTC by jorg-vr

This pull request

- [ ] Tests were added
- [ ] Documentation update can be found at dodona-edu/dodona-edu.github.io#

Closes # .

2022-03-18 09:43 UTC, BTWS2 commented
@jorg-vr Is there a "copy submission link to clipboard button" implemented in this design? Related: #2213 and #3215.

2022-03-21 08:15 UTC, jorg-vr commented
@BTWS2  There is no copy to clipboard in this design. But the numbers are actual links. So a right click `copy link address` will work, as well as clicking on the link and then selecting the new address in the address bar.

2022-03-21 08:41 UTC, bmesuere requested changes

2022-03-21 08:41 UTC, bmesuere commented on app/models/submission.rb
> +  trigger.before(:insert) do
Can you motivate why you need this (hairtrigger)? It seems to require a number of big dependencies.

2022-03-21 08:41 UTC, bmesuere commented on app/views/submissions/_submissions_table.html.erb
> +      <th><%= t ".number" %></th>
I would not add a title to this column because of the extra width it introduces. Instead a title tag to the individual links such as `submission #23` might provide enough context.

2022-03-21 08:41 UTC, bmesuere commented on db/migrate/20220317145048_create_trigger_submissions_insert.rb
> +    create_trigger("submissions_before_insert_row_tr", :compatibility => 1).
I would not add these using a migration. Because of the size of the submissions table, this will take a very long time (with the deploy also taking this much time). I would make sure the code can handle "missing" numbers and fill these in later using the rails console or runner function.

2022-03-21 08:41 UTC, bmesuere commented on db/schema.rb
> -    t.datetime "sign_in_at", precision: 6
weren't these additional precisions added in a previous PR?

2022-03-21 08:45 UTC, jorg-vr commented on app/models/submission.rb
> +  trigger.before(:insert) do
I mostly used it to have database independent triggers. It also helped to get the triggers in the test database (But there are probably also other solutions for this)

But it is no big issue for me to leave it out and just use a plain mysql trigger (As I did in my earlier commits)

2022-03-21 08:47 UTC, jorg-vr commented on db/migrate/20220317145048_create_trigger_submissions_insert.rb
> +    create_trigger("submissions_before_insert_row_tr", :compatibility => 1).
These are not added in using a migration. I only add the trigger here (So that for each future submission the number is set correctly)

2022-03-21 08:47 UTC, jorg-vr commented on db/migrate/20220317145048_create_trigger_submissions_insert.rb
> +    create_trigger("submissions_before_insert_row_tr", :compatibility => 1).
The code is able to handle missing numbers

2022-03-21 08:51 UTC, jorg-vr commented on db/schema.rb
> -    t.datetime "sign_in_at", precision: 6
Damn it looked over it when reviewing my own pr :/ 
I'll have a look at my database setup, because he sometimes removes and re adds these precisions when I am rolling out new migrations, but I am not sure why

2022-03-21 09:03 UTC, BTWS2 commented
@jorg-vr Would you consider adding [a chainlink icon like Peter suggested](https://github.com/dodona-edu/dodona/issues/2213#issue-692134559) before the `#` (similar to the filter icon)? And also in #3470?

> ![image](https://user-images.githubusercontent.com/56451049/159229239-bd5dda05-842f-4811-b6e5-9ca169b60654.png)
> Suggestion from Peter

<img src="https://user-images.githubusercontent.com/56451049/159230165-55a0ae4d-a213-42ef-ab3b-892867054c7b.png" width="500">
<img src="https://user-images.githubusercontent.com/56451049/159230283-78acf025-919f-42de-9c2c-78b2d900af95.png" width="500">
<img src="https://user-images.githubusercontent.com/56451049/159230407-46552fc2-9cfb-44ac-9f24-125f98949da6.png" width="500">

Ideally sharing the link should be as simple as possible. In the past we had the really emphasize we want a submission link and not https://dodona.ugent.be/nl/courses/???/activities/???/ for example (where the submission is visible at the bottom of the page for students but not for teachers).

I'm not keen on the right click method. The text is different dependent on the browser and language (in Chrome `Linkadres kopiëren` and in Edge `Koppeling kopiëren`). If students use this regularly I would like it to be more discoverable.

Clicking on the link and selecting the new address in the address bar involves too many steps (new page load, select full link, right click, copy). If a students clicks one more time, the selection is gone and they have to select the URL themselves. Not everyone uses the `Ctrl+C` shortcut, which adds another step.

For young students a single click in the UI, which copies the link to the clipboard is less cumbersome.

2022-03-21 12:24 UTC, jorg-vr commented on db/schema.rb
> -    t.datetime "sign_in_at", precision: 6
Researched it a bit.

It is reletatd to https://github.com/rails/rails/issues/43909 and https://github.com/rails/rails/issues/44571

From one of the comments
> `precision: 6` is the default in schema version `7.0`. (But before `7.0.2`, it was still [unnecessarily] being dumped explicitly.)

So the current rails version removes the unneeded precision statements that match the default when I run `rails db:migrate`

2022-03-21 15:47 UTC, chvp commented on app/models/submission.rb
> +    submissions = submissions.where(course_id: course&.id)
It could be me misremembering as well. @bmesuere Do you recall?

2022-03-22 07:53 UTC, jorg-vr commented on app/models/submission.rb
> +    submissions = submissions.where(course_id: course&.id)
The code is already there, I will leave it as is. The numbers won't hurt anyone and could potentially be useful to some

2022-03-22 09:26 UTC, chvp approved these changes

2022-03-23 13:05 UTC, bmesuere approved these changes

2022-03-23 13:05 UTC, bmesuere commented on app/models/submission.rb
> +    self.number = submissions.length + 1
this should probably be count or size to prevent loading everything into memory.

2022-03-23 13:15 UTC, merged