Add sort buttons to tables
dodona-edu/dodona pull request #3498
Opened 2022-03-24 16:12 UTC by jorg-vr

This pull request

- [ ] Tests were added
- [ ] Documentation update can be found at dodona-edu/dodona-edu.github.io#

Closes # .

2022-04-19 08:35 UTC, chvp requested changes
- [x] Only some small code nits. I didn't do any functional testing yet, since the compile step of the assets seems to fail when deploying to Naos.

2022-04-19 08:35 UTC, chvp commented on app/assets/javascripts/components/search_actions.ts
> +    }
This seems to be present in (almost?) every one of the element classes. Would it make sense to make a generic DodonaElement, so that we don't have to repeat this all the time?

2022-04-19 08:35 UTC, chvp commented on app/assets/javascripts/components/search_actions.ts
> +const isSearchAction= (action): action is SearchAction => (action as SearchAction).js !== undefined || (action as SearchAction).action !== undefined || (action as SearchAction).url !== undefined;
The formatting of these two lines is different?

2022-04-19 08:35 UTC, chvp commented on app/views/activities/_activities_table.html.erb
> +                </small>
Indentation seems off here?

2022-04-19 08:38 UTC, jorg-vr commented on app/assets/javascripts/components/search_actions.ts
> +    }
I'll call it a ShadowlessLitElement or something (to explain the class better, and for some dodona elements the shadow dom can still be usefull)

2022-04-19 10:01 UTC, niknetniko requested changes
A big improvement!

I left some minor comments here and there, and:

- [ ] Would it be possible to indicate the initial sort of the table somehow?
- [x] Sometimes when searching, the dropdown with suggestions is shown empty:
![image](https://user-images.githubusercontent.com/1756811/163979892-5cd452e3-16cb-4029-a75d-e9bc8f255383.png)

2022-04-20 17:48 UTC, bmesuere requested changes
This is awesome work 🔥 

- [x] In the screen recording, the "whitespace" of the tokens looks off, but when I run this locally it looks ok. Does the screen recording use an old version of the code and has this indeed been fixed or is it a rendering issue in your browser? For reference, the current design was taken from https://material.io/components/chips#specs

- [x] In the suggestion list, the "headers" are quite similar to the items. I have looked for material design examples but haven't really found any. Maybe it helps to play with the top and bottom margin to leave more space between the "blocks" and but the header a little closer to the items? If all else fails, the items could be indented a little like in the current implementation.

- [x] Sorting is nice, but I'm not sure about the icons. I agree with @niknetniko that the default sort order should be shown. In the material design spec, an arrow icon is only shown next to the column that is currently sorted. Clicking on a table header sorts them (and adds the arrow), hovering over the header shows a lighter arrow to indicate that sorting will be applied when you click the header. I'm not sure is a similar behaviour is possible here since I think you added the behaviour to the icon itself. If we keep it linked to the icons, maybe we could use the up and down arrows to indicate the currently sorted column (without the 3 stripes) because now the icons are very similar.

- [x] In the action menu, long items are split over 2 lines which is not usually done.

(A lot of queries are happening on these pages, but I think this was already the case previously. It might be time for another n+1 query hunt.)

2022-04-20 17:48 UTC, bmesuere commented on app/javascript/packs/application_pack.js
> +import "components/filter_button.ts";
Is there a reason why these are added here and not in the search pack?

2022-04-21 07:51 UTC, jorg-vr commented
@bmesuere and @niknetniko The initial sort is often the index, which is not present as a column. Thus hard to visualize correctly.

Ideas are welcome for this

2022-04-21 13:51 UTC, jorg-vr commented on app/helpers/application_helper.rb
>      def html_container(html)
initPagination() needs to be called after the pagination buttons are added in the page. 
These are often dynamically included in the page and reload. I tried to write code that triggered when the buttons appeared on the page, but failed to do so.

Including this script part in the HTML partial of this container assures it is executed whenever the html partial is added to the page

2022-04-28 14:08 UTC, niknetniko approved these changes
:+1:  (apologies for the small nitpicks)

2022-05-01 17:06 UTC, bmesuere requested changes
This looks very good 👍 

The headers in the autocomplete are more clear now and the left alignment of the tokens, search and selects is good. To me, the chips are a bit too close to each other (especially compared to the generous spacing between the selects below). The spec mentions 8px in between chips but I couldn't find the current value.

- [ ] fix spacing between chips

---

Given this refactor, how hard would it be to store the selected filters for the exercise search within a course (on the series edit page) in local storage and restore them if present? In this case, I think teachers mostly use the same settings to find exercises (certain programming language/repo/language) in a certain course so this would speed things up for them.

---
For the sorting, I'm not convinced of the current solution. Clicking the header instead of the icon is easier but by removing the icon it becomes less discoverable. In addition, the lack of showing the default sort seems suboptimal. Would it be possible to manually add the default sort order (in code) so we could show the correct icon in the respective column? This would also improve the discoverability: if an arrow is shown next to a column header, this hints that you can sort them.

When sorting for the first time, the addition of a sort icon increases the header height and makes the entire header jump. (Adding the default order would solve this)

Do we need the third "blank" toggle item? This seems to make ik more complicated.

Because the icon is in front of the title, the label jumps to the right when hovering over it. I can see 2 possible fixes: reserve some blank space in front that's only filled in on hover/sort (but then the left alignment of the titles with the content breaks) or add the icon to the right of the title (against the spec but this seems acceptable).

If I understood correctly, you added the sort here as a proof of concept? We might have to discuss where to add sorting and where not. For example, sorting all submissions (or even all submissions within a large course) can take a lot of time. Because of the size of this PR, is it an option to disable sorting for now, get this merged and solve this in a subsequent PR?

- [ ] move sorting to different pr

2022-05-02 07:54 UTC, jorg-vr commented
It would be very doable to to store selected filters in local storage. An easy solution would be to store the last used search url, and use it for the existing setbasurl method to initialize search params on a new page load without search params. 

I'll make an issue for this

2022-05-02 10:58 UTC, bmesuere approved these changes

2022-05-02 11:06 UTC, bmesuere commented
I also think this removes the last major dependency on jQuery!

2022-05-02 11:23 UTC, chvp requested changes

2022-05-02 11:23 UTC, chvp commented on app/assets/javascripts/components/search_field.ts
> +export abstract class SearchFieldSuggestion extends FilterCollectionElement {
Maybe I'm missing something, but this is an abstract class that is seemingly never inherited from? If this is intended, a comment explaining why this is the case would be good IMO.

2022-05-02 11:23 UTC, chvp commented on app/assets/javascripts/components/search_token.ts
> +export abstract class SearchToken extends FilterCollectionElement {
Same here.

2022-05-02 11:23 UTC, chvp commented on app/assets/stylesheets/components/dropdown.css.scss
> +.dropdown-item-text{
```suggestion
.dropdown-item-text {
```

2022-05-02 11:23 UTC, chvp commented on app/assets/stylesheets/components/search_field.css.scss
> +  .dropdown-header{
```suggestion
  .dropdown-header {
```

2022-05-02 11:23 UTC, chvp commented on app/assets/stylesheets/components/search_field.css.scss
> +  .dropdown-item{
```suggestion
  .dropdown-item {
```

2022-05-02 11:26 UTC, chvp requested changes
On the version that is currently deployed to Naos, course member label edit does not look good, and does not autocomplete either.

2022-05-02 13:18 UTC, chvp approved these changes

2022-05-02 13:22 UTC, merged