Show transient messages
dodona-edu/dodona pull request #3533
Opened 2022-04-15 14:53 UTC by jorg-vr

This pull request

- [ ] Tests were added
- [ ] Documentation update can be found at dodona-edu/dodona-edu.github.io#

Closes # .

2022-04-20 13:53 UTC, niknetniko reviewed
(I did a first review of the functionality, haven't looked at the code yet)

Some thoughts:

- [ ] The dropdown in the form for announcements is not styled correctly:
![image](https://user-images.githubusercontent.com/1756811/164244248-7b7ba46c-248c-4b24-8e35-16f43ce8ce7d.png)
- [ ] The text box in the form should indicate markdown is supported, as we do in other places
- [ ] I would add a confirm dialog to the delete button in the announcement itself
- [ ] Mark as read doesn't work on the index page for announcements.
- [ ] I think the index page (for admins) is a bit much, since all announcements are also fully styled in that page. Perhaps a more "table"-like overview would be better? E.g. the mark as read button should not be in the overview page.
- [ ] Perhaps we also want a way to edit an announcement (e.g. to fix spelling mistakes)? Unsure if editing an announcement should reset the read status. If we add a warning this is the case on the edit page, it might not be needed to reset the read status (e.g. for fixing a spelling mistake, those who have read it already don't need to again)
- [ ] Announcements are wider than other alerts:
![image](https://user-images.githubusercontent.com/1756811/164245345-9731e2f4-a3a9-4ce3-82f0-a61ed834f4fa.png)

2022-04-21 19:01 UTC, bmesuere commented
We also want a Dutch and English text

2022-05-06 12:32 UTC, niknetniko requested changes
The index page is much nicer than the previous version :+1: 
I personally would prefer top-aligning the table cells:
![image](https://user-images.githubusercontent.com/1756811/167131855-373ac502-d8c6-4ad0-88dd-770ef391cdb4.png)

2022-05-06 12:32 UTC, niknetniko commented on app/models/announcement.rb
> +        .where('announcement_views.announcement_id IS NULL AND announcement_views.user_id IS NULL')
I think at least this second part can be written without strings, e.g. something like `.where(announcement_views: {announcement_id: nil, user_id: nil})`.

2022-05-06 12:32 UTC, niknetniko commented on app/policies/announcement_policy.rb
> +    true
I'm not sure if the index should be public or not.

2022-05-06 12:32 UTC, niknetniko commented on app/policies/announcement_policy.rb
> +        scope
Do we want to show all announcements to Zeus, or only those that are active? (Since only we can handle it, we can just delete old announcements of course, so perhaps this is something we want).

2022-05-06 12:32 UTC, niknetniko commented on app/views/announcements/_form.html.erb
> +  dodona.initDatePicker('#stop-delivering-at-group');
For some reason, these are always in English, even if I am using Dodona in Dutch.

2022-05-06 12:32 UTC, niknetniko commented on config/locales/models/nl.yml
> +        text_nl: Nederelands aankondiging
```suggestion
        text_nl: Nederlandse aankondiging
```

2022-05-06 12:32 UTC, niknetniko commented on config/locales/models/nl.yml
> +        user_group: Gebruikers groep
```suggestion
        user_group: Gebruikersgroep
```

2022-05-06 12:32 UTC, niknetniko commented on config/locales/models/nl.yml
> +        style: Bootstrap stijl
```suggestion
        style: Bootstrap-stijl
```

2022-05-06 12:32 UTC, niknetniko commented on config/locales/models/nl.yml
> +        institution_id: Onderwijsinstelling id
```suggestion
        institution_id: ID van onderwijsinstelling
```

2022-05-06 12:32 UTC, niknetniko commented on config/locales/models/en.yml
> +        institution_id: Institution id
```suggestion
        institution_id: Institution ID
```

2022-05-06 12:32 UTC, niknetniko commented on config/locales/views/announcements/nl.yml
> +      title: Bewerk aankondiging
```suggestion
      title: Aankondiging bewerken
```

2022-05-06 12:32 UTC, niknetniko commented on config/locales/views/announcements/nl.yml
> +      title: Maak een nieuwe aankondiging
```suggestion
      title: Nieuwe aankondiging
```

2022-05-06 12:32 UTC, niknetniko commented on config/locales/views/announcements/nl.yml
> +      markdown_html: <a href="https://docs.dodona.be/en/references/exercise-description/#markdown" target="_blank">Markdown</a> formaat wordt ondersteund.
```suggestion
      markdown_html: <a href="https://docs.dodona.be/nl/references/exercise-description/#markdown" target="_blank">Markdown</a> wordt ondersteund.
```

2022-05-06 12:32 UTC, niknetniko commented on config/locales/views/announcements/en.yml
> +      markdown_html: <a href="https://docs.dodona.be/en/references/exercise-description/#markdown" target="_blank">Markdown</a> formatting is supported.
```suggestion
      markdown_html: <a href="https://docs.dodona.be/en/references/exercise-description/#markdown" target="_blank">Markdown</a> is supported.
```

2022-05-06 12:32 UTC, niknetniko commented on config/locales/views/announcements/nl.yml
> +      new: Maak een nieuwe aankondiging
```suggestion
      new: Nieuwe aankondiging maken
```

2022-05-06 12:32 UTC, niknetniko commented on config/locales/views/announcements/nl.yml
> +      stopped: Beeindigd
```suggestion
      stopped: Beëindigd
```

2022-05-06 12:32 UTC, niknetniko commented on config/locales/views/announcements/nl.yml
> +      dismiss: sluit aankondiging
```suggestion
      dismiss: aankondiging sluiten
```

2022-05-06 12:32 UTC, niknetniko commented on config/locales/views/announcements/nl.yml
> +      destroy: Verwijder deze aankondiging permanent
```suggestion
      destroy: Aankondiging permanent verwijderen
```

2022-05-06 12:32 UTC, niknetniko commented on db/migrate/20220413130927_create_announcement_tables.rb
> +      t.integer :user_id
You first need to create the announcements table, and then these should be foreign keys, e.g. `t.references :user, foreign_key: true, null: false, type: :integer`.

2022-05-06 12:32 UTC, niknetniko commented on db/migrate/20220413130927_create_announcement_tables.rb
> +      t.integer :institution_id
This should also be a foreign key.

2022-05-06 12:32 UTC, niknetniko commented on db/migrate/20220413130927_create_announcement_tables.rb
> +    add_index(
I don't think it is necessary to add a name to the index, rails will pick one for us.

2022-05-15 15:05 UTC, bmesuere requested changes
- instead of showing a remove action in the announcement for zeus, I would link to the edit page instead
- on the edit page, make it possible to remove?
- on the index page, showing the formatted announcement clutters the page really quickly. Maybe show the first x chars of the raw markdown instead?
- edit should have the option to reset all read-states

2022-05-15 15:05 UTC, bmesuere commented on app/policies/announcement_policy.rb
> +    true
I would also limit this to zeus-only

2022-05-17 07:44 UTC, jorg-vr commented on app/policies/announcement_policy.rb
> +        scope
Yes, I would prefer zeus to be able to see al announcements. Maybe to reuse old announcements etc

2022-05-17 11:37 UTC, jorg-vr commented on app/views/announcements/index.html.erb
> +                  <%= style_icon announcement.style %>
I added the border but kept the icon with tooltip, as it is hard to add a tooltip to a border

2022-05-18 18:21 UTC, bmesuere requested changes

2022-05-18 18:21 UTC, bmesuere commented on app/assets/javascripts/components/datalist_input.ts
> +@customElement("dodona-datalist-input")
Can you add a little comment here to describe the component? 

Maybe we should look for a better way to document these components, something catalogue-like. I'll look if something like that already exists.

2022-05-18 18:21 UTC, bmesuere commented on app/controllers/application_controller.rb
> +  before_action :set_announcement
don't we want to skip this for remote_requests? (I'm not sure why we also don't skip setting notifications in that case, maybe @chvp knows?)

2022-05-18 18:21 UTC, bmesuere commented on app/views/announcements/_form.html.erb
> +      <%= f.label :institution_id %>
The label should now be institution instead of institution id

2022-05-18 18:21 UTC, bmesuere commented on app/views/announcements/_form.html.erb
> +          <input id="reset_announcement_views" class="form-check-input" type="checkbox" name="reset_announcement_views">
We usually put the (long) label to the right of the checkbox in such cases:
![image](https://user-images.githubusercontent.com/481872/169116052-e19f3990-3f9e-4f61-9a99-a0a58fdfdb86.png)

2022-05-18 18:21 UTC, bmesuere commented on app/views/announcements/mark_as_read.js.erb
> +location.reload();
Why is this? Shouldn't mark as read just remove/hide the notification? This way, current page state could be lost.

2022-05-18 18:21 UTC, bmesuere commented on app/views/layouts/_drawer.html.erb
> +          <% if current_user.zeus? %>
This should probably be a policy check for index.

2022-05-18 18:21 UTC, bmesuere commented on config/locales/models/en.yml
> +        stop_delivering_at: Stop delivering at
```suggestion
        start_delivering_at: Start showing at
        stop_delivering_at: Stop showing at
```

2022-05-18 18:21 UTC, bmesuere commented on config/locales/views/announcements/en.yml
> +      destroy: Permanently remove this announcement
```suggestion
      destroy: Remove permanently
```

2022-05-18 18:21 UTC, bmesuere commented on config/locales/views/announcements/nl.yml
> +      destroy: Aankondiging permanent verwijderen
```suggestion
      destroy: Definitief verwijderen
```

2022-05-18 18:27 UTC, bmesuere commented on app/views/announcements/index.html.erb
> +<div class="row">
How about removing the "state" icon and displaying 3 separate tables for scheduled, active and old announcements? If a category is empty, you could not display the table/header.

2022-05-19 07:15 UTC, jorg-vr commented on app/controllers/application_controller.rb
> +  before_action :set_announcement
Disabled announcements for remote requests, let me know if I need to do notifications to

2022-05-19 07:41 UTC, jorg-vr commented on app/views/announcements/mark_as_read.js.erb
> +location.reload();
It is a bit more complex, as there can be another announcement to be displayed once this one is dismissed. But I'll write it better, because a state loss would indeed be an unwanted side effect

2022-05-19 09:11 UTC, niknetniko requested changes
Besides a few nit picks here and there, I'm not 100% convinced of the delete button in the edit form:
![image](https://user-images.githubusercontent.com/1756811/169257520-aeeac5d8-a4b9-4840-bb7b-4c427beed38c.png)

I feel like this button is placed where normally the OK or save button is placed. When editing an announcement, I have almost pressed it twice, while I intended to save the form.

2022-05-19 09:11 UTC, niknetniko commented on app/views/announcements/edit.html.erb
> +            <hr/>
This button should go in the card actions, which takes care of adding the line.

```html
<div class="card-actions card-border">
   <button>
</div>
```

2022-05-19 09:11 UTC, niknetniko commented on config/locales/views/announcements/nl.yml
> +      reset_announcement_views: "Toon deze aankondiging opnieuw aan gebruikers die hem al gelezen hebben"
```suggestion
      reset_announcement_views: "Toon deze aankondiging opnieuw aan gebruikers die ze al gelezen hebben"
```

2022-05-19 11:20 UTC, niknetniko approved these changes

2022-05-22 08:06 UTC, bmesuere approved these changes
I think splitting the table in 3 sections is a lot clearer 👍 

A final suggestion: if I'm correct, the dates and institution aren't required fields. Maybe add a little help text below those fields stating what will happen if the field is left blank (will show up immediately, will keep displaying until disabled manually, will show to users of all institutions).

FYI: you can group the acceptance of suggested changes in a single commit by adding them to the "batch" (but I think this only works from the Files changed tab).

2022-05-24 07:12 UTC, pdawyndt commented on config/locales/views/announcements/nl.yml
> +      start_delivering_at_help: "Aankondiging zal onmiddelijk getoond worden bij lege input."
onmiddellijk

2022-05-24 07:15 UTC, pdawyndt commented on config/locales/views/announcements/nl.yml
> +      start_delivering_at_help: "Aankondiging zal onmiddelijk getoond worden bij lege input."
Of: Niets invullen om aankondiging onmiddellijk te tonen.

2022-05-24 07:26 UTC, merged