Correctly handle each asset type
dodona-edu/dodona pull request #3563
Opened 2022-04-25 13:31 UTC by winniederidder

This pull request tries to fix the asset resolution problem for the input service worker by choosing the correct assets in any environment and obtaining the correct filename.

2022-04-25 13:36 UTC, chvp requested changes

2022-04-25 13:36 UTC, chvp commented on app/controllers/activities_controller.rb
> +                 Rails.application.assets_manifest.assets[INPUT_SERVICE_WORKER]
This returns something of the form `"inputServiceWorker-abadf00e34692d3841e1f735d8f83f1d9879fd0b95ee577ded766655f9d28661.js"`. Just `send_file`-ing that will not work.

2022-04-25 13:45 UTC, winniederidder commented on app/controllers/activities_controller.rb
> +                 Rails.application.assets_manifest.assets[INPUT_SERVICE_WORKER]
Would something like Rails.root.join("app", "assets", "inputServiceWorker-abadf00e34692d3841e1f735d8f83f1d9879fd0b95ee577ded766655f9d28661.js") work, or will this file also be in the build subdirectory in production?

2022-04-25 13:47 UTC, chvp commented on app/controllers/activities_controller.rb
> +                 Rails.application.assets_manifest.assets[INPUT_SERVICE_WORKER]
It will be in `public/assets`, but that doesn't really feel like a clean solution to me.

2022-04-25 13:49 UTC, jorg-vr commented on app/controllers/activities_controller.rb
> +                 Rails.application.assets_manifest.assets[INPUT_SERVICE_WORKER]
`Rails.application.assets_manifest.directory` contains the directory the file is in.

2022-04-25 13:51 UTC, jorg-vr commented on app/controllers/activities_controller.rb
> +                 Rails.application.assets_manifest.assets[INPUT_SERVICE_WORKER]
https://stackoverflow.com/a/61552216

2022-04-26 07:51 UTC, chvp approved these changes

2022-04-26 09:15 UTC, bmesuere approved these changes

2022-04-26 11:45 UTC, jorg-vr approved these changes

2022-04-26 15:24 UTC, niknetniko approved these changes

2022-04-27 07:32 UTC, merged