Upgrade Papyros
dodona-edu/dodona pull request #3589
Opened 2022-05-02 18:49 UTC by winniederidder

This pull request integrates the latest version of Papyros.
This includes the following:
Interrupts are handled more gracefully.
Dark mode styling is more consistent
Output overflows can be downloaded

2022-05-03 09:18 UTC, bmesuere requested changes
The output area grows too large instead of scrolling on Chrome:
![image](https://user-images.githubusercontent.com/481872/166430185-8e64b1cd-0a30-4ac4-a213-22b4139ebb11.png)

2022-05-03 12:14 UTC, bmesuere submitted a review, later dismissed

2022-05-03 12:36 UTC, bmesuere requested changes
Sorry, I missed this before. A toast is not the right way to show this error message. Papyros is visible on screen so it makes a lot more sense to show the error there. In addition, isn't this something we want to add to papyros itself instead of the Dodona integration?

2022-05-03 13:52 UTC, winniederidder commented
> Sorry, I missed this before. A toast is not the right way to show this error message. Papyros is visible on screen so it makes a lot more sense to show the error there. In addition, isn't this something we want to add to papyros itself instead of the Dodona integration?

Implemented this in https://github.com/dodona-edu/papyros/pull/155. When approved, I'll integrate it here.

2022-05-03 14:51 UTC, bmesuere approved these changes

2022-05-04 08:26 UTC, chvp approved these changes

2022-05-05 10:29 UTC, merged