Allow easy re-use of annotations
dodona-edu/dodona pull request #3600
Opened 2022-05-06 13:55 UTC by chvp

This pull request adds the re-use of annotations. Annotations are saved separately for re-use, with an extra added title.

TODO:
 - [ ] Make save UI actually do something
 - [ ] Add UI for searching and selecting saved annotations while adding comment
 - [ ] Add some views to make sure saved annotations can be edited
 - [ ] Add tests

First draft screenshots, subject to change:
![screenshot_2022-05-06-155306](https://user-images.githubusercontent.com/42220376/167146802-07c2ffd0-029d-4d9a-ad47-a26ccefc553f.png)
![screenshot_2022-05-06-155301](https://user-images.githubusercontent.com/42220376/167146809-ee1ab77f-20d9-43ca-b0a9-4b72d8ce54f6.png)

- [ ] Tests were added

The plan is to first allow this in a (very) closed beta, so I will wait with writing documentation until the results of that closed beta are clear.

Closes #2825.

2022-06-28 12:03 UTC, niknetniko requested changes
Functionally:

1. Saving an annotation at creation time by filling in the title doesn't work. It is currently not obvious that this isn't intended.
2. When editing an annotation that is linked to a saved annotation, the title of the saved annotation remains, but the saved annotation is not updated. I think this can be confusing.
3. Could we modify this a bit to make the title optional? I can imagine it wouldn't always be necessary, if we can allow autocomplete based on the body (but this is probably a bigger change, so not sure if it is worth it)

4. Finally, what is the benefit of doing for example the overview page client side? For editing/saving the annotations, it is obvious, since everything there is already client side. But for the overview page, the benefit is less obvious to me.

2022-06-28 12:03 UTC, niknetniko commented on app/controllers/saved_annotations_controller.rb
> +        format.json { render json: @saved_annotation.errors.full_messages, status: :unprocessable_entity }
Is is easy to add a test with wrong data?

2022-06-28 12:16 UTC, jorg-vr commented on app/assets/javascripts/state/PubSub.ts
> + * heavily based on https://github.com/hankchizljaw/vanilla-js-state-management/blob/master/src/js/lib/pubsub.js
I did look for a library but did not find something that was both small and satisfied my requirements.

For example the linked package uses and ugly notation  where methods are called as strings. (eg `storeInstance.dispatch('saySomething', textElement.value.trim());` )

It also isn't actively maintained.

2022-06-28 12:22 UTC, niknetniko commented on app/assets/javascripts/state/PubSub.ts
> + * heavily based on https://github.com/hankchizljaw/vanilla-js-state-management/blob/master/src/js/lib/pubsub.js
In that case, there is no issue :)

2022-06-28 12:50 UTC, jorg-vr commented
> Saving an annotation at creation time by filling in the title doesn't work. It is currently not obvious that this isn't intended.

- [ ] Could this be as simple as replacing the placeholder and title text by `Search saved annotation` or `Reuse saved annotation`. Or do you have a better suggestion to improve this?

> When editing an annotation that is linked to a saved annotation, the title of the saved annotation remains, but the saved annotation is not updated. I think this can be confusing.

- [ ] This is indeed confussing: I'll remove the link to the saved annotation if the text is eddited

> Could we modify this a bit to make the title optional? I can imagine it wouldn't always be necessary, if we can allow autocomplete based on the body (but this is probably a bigger change, so not sure if it is worth it)

- [ ] This would be a bit of extra work, but if desired I could make autocomplete also work based on body.
- [ ] I would not allow empty titles, but we could suggest a cropped first part of the annotation by default?


> Finally, what is the benefit of doing for example the overview page client side? For editing/saving the annotations, it is obvious, since everything there is already client side. But for the overview page, the benefit is less obvious to me.

I made the listing overview in the sidebar first. This worked better client side, together with the state system to keep it always consistent.

I then made the seperate listing page also client side because it allowed me to reuse all the code I had already written. (But here there is no obvious other benefit)

2022-06-28 13:02 UTC, niknetniko commented
> Could this be as simple as replacing the placeholder and title text by Search saved annotation or Reuse saved annotation. Or do you have a better suggestion to improve this?

I think this is a good solution.

> but we could suggest a cropped first part of the annotation by default?

Also seems like a good solution to me.

2022-06-28 14:47 UTC, chvp commented
> > When editing an annotation that is linked to a saved annotation, the title of the saved annotation remains, but the saved annotation is not updated. I think this can be confusing.
> 
>     * [ ]  This is indeed confussing: I'll remove the link to the saved annotation if the text is eddited

It is an explicit goal to keep this link. Users might want to load a saved annotation and edit it to account for variable name choice by users. Keeping the link will allow us to analyze these links (and the code the annotations were made near to) in the future.

2022-06-30 10:00 UTC, chvp reviewed
Looks good!

Some small comments:
 - [x] The saved annotations management page is only accessible via the annotation edit menu.
 - [x] I think we should replace the save button with a link icon or similar if the annotation is already saved?
 - [ ] The idea is to release this in a very closed beta. The limiting code for this still needs to be written. I think limiting on course ids will probably be the easiest?

2022-06-30 10:07 UTC, niknetniko approved these changes

2022-07-01 13:22 UTC, chvp commented
This year's courses taught by us. So `773` and `1151`.

2022-07-01 13:53 UTC, chvp reviewed
Code and UI changes look good to me

2022-08-03 13:08 UTC, bmesuere requested changes
### General
- It is not clear for me from using this feature if comments are linked to a course/exercise/user. All are valid choices, but a little help text might clarify this.

### Manage saved comments
- What is the goal of this page? It is not clear to me why there is a link to this page from the "add comment" form. (and for example no link in the save comments section)

### Saved comments section
- I would move the section with saved comments to its own card instead of a section in the existing card.
- Add an empty state to the saved comments (or don't show it at all if there are none)
- Remove the remove button and add it to the edit modal?
- Text overflow is used (which is good) but the title attribute (to trigger the tooltip) with the full text is missing
- Is it an option to show a second line (in a smaller font) with some statistics like "used xx times"

### Edit saved comment
- The modal dismissed by clicking on the backdrop. It is not clear of the changes will be saved in that case
- Add a remove button
- I know we use this form style on a lot of pages on Dodona, but in a modal it seems like a waste of space to put the title left instead of on top
- In the info text, maybe mention that changes to the text will not be applied to the already used instances of this comment

### Adding/reusing comment
- The "linked" icon looks very much like a button and is positioned next to a button which is not good. Putting it in the header row (next to the comment not visible icon) would be better.
- I'm not sure about the "save" flow. I would expect it to be a checkbox in the form (which shows the title input after checking)
- Could be a browser thing, but the title of a comment is shown twice in the "search" field, once big and once before the `:`:
  <img width="571" alt="image" src="https://user-images.githubusercontent.com/481872/182614382-f761d0b5-fda7-4f2a-a6a7-13c31f5c84b0.png">
- Not really sure about the search and reuse UI. Because of the alignment, its hierarchy to the actual form seems ambiguous. For one, I would try to add some kind of title like "reuse save comment" to make the intent of the search box more clear. In addition, I would expect it to be at the top of the text area because in a top to bottom flow, you would first select a saved comment, then tweak the text and then click save.

2022-08-04 14:09 UTC, jorg-vr commented
> - It is not clear for me from using this feature if comments are linked to a course/exercise/user. All are valid choices, but a little help text might clarify this.

They are linked to course, exercise and user. And all those filters are currently active when trying to reuse comments. But I can think of usecases for less strict limiting of all those options:
- a course tries to teach certain principles, so some comments are relevant for the whole course (The exercise restriction does not make sense here)
- an exercise is reused every year, or a teacher gives multiple parallel course with the same exercise (The course restriction does not make sense here)
- Multiple teachers are grading the same exercise and want to give the same types of feedback (The user limit does not make sense here)

In future versions we can explore different forms of filtering maybe, but for now this pr is already big enough to not diversify here. 

- [ ] I'll add a help text explaining that saved comments are filtered by course, exercise and user

>### Manage saved comments
>
> - What is the goal of this page? It is not clear to me why there is a link to this page from the "add comment" form. (and for example no link in the save comments section)

Saved comments are also available outside the evaluation module. (Eg. when answering questions on a random submission within a course) Here there is no sidebar available. I discussed this with @chvp and she suggested a link to a separate page as a solution.
This separate page is also available through the sidebar and allows you to manage all saved annotations across all courses.  (Similar to the other global listings pages) It thus has more general than the sidebar (And also contains a bit more info for this reason)
- [ ] I'll add a link to this from the saved comments sidebar

>### Saved comments section

All good ideas :) I'll work on it

- [ ] I would move the section with saved comments to its own card instead of a section in the existing card.
- [ ] Add an empty state to the saved comments (or don't show it at all if there are none)
- [ ] Remove the remove button and add it to the edit modal?
- [ ] Text overflow is used (which is good) but the title attribute (to trigger the tooltip) with the full text is missing
- [ ]  Is it an option to show a second line (in a smaller font) with some statistics like "used xx times"

>### Edit saved comment
>
> - The modal dismissed by clicking on the backdrop. It is not clear of the changes will be saved in that case
- [ ] Disable modal closing by clicking backdrop

> - I know we use this form style on a lot of pages on Dodona, but in a modal it seems like a waste of space to put the title left instead of on top
- [ ] Change form style
- [ ] In the info text, maybe mention that changes to the text will not be applied to the already used instances of this comment

> ### Adding/reusing comment

- [ ] The "linked" icon looks very much like a button and is positioned next to a button which is not good. Putting it in the header row (next to the comment not visible icon) would be better.

> - I'm not sure about the "save" flow. I would expect it to be a checkbox in the form (which shows the title input after checking)

I don't have enough experience evaluating to know if saving an annotation is something you do while you write the annotation, or as an after thought, when you go back to copy paste it because you have spotted the same mistake again. (The first case would suggest your flow, while the second would suggest the current flow) @chvp do you have an opinion (As you originally put the current button where it is)

> - Could be a browser thing, but the title of a comment is shown twice in the "search" field, once big and once before the ::

This is actually an OS thing. But this is not ideal
- [ ] I'll rewrite our datalist component to a custom dropdown instead of the browser native thing. 

> - Not really sure about the search and reuse UI. Because of the alignment, its hierarchy to the actual form seems ambiguous. For one, I would try to add some kind of title like "reuse save comment" to make the intent of the search box more clear. In addition, I would expect it to be at the top of the text area because in a top to bottom flow, you would first select a saved comment, then tweak the text and then click save.
- [ ] Good point. I'll try to make a more logical design

2022-08-04 14:58 UTC, chvp commented
> I don't have enough experience evaluating to know if saving an annotation is something you do while you write the annotation, or as an after thought, when you go back to copy paste it because you have spotted the same mistake again. (The first case would suggest your flow, while the second would suggest the current flow) @chvp do you have an opinion (As you originally put the current button where it is)

When implementing, I imagined myself going back to a previous instance of an annotation to save it there when wanting to re-use. I think part of the reason for the closed beta is so that we can discover the most intuitive interface. It might be the case that when actually using the functionality this is not the way I'll use it.

2022-09-13 09:00 UTC, jorg-vr commented
@bmesuere I think I handled all your comments.

I'll add some more tests later, but would prefer to have your review first. (So I don't need to change the tests multiple times because of functionality changes)

2022-09-15 13:45 UTC, bmesuere approved these changes

2022-09-15 13:55 UTC, chvp commented on app/assets/javascripts/saved_annotation_beta.ts
> +const BETA_COURSES = new Set([10, 773, 1151]);
```suggestion
const BETA_COURSES = new Set([10, 773, 1151, 1659]);
```

2022-09-15 13:55 UTC, chvp commented on app/policies/saved_annotation_policy.rb
> +  BETA_COURSES = [10, 773, 1151].freeze
```suggestion
  BETA_COURSES = [10, 773, 1151, 1659].freeze
```

2022-09-15 13:55 UTC, chvp commented on app/assets/javascripts/components/annotations/annotation_form.ts
> +        if (e.detail.text) {
Will this ever not be the case?

2022-09-15 13:55 UTC, chvp commented on app/assets/javascripts/components/pagination.ts
> +                    ${this.total > 3 + 2 * this.width && this.total - this.current > 2 + this.width ? this.pageButton(undefined, "...") : ""}
```suggestion
                    ${this.total > 3 + 2 * this.width && this.total - this.current > 2 + this.width ? this.pageButton(undefined, "…") : ""}
```

2022-09-15 13:55 UTC, chvp commented on app/assets/javascripts/components/pagination.ts
> +                    ${this.total > 3 + 2 * this.width && this.current > 3 + this.width ? this.pageButton(undefined, "...") : ""}
```suggestion
                    ${this.total > 3 + 2 * this.width && this.current > 3 + this.width ? this.pageButton(undefined, "…") : ""}
```

2022-09-15 13:55 UTC, chvp commented on app/assets/javascripts/i18n/translations.js
> +I18n.translations["en"] = I18n.extend((I18n.translations["en"] || {}), JSON.parse('{"date":{"abbr_day_names":["Sun","Mon","Tue","Wed","Thu","Fri","Sat"],"abbr_month_names":[null,"Jan","Feb","Mar","Ap
This file has been removed on develop?

2022-09-15 13:58 UTC, chvp commented
It seems weird to me that one can save an annotation when re-using a saved annotation. (During annotation creation.)

2022-09-15 15:07 UTC, jorg-vr commented
@chvp i was unsure about this. Potential usecase (why I allowed it) is if you want to start from a saved annotation, edit it and save it again as a variant

2022-09-15 15:08 UTC, chvp commented
Makes sense. Definitely fine to leave in for the closed beta.

2022-09-19 07:50 UTC, merged