Let users sign in with a known provider before linking a new provider to the user
dodona-edu/dodona pull request #3670
Opened 2022-05-30 07:22 UTC by jorg-vr

This pull request

- [ ] Tests were added
- [ ] Documentation update can be found at dodona-edu/dodona-edu.github.io#

Closes # .

2022-06-03 11:46 UTC, bmesuere requested changes
I would prefer this to be on a separate page or at least a modal instead of a flash/alert. This is an important action for the user and it feels somewhat wrong to stash this away like this.

If we make linking more transparent like this, it might also be  a good idea to list the linked providers on the profile page of a user?

2022-06-03 12:08 UTC, pdawyndt commented on config/locales/devise.nl.yml
> +      redirect_to_known_provider: "Een gebruiker (%{user}) met dezelfde gebruikersnaam (%{username}) en/of hetzelfde email address (%{email}) bestaat al voor deze onderwijsinstelling (%{institution})
de gebruiker waarVOOR je probeerde in te loggen

2022-06-03 12:09 UTC, pdawyndt commented on config/locales/devise.nl.yml
> +      identity_created: "Vanaf nu kan je ook inloggen in deze gebruiker via %{provider}."
VOOR deze gebruiker

2022-06-03 12:09 UTC, pdawyndt commented on config/locales/devise.nl.yml
> +      redirect_to_known_provider_contact: "Contacteer support als je problemen blijft hebben."
Link naar contactformulier toevoegen?

2022-06-07 11:56 UTC, niknetniko requested changes
This is more of a question, but is there an easy way to test this? Or would I have to modify the database on naos to adjust trigger this flow?

2022-06-07 11:56 UTC, niknetniko commented on app/views/users/show.html.erb
> +            <% @user.providers.where(mode: %i[prefer secondary]).each do |provider| %>
On Naos, these buttons seem to link to `https://naos.ugent.be/nl/stats/punchcard?user_id=824` for me.

2022-06-07 11:56 UTC, niknetniko commented on config/locales/devise.nl.yml
> +      duplicate_email_for_provider: "Een andere gebruiker met hetzelfde email adres (%{email_address}) bestaat al in %{provider}. Er is een manuelle tussenkomst van het Dodona support team nodig om d
```suggestion
      duplicate_email_for_provider: "Een andere gebruiker met hetzelfde e-mailadres (%{email_address}) bestaat al in %{provider}. Er is een manuele tussenkomst van het Dodona support team nodig om dit op te lossen."
```

2022-06-07 11:56 UTC, niknetniko commented on config/locales/views/auth/nl.yml
> +      title: Email adres en/of gebruikersnaam zijn niet uniek
```suggestion
      title: E-mailadres en/of gebruikersnaam zijn niet uniek
```

2022-06-07 11:56 UTC, niknetniko commented on config/locales/views/auth/en.yml
> +      message: "A user with the same username and/or email address already exists for this institution."
```suggestion
      message: "A user with the same email address and/or username already exists for this institution."
```

2022-06-07 11:56 UTC, niknetniko commented on config/locales/views/auth/nl.yml
> +      message: "Een gebruiker met dezelfde gebruikersnaam en/of hetzelfde email adres bestaat al voor deze onderwijsinstelling."
```suggestion
      message: "Een gebruiker met hetzelfde e-mailadres en/of dezelfde gebruikersnaam bestaat al voor deze onderwijsinstelling."
```

2022-06-07 11:56 UTC, niknetniko commented on config/locales/views/auth/nl.yml
> +      providers_message: "Als dit de gebruiker is waarvoor je probeerde in te loggen, bevestig dan je identiteit door in te loggen met een van onderstaande login methodes."
```suggestion
      providers_message: "Als dit de gebruiker is waarvoor je probeerde in te loggen, bevestig dan je identiteit door in te loggen met een van onderstaande login-methodes."
```

2022-06-07 11:56 UTC, niknetniko commented on config/locales/views/users/nl.yml
> +      providers_message: "Je kan inloggen via onderstaande login methodes"
```suggestion
      providers_message: "Je kan inloggen via onderstaande login-methodes"
```

2022-06-07 11:58 UTC, jorg-vr commented
@niknetniko I removed one of my identities on noas manually in the database to test this

2022-06-07 12:03 UTC, jorg-vr commented on app/views/users/show.html.erb
> +            <% @user.providers.where(mode: %i[prefer secondary]).each do |provider| %>
Hmm odd issue, they do redirect to the sign in method. But if the user is you and you are already signed in it auto succeeds. 

After this it redirects to your last requested page. Which sounds logical, but in this case it is the punchcard. I'll have a look at fixing this

2022-06-10 11:39 UTC, bmesuere requested changes
Looks good 👍 

Can you remove the drop shadow from the providers on the profile page? They look a lot like buttons now which they aren't. I think outlined-cards could work here, but I don't think I implemented them yet in the m3 refactor.

2022-06-14 06:01 UTC, bmesuere approved these changes

2022-06-27 20:03 UTC, chvp approved these changes

2022-06-27 20:03 UTC, chvp commented on config/locales/views/auth/nl.yml
> +      contact_form: "contact formulier"
```suggestion
      contact_form: "contactformulier"
```

2022-06-28 12:24 UTC, niknetniko approved these changes
Looks good. I added a test I used to review this, and there was no reason to not commit it.

2022-06-28 13:57 UTC, merged