Update Papyros
dodona-edu/dodona pull request #3684
Opened 2022-05-30 18:40 UTC by winniederidder

This pull request integrates the latest version of Papyros: v1.0.0

2022-06-27 20:06 UTC, chvp commented on app/assets/stylesheets/components/scratchpad.css.scss
> +#scratchpad-editor-wrapper , #scratchpad-editor-wrapper > div:first-child {
```suggestion
#scratchpad-editor-wrapper,
#scratchpad-editor-wrapper>div:first-child {
```
Style was made uniform in #3694, please follow it.

2022-06-28 08:30 UTC, chvp commented on app/assets/stylesheets/components/scratchpad.css.scss
> +#scratchpad-output-wrapper > div:first-child {
```suggestion
#scratchpad-output-wrapper>div:first-child {
```

2022-06-28 11:44 UTC, bmesuere commented
In chrome on mac, there is a layout jump when running code:

[Curling---Dodona.webm](https://user-images.githubusercontent.com/481872/176170353-cd2964d4-535b-4ae3-ac39-427c25440c14.webm)

2022-06-28 11:44 UTC, bmesuere requested changes
see comment above

2022-06-30 12:09 UTC, bmesuere commented
The reason is that the "switch input" link at the bottom disappears while the code is running. @winniederidder this probably needs to be fixed in papyros itself and not in the integration here?

2022-06-30 18:53 UTC, winniederidder commented
> The reason is that the "switch input" link at the bottom disappears while the code is running. @winniederidder this probably needs to be fixed in papyros itself and not in the integration here?

Indeed, this would require a small change in InputManager.ts to prevent hiding the link. The problem however with switching during a run is that we now have visual elements indicating the used lines and such, which would get out of sync. I disabled switching the mode during a run for that reason, as requiring all input handlers to be updated/active all the time when sending input goes against the purpose of having separate modes active at a time. I'm not entirely sure what the best solution would be for that, maybe a simpler solution is to somehow fix the height to prevent the rendering issue?

2022-07-02 14:39 UTC, bmesuere approved these changes

2022-07-02 14:44 UTC, bmesuere commented
Thanks @winniederidder, we'll release this early next week.

2022-07-02 14:44 UTC, merged