Add a setting to courses to limit registration to institutional accounts
dodona-edu/dodona pull request #3752
Opened 2022-06-29 13:15 UTC by jorg-vr

This pull request adds a setting to courses to limit registration to institutional accounts. (Thus excluding personal accounts). This is also the new default setting for courses.

![image](https://user-images.githubusercontent.com/21177904/182618396-9170237a-b669-43e4-a29d-8c206fcfe981.png)

What a personal account sees:
![image](https://user-images.githubusercontent.com/21177904/182618176-e2e089f2-125d-4636-9c3e-08983d3b25a3.png)

- [x] Tests were added

Part of #2597
Closes #3802

2022-08-05 11:46 UTC, niknetniko requested changes
Looks good to me (I assume #3802 is nog longer needed then?).

Do we also want to migrate existing courses to "institutional only"?

2022-08-05 11:46 UTC, niknetniko commented on config/locales/views/courses/en.yml
> +      registration-open_for_institutional_users-help_html: Anyone that belongs to an institution can register for this course. Users that signed in using a private account, such as a personal gmail o
```suggestion
      registration-open_for_institutional_users-help_html: Anyone that belongs to an institution can register for this course. Users that signed in using a private account, such as a personal Gmail or Outlook account, cannot register.
```

2022-08-05 11:46 UTC, niknetniko commented on config/locales/views/courses/en.yml
> +      registration-open_for_institutional_users-info: "Registrations are open for users that belong to an institution: only they can register for this course. Registrations are closed for users who s
```suggestion
      registration-open_for_institutional_users-info: "Registrations are open for users that belong to an institution: only they can register for this course. Registrations are closed for users who signed in using a private account, such as a personal Gmail or Outlook account."
```

2022-08-05 11:46 UTC, niknetniko commented on config/locales/views/courses/nl.yml
> +      registration-open_for_institutional_users-help_html: Iedereen die tot een instelling behoort kan zich voor deze cursus registreren. Gebruikers die zijn ingelogd met een privaat account, zoals e
```suggestion
      registration-open_for_institutional_users-help_html: Iedereen die tot een instelling behoort kan zich voor deze cursus registreren. Gebruikers die zijn ingelogd met een privéaccount, zoals een persoonlijk Gmail- of Outlook-account, kunnen niet registreren.
```

2022-08-05 11:46 UTC, niknetniko commented on config/locales/views/courses/nl.yml
> +      registration-open_for_institutional_users-info: 'De registraties staan open voor gebruikers die tot een instelling behoren: enkel zij kunnen zich registreren voor deze cursus. De registraties z
```suggestion
      registration-open_for_institutional_users-info: 'De registraties staan open voor gebruikers die tot een instelling behoren: enkel zij kunnen zich registreren voor deze cursus. De registraties zijn gesloten voor gebruikers die zijn ingelogd met een privéaccount, zoals een persoonlijk Gmail- of Outlook-account.'
```

2022-08-08 07:01 UTC, jorg-vr commented
@niknetniko This is indeed a replacement of #3802 so I will close that pr once this one is approved

With the current code all existing courses which where `open for all` will be migrated to `open for institutional` because I changed the meaning of the enum value 0

2022-08-08 09:26 UTC, niknetniko approved these changes

2022-08-12 14:58 UTC, bmesuere approved these changes
I've added some text suggestions. Shouldn't there also be a migration here to change the access level in the database?

2022-08-12 14:58 UTC, bmesuere commented on config/locales/views/courses/en.yml
> +      registration-open_for_institutional_users-info: "Registrations are open for users that belong to an institution: only they can register for this course. Registrations are closed for users who s
```suggestion
      registration-open_for_institutional_users-info: "Registrations are open for users that belong to any institution. Registrations are closed for users who signed in using a private account, such as a personal Gmail or Outlook account."
```

2022-08-12 14:58 UTC, bmesuere commented on config/locales/views/courses/nl.yml
> +      registration-open_for_institutional_users-help_html: Iedereen die tot een instelling behoort kan zich voor deze cursus registreren. Gebruikers die zijn ingelogd met een privéaccount, zoals een
```suggestion
      registration-open_for_institutional_users-help_html: Iedereen die tot een instelling behoort kan zich voor deze cursus registreren. Gebruikers die zijn ingelogd met een <b>privéaccount</b>, zoals een persoonlijk Gmail- of Outlook-account, kunnen zich <b>niet</b> registreren.
```

2022-08-12 14:58 UTC, bmesuere commented on config/locales/views/courses/nl.yml
> +      registration-open_for_institutional_users-info: 'De registraties staan open voor gebruikers die tot een instelling behoren: enkel zij kunnen zich registreren voor deze cursus. De registraties z
```suggestion
      registration-open_for_institutional_users-info: 'De registraties staan open voor gebruikers die tot een instelling behoren. De registraties zijn gesloten voor gebruikers die zijn ingelogd met een privéaccount, zoals een persoonlijk Gmail- of Outlook-account.'
```

2022-08-12 14:58 UTC, bmesuere commented on config/locales/views/courses/en.yml
> +      registration-open_for_institutional_users-help_html: Anyone that belongs to an institution can register for this course. Users that signed in using a private account, such as a personal Gmail o
```suggestion
      registration-open_for_institutional_users-help_html: Anyone that belongs to an institution can register for this course. Users that signed in using a <b>private account</b>, such as a personal Gmail or Outlook account, <b>cannot</b> register.
```

2022-08-12 15:07 UTC, jorg-vr commented
@bmesuere as stated above

> With the current code all existing courses which where open for all will be migrated to open for institutional because I changed the meaning of the enum value 0

2022-08-16 07:13 UTC, merged