Allow personal users
dodona-edu/dodona pull request #3806
Opened 2022-07-13 13:39 UTC by jorg-vr

This pull request

- [ ] Tests were added
- [ ] Documentation update can be found at dodona-edu/dodona-edu.github.io#

Closes # .

2022-07-15 12:36 UTC, jorg-vr commented on config/locales/views/auth/nl.yml
> +      other-education: "Generieke login methodes"
```suggestion
      other-education: "Generieke loginmethodes"
```

2022-07-31 15:12 UTC, chvp approved these changes
Looks good. I'm wondering if we should change the buttons on the sign in page to something more generic, since Google Workspace is Google's enterprise offering.

2022-08-01 09:56 UTC, niknetniko approved these changes

2022-08-01 09:56 UTC, niknetniko commented on config/initializers/office365.rb
> +            last_name: raw_info['name'].split(' ').drop(1).join(' '),
What happens if the name doesn't contain a space, e.g. if the user has no last/first name? (Unsure which guarantees Microsoft gives about this field, so perhaps this is not possible)

2022-08-01 09:58 UTC, jorg-vr commented on config/initializers/office365.rb
> +            last_name: raw_info['name'].split(' ').drop(1).join(' '),
Microsoft does not give any guarantees on this field. Good catch. I'll test this and make sure it works

2022-08-03 11:09 UTC, jorg-vr commented on config/initializers/office365.rb
> +            last_name: raw_info['name'].split(' ').drop(1).join(' '),
![image](https://user-images.githubusercontent.com/21177904/182593900-37699205-6c43-4a60-84f5-dadbaead0687.png)

It all works without issues

2022-08-12 15:23 UTC, bmesuere requested changes
I probably reviewed this during a coffee break previously, so here is the written down version.

I'm not a fan of combining the sign in buttons for school logins and private logins even though they take you to a common page and can be combined. The reason is that in the current solution it isn't clear what the buttons do.

A new institutional user having a google workspace account might think that the google button won't work for them because it simply says Google. In the current design, it clearly says "educational institutions" so that user knows those buttons work for them.

There is also a potential problem the other way around. Since we currently don't support gmail sign ins, a user that already knows Dodona might not infer that we support them now.

Because of this and the marketing value of this feature (this should be the 6.0 highlight), I propose adding separate buttons by adding a section between educational accounts and other institutional accounts with the microsoft and google buttons (and rename the google one back to google workspace in the first section). After a while, we could then potentially merge the private account and other account sections.

2022-08-16 12:54 UTC, jorg-vr commented
I updated the page

2022-08-16 18:20 UTC, bmesuere approved these changes

2022-08-18 08:57 UTC, merged