fix: solve typing issues
dodona-edu/dodona pull request #3850
Opened 2022-08-01 13:12 UTC by BramDevlaminck

This pull request solves typing issues in `assets/javascripts`

I added the `@types/bootstrap` dependency to solve typing issues created by bootstrap

Closes #3497.

2022-08-01 14:47 UTC, chvp requested changes

2022-08-01 14:47 UTC, chvp commented on .github/workflows/lint.yml
> +        yarn tsc --skipLibCheck --noEmit
```suggestion
        yarn typeCheck
```

2022-08-02 07:34 UTC, jorg-vr commented on app/assets/javascripts/types/index.d.ts
> +declare var bootstrap: { Alert: any, Button: any, Collapse: any, Dropdown: any, Modal: any, Popover: any, Tab: any, Tooltip: any };
Shouldn't this be fixed by the new dependency  `"@types/bootstrap"`?
If  `"@types/bootstrap"` does not fix the bootstrap typing errors, why do we still need it?

2022-08-02 07:45 UTC, chvp commented on app/assets/javascripts/types/index.d.ts
> +declare var bootstrap: { Alert: any, Button: any, Collapse: any, Dropdown: any, Modal: any, Popover: any, Tab: any, Tooltip: any };
Or at least, shouldn't the `any`s here be replaced with the relevant constructor types (if possible)?

2022-08-02 08:00 UTC, BramDevlaminck commented on app/assets/javascripts/types/index.d.ts
> +declare var bootstrap: { Alert: any, Button: any, Collapse: any, Dropdown: any, Modal: any, Popover: any, Tab: any, Tooltip: any };
> Shouldn't this be fixed by the new dependency `"@types/bootstrap"`?
> If `"@types/bootstrap"` does not fix the bootstrap typing errors, why do we still need it?

It seems that the `@types/bootstrap` dependency is used in `app/assets/javascripts/score_item.ts` on line 84 and 87 to make the `.collapse` possible. 

![image](https://user-images.githubusercontent.com/68779933/182321253-c92f7aae-e10b-4bee-894f-169daee87d9e.png)

I don't immediately see another way of solving that type issue without the dependency. There is no obvious type that the element can be cast to that has the required properties

2022-08-02 08:02 UTC, BramDevlaminck commented on app/assets/javascripts/types/index.d.ts
> +declare var bootstrap: { Alert: any, Button: any, Collapse: any, Dropdown: any, Modal: any, Popover: any, Tab: any, Tooltip: any };
> Or at least, shouldn't the `any`s here be replaced with the relevant constructor types (if possible)?

I'll take a look if this is possible. I just took inspiration from the `Window`-interface defined at the top of that file
```ts
declare interface Window {
    dodona: any;
    bootstrap: { Alert: any, Button: any, Collapse: any, Dropdown: any, Modal: any, Popover: any, Tab: any, Tooltip: any };
    MathJax: MathJaxObject;
}
```

2022-08-02 08:16 UTC, chvp commented on app/assets/javascripts/types/index.d.ts
> +declare var bootstrap: { Alert: any, Button: any, Collapse: any, Dropdown: any, Modal: any, Popover: any, Tab: any, Tooltip: any };
That's probably because we didn't have `@types/bootstrap` yet. Now that we have it, that should be updated as well IMO.

2022-08-02 12:03 UTC, BramDevlaminck commented on app/assets/javascripts/types/index.d.ts
> +declare var bootstrap: { Alert: any, Button: any, Collapse: any, Dropdown: any, Modal: any, Popover: any, Tab: any, Tooltip: any };
As a *fix* for the UMD global access error that kept showing up I allowed UMD global access since that is how it was done. Please let me know if we don't want this.

The problem is that to not use the UMD global access, a `bootstrap`-variable needs to be defined in `index.d.ts`. However, this makes accessing the `bootstrap`-namespace in that file impossible, which implies I can't access the types from `@types/bootstrap`.

2022-08-02 12:09 UTC, jorg-vr commented on app/assets/javascripts/types/index.d.ts
> +    bootstrap: { Alert: bootstrap.Alert, Button: bootstrap.Button, Collapse: bootstrap.Collapse, Dropdown: bootstrap.Dropdown, Modal: bootstrap.Modal, Popover: bootstrap.Popover, Tab: bootstrap.Tab,
could this be reduced to bootstrap: bootstrap?

2022-08-02 12:11 UTC, BramDevlaminck commented on app/assets/javascripts/types/index.d.ts
> +    bootstrap: { Alert: bootstrap.Alert, Button: bootstrap.Button, Collapse: bootstrap.Collapse, Dropdown: bootstrap.Dropdown, Modal: bootstrap.Modal, Popover: bootstrap.Popover, Tab: bootstrap.Tab,
Sadly not since the bootstrap used in `bootstrap.Alert` (and so on,...) is a namespace and not a type.

2022-08-02 12:14 UTC, jorg-vr commented on app/assets/javascripts/types/index.d.ts
> +declare var bootstrap: { Alert: any, Button: any, Collapse: any, Dropdown: any, Modal: any, Popover: any, Tab: any, Tooltip: any };
I think this is an ok fix. 

I am not a big fan of bootstrap being a not imported global variable in general (Which is why this modifier is needed if I understand it correctly?). But fixing that is probably out of the scope of this pr

2022-08-02 12:15 UTC, jorg-vr approved these changes

2022-08-02 12:15 UTC, niknetniko commented on app/assets/javascripts/types/index.d.ts
> +    bootstrap: { Alert: bootstrap.Alert, Button: bootstrap.Button, Collapse: bootstrap.Collapse, Dropdown: bootstrap.Dropdown, Modal: bootstrap.Modal, Popover: bootstrap.Popover, Tab: bootstrap.Tab,
You should be able to write it as `bootstrap: typeof bootstrap;`.

2022-08-02 12:23 UTC, niknetniko approved these changes

2022-08-02 13:05 UTC, chvp approved these changes

2022-08-02 13:05 UTC, merged