Create bash script for releasing
dodona-edu/dodona pull request #3853
Opened 2022-08-02 08:46 UTC by jorg-vr

This pull request adds a shell script that automates releasing new versions.

Script can be run as `bin/release [version]`

Tested it for release 5.6.5

Script folows the commands from https://github.com/dodona-edu/wiki/blob/main/technical/release.md which I already copy pasted on release
The only changes is that I added some sed commands to edit `config/initializers/00_version.rb`
I also made it run all tests on every release
And I made sure the scripts exits if any single command fails

2022-08-02 08:50 UTC, chvp requested changes

2022-08-02 08:50 UTC, chvp commented on bin/release
> +#!/bin/bash
```suggestion
#!/usr/bin/env bash
```

2022-08-02 08:50 UTC, chvp commented on bin/release
> +version=$1
I would add a check before this that `$#` is exactly equal to 1 (and print a help message and exit otherwise).

2022-08-02 08:50 UTC, chvp commented on bin/release
> +readarray -d . -t version_array<<<"$version."
Also maybe add a check here that `version_array`'s length is exactly equal to three?

2022-08-02 09:39 UTC, chvp commented
Shellcheck is not entirely happy:

```
[Line 5:](javascript:setPosition(5, 6))
trap 'last_command=$current_command; current_command=$BASH_COMMAND' DEBUG
     ^-- [SC2154](https://www.shellcheck.net/wiki/SC2154) (warning): current_command is referenced but not assigned.
 
[Line 7:](javascript:setPosition(7, 6))
trap 'echo "\"${last_command}\" command failed with exit code $?."' EXIT
     ^-- [SC2154](https://www.shellcheck.net/wiki/SC2154) (warning): last_command is referenced but not assigned.
```

2022-08-02 13:07 UTC, chvp approved these changes

2022-08-02 13:07 UTC, chvp commented on bin/release
> +if [ "$#" -ne 1 ];
```suggestion
if [ "$#" -ne 1 ]
```

2022-08-02 13:07 UTC, chvp commented on bin/release
> +sed -i "s/PATCH = [0-9]\+/PATCH = ${version_array[2]}/g" config/initializers/00_version.rb;
```suggestion
sed -i "s/MAJOR = [0-9]\+/MAJOR = ${version_array[0]}/g" config/initializers/00_version.rb
sed -i "s/MINOR = [0-9]\+/MINOR = ${version_array[1]}/g" config/initializers/00_version.rb
sed -i "s/PATCH = [0-9]\+/PATCH = ${version_array[2]}/g" config/initializers/00_version.rb
```

2022-08-02 13:07 UTC, chvp commented on bin/release
> +if [ "${#version_array[@]}" -ne 3 ];
```suggestion
if [ "${#version_array[@]}" -ne 3 ]
```

2022-08-02 13:07 UTC, chvp commented on bin/release
> +if [ "$confirm" == "A" ] || [ "$confirm" == "a" ];
```suggestion
if [ "$confirm" == "A" ] || [ "$confirm" == "a" ]
```

2022-08-02 13:29 UTC, chvp requested changes
The script exits with `"cap production deploy" command failed with exit code 0.` which is kinda weird.

2022-08-02 13:31 UTC, chvp commented on bin/release
> +trap 'echo "\"${last_command}\" command failed with exit code $?."' EXIT
```suggestion
trap '[ $? -eq 0 ] || echo "\"${last_command}\" command failed with exit code $?."' EXIT
```

2022-08-02 13:39 UTC, chvp approved these changes

2022-08-03 08:11 UTC, bmesuere approved these changes
During the coffee break, we should brainstorm about releasing using a github action

2022-08-03 08:20 UTC, merged