Update privacy declaration to also cover personal accounts
dodona-edu/dodona pull request #3855
Opened 2022-08-02 13:39 UTC by jorg-vr

This pull request updates the privacy page and the data page to also cover personal accounts.

Part of https://github.com/dodona-edu/dodona/issues/2597.

2022-08-02 13:49 UTC, niknetniko commented on app/views/pages/privacy.nl.html.erb
> +        <p>Indien je dodona gebruikt in functie van een bedrijf, school, onderwijs- of onderzoeksinstelling zijn zij de
```suggestion
        <p>Indien je Dodona gebruikt in functie van een bedrijf, school, onderwijs- of onderzoeksinstelling zijn zij de
```

2022-08-05 10:03 UTC, niknetniko requested changes

2022-08-05 10:03 UTC, niknetniko commented on app/views/pages/data.en.html.erb
> +            <p>When signing into Dodona, we exclusively use external authentication systems. Examples of these are Office 365, google, Smartschool (for secondary education only) and SAML (for higher
```suggestion
            <p>When signing into Dodona, we exclusively use external authentication systems. Examples of these are Office 365, Google, Smartschool (for secondary education only) and SAML (for higher education only). This means that under no circumstances, Dodona gets access to your password. What we do get access to when signing in are your <b>name</b>, <b>username</b> and <b>email address</b>. We need these data to identify you correctly and to be able to contact you in case of any problems. Next to that, we also store the <b>institution</b> you used to sign in, your <b>preferred language</b> and your <b>local timezone</b>. Your timezone is needed to display any deadlines set by  courses correctly.</p>
```

2022-08-05 10:03 UTC, niknetniko commented on app/views/pages/data.nl.html.erb
> +            <p>Om aan te melden bij Dodona gebruiken we uitsluitend het externe loginsystemen. Voorbeelden hiervan zijn Office 365, google, Smartschool (alleen voor het secundair onderwijs) en SAML (
```suggestion
            <p>Om aan te melden bij Dodona gebruiken we uitsluitend het externe loginsystemen. Voorbeelden hiervan zijn Office 365, Google, Smartschool (alleen voor het secundair onderwijs) en SAML (alleen voor het hoger onderwijs). Dodona krijgt hierdoor op geen enkel moment jouw wachtwoord te zien. Wat we wel meekrijgen bij het inloggen zijn je <b>naam</b>, <b>gebruikersnaam</b> en <b>e-mailadres</b>. Deze gegevens hebben we nodig om je correct te identificeren en om je te contacteren in geval van problemen. Daarnaast houden we ook bij via <b>welke school</b> je bent ingelogd, wat je <b>voorkeurstaal</b> is en in welke <b>tijdzone</b> je je bevindt. Dit laatste is nodig om eventuele deadlines correct weer te geven.</p>
```

2022-08-05 10:03 UTC, niknetniko commented on app/views/pages/privacy.nl.html.erb
> +        <p>Bij het aanmaken van een dodona account wordt jouw expliciete instemming met deze privacyverklaring gevraagd.
```suggestion
        <p>Bij het aanmaken van een Dodona-account wordt jouw expliciete instemming met deze privacyverklaring gevraagd.
```

2022-08-05 11:46 UTC, niknetniko approved these changes

2022-08-16 08:33 UTC, bmesuere requested changes

2022-08-16 08:33 UTC, bmesuere commented on app/views/pages/data.nl.html.erb
> +            <p>Om aan te melden bij Dodona gebruiken we uitsluitend het externe loginsystemen. Voorbeelden hiervan zijn Office 365, Google, Smartschool (alleen voor het secundair onderwijs) en SAML (
```suggestion
            <p>Om aan te melden bij Dodona gebruiken we uitsluitend externe loginsystemen. Voorbeelden hiervan zijn Office 365, Google, Smartschool (alleen voor het secundair onderwijs) en SAML (alleen voor het hoger onderwijs). Dodona krijgt hierdoor op geen enkel moment jouw wachtwoord te zien. Wat we wel meekrijgen bij het inloggen zijn je <b>naam</b>, <b>gebruikersnaam</b> en <b>e-mailadres</b>. Deze gegevens hebben we nodig om je correct te identificeren en om je te contacteren in geval van problemen. Daarnaast houden we ook bij via <b>welke school</b> je bent ingelogd, wat je <b>voorkeurstaal</b> is en in welke <b>tijdzone</b> je je bevindt. Dit laatste is nodig om eventuele deadlines correct weer te geven.</p>
```

2022-08-16 08:33 UTC, bmesuere commented on app/views/pages/privacy.en.html.erb
> +        <p>If you are log in to Dodona using an account that belongs to a school, educational or research institution, they are the data controller.
```suggestion
        <p>If you log in to Dodona using an account that belongs to a school, educational or research institution, they are the data controller and Dodona processes the data on behalf of them.
```

2022-08-16 08:33 UTC, bmesuere commented on app/views/pages/privacy.en.html.erb
> +          to the processing of your personal data?"</p>
The acceptance should not be the case for institutional accounts, right? In addition, I would change "create an account on Dodona" to "use Dodona" to be more correct.

2022-08-16 08:33 UTC, bmesuere commented on app/views/pages/privacy.en.html.erb
> +          rights, you can address the Dodona team. If relevant we will first coordinate your request with your
maybe add an additional link to the contact form here?

2022-08-16 08:41 UTC, jorg-vr commented on app/views/pages/privacy.en.html.erb
> +          to the processing of your personal data?"</p>
As currently implemented in #3859 it is just forced for everyone

As you specified in #2597
> Show the terms of service on first sign in (actually, it wouldn't be a bad idea to do this for other new accounts as well)

2022-08-16 08:41 UTC, jorg-vr commented on app/views/pages/privacy.en.html.erb
> +          to the processing of your personal data?"</p>
I am not sure how "use Dodona" is more correct. Are you not using dodona when you are clicking through the pages without signing in?

2022-08-16 09:41 UTC, chvp reviewed
Changes look good, but as discussed in the break the split between institutional use and personal use needs to be clearer. (Reviewing so that it's not in my to-review list.)

2022-08-16 18:19 UTC, bmesuere approved these changes

2022-08-16 19:16 UTC, chvp approved these changes

2022-08-16 19:16 UTC, chvp commented on app/views/pages/privacy.en.html.erb
> +          technical issues. At the request of an individual user, the processing of his/her data can be stopped if this
```suggestion
          technical issues. At the request of an individual user, the processing of their data can be stopped if this
```

2022-08-16 19:16 UTC, chvp commented on app/views/pages/privacy.nl.html.erb
> +          vraag van een individuele gebruiker kan de verwerking van zijn/haar gegevens stopgezet worden, indien dit in overeenstemming is met de
```suggestion
          vraag van een individuele gebruiker kan de verwerking van hun gegevens stopgezet worden, indien dit in overeenstemming is met de
```

2022-08-17 13:06 UTC, merged