Force new users to accept the privacy policy before creating an account
dodona-edu/dodona pull request #3859
Opened 2022-08-04 08:16 UTC by jorg-vr

This pull request forces new users to accept the privacy policy before creating an account. Replaces #3803 

- [ ] Tests were added
- [ ] Documentation update can be found at dodona-edu/dodona-edu.github.io#

Closes # .

2022-08-05 11:56 UTC, niknetniko requested changes

2022-08-05 11:56 UTC, niknetniko commented on config/locales/views/auth/nl.yml
> +      accept_button: Accepteer de privacyverklaring
```suggestion
      accept_button: Privacyverklaring accepteren
```

2022-08-05 11:56 UTC, niknetniko commented on config/locales/views/auth/nl.yml
> +      text_html: "Om Dodona te gebruiken moet je onze privacyverklaring accepteren. Op de <a href=\"%{your_data}\" target=\"_blank\">jouw data</a> pagina leggen we in mensentaal uit welke data we ver
```suggestion
      text_html: "Om Dodona te gebruiken moet je onze privacyverklaring accepteren. Op de pagina <a href=\"%{your_data}\" target=\"_blank\">jouw data</a> leggen we in mensentaal uit welke data we verzamelen en hoe we die gebruiken. De juridisch bindende versie kan je in onze <a href=\"%{privacy_statement}\" target=\"_blank\">privacyverklaring</a> vinden."
```

2022-08-05 12:36 UTC, niknetniko approved these changes

2022-08-16 09:43 UTC, chvp reviewed
Looks good, but if I understood correctly this will be changed to not force an accept for institutional users?

2022-08-16 13:07 UTC, jorg-vr commented
@chvp yes I will update this, so that the new behavior only applies for personal accounts

2022-08-16 18:22 UTC, bmesuere approved these changes

2022-08-16 19:18 UTC, chvp approved these changes

2022-08-18 08:58 UTC, merged