Handle errors when Dodona has no push rights to exercise repo
dodona-edu/dodona pull request #3860
Opened 2022-08-04 08:42 UTC by BramDevlaminck

This pull request gives an error when Dodona has no push rights to an exercise repo.
This way we are notified when pushing fails

Closes #3298  .

2022-08-04 13:46 UTC, chvp requested changes
[This translation](https://github.com/dodona-edu/dodona/blob/develop/config/locales/views/repositories/nl.yml#L4) should be updated to mention the push requirement (also in English).

2022-08-04 13:58 UTC, BramDevlaminck commented on app/models/repository.rb
> +      errors.push err unless status
Ah, in this case I assume I have to do push a new ConfigParseError object to this array. Or should I not use this type of error to process the error message given by git?

2022-08-05 07:58 UTC, BramDevlaminck commented on app/models/repository.rb
> +      errors.push err unless status
I've updated the pr description with how the email looks like

2022-08-05 08:03 UTC, jorg-vr commented on test/models/repository_test.rb
> +  test 'should catch error when commit fails' do
Could you add another test that checks if the email gets send?

2022-08-05 08:06 UTC, BramDevlaminck commented on test/models/repository_test.rb
> +  test 'should catch error when commit fails' do
Yes, I'll do

2022-08-05 08:20 UTC, chvp commented on config/locales/views/error_mailer/nl.yml
> +          Tijdens het verwerken "%{repository}" kon Dodona de aanpassingen van de verwerkte oefeningen niet pushen. De exacte error was: %{error}.
```suggestion
          Tijdens het verwerken van "%{repository}" kon Dodona de aanpassingen aan de verwerkte oefeningen niet pushen. De exacte error was: %{error}.
```

2022-08-05 08:20 UTC, chvp commented on config/locales/views/error_mailer/nl.yml
> +          Zorg er zeker voor dat de Dodona gebruiker push rechten heeft op je repository.
```suggestion
          Zorg er zeker voor dat de Dodona gebruiker pushrechten heeft op je repository.
```

2022-08-05 08:20 UTC, chvp commented on config/locales/views/error_mailer/en.yml
> +          While processing "%{repository}", Dodona was unable to push the edits to the processed exercises. The exact error was: %{error}
```suggestion
          While processing "%{repository}", Dodona was unable to push the edits to the processed exercises. The exact error was: %{error}.
```

2022-08-05 08:20 UTC, chvp commented on config/locales/views/error_mailer/nl.yml
> +      subject: 'Pushen naar "%{repository}" mislukt'
```suggestion
      subject: '[Dodona] Pushen naar "%{repository}" mislukt'
```

2022-08-05 08:20 UTC, chvp commented on config/locales/views/error_mailer/en.yml
> +      subject: 'Failed to push to "%{repository}"'
```suggestion
      subject: '[Dodona] Failed to push to "%{repository}"'
```

2022-08-05 08:20 UTC, chvp commented on config/locales/views/error_mailer/nl.yml
> +        error_message_html: |
The `_html` postfix is used for translations that include HTML which should not be escaped. That's not the case for this translation, so it should be left out.

2022-08-05 08:20 UTC, chvp commented on app/mailers/error_mailer.rb
> +           )
Did you have a reason not to create a view in `app/views/error_mailer`? Then we can serve a multipart email with both HTML and plain text.

2022-08-05 08:20 UTC, chvp commented on test/models/repository_test.rb
> +  test 'should send a mail chen commit fails' do
```suggestion
  test 'should send a mail when commit fails' do
```

2022-08-05 08:21 UTC, BramDevlaminck commented on app/mailers/error_mailer.rb
> +           )
No I did not have a reason to do this. I just did not notice, I'll change this

2022-08-05 08:47 UTC, BramDevlaminck commented on config/locales/views/error_mailer/nl.yml
> +        error_message_html: |
it seems this is needed for 1 link that is in the message:

without `_html` suffix
<img width="1451" alt="image" src="https://user-images.githubusercontent.com/68779933/183039570-d15e5baf-05dd-4d07-a720-73323d709980.png">

with `_html` suffix
<img width="1297" alt="image" src="https://user-images.githubusercontent.com/68779933/183040072-ef1fc10c-a14a-4f26-97e8-63fc940b4679.png">

2022-08-05 08:50 UTC, chvp commented on config/locales/views/error_mailer/nl.yml
> +        error_message_html: |
Where does this link come from? Only the name is set [here](https://github.com/dodona-edu/dodona/pull/3860/files/44009a6bb61eec67b52a1e95e0ba49f8814f506d#diff-e45dbb23b29d2ff475462fffb81b0fa06f75f18281dca9bb9e3b37aec00424deR46) as far as I can tell?

2022-08-05 08:51 UTC, jorg-vr commented on config/locales/views/error_mailer/nl.yml
> +        error_message_html: |
`The exact error was: %{error}.` It is in the errorstring

2022-08-05 08:53 UTC, jorg-vr commented on config/locales/views/error_mailer/nl.yml
> +        error_message_html: |
ah but is the name taht turns into a link, my mistake, odd

2022-08-05 08:54 UTC, BramDevlaminck commented on config/locales/views/error_mailer/nl.yml
> +        error_message_html: |
I found my mistake. I forgot a `.name` in the `.html.erb` file

2022-08-05 09:39 UTC, chvp approved these changes

2022-08-05 11:59 UTC, niknetniko requested changes

2022-08-05 11:59 UTC, niknetniko commented on config/locales/views/error_mailer/nl.yml
> +      auto-generated: ps. Dit bericht werd automatisch gegenereerd.
```suggestion
      auto-generated: PS Dit bericht werd automatisch gegenereerd.
```

2022-08-05 11:59 UTC, niknetniko commented on config/locales/views/error_mailer/nl.yml
> +      hint: 'Zorg er zeker voor dat de Dodona gebruiker pushrechten heeft op je repository.'
```suggestion
      hint: 'Zorg er zeker voor dat de Dodona-gebruiker pushrechten heeft op je repository.'
```

2022-08-05 12:18 UTC, niknetniko approved these changes

2022-08-05 12:29 UTC, jorg-vr approved these changes

2022-08-05 12:29 UTC, merged