Obscure reviewers name in feedback evaluation
dodona-edu/dodona pull request #3862
Opened 2022-08-05 15:30 UTC by BramDevlaminck

This pull request adds the option for reviewers to hide their name for students in an evaluation.

- [ ] Tests were added
- [ ] Documentation update can be found at dodona-edu/dodona-edu.github.io#

Closes #2717  .

2022-08-16 08:27 UTC, jorg-vr requested changes
For me it was not immediately clear which of these two buttons was active: 

![image](https://user-images.githubusercontent.com/21177904/184826412-cbe4f549-e964-44c2-bf68-730b699445d0.png)


Overall good work on this one :)

2022-08-16 08:27 UTC, jorg-vr commented on app/assets/stylesheets/theme/m3-colors.css.scss
> +$gray-15: #2b2b2f;
If you add a new color, put it a the correct line :) Is this color in line with the material design specification? (these colors are all auto generated)

2022-08-16 08:27 UTC, jorg-vr commented on app/views/annotations/_annotation.json.jbuilder
> +  if !current_user.a_course_admin? && !annotation.evaluation.nil? && annotation.evaluation.anonymous? && (current_user.id != annotation.user.id)
I would make this a function in the annotation model

You can shorten `!annotation.evaluation.nil? && annotation.evaluation.anonymous?`
to `annotation.evaluation&.anonymous?`

2022-08-16 08:27 UTC, jorg-vr commented on test/controllers/evaluations_controller_test.rb
> +  end
Could you also write a test to see if the name is effectively hidden when anonymous is active.

(And maybe two further tests that course admins, and own annotations still show the correct name)

2022-08-16 08:50 UTC, BramDevlaminck commented on app/assets/stylesheets/theme/m3-colors.css.scss
> +$gray-15: #2b2b2f;
Oops, I did not mean to put it out of order :sweat_smile: .

How can I best check if this color is in spec? I *stole* it from the user-table in the same screen. It's the same grey that is used to indicate the selected-rows in the user table. Maybe I'm wrong, but this seems to be some default grey used by the table because I could not find it back in the stylesheet.

<img width="1192" alt="Screenshot 2022-08-16 at 10 49 25" src="https://user-images.githubusercontent.com/68779933/184838544-dd544b79-8e30-4d86-9097-97996e5b69eb.png">

2022-08-16 08:53 UTC, BramDevlaminck commented
> For me it was not immediately clear which of these two buttons was active:
> 
> ![image](https://user-images.githubusercontent.com/21177904/184826412-cbe4f549-e964-44c2-bf68-730b699445d0.png)
> 
> Overall good work on this one :)

I agree that this colour is not very clear. The problem is that when using 1 shade darker it seems really dark and that colour is not yet used in that screen

<img width="1129" alt="image" src="https://user-images.githubusercontent.com/68779933/184838942-fc28178d-9d48-4b95-865f-aa07d4081e20.png">

As described in my response to the new colour, I tried to reuse the already present colours in the UI.

2022-08-16 08:55 UTC, bmesuere commented on app/assets/stylesheets/theme/m3-colors.css.scss
> +$gray-15: #2b2b2f;
Isn't it possible to reuse a (different) existing color? These scales are auto-generated so I would advise against adding new lightness values.

2022-08-16 08:58 UTC, bmesuere requested changes
The indication of the "hide reviewers" setting is too prominent in the overview page. It is in a lager font and it is at the top of the page. In my opinion, it should be the same size as the sentence below (or even smaller) and I would put it below the existing sentence. I also wouldn't use an icon there because we don't do is for the other settings. If possible, add a link to change the setting.

2022-08-16 09:04 UTC, jorg-vr commented
For the button colors: I would look at the color scheme of elevated buttons https://m3.material.io/components/buttons/specs#0eea2a85-b4d7-4c74-b08e-98410b9412c7 as this is closest to the current button

2022-08-16 15:25 UTC, niknetniko commented on config/locales/js/nl.yml
> +      anonymous_message: 'Dit commentaar is deel van een evaluatie'
```suggestion
      anonymous_message: 'Deze opmerking is deel van een evaluatie'
```

2022-08-16 15:49 UTC, niknetniko approved these changes

2022-08-16 18:32 UTC, bmesuere requested changes

2022-08-16 18:32 UTC, bmesuere commented on app/assets/javascripts/code_listing/user_annotation.ts
> +            return this.createdAt;
I'm confused by this. Does "created at" contain the message? Why?

2022-08-16 18:32 UTC, bmesuere commented on app/assets/javascripts/evaluation.ts
> +
Aren't the changes in this file an artefact of the previous implementation? Can't they be removed or is there a good reason to keep them?

2022-08-16 18:32 UTC, bmesuere commented on app/models/annotation.rb
> +  end
@jorg-vr I think this should be moved to the policy, right?

2022-08-16 18:32 UTC, bmesuere commented on app/views/annotations/_annotation.json.jbuilder
> +end
Ok, now I see where the created_at came from. This is a bit of a hack and I would prefer a cleaner solution.

2022-08-17 16:20 UTC, BramDevlaminck commented on app/assets/javascripts/evaluation.ts
> +
These changes are indeed artefacts from the previous implementation. I left them because when I had to add another choice-option I had to rename all these variables because the original names *assume* that it's the only choice that will need to be made in that screen. It seemed better to me to leave this name-change in case that anyone would need to add something later.

If you prefer, I'll just change it back to the original names.

2022-08-18 07:39 UTC, jorg-vr commented on app/models/annotation.rb
> +  end
It could move there, but I don't have a strong opinion on it.

The method name should end on a question mark though, as it returns a boolean

2022-08-18 08:11 UTC, BramDevlaminck commented on app/models/annotation.rb
> +  end
What should I do?

2022-08-18 08:15 UTC, jorg-vr commented on app/models/annotation.rb
> +  end
Move the relevant check to the annotation_policy (Which manages who can see or edit what about annotations)

and add a question mark to the method name

2022-08-18 12:35 UTC, jorg-vr requested changes

2022-08-18 12:35 UTC, jorg-vr commented on app/policies/annotation_policy.rb
> +    !user.a_course_admin? && !record.evaluation.nil? && (user.id != record.user.id)
We probably want to check if the user is course admin of this course (Not just any course)

2022-08-18 12:35 UTC, jorg-vr commented on app/views/annotations/_annotation.json.jbuilder
> +json.test annotation.user.id
this test line is probably no longer needed?

2022-08-18 13:06 UTC, BramDevlaminck commented on app/policies/annotation_policy.rb
> +    !user.a_course_admin? && !record.evaluation.nil? && (user.id != record.user.id)
yes! thank you. I did not see the difference

2022-08-18 14:15 UTC, jorg-vr approved these changes

2022-08-25 12:34 UTC, bmesuere requested changes
Can you request a review from @chvp when you updated the PR?

2022-08-25 12:34 UTC, bmesuere commented on app/views/annotations/_annotation.json.jbuilder
> +
Is there a reason why this message is passed from the API? I would expect that this would just be a boolean and that the JS-side fetches the message. You are already using the js i18n.

2022-08-25 12:34 UTC, bmesuere commented on config/locales/js/nl.yml
> +      anonymous_message: 'Deze opmerking is deel van een evaluatie'
```suggestion
      anonymous_message: 'Deze opmerking maakt deel uit van een evaluatie'
```

2022-08-25 12:34 UTC, bmesuere commented on app/views/annotations/_annotation.json.jbuilder
> +    json.url ''
I discussed this with @chvp. The cleanest thing to do in this case is not return the field at all in the json output instead of setting an empty string. The same is true for last_updated below.

2022-08-25 12:52 UTC, bmesuere commented on app/views/annotations/_annotation.json.jbuilder
> +
I would generalize it and make it a boolean named part_of_evaluation. The client can then decide on how to handle that.

2022-08-25 12:56 UTC, BramDevlaminck commented on app/views/annotations/_annotation.json.jbuilder
> +
Isn't it more logical to name the boolean something like `is_anonymized`? The client will never receive the name if the feedback is part of an evaluation. The only choice they have is which message they show to indicate this happened.

2022-08-27 07:48 UTC, chvp requested changes

2022-08-27 07:48 UTC, chvp commented on app/assets/javascripts/code_listing/user_annotation.ts
> +    public readonly lastUpdatedBy: UserAnnotationUserData | null;
These type annotations don't match the generated JSON in the jbuilder file. In the jbuilder file you don't send the fields in these objects. Sending `null` values in the jbuilder file seems like the correct way to do this.

2022-08-27 08:00 UTC, bmesuere commented on app/assets/javascripts/code_listing/user_annotation.ts
> +    public readonly lastUpdatedBy: UserAnnotationUserData | null;
@chvp didn't you suggest to not send the fields when we discussed this?

2022-08-27 08:06 UTC, chvp commented on app/assets/javascripts/code_listing/user_annotation.ts
> +    public readonly lastUpdatedBy: UserAnnotationUserData | null;
I didn't realize the fields were in objects at the time. Not sending the objects at all also sounds good, but not as nice to represent in the typescript definition I think?

2022-08-29 06:57 UTC, BramDevlaminck commented on app/assets/javascripts/code_listing/user_annotation.ts
> +    public readonly lastUpdatedBy: UserAnnotationUserData | null;
I've changed it to make the types match. The field `name` in the `UserAnnotationUserData`-object can now be null and in the json I send the explicit `nil` value for the fields that should be hidden when the feedback is part of an evaluation.

2022-08-29 07:00 UTC, chvp commented on app/assets/javascripts/code_listing/user_annotation.ts
> +    public readonly lastUpdatedBy: UserAnnotationUserData | null;
That was not one of the options 😉. Either leave the object out or send a null value in its place.

2022-08-29 07:03 UTC, chvp commented on app/assets/javascripts/code_listing/user_annotation.ts
> +    public readonly lastUpdatedBy: UserAnnotationUserData | null;
And I think @bmesuere prefers leaving the object out.

2022-08-29 07:08 UTC, BramDevlaminck commented on app/assets/javascripts/code_listing/user_annotation.ts
> +    public readonly lastUpdatedBy: UserAnnotationUserData | null;
> That was not one of the options 😉. Either leave the object out or send a null value in its place.

Ah, okay, I understood your message wrong. I'll change it back to leaving it out, my bad

2022-08-29 07:41 UTC, chvp approved these changes

2022-08-29 07:41 UTC, chvp commented on app/policies/annotation_policy.rb
> +    # "user" is the person that receives the annotation
```suggestion
    # "user" is the person that is viewing the annotation
```

2022-08-29 07:41 UTC, chvp commented on app/views/annotations/_annotation.json.jbuilder
> +# hide reviewer name depending on evaluation and current user
```suggestion
# hide name of last editor depending on evaluation and current user
```

2022-08-29 07:41 UTC, chvp commented on app/assets/javascripts/code_listing/user_annotation.ts
> +        const user = this.user?.name;
```suggestion
        const user = this.user!.name;
```
(Using the non null assertion makes more sense semantically to me.)

2022-08-29 08:45 UTC, BramDevlaminck commented on app/assets/javascripts/code_listing/user_annotation.ts
> +        const user = this.user?.name;
I don't really like the usage of `!`. I see what you mean that it makes more sense since the name should always exist when we get there, but it feels like asking for trouble. 

Wouldn't it be a better option to use `?`, but place a comment next to the line that shows the developer that name should always exist?

2022-08-29 09:03 UTC, niknetniko commented on app/assets/javascripts/code_listing/user_annotation.ts
> +        const user = this.user?.name;
> Wouldn't it be better to use `?`, but place a comment next to the line that shows the developer that name should always exist?

This seems to me to be exactly the purpose of `!`; to indicate that the developer is certain a value will always be there and won't be null/undefined.

2022-08-30 17:47 UTC, bmesuere approved these changes

2022-08-30 17:47 UTC, merged