Use local storage to save filter in edit series to add exercises
dodona-edu/dodona pull request #3881
Opened 2022-08-12 15:27 UTC by BramDevlaminck

This pull request uses the local storage to keep track of the filters used in edit series to add exercises.

Closes #3578 .

2022-08-16 07:33 UTC, jorg-vr requested changes

2022-08-16 07:33 UTC, jorg-vr commented on app/assets/javascripts/search.ts
I am not a fan of how you are passing around `localStorageKey` in every method. I would just set it as a class param here. And then you can use it in the relevant methods

2022-08-16 07:33 UTC, jorg-vr commented on app/assets/javascripts/search.ts
> +        this.arrayQueryParams.listeners = this.arrayQueryParams.listeners.map(() => (k => this.paramChange(k, localStorageKey)));
This will have unintended consequences. There are other listeners (outside this class) that will be overwritten this way.

2022-08-16 07:33 UTC, jorg-vr commented on app/views/layouts/_searchbar.html.erb
> +          url += "?" + prevDefinedSearchParams;
I don't like this string concat way of building the query. For example the baseurl could already contain some query params. We have helper methods for this in util.js 

Is there a reason you choose not to store the full url in local storage? This would avoid this issue.

2022-08-16 07:36 UTC, BramDevlaminck commented on app/views/layouts/_searchbar.html.erb
> +          url += "?" + prevDefinedSearchParams;
I did not store the whole url because this includes the id of the specific series:
```
http://dodona.localhost:3000/nl/series/47/available_activities/?programming_language=python&page=1&filter=curl&format=js
```
If I set the whole url the results of series with id 47 would be given and my assumption is that this would give different results.

2022-08-16 07:39 UTC, jorg-vr commented on app/views/layouts/_searchbar.html.erb
> +          url += "?" + prevDefinedSearchParams;
good call, I did not think of that. It is indeed better to only store the actual filters in this case

2022-08-16 07:41 UTC, BramDevlaminck commented on app/views/layouts/_searchbar.html.erb
> +          url += "?" + prevDefinedSearchParams;
I'll try to find a way to check if there are already search params in the base url. I might find something [here](https://developer.mozilla.org/en-US/docs/Web/API/URL) that helps with this.

2022-08-17 08:08 UTC, chvp requested changes

2022-08-17 08:08 UTC, chvp commented on app/assets/javascripts/search.ts
> +                this.setBaseUrl(localStorageKey);
This will pass the `localStorageKey` to the `baseUrl` param?

2022-08-17 08:08 UTC, chvp commented on app/assets/javascripts/search.ts
> +            }).then(() => {
Why do this in a third `then`? It doesn't relay on any `Promise`d results from the previous step?

2022-08-17 08:08 UTC, chvp commented on app/views/layouts/_searchbar.html.erb
> +        dodona.searchQuery.setBaseUrl(urlObj.pathname + urlObj.search, localStorageKey);
This feels a bit hacky. It's also a lot of actual code to put in the HTML templates. I would expect most of this to happen in `search.ts` as well.

2022-08-17 08:08 UTC, chvp commented on app/views/layouts/_searchbar.html.erb
> +        dodona.searchQuery.setBaseUrl(urlObj.pathname + urlObj.search, localStorageKey);
Also, I would not expect the actual base URL to change? Just the pre-filled parameters?

2022-08-17 10:28 UTC, jorg-vr commented on app/views/layouts/_searchbar.html.erb
> +        dodona.searchQuery.setBaseUrl(urlObj.pathname + urlObj.search, localStorageKey);
If you put this code in search.ts, there is no need to reuse setBaseUrl. This way you can avoid having to build a new URL and just reuse the updateParam methods directly

2022-08-17 16:26 UTC, BramDevlaminck commented on app/assets/javascripts/search.ts
> +            }).then(() => {
My idea was that I only wanted to update the value in the `localStorage` if the fetch of the updated URL succeeded.

2022-08-18 12:27 UTC, jorg-vr requested changes
Code looks good :) just one minor remark

2022-08-18 12:27 UTC, jorg-vr commented on app/assets/javascripts/search.ts
> +    setBaseUrl(baseUrl?: string, localStorageKey?: string): void {
Is there a reason this is still in the setBaseUrl method? or is this just legacy?
I would expect a seperate setLocalStorage key method

2022-08-18 12:28 UTC, chvp commented on app/assets/javascripts/search.ts
> +    setBaseUrl(baseUrl?: string, localStorageKey?: string): void {
Setting the `baseUrl` and the `localStorageKey` seems pretty independent. Would it make sense to add a `setLocalStorageKey` method?

2022-08-18 12:28 UTC, chvp commented on app/assets/javascripts/search.ts
> +        this.setBaseUrl(baseUrl, localStorageKey);
Where is this constructor used? If I look at the other changes in this PR, it doesn't seem like this last param will ever be used?

2022-08-18 12:28 UTC, chvp commented on app/assets/javascripts/search.ts
> +                this.setBaseUrl(null, localStorageKey);
If `setLocalStorageKey` becomes a separate method then this does not need to be updated.

2022-08-18 12:40 UTC, BramDevlaminck commented on app/assets/javascripts/search.ts
> +    setBaseUrl(baseUrl?: string, localStorageKey?: string): void {
it would make sense to have a separate `setLocalStorageKey` method, but this would mean that when another page uses the `searchQuery`-object **after** that a page used a `localStorageKey` and the new page does not use the local storage to store previous params. The localStorageKey will still be set and the local storage from the previous page will keep being changed with the params from the new page.

To prevent this I just combined these 2 to make sure that all the other places automatically reset the localStorageKey (because the `localStorageKey-argument` is empty there).

A solution to not break everything but still have a separate `setLocalStorageKey`-function would be to
- always reset the `localStorageKey` to be `null` when `setBaseUrl` is called
- manually call `setLocalStorageKey` AFTER `setBaseURL` when the local storage is used

What do you think?

2022-08-18 12:41 UTC, BramDevlaminck commented on app/assets/javascripts/search.ts
> +    setBaseUrl(baseUrl?: string, localStorageKey?: string): void {
Jorg had the same question, I answered it [here](https://github.com/dodona-edu/dodona/pull/3881#discussion_r949083662) and proposed a possible solution

2022-08-18 12:42 UTC, BramDevlaminck commented on app/assets/javascripts/search.ts
> +        this.setBaseUrl(baseUrl, localStorageKey);
It is indeed never used right now, I added it to give the option to do this immediately. I'll remove it since this can easily be set in another function

2022-08-18 13:04 UTC, jorg-vr commented on app/assets/javascripts/search.ts
> +    setBaseUrl(baseUrl?: string, localStorageKey?: string): void {
This should not be the case. If search query is used on another page, then all code in searchbar.html.erb should be rerun setting al relevant parameters. For example `refreshEllement`  is also different across all pages, so this would break if only `setbaseurl` was updated.

2022-08-18 13:08 UTC, BramDevlaminck commented on app/assets/javascripts/search.ts
> +    setBaseUrl(baseUrl?: string, localStorageKey?: string): void {
ah okay. In that case it will indeed be a lot cleaner to separate these functions

2022-08-18 14:14 UTC, jorg-vr requested changes

2022-08-18 14:14 UTC, jorg-vr commented on app/assets/javascripts/search.ts
> +                const currentSearchParams = new URL(this.baseUrl).searchParams;
This part won't work as this.baseurl is set as url.href (Which does not contain any params)

All params are stored in `this.arrayQueryParams` and `this.queryParams`. So this is where you would look if one has already been set in the current state.

2022-08-18 14:14 UTC, jorg-vr commented on app/assets/javascripts/search.ts
> +        this.useLocalStorage();
I would expect this code to be in ` setLocalStorageKey` instead of `setBaseUrl`

2022-08-18 21:35 UTC, chvp approved these changes

2022-08-19 07:09 UTC, jorg-vr requested changes

2022-08-19 07:09 UTC, jorg-vr commented on app/assets/javascripts/search.ts
> +                    if (this.queryParams.params.get(key) !== undefined || this.arrayQueryParams.params.get(key) !== undefined) {
array query params in the url will contain `[]` at the end, while they are stored without `[]` in the `arrayQueryParams` object.

see `intialiseParams` for example code

`this.arrayQueryParams.params.get(key) !== undefined` will thus not have the desired effect

2022-08-19 08:46 UTC, jorg-vr approved these changes

2022-08-25 12:41 UTC, bmesuere approved these changes
👍  nice work

2022-08-25 12:41 UTC, merged