Add references to manual
dodona-edu/dodona pull request #3896
Opened 2022-08-16 15:10 UTC by BramDevlaminck

This pull request adds references to the manual

Closes #2229  .

2022-08-25 13:09 UTC, bmesuere requested changes
I added a comment under each screenshot.

> ###### courses/index
> <img alt="image" width="1499" src="https://user-images.githubusercontent.com/68779933/185610134-a78dbf15-748a-40e8-8339-332a8f19063b.png">
I would remove this one.

> ###### courses/new
> <img alt="image" width="1501" src="https://user-images.githubusercontent.com/68779933/185610578-8b2d0f35-8120-4e1a-8e17-edbd9315d0cc.png">
Here, the message is appropriate, but I would restyle it and use the "header info text" style we already use on several other page (e.g. see series edit page), and put it below the title.

> ###### evaluations/new
> <img alt="image" width="1501" src="https://user-images.githubusercontent.com/68779933/185610813-3ae2554a-b21d-4683-a899-e45856538b42.png">
Isn't a link already present in the bigger callout that is also on the screenshot?
 
> ###### evaluations/show
> <img alt="image" width="713" src="https://user-images.githubusercontent.com/68779933/185612991-edfac891-a217-43f5-875f-c18aeccdecec.png">
Ok

> ###### repositories/_form
> this is both visible in the create and edit repository screen <img alt="image" width="1500" src="https://user-images.githubusercontent.com/68779933/185611413-1f2baa0d-da35-477e-bb83-ace554cc99ef.png">
Ok

> ###### repositories/show
> <img alt="image" width="1486" src="https://user-images.githubusercontent.com/68779933/185611675-0deaa249-a038-4d39-a29b-b5c02decd5b6.png">
Ok, but setup title is a bit strange

> ###### series/_form
> This is both visible in the create and edit series screen <img alt="image" width="1492" src="https://user-images.githubusercontent.com/68779933/185612002-6c5291a8-89cd-46b8-af9c-6e9bb191c164.png">
I think a callout is too prominent here since this is a common and straightforward action.

> ###### submissions/_description
> <img alt="image" width="1500" src="https://user-images.githubusercontent.com/68779933/185612533-212bf932-7885-478d-bed1-939e4cd57e37.png">
The "distance" between the callout and what the message is about is too large. I would add a small text message at the bottom of the ask question form (I think we already have a markdown message there).
 
> ###### users/show
> <img alt="image" width="1090" src="https://user-images.githubusercontent.com/68779933/185619605-ec60f04c-7919-4d98-9aef-e4d5c4823f3c.png">
Remove the last sentence, but add "vs code" to the first sentence and link jetbrains and vs code to the pages that were linked to in the last sentence.

2022-08-26 07:19 UTC, BramDevlaminck commented
> Isn't a link already present in the bigger callout that is also on the screenshot?

In Dutch this was indeed the case, but in English the bigger callout did not contain the link to the documentation. I'll modify the bigger callout in English to contain the link and removed the new callout.

2022-08-26 07:27 UTC, BramDevlaminck commented
> Ok, but setup title is a bit strange

Instead, I'll change the title to the next:
English: "Getting started"
Dutch: "Aan de slag" -> I'm not convinced on this one, maybe someone else has a better idea?

2022-08-26 08:03 UTC, BramDevlaminck commented
> The "distance" between the callout and what the message is about is too large. I would add a small text message at the bottom of the ask question form (I think we already have a markdown message there).

The modified version:
<img width="1038" alt="image" src="https://user-images.githubusercontent.com/68779933/186853736-41afe012-0960-49cd-b1c3-ac9244207910.png">

2022-08-27 09:02 UTC, chvp requested changes
> > The "distance" between the callout and what the message is about is too large. I would add a small text message at the bottom of the ask question form (I think we already have a markdown message there).
> 
> The modified version: <img alt="image" width="1038" src="https://user-images.githubusercontent.com/68779933/186853736-41afe012-0960-49cd-b1c3-ac9244207910.png">

I think @bmesuere meant to add this to the actual annotation form (so after pressing the `Ask a question` button).

I would generally rewrite the help texts to talk to the user directly like I did with a few examples (it reads more comfortably to me), but maybe @bmesuere has another opinion.

2022-08-29 08:03 UTC, BramDevlaminck commented on config/locales/views/evaluations/en.yml
> +      explanation_no_grading_html: "<p>In the summary table, you can click on the <i class='mdi mdi-chevron-right mdi-18'></i> icon next to an exercise. You will then be taken to an incompleted submi
I intentionally used that tag because then you are immediately on the part of the guide where you clicked on the URL. It does not seem logical to me that when you click on the link to the documentation on "page x", the first thing you see in the documentation is "how to go to page x". You want to see "What can I do starting from page x".

2022-08-29 08:06 UTC, chvp commented on config/locales/views/evaluations/en.yml
> +      explanation_no_grading_html: "<p>In the summary table, you can click on the <i class='mdi mdi-chevron-right mdi-18'></i> icon next to an exercise. You will then be taken to an incompleted submi
Yes, that's fine, this was more a comment about the Dutch anchor on an English page.

2022-08-29 08:11 UTC, BramDevlaminck commented on config/locales/views/evaluations/en.yml
> +      explanation_no_grading_html: "<p>In the summary table, you can click on the <i class='mdi mdi-chevron-right mdi-18'></i> icon next to an exercise. You will then be taken to an incompleted submi
Ah okay. The *problem* is that these pages are Dutch-only. When using the English link, as I did here (`docs.dodona.be/en/...`). There is just a small warning at the top of the page that that page is currently only available in Dutch. The anchor stays in Dutch all the time. I don't think there is a better way to do this as long as the documentation is mostly Dutch-only

2022-08-29 08:14 UTC, BramDevlaminck commented
> > > The "distance" between the callout and what the message is about is too large. I would add a small text message at the bottom of the ask question form (I think we already have a markdown message there).
> > 
> > 
> > The modified version: <img alt="image" width="1038" src="https://user-images.githubusercontent.com/68779933/186853736-41afe012-0960-49cd-b1c3-ac9244207910.png">
> 
> I think @bmesuere meant to add this to the actual annotation form (so after pressing the `Ask a question` button).

The updated version with the annotation move to the question form:
<img width="1100" alt="image" src="https://user-images.githubusercontent.com/68779933/187155693-7dcb4b0e-9122-4a8b-8357-5e49e89b9b0f.png">

2022-08-29 16:46 UTC, chvp approved these changes

2022-08-29 16:46 UTC, chvp commented on config/locales/views/evaluations/nl.yml
> +      explanation_no_grading_html: "<p>In de samenvattende tabel kan je naast een oefening op <i class='mdi mdi-chevron-right mdi-18'></i> klikken. Je komt dan op een nog te bekijken oplossing van ee
```suggestion
      explanation_no_grading_html: "<p>In de samenvattende tabel kan je naast een oefening op <i class='mdi mdi-chevron-right mdi-18'></i> klikken. Je komt dan op een nog te bekijken oplossing van een willekeurige student terecht. Vervolgens kan je indien gewenst feedback op de code geven en de oplossing als afgewerkt markeren. Bemerk dat je ook een oplossing als afgewerkt kan markeren zonder feedback achter te laten. We hebben alvast alle oefeningen zonder ingediende oplossing als afgewerkt gemarkeerd.</p><p>Meer informatie kan je in <a href='https://docs.dodona.be/nl/guides/teachers/grading/#het-evaluatieoverzicht'>onze documentatie</a> vinden.</p><p>Ter herinnering, de studenten krijgen de gegeven feedback <b>niet</b> automatisch te zien, daarvoor dien je hieronder op 'Feedback vrijgeven' te klikken.</p>"
```

2022-08-29 16:46 UTC, chvp commented on config/locales/views/evaluations/nl.yml
> +      explanation_yes_grading_html: "<p>In de samenvattende tabel kan je naast een oefening op <i class='mdi mdi-chevron-right mdi-18'></i> klikken. Je komt dan op een nog te bekijken oplossing van e
```suggestion
      explanation_yes_grading_html: "<p>In de samenvattende tabel kan je naast een oefening op <i class='mdi mdi-chevron-right mdi-18'></i> klikken. Je komt dan op een nog te bekijken oplossing van een willekeurige student terecht. Vervolgens kan je indien gewenst feedback op de code geven en scores toekennen via de scoreonderdelen die je geconfigureerd hebt. Je kan de scores ook invullen zonder feedback achter te laten. Oefeningen zonder ingediende oplossing kan je geen scores geven, deze zullen automatisch een 0 krijgen in het puntenoverzicht.</p><p>Meer informatie kan je in <a href='https://docs.dodona.be/nl/guides/teachers/grading/#het-evaluatieoverzicht'>onze documentatie</a> vinden.</p><p>Ter herinnering, de studenten krijgen de gegeven feedback en scores <b>niet</b> automatisch te zien, daarvoor dien je hieronder op 'Feedback vrijgeven' te klikken.</p>"
```

2022-08-30 07:42 UTC, jorg-vr approved these changes

2022-08-30 08:40 UTC, niknetniko requested changes

2022-08-30 08:40 UTC, niknetniko commented on app/views/repositories/show.html.erb
> +            <% if @repository.exercises.count === 0 && @repository.content_pages.count === 0 %>
```suggestion
            <% if @repository.exercises.empty? && @repository.content_pages.empty? %>
```

In general, you rarely need the `===` operator in Ruby.

2022-08-30 08:40 UTC, niknetniko commented on config/locales/views/repositories/en.yml
> +      help_html: "You can find guide with more information on managing repositories in <a href='https://docs.dodona.be/nl/guides/teachers/new-exercise-repo/#_1-een-git-repository-aanmaken'>our docume
```suggestion
      help_html: "You can find a guide with more information on managing repositories in <a href='https://docs.dodona.be/nl/guides/teachers/new-exercise-repo/#_1-een-git-repository-aanmaken'>our documentation</a>."
```

2022-08-30 08:40 UTC, niknetniko commented on config/locales/views/repositories/en.yml
> +      empty_repo_help_html: "We noticed your repository is empty, learn in <a href='https://docs.dodona.be/nl/references/repository-directory-structure/#repository-bestandenstructuur'>our documentati
```suggestion
      empty_repo_help_html: "We noticed your repository is empty, learn how you can add exercises to your repository in <a href='https://docs.dodona.be/nl/references/repository-directory-structure/#repository-bestandenstructuur'>our documentation</a>."
```

2022-08-30 08:40 UTC, niknetniko commented on config/locales/views/repositories/nl.yml
> +      empty_repo_help_html: "We zien dat je repository leeg is, leer in <a href='https://docs.dodona.be/nl/references/repository-directory-structure/#repository-bestandenstructuur'>onze documentatie<
```suggestion
      empty_repo_help_html: "We zien dat je repository leeg is, leer hoe je oefeningen aan je repository kunt toevoegen in <a href='https://docs.dodona.be/nl/references/repository-directory-structure/#repository-bestandenstructuur'>onze documentatie</a>."
```

2022-08-30 08:51 UTC, niknetniko approved these changes

2022-08-30 17:50 UTC, bmesuere approved these changes
I would leave out the newline where I left the comment. Nice work otherwise 👍

2022-08-30 17:50 UTC, bmesuere commented on app/assets/javascripts/code_listing/code_listing.ts
> +             <br><span class='help-block'>${I18n.t("js.user_annotation.help_student")}</span>
```suggestion
             <span class='help-block'>${I18n.t("js.user_annotation.help_student")}</span>
```

2022-08-31 07:10 UTC, merged