Clear all grades button
dodona-edu/dodona pull request #3918
Opened 2022-08-22 12:30 UTC by BramDevlaminck

This pull request adds a button to clear all score items in the feedback panel

Closes #2716  .

2022-08-24 13:16 UTC, chvp requested changes

2022-08-24 13:16 UTC, chvp commented on app/assets/javascripts/feedback/actions.ts
> +            this.deleteAllButton.disabled = this.scoreSumElement.value === "-"; // '-' is the placeholder if no score items are filled in yet
Using string matching for this doesn't feel very clean. Especially using a string from the HTML.

2022-08-24 13:16 UTC, chvp commented on app/assets/javascripts/feedback/actions.ts
> +            body: JSON.stringify({ feedback: data, clear_scores: clearScores }),
I think it would be cleaner to make the data an object matching the score item to a `null` value. Not sure if this would work on the rails side, but if it works that would be preferable IMO.

2022-08-24 13:16 UTC, chvp commented on app/controllers/feedbacks_controller.rb
> +        format.json { render :show, status: :no_content, location: @feedback }
Rendering `show` with a status `no content` feels weird.

2022-08-25 07:21 UTC, chvp requested changes

2022-08-25 07:21 UTC, chvp commented on app/assets/javascripts/feedback/actions.ts
> +                await this.update(null);
This is not what I meant with making things `null`. Just like the all correct and the all wrong button, I would make the actual (individual) score items sent to the backend `null`.

2022-08-25 13:40 UTC, bmesuere commented on app/assets/javascripts/feedback/actions.ts
> +            this.completedIcon.hidden = !completed;
Is there a reason why the partial icon was removed?

2022-08-25 13:40 UTC, bmesuere commented on app/assets/javascripts/feedback/actions.ts
> +                await this.update({
I'm probably missing something obvious, but is there a reason to add await here (and thus make it async)?

2022-08-25 13:40 UTC, bmesuere commented on app/assets/javascripts/feedback/score.ts
> +        const newScore = setNullScore? null: this.input.value;
```suggestion
        const newScore = setNullScore ? null : this.input.value;
```

2022-08-25 13:40 UTC, bmesuere commented on app/controllers/feedbacks_controller.rb
>    def update
@chvp or @jorg-vr might not agree, but it seems there is almost no common code in the 2 cases of the if. Doesn't it then make more sense to add a separate action in the controller?

2022-08-25 13:47 UTC, BramDevlaminck commented on app/assets/javascripts/feedback/actions.ts
> +            this.completedIcon.hidden = !completed;
Not specifically. I just did something similar to the checkmarks that were there in the sub-scores. Do you prefer the partial icon to be there when the feedback is not yet complete?

I'm just not sure if it adds unnecessary complexity or not. The icon itself does not add a lot of value imo.

2022-08-25 13:51 UTC, BramDevlaminck commented on app/assets/javascripts/feedback/actions.ts
> +                await this.update({
The `await` is there since `this.update` is an async function (returns the `fetch`)

2022-08-25 14:41 UTC, bmesuere commented on app/assets/javascripts/feedback/actions.ts
> +                await this.update({
yes, I know, but adding await won't make a difference, right? There is no code below in the function and the function is inline so nothing is waiting on it.

2022-08-25 14:58 UTC, BramDevlaminck commented on app/assets/javascripts/feedback/actions.ts
> +                await this.update({
I think so yeah. But not using the `await` keyword gives a warning. The "solution" to prevent this warning is to just place `.then()`. But as you said, it shouldn't make a difference. (the same should be true for the other buttons above the delete all button).

2022-08-27 07:58 UTC, chvp requested changes

2022-08-27 07:58 UTC, chvp commented on app/assets/javascripts/feedback/actions.ts
> +            this.completedIcon.hidden = !completed;
There is a reason though? The delete button was put in its place?

2022-08-27 07:58 UTC, chvp commented on app/controllers/feedbacks_controller.rb
> +    if params[:feedback][:scores_attributes]&.all? { |item| item[:score].nil? }
I would hope that this is not required due to the `accepts_nested_attributes_for` in `app/models/feedback.rb`. If it is required, I agree with @bmesuere to move this to a separate action in the controller. (Or maybe check in that case if `accepts_nested_attributes_for` has some other mechanism for deletion?)

2022-08-27 08:02 UTC, bmesuere commented on app/assets/javascripts/feedback/actions.ts
> +            this.completedIcon.hidden = !completed;
Yes, but the checkmark was simply moved to a new position so it seems logical to also move the partial icon to the new place?

2022-08-29 12:28 UTC, BramDevlaminck commented on app/controllers/feedbacks_controller.rb
> +    if params[:feedback][:scores_attributes]&.all? { |item| item[:score].nil? }
What exactly is required? If you mean that the scores have to be nil? It's not really required in general  (but it is for this implementation). It's also not forced by `accepts_nested_attributes_for`. It's just how I identify if the request sent by the client is to delete the scores or if it is to modify the scores.

I debated using the `destroy` function as a separate action, but that did not really seem appropriate since the feedback itself is not getting deleted. Only the scores in the feedback.

2022-08-30 08:21 UTC, jorg-vr requested changes

2022-08-30 08:21 UTC, jorg-vr commented on app/assets/javascripts/feedback/score.ts
> +    public getDataForNested(setNullScore=false): Record<string, unknown> {
I do not like this `setNullScore` parameter to the getter method. Just do an extra `map` call after calling this method when needed instead editing this method

2022-08-30 08:21 UTC, jorg-vr commented on app/controllers/feedbacks_controller.rb
>    def update
I agree that this should probably be a separate method. 
Restfull I would expect the endpoint to be a DELETE request on feedback/{ID}/scores
(And not a DELETE on feedback/{id} as you discussen in your response to @chvp )

As the functionality is `@feedback.scores.each(&:destroy)`

2022-08-30 08:21 UTC, jorg-vr commented on app/controllers/feedbacks_controller.rb
> +    if params[:feedback][:scores_attributes]&.all? { |item| item[:score].nil? }
If you do keep it as a single method, I would not expect this check. Instead I would expect the method to be able to handle any combination of `nil` and filled out scores (Destroying those which are nil). This way more code would be shared.

But as pointed out above a separate method is probably easier and thus preferable.

2022-08-30 13:51 UTC, BramDevlaminck commented on app/assets/javascripts/feedback/actions.ts
> +            this.completedIcon.hidden = !completed;
I've updated the description with a new screenshot that contains the partial icon when not all the score items are filled in

2022-08-30 13:57 UTC, jorg-vr commented
could you fix the failing tests?

2022-08-30 14:11 UTC, jorg-vr approved these changes

2022-08-30 18:07 UTC, bmesuere requested changes
Looks good 👍 
A last minor request, could you add tooltips (by setting the title attribute) to the partial and complete icon on the total row, and to the saved icon on the other rows?

2022-08-31 08:00 UTC, chvp approved these changes

2022-08-31 08:52 UTC, bmesuere approved these changes

2022-08-31 08:52 UTC, merged