Course.js: remove jquery and convert to typescript
dodona-edu/dodona pull request #3921
Opened 2022-08-23 14:55 UTC by BramDevlaminck

This pull request removes jquery code out of `course.js`

progress on  #3590, closes #3923  .

2022-08-24 09:54 UTC, BramDevlaminck commented on app/assets/javascripts/course.js
> +                .innerHTML = this.getAttribute("data-answer");
Solved by using `.textContent` instead of `.innerHTML`

2022-08-24 09:54 UTC, BramDevlaminck commented on app/assets/javascripts/course.js
> +                .innerHTML = this.getAttribute("data-answer");
Solved by using `.textContent` instead of `.innerHTML`

2022-08-24 13:52 UTC, niknetniko requested changes

2022-08-24 13:52 UTC, niknetniko commented on app/assets/javascripts/course.ts
> +        if (userTabs !== null) {
Maybe this would be clearer by reversing the `if` and returning early, but I'm unsure what others think about this.

Something like this:

```typescript
if (userTabs === null) {
    return;
}
```

2022-08-24 13:52 UTC, niknetniko commented on app/assets/javascripts/course.ts
> +            const baseUrl = userTabs.getAttribute("data-baseurl");
```suggestion
            const baseUrl = userTabs.dataset.baseurl;
```
A similar change can be done for other data attributes.

2022-08-24 13:52 UTC, niknetniko commented on app/assets/javascripts/course.ts
> +                const status = tab.getAttribute("data-status");
```suggestion
                const status = tab.dataset.status;
```

2022-08-24 13:52 UTC, niknetniko commented on app/assets/javascripts/course.ts
> +                    const dataType = item.getAttribute("data-type");
```suggestion
                    const dataType = item.dataset.type;
```

2022-08-24 13:52 UTC, niknetniko commented on app/assets/javascripts/course.ts
> +                for (const item of Array.from(kebabItems)) {
```suggestion
                for (const item of kebabItems) {
```
You should be able to loop over a `NodeList` with a `for...of` directly.

2022-08-24 13:52 UTC, niknetniko commented on app/assets/javascripts/course.ts
> +                        selectTab(this);
What is the `this` referring to here? Since arrow functions don't have their own `this`. If I am correct, this would refer to the context of the `initUserTabs` function, but I'm not sure this is what we want.

2022-08-24 13:52 UTC, niknetniko commented on app/assets/javascripts/course.ts
> +            fetch(`/courses/${modal.getAttribute("data-course_id")}/members/upload_labels_csv`, {
```suggestion
            fetch(`/courses/${modal.dataset.course_id}/members/upload_labels_csv`, {
```

2022-08-24 13:52 UTC, niknetniko commented on app/assets/javascripts/course.ts
> +    getTop(): number {
Perhaps we can use the getter syntax here?

2022-08-24 13:52 UTC, niknetniko commented on app/assets/javascripts/course.ts
> +        this.url = this.card.getAttribute("data-series-url");
```suggestion
        this.url = this.card.dataset.seriesUrl;
```

2022-08-24 13:52 UTC, niknetniko commented on app/assets/javascripts/course.ts
> +    reselect(cardSelector): void {
This param is no longer the selector, but the element I think (see the call on line 150)

2022-08-24 13:52 UTC, niknetniko commented on app/assets/javascripts/course.ts
> +        typeCollapseElement.addEventListener("show.bs.collapse", function () {
This can be an arrow function I think.

2022-08-24 13:52 UTC, niknetniko commented on app/assets/javascripts/course.ts
> +        chooseCollapseElement.addEventListener("show.bs.collapse", function () {
This can be an arrow function I think.

2022-08-24 13:52 UTC, niknetniko commented on app/assets/javascripts/course.ts
> +        formCollapseElement.addEventListener("show.bs.collapse", function () {
This can be an arrow function I think.

2022-08-24 13:52 UTC, niknetniko commented on app/assets/javascripts/course.ts
> +                    .textContent = this.getAttribute("data-answer");
```suggestion
                    .textContent = this.dataset.answer";
```

2022-08-24 13:52 UTC, niknetniko commented on app/assets/javascripts/course.ts
> +            el.addEventListener("click", function (e) {
This can be an arrow function I think.

2022-08-24 13:52 UTC, niknetniko commented on app/assets/javascripts/course_membership.js
> -            $.each(result, (i, val) => {
It doesn't feel like these changes belong on this PR, as there are still jQuery usages in this file (and also since the titles says it's about courses.js)

2022-08-25 06:46 UTC, BramDevlaminck commented on app/assets/javascripts/course.ts
> +                for (const item of Array.from(kebabItems)) {
I thought so too, but the typescript linter thought otherwise.

The solution was to add `DOM.iterable` to the libs in tsconfig. (as suggested in the comment on [this](https://stackoverflow.com/questions/65364900/ts-lint-error-with-document-queryselectorall) stackoverflow post)

2022-08-25 06:58 UTC, BramDevlaminck commented on app/assets/javascripts/course.ts
> +                        selectTab(this);
ah this is indeed a mistake, this `this` had to refer to the selected tab (in this case `el`)

2022-08-26 08:54 UTC, niknetniko commented on app/assets/javascripts/course.ts
> +                for (const item of Array.from(kebabItems)) {
The problem is that the `target` in our `tsconfig.js` is `es5`. `NodeList` was added in `es6`, so Typescript isn't happy. Since we use Babel I think we could set the target to `es6`, but I'm not completely sure on this.

2022-08-26 09:26 UTC, bmesuere commented on app/assets/javascripts/course.ts
> +                for (const item of Array.from(kebabItems)) {
I think we could. Even without babel, es6 should be supported by the browsers we cover.

2022-08-26 11:21 UTC, BramDevlaminck commented on app/assets/javascripts/course.ts
> +                for (const item of Array.from(kebabItems)) {
> The problem is that the `target` in our `tsconfig.js` is `es5`. `NodeList` was added in `es6`, so Typescript isn't happy. Since we use Babel I think we could set the target to `es6`, but I'm not completely sure on this.

Why is it a problem that our target is `es5`? I don't immediately find anything online about it and even when we use `es6`as target the linter warning stays without adding the `DOM.iterable` lib

2022-08-26 11:32 UTC, niknetniko commented on app/assets/javascripts/course.ts
> +                for (const item of Array.from(kebabItems)) {
I tried https://stackoverflow.com/questions/51723962/typescript-nodelistofelement-is-not-an-array-type-or-a-string-type locally and for me it seemed to work

2022-08-26 11:38 UTC, BramDevlaminck commented on app/assets/javascripts/course.ts
> +                for (const item of Array.from(kebabItems)) {
Hmm, it does not work for me (tried both in VSCode and Webstorm to double-check).

2022-08-27 08:44 UTC, chvp commented on app/assets/javascripts/course.ts
> +                for (const item of Array.from(kebabItems)) {
It also doesn't work for me when setting the target to `es6` and removing `DOM.iterable` from the `lib` list. But I don't see any issue with adding `DOM.iterable` to `lib`?

2022-08-27 08:45 UTC, chvp approved these changes

2022-08-27 16:09 UTC, niknetniko commented on app/assets/javascripts/course.ts
> +                for (const item of Array.from(kebabItems)) {
You are right that setting the target itself doesn't work (oops, I modified more locally apparently).

I think the best solution is probably removing `lib` and setting `"target": "es2021"`. Setting the [`target`](https://www.typescriptlang.org/tsconfig#target) will also set a default for [`lib`](https://www.typescriptlang.org/tsconfig#lib), unless you specific it yourself, which is what we did. Since we already include `es2021` libs, we might as well set the target to `es2021` and use the default value.

2022-08-29 11:47 UTC, niknetniko approved these changes

2022-08-30 18:10 UTC, bmesuere approved these changes
A minor nitpick: I think template strings (between backticks) would look cleaner for the selectors where you now have to escape the double quotes, e.g., in `type=\"radio\"`.

2022-08-31 08:37 UTC, BramDevlaminck commented
> A minor nitpick: I think template strings (between backticks) would look cleaner for the selectors where you now have to escape the double quotes, e.g., in `type=\"radio\"`.

I've applied this and also changed the `.eslintrc` to allow this. With the previous `.eslintrc` eslint would not allow this since it forced you to use double quotes on every string

2022-08-31 08:52 UTC, merged