Improve buttons in choose submission screen for evaluation
dodona-edu/dodona pull request #3926
Opened 2022-08-25 09:59 UTC by BramDevlaminck

This pull request changes the buttons that are used to select the submission and adds an indication to the currently selected submission.

<img width="1322" alt="image" src="https://user-images.githubusercontent.com/68779933/186635463-e0b20226-1190-4adb-8656-d752d29b0420.png">
<img width="1315" alt="image" src="https://user-images.githubusercontent.com/68779933/186635518-f0ce3be3-d853-4c70-980f-d2a1e63be014.png">

Closes #3795  .

2022-08-27 08:02 UTC, chvp reviewed
Maybe it's just my imagination but the "Selected" in the English screenshot looks very weirdly aligned. LGTM otherwise.

2022-08-29 07:47 UTC, niknetniko commented on config/locales/views/submissions/nl.yml
> +      select: Selecteer
```suggestion
      select: Selecteren
```

2022-08-29 09:45 UTC, niknetniko approved these changes

2022-08-29 11:23 UTC, BramDevlaminck commented
> Maybe it's just my imagination but the "Selected" in the English screenshot looks very weirdly aligned. LGTM otherwise.

It indeed seemed a bit off-centre. To make it fit, I've shifted the button a bit. Is this new version better?
<img width="1319" alt="image" src="https://user-images.githubusercontent.com/68779933/187190319-f5528fc0-f2a4-46c1-b080-f7d8e251324d.png">
<img width="1313" alt="image" src="https://user-images.githubusercontent.com/68779933/187190351-66c8dccb-23ef-4c9b-808a-4c06e3d8ba46.png">

2022-08-30 08:29 UTC, jorg-vr requested changes

2022-08-30 08:29 UTC, jorg-vr commented on app/views/feedbacks/_submissions_table.html.erb
> +              <button class="btn btn-text outline-btn-alignment" disabled>
You should not be using a btn-text to simulate a disabled btn-outline

Disabled btn-outline has its own spec:
![image](https://user-images.githubusercontent.com/21177904/187388522-dc60d519-487c-4627-971e-32fdb742b5a2.png)

See: https://m3.material.io/components/buttons/specs

If this style is not yet implemented for outlined buttons it should be, instead of misusing btn-text

2022-08-30 09:58 UTC, BramDevlaminck commented on app/views/feedbacks/_submissions_table.html.erb
> +              <button class="btn btn-text outline-btn-alignment" disabled>
This would look something like this:
<img width="1324" alt="image" src="https://user-images.githubusercontent.com/68779933/187407681-7a9ec4e9-b524-4654-8990-26b3c6e40424.png">

It just looks weird to me with the 1 button that is bigger. That's why I just used btn-text (since that has no outline).
I just used the text since it seemed a good indicator to show what was selected and still had the same style as the buttons.

What do you think of this?

2022-08-30 10:51 UTC, jorg-vr commented on app/views/feedbacks/_submissions_table.html.erb
> +              <button class="btn btn-text outline-btn-alignment" disabled>
Can't this be solved by some kind of centered alignment of the buttons  (Instead of pulled to the right as they are right now)

2022-08-30 11:39 UTC, BramDevlaminck commented on app/views/feedbacks/_submissions_table.html.erb
> +              <button class="btn btn-text outline-btn-alignment" disabled>
Centring the elements won't work, since the buttons start to "float" somewhere in the row.

<img width="1315" alt="image" src="https://user-images.githubusercontent.com/68779933/187425509-cf212012-74dc-4751-af61-fe49b0ec6cd6.png">

There also does not seem to be an obvious way to right-align the buttons and center them at the same time.

I could try some hacky way by adding an extra class to the active buttons that adds more padding to the right, but that's not really a solution to this problem. It's only hiding the real problem a bit.

2022-08-30 11:55 UTC, jorg-vr commented on app/views/feedbacks/_submissions_table.html.erb
> +              <button class="btn btn-text outline-btn-alignment" disabled>
just give the actions column a predefined width. eg:
```css
.table-resource .actions {
  text-align: center;
  width: 150px;
}
```

This is much less hacky than custom paddings

![image](https://user-images.githubusercontent.com/21177904/187430025-1de94a83-8073-4609-bf17-5fc3c2d029cb.png)

2022-08-30 12:13 UTC, BramDevlaminck commented on app/views/feedbacks/_submissions_table.html.erb
> +              <button class="btn btn-text outline-btn-alignment" disabled>
I've updated the description of the pr to contain the new screenshots

2022-08-30 12:20 UTC, jorg-vr approved these changes

2022-08-30 12:20 UTC, jorg-vr commented on app/assets/stylesheets/components/table.css.scss
> +  width: 1px; // by default the size of the element in the col is used as width if width is smaller than that element. This width is just here to force everything to the right
As you made this edit globally, did you check all other tables for issues created by this change?

If you encounter issues, just make it more specific with the `.submissions-table` selector

2022-08-30 12:23 UTC, BramDevlaminck commented on app/assets/stylesheets/components/table.css.scss
> +  width: 1px; // by default the size of the element in the col is used as width if width is smaller than that element. This width is just here to force everything to the right
i've checked this on multiple places and it all seemed to work. But I'll make it more specific just to be sure since it's possible there is a table somewhere where this will break. I should've done that in the first place

2022-08-31 07:11 UTC, merged