Remove Jquery code from exercise.js
dodona-edu/dodona pull request #3930
Opened 2022-08-26 15:09 UTC by BramDevlaminck

This pull request removes jquery code from exercise.js

progress on #3590  .

2022-09-02 12:36 UTC, niknetniko requested changes

2022-09-02 12:36 UTC, niknetniko commented on app/assets/javascripts/exercise.ts
> +    document.querySelectorAll<HTMLElement>(".activity-description img, a.dodona-lightbox").forEach(el => {
```suggestion
    document.querySelectorAll<HTMLElement>(".activity-description img, a.dodona-lightbox").forEach((el, index) => {
```

The callback to the [`forEach`](https://developer.mozilla.org/en-US/docs/Web/API/NodeList/forEach) has an optional second argument, which is the index of the current element.

2022-09-02 12:36 UTC, niknetniko commented on app/assets/javascripts/exercise.ts
> +    function feedbackTableLoaded(userId: number, exerciseId: number, courseId: number): void {
`courseId` can be undefined

2022-09-02 12:36 UTC, niknetniko commented on app/assets/javascripts/types/index.d.ts
> +declare var ace;
I think that including the `@types/ace` package should take care of this (or at least, that's what it does in my editor, but unsure if they all do that; something to try).

2022-09-02 13:06 UTC, BramDevlaminck commented on app/assets/javascripts/exercise.ts
> +function onFrameMessage(event): void {
This is an event from the iFrameResizer library and there is no obvious way to define a good type for it. I could try to define a type that contains what I can see in the message send here but I don't know if this really adds a lot of extra information

2022-09-02 13:12 UTC, BramDevlaminck commented on app/assets/javascripts/exercise.ts
> +function onFrameMessage(event): void {
A solution is to use the `@types/iframe-resizer` library which has the appropriate types, so this problem is solved

2022-09-02 13:21 UTC, BramDevlaminck commented on app/assets/javascripts/exercise.ts
> +function onFrameMessage(event): void {
I've double-checked by logging the event in the console, and it's an `IFrameMessageData`-event from the library, but the message is custom (indeed from line 45).

The interface of the type from `@types/iframe-resizer`:
```ts
interface IFrameMessageData {
    iframe: IFrameComponent;
    message: any;
  }
```
You can see in the defined type that message can be whatever you want. In our case that is what is used on line 45.

2022-09-02 13:27 UTC, BramDevlaminck commented on app/assets/javascripts/exercise.ts
> +        return fetch("/submissions.json", {
ah this is exactly what I was looking for (I was already wondering if there was a function defined somewhere that did this), sweet!

2022-09-06 09:07 UTC, niknetniko approved these changes

2022-09-06 09:54 UTC, jorg-vr approved these changes

2022-09-08 15:21 UTC, bmesuere approved these changes

2022-09-09 12:35 UTC, chvp approved these changes

2022-09-09 12:35 UTC, merged