Fix empty series in course crash
dodona-edu/dodona pull request #3961
Opened 2022-09-01 13:07 UTC by BramDevlaminck

This pull request solves the crash when a course has an empty series

2022-09-01 13:40 UTC, niknetniko requested changes

2022-09-01 13:40 UTC, niknetniko commented on app/assets/javascripts/course.ts
> -        this.skeleton = this.table_wrapper.querySelector(SKELETON_TABLE_SELECTOR);
While this is a correct fix, the types of the instance variables should also reflect that `table_wrapper` and `skeleton` can be `null`.

<hr>

However, an even better improvement is probably to remove `card`,  `table_wrapper` and `skeleton` from the instance variables and just use them locally in the function, like so:

```javascript
reselect(card: HTMLElement): void {
    this.url = card.dataset.seriesUrl;
    const tableWrapper = card.querySelector(TABLE_WRAPPER_SELECTOR);
    const skeleton = tableWrapper?.querySelector(SKELETON_TABLE_SELECTOR);
    this.loaded = skeleton === null;
    this.loading = false;
    this._top = card.getBoundingClientRect().top + window.scrollY;
    this._bottom = this.top + card.getBoundingClientRect().height;
}
```
(Not necessarily needed for this PR, if we want to keep this one smaller)

2022-09-01 13:49 UTC, BramDevlaminck commented on app/assets/javascripts/course.ts
> -        this.skeleton = this.table_wrapper.querySelector(SKELETON_TABLE_SELECTOR);
I'll change them to local values, since this indeed is better and the rewrite is minimal

2022-09-01 15:03 UTC, chvp requested changes
As mentioned during the coffee break, I think that while this fix works, it isn't *really* correct. Because with this fix, the series will be marked as not loaded, even though the content of the series is all there.

2022-09-02 06:32 UTC, chvp approved these changes

2022-09-02 07:52 UTC, niknetniko approved these changes

2022-09-05 07:18 UTC, jorg-vr approved these changes

2022-09-05 07:24 UTC, merged