favorite_course_buttons.js: remove jquery and use typescript
dodona-edu/dodona pull request #3963
Opened 2022-09-02 08:18 UTC by BramDevlaminck

This pull request removes jquery code from `favorite_course_button.js` and migrates js to ts.

progress on  #3590 .

2022-09-02 12:44 UTC, niknetniko requested changes

2022-09-02 12:44 UTC, niknetniko commented on app/assets/javascripts/favorite_course_buttons.ts
> +        fetch(`/courses/${courseId}/favorite.js`, {
Here it is also worth using the `fetch` from `utils.js`.

2022-09-02 12:44 UTC, niknetniko commented on app/assets/javascripts/favorite_course_buttons.ts
> +            if (response.ok) {
We might want to create a wrapper that automatically fails the promise if the return status is not `ok`, since we need this in a bunch of places here and in other PR's (this is probably not something for this PR, but just a note for another time)

2022-09-02 13:33 UTC, BramDevlaminck commented on app/assets/javascripts/favorite_course_buttons.ts
> +            if (response.ok) {
That would indeed be better since it's ugly that the `catch` gets the error when there is a network issue and the `else` in the `then` for server issues,... It would also make the rewrite easier since it would follow the `.done` and `.fail` from ajax

2022-09-02 13:36 UTC, niknetniko commented on app/assets/javascripts/favorite_course_buttons.ts
> +            if (response.ok) {
Yep

2022-09-05 07:27 UTC, jorg-vr approved these changes

2022-09-05 09:46 UTC, niknetniko approved these changes

2022-09-06 09:55 UTC, merged