Update .browserslist
dodona-edu/dodona pull request #3964
Opened 2022-09-02 11:29 UTC by BramDevlaminck

This pull request updates the `.browserslist` file to the browser versions we're going to support this year

Closes #3691  .

2022-09-02 12:23 UTC, bmesuere requested changes
Can you add a little more information to the PR as is done in https://github.com/dodona-edu/dodona/pull/2738

2022-09-02 13:03 UTC, BramDevlaminck commented
> Can you add a little more information to the PR as is done in #2738

I did not find a way to get the information about `babel` and I don't know what all the file sizes mean. What's the difference between the first and second size you specified?

2022-09-06 12:28 UTC, bmesuere requested changes
ios safari should be bumped as well. There are some exotic browser names in the list (at least to me), I'm not sure if we explicitly want to support those.

2022-09-07 07:46 UTC, chvp approved these changes

2022-09-09 12:15 UTC, bmesuere approved these changes

2022-09-09 12:25 UTC, merged