Replace i18n-js by polyglot
dodona-edu/dodona pull request #3975
Opened 2022-09-08 08:33 UTC by jorg-vr

This pull request

- [ ] Tests were added
- [ ] Documentation update can be found at dodona-edu/dodona-edu.github.io#

Closes # .

2022-09-09 13:15 UTC, bmesuere approved these changes

2022-09-09 13:17 UTC, chvp approved these changes

2022-09-09 13:37 UTC, niknetniko requested changes

2022-09-09 13:37 UTC, niknetniko commented on app/assets/javascripts/code_listing/user_annotation.ts
> +        const timestamp = dayjs.utc(this.createdAt).format(I18n.t("time.formats.annotation"));
I don't think this takes the locale into account, e.g.

![image](https://user-images.githubusercontent.com/1756811/189362064-cdd63096-80d2-4f9d-bdc4-905f2e2964a1.png)

The date is still in English.

2022-09-09 13:37 UTC, niknetniko commented on config/locales/defaults/nl.yml
> +      sec: "%{smart_count} seconde |||| %{smart_count} secondes"
```suggestion
      sec: "%{smart_count} seconde |||| %{smart_count} seconden"
```

2022-09-09 14:23 UTC, jorg-vr commented on app/assets/javascripts/code_listing/user_annotation.ts
> +        const timestamp = dayjs.utc(this.createdAt).format(I18n.t("time.formats.annotation"));
Thanks for noticing, everything looked great in September :p (Except the capital s)

Fixed it

2022-09-12 11:11 UTC, niknetniko approved these changes

2022-09-12 11:36 UTC, merged