Correctly set scores and completed states when a new user is added to an evaluation
dodona-edu/dodona pull request #4061
Opened 2022-10-04 07:43 UTC by jorg-vr

I am not entirely happy that I have to pass around current_user two times, but I didn't find a better method.

Closes #3983

2022-10-04 08:30 UTC, chvp approved these changes
Maybe add soms tests?

2022-10-04 11:56 UTC, niknetniko requested changes

2022-10-04 11:56 UTC, niknetniko commented on app/models/feedback.rb
> +  def uncomplete_or_set_blank_to_zero
In which scenario should the feedback be uncompleted? I'm just wondering when it happens that we create a new feedback that is already completed.

2022-10-04 11:56 UTC, niknetniko commented on test/controllers/evaluations_controller_test.rb
> +  test 'Scores are set if a user is added' do
This test feels more like it belongs in the model tests.

2022-10-04 11:56 UTC, niknetniko commented on app/models/feedback.rb
> +  after_create :uncomplete_or_set_blank_to_zero
Thinking about it, should we also set blank submissions to zero if the submission changes? (The incomplete state is normally already unset by deleting the scores)

We currently don't, and this is a very unlikely scenario, so perhaps not needed.

2022-10-04 11:58 UTC, jorg-vr commented on app/models/feedback.rb
> +  def uncomplete_or_set_blank_to_zero
complete appears to be the default. So a blank submission is completed automatically

2022-10-04 12:00 UTC, jorg-vr commented on app/models/feedback.rb
> +  after_create :uncomplete_or_set_blank_to_zero
It is impossible to select no submission when changing a feedback. so submission.blank? will never be true after an update

2022-10-04 12:04 UTC, niknetniko commented on app/models/feedback.rb
> +  def uncomplete_or_set_blank_to_zero
Ah some code must set it then, I was assumed it was uncompleted by default, since

```
#  completed              :boolean          default(FALSE), not null
```

but I haven't checked all callbacks

2022-10-04 12:07 UTC, jorg-vr commented on app/models/feedback.rb
> +  def uncomplete_or_set_blank_to_zero
Tests work without the uncomplete, so I'll remove it. I am unsure where blanks where set to complete, but it did happen automatically

2022-10-04 12:16 UTC, niknetniko approved these changes

2022-10-05 09:24 UTC, bmesuere approved these changes

2022-10-06 09:42 UTC, merged