punchcard.js: convert to typescript
dodona-edu/dodona pull request #4080
Opened 2022-10-10 12:10 UTC by freyavs

2022-10-10 14:14 UTC, jorg-vr approved these changes

2022-10-10 14:30 UTC, bmesuere commented on app/assets/javascripts/punchcard.ts
> +        })
Is there a reason for this rather complex function?

2022-10-11 10:01 UTC, niknetniko requested changes

2022-10-12 12:37 UTC, freyavs commented on app/assets/javascripts/punchcard.ts
> +        })
While going over the x values, it sets them to hours on the x-as. 

I could also just append `":00"` here (to the original x-axis elements 0-23). Or set x as `scaleTime ` instead of `scaleLinear`, but the hours in the data are strings 0-23 so that brings other (small) complications in another part of the code. 

I'm not sure which is the cleanest, or if you have another suggestion?

2022-10-12 12:43 UTC, bmesuere commented on app/assets/javascripts/punchcard.ts
> +        })
maybe something like this?
```javascript
`${hour < 10 ? '0' : ''}${hour}:00`
```

2022-10-12 12:44 UTC, chvp approved these changes

2022-10-12 12:54 UTC, freyavs commented on app/assets/javascripts/punchcard.ts
> +        })
Alright, I'll apply this

2022-10-12 13:35 UTC, niknetniko approved these changes

2022-10-13 07:25 UTC, merged