course_membership.js: remove jquery and use typescript
dodona-edu/dodona pull request #4083
Opened 2022-10-17 09:03 UTC by freyavs

2022-11-16 10:55 UTC, jorg-vr requested changes
This looks good :) 

I left some minor remarks but these are mostly about comments

One visual issue I noticed, could you add a bit of margin to the top or bottom of the labels? they don't look great when there is more than one row
![image](https://user-images.githubusercontent.com/21177904/202161479-5a70622c-a9ae-41f0-8ee3-99c53f26092f.png)

2022-11-16 10:55 UTC, jorg-vr commented on app/assets/javascripts/components/course_labels_search_bar.ts
> + * This component represents a list of d-label-token
This comment does not look correct

2022-11-16 10:55 UTC, jorg-vr commented on app/assets/javascripts/components/course_labels_search_bar.ts
> +        this.requestUpdate();
Could you double check if this is required? I would expect the request update to be triggered by the change to labels in the line above. (But maybe lit has problems with auto detecting changes in lists)

2022-11-16 10:55 UTC, jorg-vr commented on app/assets/javascripts/components/course_labels_search_bar.ts
> + * @prop {string[]} SelectedLabels
Please describe the function of the element and all properties in the comments

2022-11-16 10:55 UTC, jorg-vr commented on app/assets/javascripts/components/datalist_input.ts
> +            e.preventDefault();
Maybe add a comment here why this is done

2022-11-17 09:58 UTC, freyavs commented on app/assets/javascripts/components/course_labels_search_bar.ts
> +        this.requestUpdate();
Yes so without `requestUpdate` this doesn't rerender. I tried fixing it by copying the list, doing the changes on that list, and then assigning this new list to the `this.labels` (it shoud only autodetects when you assign a new value instead of changing the current list). 

This works, but then when I start to type again, the list gets "overwritten" by the searchbar component as the deletion hasn't been registered there (so when deleting a label it just appears again when you start typing to add another label). And something weird.. when I call `requestUpdate` after the fix of assigning a new list instead of just changing the existing one, it still doesn't change the list in the searchbar component, which causes the same problem. 

Should I keep it like this then?

2022-11-17 09:59 UTC, jorg-vr commented on app/assets/javascripts/components/course_labels_search_bar.ts
> +        this.requestUpdate();
yes keep it as is :)

2022-11-17 10:44 UTC, jorg-vr approved these changes

2022-11-17 15:53 UTC, bmesuere reviewed
The code looks good, but I have a minor UX remark. If I'm correct, you can type something that is not present in the list and add it as well, but the UI isn't super clear on that because of the double focus on "search" both in the placeholder text and the info below.

Maybe searching doesn't even have to be mentioned because it's not needed?

2022-11-21 09:16 UTC, niknetniko approved these changes

2022-11-21 09:29 UTC, freyavs commented
> The code looks good, but I have a minor UX remark. If I'm correct, you can type something that is not present in the list and add it as well, but the UI isn't super clear on that because of the double focus on "search" both in the placeholder text and the info below.
> 
> Maybe searching doesn't even have to be mentioned because it's not needed?

I agree. Would this be better, or still not clear enough?
info:  "Add an existing userlabel or create a new one"
placeholder: just something like "start typing..."

2022-11-21 10:53 UTC, bmesuere commented
> > The code looks good, but I have a minor UX remark. If I'm correct, you can type something that is not present in the list and add it as well, but the UI isn't super clear on that because of the double focus on "search" both in the placeholder text and the info below.
> > Maybe searching doesn't even have to be mentioned because it's not needed?
> 
> I agree. Would this be better, or still not clear enough? info: "Add an existing userlabel or create a new one" placeholder: just something like "start typing..."

I agree with the info text, but would just use "Label" as placeholder text. This best matches the material design spec.

2022-11-21 16:47 UTC, bmesuere approved these changes

2022-11-21 16:54 UTC, merged