Temporal icon
dodona-edu/dodona pull request #4188
Opened 2022-11-23 11:03 UTC by tibvdm

# Temporal overlay for Christmas

![assembled_plain](https://user-images.githubusercontent.com/34175340/203528826-39931363-b0c6-4af8-9401-c16f487c82d9.svg)

Ho Ho Ho, Santa has found his way to Dodona. He will be sitting on your status icons in order to watch your progress. Santa left his hat on every single status icon. When you hover the icon, he will come forward and take a peek.

<img width="1088" alt="Screenshot 2022-11-23 at 11 56 55" src="https://user-images.githubusercontent.com/34175340/203529914-e0486211-589f-4463-b5e1-f473e8a34489.png">

<img width="1088" alt="Screenshot 2022-11-23 at 11 56 34" src="https://user-images.githubusercontent.com/34175340/203529928-8fb91350-7a20-4619-b819-1703b1358ca6.png">

This PR adds a `temporal helper` to select some specific css depending on the current date. Extra folders enables extra seasons in the future.

- [ ] Tests were added
- [ ] Documentation update can be found at dodona-edu/dodona-edu.github.io#

2022-11-23 12:47 UTC, jorg-vr requested changes
I really like the santa figure, thanks for the contribution!

BTW: I'll give you access to create branches on dodona, so you don't need to work from your own fork if you want to contribute more in the future.

2022-11-23 12:47 UTC, jorg-vr commented on app/helpers/temporal_helper.rb
> +    return current_time.month == 12 && current_time.day.between?(25, 31)
I would include the 24th because Christmas eve also deserves a smiling Santa

2022-11-23 12:47 UTC, jorg-vr commented on app/views/series/_series_status.html.erb
> +    <% deadline_class, deadline_icon = series_status_deadline(series, user) %>
There are some unneeded white space changes here, could you avoid those?

2022-11-23 12:47 UTC, jorg-vr commented on app/views/series/_series_status.html.erb
> +            <div class="overlay"></div>
I think you can avoid this extra div using an ::after element in css

2022-11-23 12:47 UTC, jorg-vr commented on app/assets/stylesheets/temporal/christmas.css.scss
> +          &.deadline-missed .mdi-alarm-off {
I do not like the fact that you have to manually set every possible combination with other icons to transparent.
This will result in errors if new classes are ever added.

Either display the overlay on top (By specifying a higher z index)
Or try to find a more general css query that matches all desired classes. (You can use `!important` to make sure your css has priority over more specific classes)

2022-11-23 14:07 UTC, bmesuere commented on app/helpers/temporal_helper.rb
> +    return current_time.month == 12 && current_time.day.between?(25, 31)
I would even start this as soon as december first

2022-11-24 06:47 UTC, pdawyndt commented on app/helpers/temporal_helper.rb
> +    return current_time.month == 12 && current_time.day.between?(25, 31)
My kids would strongly object doing this earlier than December 7th: no competition allowed!

2022-11-24 08:29 UTC, jorg-vr requested changes
Except for the lockfile, everything looks good.

Side note: Once you have applied changes you can click on the circle arrows (Top right) to re request a review, which will notify me

2022-11-24 08:29 UTC, jorg-vr commented on Gemfile.lock
> -GEM
You chose the wrong method to exclude it...
Please do not remove it from the repo, only exclude changes made by you

2022-11-24 16:08 UTC, bmesuere requested changes
I deployed this locally and it looks really nice! 

I do agree with @chvp that this might be a bit much if we apply it to all series icons for the entire month and add other seasonal decorations in the future.

We could reduce the number of appearances by only applying the hat to the "green checkmark" icon (showing santa on hover) and show santa (without hover) instead of the "rainbow checkmark". This would make santa some kind of achievement. What do the others think?

I also checked if we could replace the icons that are shown on correct submission by a set of christmas-themed icons. Unfortunately, mdi doesn't include a lot of christmas icons.

Regarding the code: there are a lot of `!important`'s in the css which is something we try to avoid. Are these strictly necessary?

2022-11-25 08:29 UTC, chvp approved these changes

2022-11-25 08:29 UTC, chvp commented on app/views/series/_series_status.html.erb
> +  <% overlay_class = series_status_overlay() %>
```suggestion
  <% overlay_class = series_status_overlay %>
```

2022-11-25 08:40 UTC, niknetniko approved these changes

2022-11-25 08:46 UTC, tibvdm commented
I updated the description and added an extra image to show the different overlay options.

2022-11-25 09:30 UTC, merged