Improve scoping of activity repositories
dodona-edu/dodona pull request #4203
Opened 2022-11-29 14:49 UTC by jorg-vr

This pull request

- [ ] Tests were added
- [ ] Documentation update can be found at dodona-edu/dodona-edu.github.io#

Closes # .

2022-11-30 15:05 UTC, bmesuere requested changes
Feedback from a quick functional test on naos:

My first reaction was a bit of confusion. Part of this might be because exercises/activities is not repeated in the tab name for all tabs (as we do on the courses page), part of this is because I wasn't expecting a tab with "Universiteit Gent" or "Scriptingtalen" as name.

Some suggestions:
-[x] Include "activities" in the name for all tabs
-[x] For the institution, use the short name (as with the courses page)
-[x] There should be a little help text explaining what is shown: or as a (bootstrap) tooltip on the tab name or as a small help text above the table
-[ ] Even with a help text, the course specific exercises are hard to explain. Wouldn't it make more sense (and easier to explain) to add this category as a search filter private/public instead?
-[ ] Suggestions for other names for "featured" are welcome. It's ok, but to me featured indicated a limited number but this section will contains hundreds of exercises. "curated" might be an alternative, but I'm also not sure about that. If we don't find a better name, featured is ok.
-[ ] The active tab isn't stored in local storage (as is done with the filters) which causes reloading (with filters selected) to fail
-[ ] Popularity of an exercise is definitely a strong indicator of interestingness of the exercise so if possible we should surface that information in the table. I don't think we want to list the exact number of courses where an exercises is used, but maybe we can use an icon with different states: low, medium, high, featured. We will then have to pick sensible threshold values. I don't know what the best strategy is for fetching this information: calculate it on demand, store it in the DB or store it in cache. In addition, we could add a filter for it.

2022-12-01 13:26 UTC, jorg-vr commented
> Even with a help text, the course specific exercises are hard to explain. Wouldn't it make more sense (and easier to explain) to add this category as a search filter private/public instead?

I agree that this is hard to explain, but I do not want to replace it with a public private filter. 
If a course has been granted access to a specific private repository, it is very likely that this will be the main source for exercises. This is why I made it the first suggested tab when in the context of a course.
If we make it a public/private filter, these activities will only be available in the "All activities" tab or the "My institution" tab. In both cases they will be mixed with results form your own private repositories if you filter on "private"

2022-12-02 13:18 UTC, jorg-vr commented
Course activities and my activities have been merged

2022-12-05 14:53 UTC, bmesuere requested changes
👍 
- [x] Did you try a bootstrap popover instead of the title attribute for the info text? It's a bit hidden right now.
- [x] What's the workflow to "feature" a repository? I couldn't see a checkbox on the repo edit page on naos.
- [ ] I'm not a fan of "recommended exercises", this gives the impression that the list is tailored towards this course/user/series. For the lack of a better name, I guess we can use featured?
- [ ] I noticed that the list of labels always ends with a `,` (not strictly related to this PR)

2022-12-06 10:43 UTC, chvp requested changes

2022-12-06 10:43 UTC, chvp commented on app/assets/javascripts/components/filter_tabs.ts
> +                    ${ this.labels.map( label => html`
```suggestion
                    ${this.labels.map(label => html`
```

2022-12-06 10:43 UTC, chvp commented on app/models/activity.rb
> +  enum repository_scope: { mine: 1, my_institution: 2, featured: 3, all: 0 }, _prefix: true
I'm a bit confused by this enum. Where is it used? AFAIK, this should correspond to a matching `repository_scope` field in the database, which is not there (and wouldn't make sense in this case (?)).

2022-12-06 10:47 UTC, jorg-vr commented on app/models/activity.rb
> +  enum repository_scope: { mine: 1, my_institution: 2, featured: 3, all: 0 }, _prefix: true
These are all the options for the scope defined below. I used to use this to generate all tabs, but as they become more complex it was no longer that useful. I'll remove it

2022-12-06 12:53 UTC, niknetniko reviewed
Besides one minor formatting nitpick, I noticed some weird behaviour when using the back button:

1. Go to the activities (or course) page
2. Press the browser back button

All params are now removed from the URL, which results in a state where no tab is selected, although they are unchanged:
![image](https://user-images.githubusercontent.com/1756811/205917779-6e29efe8-a4de-4d9d-8e08-5a260c1c4289.png)
(this is also what happens after you have done a few searches)

2022-12-06 12:53 UTC, niknetniko commented on app/assets/javascripts/components/filter_tabs.ts
> +    @property( { type: Array })
```suggestion
    @property({type: Array})
```

2022-12-07 11:06 UTC, bmesuere approved these changes
This is a good first step in solving our exercise discovery problem 👍

2022-12-07 12:49 UTC, niknetniko approved these changes

2022-12-09 09:30 UTC, chvp approved these changes

2022-12-12 08:27 UTC, merged