drag_and_drop.js: remove jquery and convert to typescript
dodona-edu/dodona pull request #4209
Opened 2022-12-02 14:04 UTC by freyavs

This pull request converts drag_and_drop.js to drag_and_drop.ts, removing jquery and converting everything to typescript.

It also adds a new util function `findParent` to replace the jquery `.parents(...)`  method.

This is progress on #3590

2022-12-05 13:13 UTC, jorg-vr approved these changes
Code looks good :)

2022-12-05 13:13 UTC, jorg-vr commented on app/assets/javascripts/util.js
> +/**
Could you also use this function in the other places where it is relevant. Such as https://github.com/dodona-edu/dodona/pull/4127/files#diff-c5bc65df73e1c820b39e10ea1e08c46f7ee47491e7b38b6134c380414573a9e7R14

2022-12-05 13:38 UTC, niknetniko requested changes

2022-12-05 13:38 UTC, niknetniko commented on app/assets/javascripts/drag_and_drop.ts
> +function copyWidth(clone: HTMLCanvasElement, original: HTMLCanvasElement, tag=undefined): void {
Why are these `HTMLCanvasElement`? The call on line 48 to this function seems to pass `td` elements.

2022-12-05 13:38 UTC, niknetniko commented on app/assets/javascripts/drag_and_drop.ts
> +            copyWidth(clone, original, "td");
We should add `@types/dragula` to the dev dependencies, as this will help with stuff like the `copyWidth` function expecting `HTMLCanvasElements`, while these don't seem to be canvas elements.

2022-12-05 13:38 UTC, niknetniko commented on app/assets/javascripts/drag_and_drop.ts
> +        moves: function (el, source, handle, sibling) {
Can these functions become arrow functions?

2022-12-05 17:52 UTC, freyavs commented on app/assets/javascripts/drag_and_drop.ts
> +function copyWidth(clone: HTMLCanvasElement, original: HTMLCanvasElement, tag=undefined): void {
Right, they are `HTMLTableRowElement`. I was getting type errors that `.width` doesn't exist on this type, so I was testing if it worked with other types but hadn't changed it back, apparently. Actually, `.width` is deprecated anyway, so probably shouldn't be used here. I'll fix this.

2022-12-06 13:25 UTC, niknetniko requested changes

2022-12-06 13:25 UTC, niknetniko commented on app/assets/javascripts/drag_and_drop.ts
> +function copyWidth(clone: Element, original: Element, tag: string = undefined): void {
Taking another look at this, this function is only ever used with "td" as the third param, so the case where the tag is undefined can be removed (if we were to need this, I think we propably should use `.children` instead of `childNodes`, as the latter includes nodes for text, which are not HTML elements, so they e.g. don't have a `clientWidth`)

2022-12-08 11:58 UTC, freyavs commented on app/assets/javascripts/drag_and_drop.ts
> +function copyWidth(clone: Element, original: Element, tag: string = undefined): void {
I removed it, also had to cast the cloned children to `HTMLElement` as typescript was complaining that `Element` doesn't have the property `style`

2022-12-08 19:00 UTC, bmesuere requested changes

2022-12-08 19:00 UTC, bmesuere commented on app/assets/javascripts/util.js
> + * Searches the parents of an element until it finds the parent containing certain classes
```suggestion
 * Returns the first parent of an element that has at least all of the given classes. Returns null if no such parent exists.
```

2022-12-12 10:26 UTC, niknetniko approved these changes

2022-12-12 12:33 UTC, bmesuere approved these changes
👍

2022-12-12 13:18 UTC, jorg-vr approved these changes

2022-12-12 13:19 UTC, merged