Only show course from latest year on home page
dodona-edu/dodona pull request #4245
Opened 2022-12-14 16:20 UTC by jorg-vr

This pull request

![image](https://user-images.githubusercontent.com/21177904/207650273-46bfcec3-5d0a-4113-ba38-e1bf6056353d.png)

![image](https://user-images.githubusercontent.com/21177904/207650471-969dc8a4-6baf-4f21-b400-f311f603576c.png)

- [ ] Tests were added
- [ ] Documentation update can be found at dodona-edu/dodona-edu.github.io#

Closes # .

2022-12-15 12:32 UTC, bmesuere requested changes
👍 Looks good, but I'm not sure about the current favorite behaviour. Shouldn't we add a separate "year" for favorites?
Two smaller things:
- Can you make the dropdown right-aligned (do the dropdown aligns with the right of the button?) Should be possible with `<div class="dropdown-menu dropdown-menu-right">`
- Can you style the years with an n-dash (?) as is done on the course cards?

2022-12-15 12:40 UTC, bmesuere commented
> 👍 Looks good, but I'm not sure about the current favorite behaviour. Shouldn't we add a separate "year" for favorites?

As an alternative, keep the current behaviour, but place the favorite courses in a separate "favorite courses" section above "courses".

2022-12-15 15:09 UTC, bmesuere approved these changes

2022-12-17 15:43 UTC, chvp approved these changes

2022-12-19 13:36 UTC, merged