Homepage course cards redesign
dodona-edu/dodona pull request #4261
Opened 2022-12-20 13:21 UTC by jorg-vr

This pull request

- [ ] Tests were added
- [ ] Documentation update can be found at dodona-edu/dodona-edu.github.io#

Closes # .

2022-12-20 13:32 UTC, jorg-vr commented
Mockups:
V1:
![image](https://user-images.githubusercontent.com/21177904/208678804-4e3dca91-2649-4969-aa01-972274bdeecb.png)
![image](https://user-images.githubusercontent.com/21177904/208678843-9ed0eb58-3e1e-48ca-ab7c-814dd7b319ab.png)
V2:
![image](https://user-images.githubusercontent.com/21177904/208678679-330ede8b-c703-4025-8333-7c591812b57e.png)
![image](https://user-images.githubusercontent.com/21177904/208678691-72dc5e67-b187-4a11-a2b7-2d7ad8bb7d7a.png)
![image](https://user-images.githubusercontent.com/21177904/208678703-c8497923-88cb-4a25-8131-63ad676cb9c0.png)
![image](https://user-images.githubusercontent.com/21177904/208678720-82f1f0e6-e6ab-4f88-96c0-5a82530445f9.png)
V3:
![image](https://user-images.githubusercontent.com/21177904/208678750-c1a44371-d406-4e73-9135-f1b4ebddc47b.png)

2022-12-23 08:53 UTC, jorg-vr commented
Always same height
![image](https://user-images.githubusercontent.com/21177904/209304761-847da5e9-1b79-47d4-92c4-94f11c14ed09.png)

2022-12-23 10:02 UTC, jorg-vr commented
Empty state mockup
![image](https://user-images.githubusercontent.com/21177904/209315650-570e0917-df89-4c64-82b7-a011bc87d3db.png)

2022-12-23 15:47 UTC, jorg-vr commented
WIP
![image](https://user-images.githubusercontent.com/21177904/209362624-9df19f02-506d-417b-a6e2-274fc47ebf9d.png)
![image](https://user-images.githubusercontent.com/21177904/209362634-7fac3db6-9a67-44a4-ad05-dcf267b30fc1.png)

2022-12-23 16:01 UTC, pdawyndt commented
Small remark that pops up when seeing these new cards (which I like a lot): by checking if a student completed a course or how far a student is from completing a course, we make the assumption that no extra series/exercises will be added to the course. Might look strange if the latter does happen. Say, for example, that a teacher opens a course for registration, but has no series/exercises in the course yet (maybe closed, but not visible to students). Then students will already start with a completed course.

2022-12-23 17:02 UTC, pdawyndt commented
When I tested on naos, loading took a long time after switching to another academic year.

2022-12-23 17:03 UTC, pdawyndt commented
The congratulations icon might do with some additional padding on top (maybe make image a tiny bit smaller to preserve the same height for all cards).

2022-12-23 17:04 UTC, pdawyndt commented
When combination of teacher name(s) and institute name is too long, the academic year might overflow to the next line, which breaks the fact that cards should have the same height.

![image](https://user-images.githubusercontent.com/5736113/209373727-d82d3632-c42d-45b8-9ebe-d1aa1fb37e4b.png)

2022-12-23 17:07 UTC, pdawyndt commented
Idea for "jump back in" when you don't have registered for any course yet: put option in "jump back in" to start selecting courses.

2022-12-23 17:35 UTC, bmesuere commented
- I liked the striped icon better
- the progress bar in the header needs a bit more padding on top, it is too close to the teacher name compared to the bottom padding
- "deze cursus afgewerkt" -> "alle oefeningen opgelost". I think we only include exercises in public series?
- the version with only 2 items looks a bit odd, there's too much spacing. Maybe make the "goed bezig" bigger like the one below?
- maybe put the newline after "gefeliciteerd" in the 2-line version? (but maybe the new text won't fit on a single line)

2022-12-24 09:48 UTC, bmesuere commented
Some ideas for teachers (could be for a next PR).
- number of open questions (or at least an indicator)
- class progress of deadline series
- mini graph showing activity / number of submissions and active users in last hour
- number of user/submissions

2023-01-03 13:07 UTC, pdawyndt requested changes

2023-01-03 13:07 UTC, pdawyndt commented on config/locales/views/pages/en.yml
> +        one: "**Doing great!** Only one activity left and you have solved all exercises."
No consistent use of activities vs exercises. Is check for all activities or all exercises?

2023-01-05 12:40 UTC, jorg-vr commented
kleur van cursus kijkt te veel op knoppen (Misschien terug ligte variant)

Oefening => naam van de reeks kan nuttige context zijn

Splits de beschrijving voor leesactiviteit en oefening

Goed bezig tekstje => oefening ipv activiteit

Bug tooltip blijft staan bij jaar wijziging

Altijd huidige reeks tonen bij oefening als er geen deadline is

Mogelijke bug => bart cursus programeren 2019-2020

Indicatie van fout/ al bezig

2023-01-12 12:32 UTC, jorg-vr commented
Series icons as svg's of different sizes, with the old version at the bottom
![image](https://user-images.githubusercontent.com/21177904/212067350-834c09de-26fa-4309-a5ca-a5dc1eb7bdfd.png)

![image](https://user-images.githubusercontent.com/21177904/212067028-a7bbeff5-fe81-4899-9c27-ddc4f866c82c.png)

2023-01-13 09:03 UTC, jorg-vr commented
![image](https://user-images.githubusercontent.com/21177904/212280614-4d9364a1-e6a9-46e7-8602-33919049b250.png)
![image](https://user-images.githubusercontent.com/21177904/212280627-6914e533-d1f3-4446-8828-43dc8ea0c2ec.png)
![image](https://user-images.githubusercontent.com/21177904/212280647-45109374-06ed-4c14-9a5b-39e8a017c003.png)
![image](https://user-images.githubusercontent.com/21177904/212280663-7e6597d8-9fd6-4d39-b812-429be3b50736.png)

2023-01-13 14:45 UTC, jorg-vr commented
Draft of exercises status overlayed
![image](https://user-images.githubusercontent.com/21177904/212347724-2e405f9b-667f-49e7-9243-85a27ad2b5f4.png)

2023-01-15 15:06 UTC, bmesuere approved these changes
I really like these changes, nice work!

I prefer the lighter header color (in light mode) that is now used. The darker one was to similar to the top actions and too "boring".

I also like the use of the exercise status icon when there is a previous submission. The overlayed variant is probably a bit too small.

A small suggestion to add a little bit of context to the exercises shown: in the title attribute of the exercise name, you could add "continue with xxxxx" or "start with xxxxx".

2023-01-16 08:59 UTC, chvp approved these changes

2023-01-16 08:59 UTC, chvp commented on app/views/application/_progress_chart.html.erb
> +  <svg viewBox="0 0 1 1" preserveAspectRatio="none" height="8" width="<%= width %>" class='progress-chart <%= muted ? 'colored-muted' : ''%>'>
```suggestion
  <svg viewBox="0 0 1 1" preserveAspectRatio="none" height="8" width="<%= width %>" class='progress-chart <%= muted ? 'colored-muted' : '' %>'>
```

2023-01-16 08:59 UTC, chvp commented on app/models/course.rb
> +  def homepage_activities(user, limit = 3)
I think this can be a private method?

2023-01-16 08:59 UTC, chvp commented on app/models/course.rb
> +
Same here?

2023-01-16 09:02 UTC, jorg-vr commented on app/models/course.rb
> +  def homepage_activities(user, limit = 3)
these methods are used in the _course_card view. I am pretty sure that would break if they were private?

2023-01-16 09:03 UTC, chvp commented on app/models/course.rb
> +  def homepage_activities(user, limit = 3)
Ah, never mind then.

2023-01-17 14:46 UTC, niknetniko approved these changes
Looks very good!

2023-01-18 08:48 UTC, merged