repository.js: remove jquery and convert to typescript
dodona-edu/dodona pull request #4298
Opened 2023-01-04 16:38 UTC by freyavs

2023-01-06 13:25 UTC, jorg-vr requested changes
Looks good, left some minor comments.

Thanks for fixing the small bugs as well!

2023-01-06 13:25 UTC, jorg-vr commented on app/controllers/repositories_controller.rb
> +        format.js
You can remove this line as we no longer support js as format

2023-01-06 13:25 UTC, jorg-vr commented on app/assets/javascripts/repository.ts
> +        fetch(`/repositories/${repositoryId}/add_admin.js`, {
You can change these paths to json (Or just omit the file type as it does not matter which response format you get as you're no longer using the result)

2023-01-09 08:09 UTC, jorg-vr approved these changes

2023-01-09 10:56 UTC, niknetniko approved these changes

2023-01-10 09:59 UTC, merged