So more relevant info for teachers on course cards
dodona-edu/dodona pull request #4299
Opened 2023-01-06 08:32 UTC by jorg-vr

This pull request

- [ ] Tests were added
- [ ] Documentation update can be found at dodona-edu/dodona-edu.github.io#

Closes # .

2023-01-15 17:27 UTC, bmesuere commented
I would leave out the number of questions from the header (but definitely include it in the card itself if there would be any). The other numbers  could be abbreviated to for example 15.5K instead of 15484.

The priority of things to show are:
- open questions
- pending registrations
- series with upcoming deadline
- series with passed deadline

For now, I would fill the rest of the slots with exercises (which is not really useful). In a later phase/PR, we could add some graphs instead of exercises.

For courses using series without deadlines, could we show something instead of the graphs? Maybe "series being worked on now"?

2023-01-18 13:59 UTC, jorg-vr commented
![image](https://user-images.githubusercontent.com/21177904/213190391-29bf9738-96de-4e23-9a63-1e387cfbf653.png)
![image](https://user-images.githubusercontent.com/21177904/213190420-db61ec4b-d928-491b-8227-b27a82fd5445.png)
![image](https://user-images.githubusercontent.com/21177904/213190456-56101205-88ac-4c5a-ba4c-1d4ed95ce105.png)

2023-01-20 11:36 UTC, chvp requested changes

2023-01-20 11:36 UTC, chvp commented on app/models/course.rb
> +  def homepage_admin_notifications
This function is doing a lot of UI work for being in a model. Maybe it can be moved to a helper?

2023-01-20 11:36 UTC, chvp commented on app/views/pages/_course_card.html.erb
> +    <div class="card-title card-title-colored-container" style="height: 111px;">
Is there a reason not to do this in CSS?

2023-01-20 11:36 UTC, chvp commented on app/views/pages/_course_card.html.erb
> +          <div style="width: 100%">
Again, why not in CSS?

2023-01-20 13:09 UTC, niknetniko reviewed
This looks very good! (I have added some small nitpicks here and there; an automated ERB formatter would be very nice)

One small side-effect I noticed though is that the home page now takes a bit longer to render. This is normal, but when using the academic year selector, there is no indication that something is actually happening. So for example, if I select another year, it feels like nothing is happening, which made me think something went wrong (although it was just loading). I think we should either add a loader or just go for a full page refresh (in which case the browser shows something is happening).

2023-01-20 13:09 UTC, niknetniko commented on config/locales/views/pages/nl.yml
> +        one: "Één onbeoordeelde oplossing"
I think we use the term "afgewerkte oplossing", so maybe something like this?

```suggestion
        one: "Één onafgewerkte oplossing"
```

The docs also talk about "onbekeken oplossingen", so perhaps that's an alternative.

2023-01-20 13:09 UTC, niknetniko commented on config/locales/views/pages/nl.yml
> +        other: "%{count} onbeoordeelde oplossingen"
```suggestion
        other: "%{count} onafgewerkte oplossingen"
```

2023-01-20 13:09 UTC, niknetniko commented on config/locales/views/pages/nl.yml
> +        other: "Voeg meer inhoud toe aan je cursus"
```suggestion
        other: "Voeg meer inhoud toe aan jouw cursus"
```

For consistency

2023-01-20 13:09 UTC, niknetniko commented on config/locales/views/pages/en.yml
> +        one: "One unreviewed submission"
In the evaluations UI, we use the term "complete", so perhaps something like this:

```suggestion
        one: "One incomplete submission"
```

2023-01-20 13:12 UTC, jorg-vr commented on config/locales/views/pages/en.yml
> +        one: "One unreviewed submission"
this would also require a change to the word submission. (As we are not completing the submission, but completing the process of reviewing the submission)

2023-01-20 13:14 UTC, jorg-vr commented on config/locales/views/pages/nl.yml
> +        one: "Één onbeoordeelde oplossing"
For the same reason as in English, I think 'afgewerkt' does not apply.

I had `onbekeken` before, but it looked rather ugly

2023-01-20 13:16 UTC, bmesuere commented on config/locales/views/pages/nl.yml
> +        one: "Één onbeoordeelde oplossing"
We hebben dit vanmorgen bespreken. Er stond eerst "onbekeken", maar dat voelde raar aan. Daarom is het aangepast naar "onbeoordeeld" (al kan " niet beoordeeld" voor mij ook). Ik was vergeten dat we vroeger "onafgewerkt" gebruikt hebben, maar ik denk dat dat in de context was dat we eerst enkel evaluaties zonder punten hadden. Voor mij werkt "beoordelen" zowel met als zonder punten geven, dus misschien moeten we die vertaling/docs dan overal aanpassen.

2023-01-20 13:18 UTC, bmesuere commented on config/locales/views/pages/en.yml
> +        one: "One unreviewed submission"
I don't really agree here. In the evaluations UI, you already have the evaluation context which is why "complete" is good enough there. On the home page, you don't have that context and "unreviewed" provides that.

2023-01-20 14:44 UTC, niknetniko approved these changes

2023-01-20 15:16 UTC, chvp approved these changes

2023-01-20 16:15 UTC, bmesuere approved these changes

2023-01-23 09:05 UTC, merged