Hide output if it is much longer than expected to avoid browser crashes
dodona-edu/dodona pull request #4353
Opened 2023-01-25 09:19 UTC by jorg-vr

This pull request hides very long submission output to avoid browser crashes. This solves #4265 

To much output is defined as 100 lines more than the expected output. (But this is open for discussion)

![image](https://user-images.githubusercontent.com/21177904/214524971-dd1ba927-6eae-42fb-8809-3cf87d0337b2.png)

Closes #4265.

2023-01-25 12:56 UTC, chvp requested changes
I think we should tackle lines that are far too long as well. In the case of #4265, we could imagine a student not adding a newline character. This would then result in one huge line, and the same problem would occur. Cutting off the output if there are 2000 (or something like that) characters more than expected would solve both cases I think.

The interaction with the simplified_table functionality also feels weird to me somehow. In the case where there is such a difference between generated and expected, I would also expect to also use the simplified table, but that's not very clear from the code.

2023-01-25 12:56 UTC, chvp commented on app/helpers/renderers/text_differ.rb
> +    @to_many_lines = @generated_linecount
```suggestion
    @too_many_lines = @generated_linecount
```

2023-01-25 12:56 UTC, chvp commented on app/helpers/renderers/text_differ.rb
> +    cut_off_message(builder) if @to_many_lines
```suggestion
    cut_off_message(builder) if @too_many_lines
```

2023-01-25 12:56 UTC, chvp commented on app/helpers/renderers/text_differ.rb
> +      builder << I18n.t('submissions.show.cut_off_message', generated: @to_many_lines, count: @expected_linecount)
```suggestion
      builder << I18n.t('submissions.show.cut_off_message', generated: @too_many_lines, count: @expected_linecount)
```

2023-01-25 12:56 UTC, chvp commented on app/helpers/renderers/text_differ.rb
> +    return unless @generated_linecount > @expected_linecount + 100
A return in the constructor feels weird to me.

2023-01-26 08:22 UTC, jorg-vr commented on app/helpers/renderers/text_differ.rb
> +    return unless @generated_linecount > @expected_linecount + 100
The constructor is also just a function...

This was also forced by our linter (Which prefers guard clauses over a regular if)

2023-01-26 09:02 UTC, chvp approved these changes

2023-01-26 09:09 UTC, bmesuere approved these changes

2023-01-26 11:27 UTC, niknetniko approved these changes

2023-01-26 12:54 UTC, merged