Limit the amount of users exposed by the repository admin screen
dodona-edu/dodona pull request #4382
Opened 2023-02-03 13:28 UTC by jorg-vr

This pull request stops the repository admin sceen from leaking all users.

All users can still be found by typing a specific enough query, but the full list is no longer loaded by default. This is a compromise between usability and privacy.

Results are only returned if at least three characters are used as filter, or if at most 5 users are returned.

![image](https://user-images.githubusercontent.com/21177904/216614675-6a6db5c4-0a80-48a1-8a7b-7e3c70e90949.png)
![image](https://user-images.githubusercontent.com/21177904/216614748-2dfe155e-8b7f-44bb-bd42-8c3cf1724708.png)

Part of #4362

2023-02-03 13:42 UTC, niknetniko approved these changes

2023-02-04 10:25 UTC, bmesuere requested changes
- I think we want a different empty state message when the page is loaded. It now says "Er werden te veel gebruikers gevonden. Gebruik de zoekbalk om de resultaten te filteren." but I didn't do anything yet. Something like "Enter at least x characters to search for users by first or last name" seems appropriate.
- If the list is truncated, "Er werden te veel gebruikers gevonden" seems strange. I would say explicitly that only the first few results are shown. Maybe also something like "Can't find who you're looking for? Try searching on their full name or filter by institution"
- The sort by length seems a bit strange/random on naos. I think we can just sort alphabetically now that we have an institution filter?

2023-02-04 10:25 UTC, bmesuere commented on app/controllers/users_controller.rb
> +    @users = @users.order_by_name_length(:asc).first(10)
the `params[:filter].nil? || params[:filter].length < 3` condition is duplicated and the magic number (10) is used twice.

2023-02-06 09:44 UTC, bmesuere approved these changes

2023-02-06 09:44 UTC, bmesuere commented on config/locales/views/users/en.yml
> +      too_many_results: "Only the first 10 results are shown. Can't find who you're looking for? Try searching on their full name or filter by institution."
```suggestion
      too_many_results: "Only the first 10 results are shown. Can't find who you're looking for? Try searching for their full name or filter by institution."
```

2023-02-06 09:44 UTC, bmesuere commented on db/schema.rb
>      t.index ["started", "user_id", "series_id"], name: "index_activity_statuses_on_started_and_user_id_and_series_id"
This was probably included by accident?

2023-02-06 10:16 UTC, niknetniko approved these changes

2023-02-07 10:20 UTC, merged