Fix/repo paper cuts
dodona-edu/dodona pull request #4383
Opened 2023-02-03 14:39 UTC by jorg-vr

This pull request
![image](https://user-images.githubusercontent.com/21177904/216630781-0a2d32ae-ade3-4eea-bf26-b55b6dba2f33.png)

Closes # .

2023-02-07 14:34 UTC, niknetniko approved these changes

2023-02-07 14:34 UTC, niknetniko commented on config/locales/models/en.yml
> +            not_accessible: The repository is not accessible for our git user. Please double check if you have given the correct permissions. Take notice that it might take a while before a github/gi
```suggestion
            not_accessible: The repository is not accessible for our git user. Please double check if you have given the correct permissions. Note that it might take a while before a GitHub/GitLab invitation is accepted by our team.
```

2023-02-07 14:34 UTC, niknetniko commented on config/locales/models/nl.yml
> +            not_accessible: De repository is niet toegankelijk voor onze git-gebruiker. Controleer of je de juiste permissies hebt ingesteld. Hou er rekening mee dat het even kan duren voor een githu
```suggestion
            not_accessible: De repository is niet toegankelijk voor onze git-gebruiker. Controleer of je de juiste permissies hebt ingesteld. Hou er rekening mee dat het even kan duren eer een uitnodiging voor GitHub/GitLab wordt geaccepteerd door ons team.
```

2023-02-08 07:55 UTC, bmesuere requested changes
I don't like the email solution either. Can't we just send an email to the address associated with the repo admin in this case? Since the repo has just been added by that user, using that address seems like a good fallback.

2023-02-08 07:55 UTC, bmesuere commented on config/locales/models/en.yml
> +            not_accessible: The repository is not accessible for our git user. Please double check if you have given the correct permissions. Note that it might take a while before a GitHub/GitLab in
```suggestion
            not_accessible: The repository is not accessible to our git user. Please double check that you have given the correct permissions. Note that it may take a while before a GitHub/GitLab invitation is accepted by our team.
```

Can we include a link to the docs here that explains the github/gitlab user thing?

2023-02-08 08:08 UTC, jorg-vr commented
the repo admin is only added after the repo is saved. 
Because cloning the repo is a delayed task, and it also takes some time to perform, this admin will almost always be added before the start of `process activities`.
However, this order of execution is not at all guaranteed and could result into bugs in some cases. (Most notably it causes this bug in our test environment where  deleyad_jobs are executed in order)

This was my first solution which I reverted because of a failing test. Do you want to continue with this approach? (In which case I would just remove the test because we know it will fail)

2023-02-08 08:11 UTC, bmesuere commented
In that case, maybe add dodona@ugent.be as ultimate fallback?

2023-02-08 15:45 UTC, bmesuere approved these changes

2023-02-08 15:52 UTC, merged