Allow responding to annotations in a thread
dodona-edu/dodona pull request #4404
Opened 2023-02-10 13:48 UTC by jorg-vr

This pull request

- [ ] Tests were added
- [ ] Documentation update can be found at dodona-edu/dodona-edu.github.io#

Closes #2827.

2023-03-13 13:47 UTC, niknetniko reviewed
Looks good and works fine for me.

A few small comments:
- The two icons don't seem aligned to me:
![image](https://user-images.githubusercontent.com/1756811/224711242-b1d5b8cc-5ae1-491e-a5ee-3f29d782de71.png)
- These don't seem to have the same size for me:
![image](https://user-images.githubusercontent.com/1756811/224711388-3ccffa0c-6d97-4cf4-a661-fd2324a0d4fd.png)
- The "hover" bubbles on the toggles seem to have both the bootstrap hover in English, and also the built-in one in Dutch:
![image](https://user-images.githubusercontent.com/1756811/224715081-027bda96-bd5b-4cd6-b8ad-ad7b6bb53961.png)

I am not 100% convinced hiding the options to edit, delete or save an annotation, as this reduces the number of buttons from 2 to 1 in most cases. Would it still be too cluttered if those buttons were also muted?

2023-03-13 13:47 UTC, niknetniko commented on tsconfig.json
> +    "module": "es2020",
Is this on purpose (just checking to make sure)?

2023-03-14 09:01 UTC, jorg-vr commented on tsconfig.json
> +    "module": "es2020",
this was intentional, because I used non es6 features to fix tests
But in the end I solved it in another way, so it's no longer required

2023-03-14 09:38 UTC, jorg-vr commented
> * The two icons don't seem aligned to me:
>       ![image](https://user-images.githubusercontent.com/1756811/224711242-b1d5b8cc-5ae1-491e-a5ee-3f29d782de71.png)

I agree that it does not look ideal, but this is due to different design choices of the mdi svg's: The circle and the rectangle are both center aligned. The bottom part of the comment icon makes it look misaligned. As these are rendered inline this is not easily fixed by css (And fixing it would require some very specific css margins). Unless others also find this important, I would leave it be

>  I am not 100% convinced hiding the options to edit, delete or save an annotation, as this reduces the number of buttons from 2 to 1 in most cases. Would it still be too cluttered if those buttons were also muted?

Three icons will be default for staff once the save button is rolled out. And I prefer this placement for the delete button (compared to inside the edit form or directly on the annotation)

2023-03-14 09:47 UTC, niknetniko commented
> As these are rendered inline this is not easily fixed by css (And fixing it would require some very specific css margins). Unless others also find this important, I would leave it be

Agree.

> Three icons will be default for staff once the save button is rolled out. And I prefer this placement for the delete button (compared to inside the edit form or directly on the annotation)

:+1:

2023-03-14 15:45 UTC, chvp commented on app/assets/javascripts/components/annotations/annotations_toggles.ts
> +                <div class="btn-group btn-toggle" role="group" aria-label="Annotaties" data-bs-toggle="buttons">
Untranslated string.

2023-03-14 15:45 UTC, chvp commented on app/assets/javascripts/components/annotations/user_annotation.ts
> +                                <d-new-saved-annotation
I would move this to the top of the dropdown.

2023-03-14 15:45 UTC, chvp commented on app/models/annotation.rb
> +    [thread_root, thread_root&.responses&.where('created_at < ?', created_at)].flatten.last
```suggestion
    [thread_root, thread_root&.responses&.where(created_at: ..created_at)].flatten.last
```

2023-03-14 15:45 UTC, chvp commented on app/models/question.rb
> +    return unless question_state == 'in_progress'
Is this tested? You have to be careful whether the deserialized object from the database is updated before this is executed (to be clear: I'm not sure whether this is the case).

2023-03-15 08:54 UTC, jorg-vr commented on app/models/annotation.rb
> +    [thread_root, thread_root&.responses&.where('created_at < ?', created_at)].flatten.last
Thanks for teaching me this notation :)

I looked it up, to better understand it: https://stackoverflow.com/a/23936233/7769243

It actually needs three dots (`.where(created_at: ...created_at)`) to correctly represent a `<`, your answer would result in a `<=` (Which would result in returning itself instead of the previous annotation)

2023-03-15 09:30 UTC, jorg-vr commented on app/models/question.rb
> +    return unless question_state == 'in_progress'
I have added extra tests for this (it works)

2023-03-15 10:54 UTC, niknetniko approved these changes

2023-03-22 09:10 UTC, chvp approved these changes

2023-03-23 09:24 UTC, bmesuere requested changes
(I know not all remarks are related to changes made in this PR)
---
<img width="731" alt="image" src="https://user-images.githubusercontent.com/481872/226884911-921c996a-3f80-444d-af95-e642f761872a.png">

- [x] The text below is a bit strange. `[Onze handleiding]() bevat meer informatie over het stellen van vragen`. The manual should also be updated to include threading.

---

<img width="748" alt="image" src="https://user-images.githubusercontent.com/481872/227154890-24f954b1-0e7a-4a75-b3d8-9026d495fe68.png">

- [ ] After asking a question, this is the result. My first reaction was that "Beantwoorden..." was a bit strange here because I just asked a question. Maybe it should say "Zelf beantwoorden..." in this case.

---
<img width="748" alt="image" src="https://user-images.githubusercontent.com/481872/227155667-55db51ae-4430-43b1-bc65-5845be7e2270.png">

- [x] If I clicked "als beantwoord markeren", this was the result which is not what I expected.
I would expect some kind of message below the question like "This question was marked as answered by xxx on xxx" and an explicit option to reopen de question.

If a question is answered by a teacher, the same UI is present for the student. I understand that from an internal perspective the question is "closed", but for a student the UI also feels a bit strange here. A teacher just answered your question and your option is "beantwoorden"

---

Question overview: the icons are a bit cryptic, so maybe use a bootstrap tooltip instead of the title tag? But maybe we can do better. The primary action by a large margin should now be to answer the question (and thus open the submission), so maybe a "split" text button where the primary action is answer and the other options are in the dropdown, or the combination of a text button and a "triple dot" overflow menu...

2023-03-23 13:11 UTC, jorg-vr commented on app/assets/javascripts/code_listing.ts
> +import { CodeListingRow } from "components/annotations/code_listing_row";
test

2023-03-23 13:21 UTC, jorg-vr commented
@bmesuere 

> After asking a question, this is the result. My first reaction was that "Beantwoorden..." was a bit strange here because I just asked a question. Maybe it should say "Zelf beantwoorden..." in this case.

I am not a fan of `zelf beantwoorden`, it gives no extra clarity compared to `beantwoorden`, where the actor is clearly implied. I would be willing to change it to the imparitive `beatwoord... of markeer als beantwoord`

I thought about using another word, but reply really is the default actions you take in a communication thread, event if the thread start is your own:
![image](https://user-images.githubusercontent.com/21177904/227216245-2f4a020d-8c70-4d66-9593-4153295ee75d.png)

2023-04-11 11:43 UTC, chvp approved these changes

2023-04-11 11:43 UTC, chvp commented on app/assets/javascripts/state/UserAnnotations.ts
> +        // this prevents inconsistencies questionstates being shown
```suggestion
        // this prevents inconsistent questionstates being shown
```

2023-04-11 12:06 UTC, merged