Fix comma's at the end of activity labels
dodona-edu/dodona pull request #4418
Opened 2023-02-16 19:18 UTC by freyavs

This pull request fixes the dynamic comma's in the activity labels list (e.g. in the exercices table).
![2023-02-16_20-13](https://user-images.githubusercontent.com/56410697/219465014-41f41b7e-760d-442b-ae4f-3fbe0c3192bb.png)

Closes #4220

2023-02-16 19:30 UTC, bmesuere requested changes
We try to avoid `raw`, especially with input coming from the user because of injection attacks.

In this case, I would use the original code, but replace the `each` with a `each_with_index `. You can then put a comma in front of the label name, except when the index is zero.

2023-02-23 13:31 UTC, jorg-vr approved these changes

2023-02-23 15:43 UTC, niknetniko requested changes

2023-02-23 15:43 UTC, niknetniko commented on app/views/activities/_labels.html.erb
> +      %><% end %>
Couldn't this be solved using something like this? To prevent the ugly comments hack

```suggestion
      <% labels.each_with_index do |label, index| %>
        <d-filter-button param="labels" value="<%= label.name %>" multi>
          <%= label.name %><%= index == labels.count - 1 ? "" : "," %>
        </d-filter-button>
      <% end %>
```

2023-02-26 12:45 UTC, freyavs commented on app/views/activities/_labels.html.erb
> +      %><% end %>
Yes actually that was the other way to avoid the problem, didn't know which one was cleaner. I'll apply this

2023-02-26 14:19 UTC, bmesuere approved these changes

2023-02-27 08:59 UTC, niknetniko approved these changes

2023-02-27 08:59 UTC, merged