Preload the latest submission in the editor on the activity show page
dodona-edu/dodona pull request #4485
Opened 2023-03-16 10:02 UTC by jorg-vr

This pull request preloads the latest submission in the code editor. When this happens, an allert is also edit that explains what happened and allows the user to restore the boilerplate.

![image](https://user-images.githubusercontent.com/21177904/225582761-9a4f04e0-4ee4-4c48-9751-94ad88bdf13c.png)
![image](https://user-images.githubusercontent.com/21177904/225582870-67e88dea-c580-4d5f-a1eb-6265cbc338ae.png)

Closes #2886

2023-03-19 14:46 UTC, bmesuere requested changes
Restoring now happens with a reload and a query string. It would be nicer for the user to do this with JS without reload.

2023-03-21 14:42 UTC, bmesuere requested changes
If you impersonate me on naos, You'll see an error on https://naos.dodona.be/nl/courses/2026/activities/1944243494/

The console logs
> caught SyntaxError: missing ) after argument list

2023-03-22 08:46 UTC, bmesuere approved these changes

2023-03-22 09:13 UTC, chvp approved these changes

2023-03-22 09:13 UTC, merged