Add copy code button to code fragments in descriptions
dodona-edu/dodona pull request #4488
Opened 2023-03-16 15:14 UTC by jorg-vr

This pull request adds a copy code button to code fragments in descriptions.

I matched on the `<code>` html tags in descriptions to match all logical cases. This tag is also correctly used by markdown.

![image](https://user-images.githubusercontent.com/21177904/225661618-965b2f2a-180b-48eb-9d4d-3f1a02d5a086.png)

- [ ] Tests were added

Closes #3532

2023-03-17 11:26 UTC, niknetniko requested changes
- For some reason it doesn't seem to work for me in Chrome (using version 111).
- The error message that appears is also not that useful I think ("Druk Ctrl-C om te kopiëren")
- Some (or most?) of the HTML problem statements don't use a `<code>` tag, only a `<pre>`, so they don't get a button.

2023-03-17 13:42 UTC, jorg-vr commented
> * For some reason it doesn't seem to work for me in Chrome (using version 111).

Fixed, it needed extra permissions because it is in an Iframe

> * The error message that appears is also not that useful I think ("Druk Ctrl-C om te kopiëren")

I now actually select the text if copying failed.

> * Some (or most?) of the HTML problem statements don't use a `<code>` tag, only a `<pre>`, so they don't get a button.

These problem statements do not follow the specification: https://docs.dodona.be/nl/references/exercise-description/#blokken-code Thus we cannot guarantee the layout.

I did update the matching form `code` to `pre code`, to avoid matching inline code

2023-03-17 15:53 UTC, niknetniko requested changes
Would it be an idea to trim the copied code? For example, when copying this code:
![image](https://user-images.githubusercontent.com/1756811/225954806-17d6b0be-0ff7-4069-b4d4-56d30136e7f5.png)
It will result in this being copied:
![image](https://user-images.githubusercontent.com/1756811/225954853-64d55445-505c-4028-b956-869778e02ffb.png)

Looks good otherwise.

2023-03-19 15:34 UTC, bmesuere requested changes
Something goes wrong with inline code. They are now rendered as a block:
Before:
![image](https://user-images.githubusercontent.com/481872/226186769-6e6754b3-a94f-4e00-99e2-8787094580b9.png)

After:
![image](https://user-images.githubusercontent.com/481872/226186790-04517f65-fad9-45f4-8eb4-0aa22a5d9b46.png)

The background of the "button" is transparent which causes un unwanted effect:
![image](https://user-images.githubusercontent.com/481872/226186863-17dee442-5e23-44cc-92d8-18f1356ceb75.png)

2023-03-20 09:52 UTC, jorg-vr commented
> Something goes wrong with inline code. They are now rendered as a block:

Forgot to push the fix for this

> Would it be an idea to trim the copied code?

That was an artifact of adding the copy button inside the codeblock. The copy button is now no longer included in the copied text. I prefer this solution to a trim, because leading and ending whitespace might be relevant in some code examples.

> The background of the "button" is transparent which causes un unwanted effect:

Fixed

2023-03-21 09:31 UTC, bmesuere approved these changes
Can we also replace the existing copy buttons by the new web component?

2023-03-21 09:31 UTC, bmesuere commented on app/assets/javascripts/components/copy_button.ts
> +@customElement("d-copy-button")
The "default" web component comments are missing here.

2023-03-21 10:44 UTC, merged