Refactor javascript statesystem
dodona-edu/dodona pull request #4530
Opened 2023-03-31 09:17 UTC by jorg-vr

This pull request

- [ ] Tests were added
- [ ] Documentation update can be found at dodona-edu/dodona-edu.github.io#

Closes # .

2023-04-06 13:38 UTC, niknetniko requested changes
Looks good in general, a fewer smaller nitpicks here and there.

I have two (larger) questions:
- (This is also a comment somewhere) Do we need the legacy decorator mode, or could we switch to TypeScript 5, which should [implement the modern decorators](https://devblogs.microsoft.com/typescript/announcing-typescript-5-0/#decorators).
- A double take to ensure we have not copied any code from `LitState`(https://www.npmjs.com/package/lit-element-state), as that library is LGPL3, which is annoying at best.

2023-04-06 13:38 UTC, niknetniko commented on app/assets/javascripts/components/annotations/annotations_cell.ts
> +import { UserAnnotationData, UserAnnotationFormData, userAnnotationState } from "state/UserAnnotations";
```suggestion
import { UserAnnotationFormData, userAnnotationState } from "state/UserAnnotations";
```

`UserAnnotationData` seems unused.

2023-04-07 08:18 UTC, jorg-vr commented
On Typescript:

The cause of the decorator issue is ts-jest. See https://github.com/kulshekhar/ts-jest/issues/1155
> Hi, if runtime react-native uses Babel, it won’t be possible to achieve the same behavior as ts-jest because ts-jest uses typescript compiler API. To achieve the same behavior as runtime, the only way is using only babel for ts transformation + tsc for typechecking.

I think the solution here would using only jest (not ts-jest), with babel compilation.
Right now the tests use the Typescript version of the code, while the browser uses the babel compiled version.

Moving to typescript 5 is also not possible. Because of ts-jest/lit. The types provided by lit still match the old typescript decorator types, which do not match with the new typescript definition. This causes ts-jest to throw errors...

2023-04-07 09:43 UTC, jorg-vr commented
- [ ] reminder for me to double check page changes when the queryParams get reset (a map clear happens)

2023-04-11 08:50 UTC, jorg-vr commented
On copying code from [litState](https://www.npmjs.com/package/lit-element-state):
I went through the code again. The greatest match was the staterecorder, which I have now given a rewrite to improve the quality. Eg. using Set instead of arrays and avoiding carrying around null pointers.

I think right now we have deviated enough of the original implementation to avoid any copyright infringements.

2023-04-11 08:59 UTC, bmesuere approved these changes
nice job! I prefer this style over the previous one. It is much clearer that you are calling state functions now in the component classes.

2023-04-12 07:47 UTC, niknetniko approved these changes

2023-04-12 07:47 UTC, merged