Render machine annotations for multiple lines or columns
dodona-edu/dodona pull request #4568
Opened 2023-04-14 07:41 UTC by jorg-vr

This pull request renders machine annotations more precisely if the judge provided the optional parameters.

This is a first step towards more precise human annotations.
I started with machine annotations as there is less code involved and it can help to test designs already.

- [ ] Tests were added
- [ ] Documentation update can be found at dodona-edu/dodona-edu.github.io#

Closes # .

2023-04-20 14:07 UTC, bmesuere requested changes
This looks very promising! Some quick (and incomplete) feedback:

- [x] I would still show all linting comments by default for the "student view" and only "hide" them if there is at least 1 manual comment/question. Maybe hiding them during grading might also be the right approach, but @chvp is better positioned to answer that question.
- [x] When showing all annotations, the tooltips are still enabled which should not be the case I think?
- [x] The order in the tooltips is different then when shown normally e.g.: line 21 on https://naos.ugent.be/nl/submissions/13036445/ In the tooltip, the info remark is shown in the top, but in the inline view it is shown at the bottom.

2023-04-20 14:16 UTC, niknetniko approved these changes

2023-04-24 13:58 UTC, bmesuere approved these changes

2023-04-24 14:19 UTC, merged

2023-04-24 14:46 UTC, pdawyndt commented
This is how the wave underline looks for me (Chrome, Windows 10):

![image](https://user-images.githubusercontent.com/5736113/234032372-dbf9735b-39cf-4f2f-92e8-2bac1c3d5230.png)