Allow creation of user annotations based on a selection
dodona-edu/dodona pull request #4596
Opened 2023-04-25 12:03 UTC by jorg-vr

This pull request

- [ ] Tests were added
- [ ] Documentation update can be found at dodona-edu/dodona-edu.github.io#

Closes # .

2023-05-04 15:48 UTC, chvp requested changes
- [x] Not sure if new, but the badge for annotation count is always shown, even when it's 0: ![screenshot_2023-05-04-171835](https://user-images.githubusercontent.com/42220376/236259854-99db27fa-0045-4807-ba61-5b1aeec822bc.png)

- [x] I would add some sort of background to the add button, the text overlapping the border looks weird to me.
![screenshot_2023-05-04-172047](https://user-images.githubusercontent.com/42220376/236259859-4239bd29-adf0-4ad2-8de2-e40d9ecbc136.png)

2023-05-04 15:48 UTC, chvp commented on app/assets/javascripts/state/UserAnnotations.ts
> +            const line = annotation.line_nr + annotation.rows - 1 ?? 0;
Does this still work with the nullish coalescing?

2023-05-04 17:40 UTC, pdawyndt commented
What is the reasoning to snap selections that run across multiple lines to whole lines?

2023-05-05 08:36 UTC, jorg-vr commented
@pdawyndt this was requested by @bmesuere 

The reasoning was that this would make it a lot faster to select whole lines, which in Bart's opinion would be the most common use case.
We also could not think of any use case for a range spanning multiple lines with an exact end and starting point.

If people with more experience grading have a different opinion on this, I am willing to change this.

2023-05-05 09:53 UTC, jorg-vr commented
I used the elevated button style, is this better @chvp?
![image](https://user-images.githubusercontent.com/21177904/236427813-b7168c86-2d34-4cbb-b14d-b350e9ee42b6.png)
![image](https://user-images.githubusercontent.com/21177904/236427834-1211d392-09b8-431c-b274-dd1a765b8b1f.png)
![image](https://user-images.githubusercontent.com/21177904/236427852-f44e3fc1-fe10-4e31-8bb2-5f117fbbe9e0.png)
![image](https://user-images.githubusercontent.com/21177904/236427868-4bee50f2-df91-4326-b141-6f463e408fcc.png)

2023-05-06 11:42 UTC, chvp approved these changes

2023-05-09 14:25 UTC, bmesuere requested changes
- [x] Regarding the button: why not make this a proper [FAB](https://m3.material.io/components/extended-fab/overview)? The collapsed version could then expand on mouseover instead of the tooltip now.

- [ ] Would it be possible to also drag the button to select lines? Drag release would then automatically trigger the button click which would be the fasted way to add a multi line comment: big click target to start drag, drag a few lines, release and directly start typing.

- [ ] The background color while selecting is ok, but seems a bit strange after adding the comment. For comments of a substring, I would expect it to mimic the curly underline of the linting comments. For single or multi-line comments it seems very prominent. Alternatives: show something in the margin or show no formatting in the code but add a "comment on line x" "comment on line x to y" to the top of the comment (which is what gitlab does). Mouseover on the line(s) or comment could then show the range using a  bg-color.

2023-05-16 18:29 UTC, bmesuere requested changes
looks good, some nitpicks:
- [ ] I think it will look better if you keep the icon left and put the text on the left. Maybe a little css transition to expand the button will also help with the smoothness
- [ ] on mouse over, the button in slightly darker (in light mode), however, the little arrow stays in the base color
- [ ] dragging the FAB doesn't work for me (chrome). I can drag the button (both in x- and y-direction, where I would expect the x-position to be locked), but when I release it, the button is gone and no form appears. In addition, the button also doesn't show up when I hover over the code. There is no error in the console.
- the default line highlights look more subtle now, well done! 
- the darker  highlight on mouse over is also very nice!

2023-05-16 18:43 UTC, bmesuere commented
Maybe we can move the button drag behaviour to a later PR to be able to make a release tomorrow.

2023-05-17 08:01 UTC, jorg-vr commented
@bmesuere I did not add the transition because I use the display properties right now got the button change, which don't work with css transitions.
For transitions I would need to use something like visibility, but this would also require a rework of the html structuring and some nit picky positioning. 

I will work on this after the release if desired.

2023-05-17 10:03 UTC, niknetniko approved these changes

2023-05-17 11:21 UTC, merged