modal.js: remove jquery and convert to typescript
dodona-edu/dodona pull request #4618
Opened 2023-05-05 16:53 UTC by freyavs

This pull request removes all jquery from modal.js and converts it to typescript.

Progress on #3590

2023-07-28 07:31 UTC, jorg-vr approved these changes

2023-07-28 08:40 UTC, bmesuere reviewed
The CodeQL warnings seem to be valid concerns. @jorg-vr do you know if we need to be able to inject html into these?

2023-07-28 08:48 UTC, jorg-vr commented
Looking at the three usecases it should support html. (all usecases are for pythia submissions)
But one case has user input in the template string (a filename, chosen by a teacher, is used in the title), thus we best improve the safety of the method

Might be best to use the `render` function from `lit`

Eg `render(title, document.querySelector("#info-modal .modal-title"))`
The title and content arguments will have to be of type `TemplateResult | string`
And usages of the function could use `html\`\`` to generate template strings, which will make sure everything is safe

2023-07-28 09:42 UTC, niknetniko requested changes

2023-07-28 09:42 UTC, niknetniko commented on app/assets/javascripts/modal.ts
> +    if (options && options.allowFullscreen) {
```suggestion
    if (options?.allowFullscreen) {
```

2023-07-28 09:42 UTC, niknetniko commented on app/assets/javascripts/modal.ts
> +    document.querySelector("#info-modal .modal-body").innerHTML = `<p>${content}</p>`;
Looking at the usage of this function, we should probably remove the `<p>` tags. Most content we pass is wrapped in a `<div>`, which is not allowed inside a `<p>` tag.

2023-08-01 07:18 UTC, jorg-vr approved these changes

2023-08-01 07:23 UTC, bmesuere approved these changes

2023-08-01 09:23 UTC, niknetniko approved these changes

2023-08-01 09:32 UTC, jorg-vr approved these changes

2023-08-01 09:32 UTC, merged