Allow creating multiline annotations by draging the create button
dodona-edu/dodona pull request #4643
Opened 2023-05-17 09:41 UTC by jorg-vr

This pull request

- [ ] Tests were added
- [ ] Documentation update can be found at dodona-edu/dodona-edu.github.io#

Closes # .

2023-05-22 15:35 UTC, niknetniko reviewed
It might be on my machine, but on a submission with a lot of multi-line annotations, the drag button gets kind of laggy: the highlight lags behind significantly when dragging the button wildly on the page (but this is no issue if there are no annotations).

2023-05-22 15:35 UTC, niknetniko commented on app/assets/javascripts/components/annotations/code_listing_row.ts
> +        if ( origin > this.row ) {
```suggestion
        if (origin > this.row) {
```

2023-05-22 15:35 UTC, niknetniko commented on app/assets/javascripts/components/annotations/create_annotation_button.ts
> +        await new Promise(resolve => setTimeout(resolve, 10));
Is there no better way to do this? "Randomly" waiting 10 ms seems like an ugly hack

2023-05-24 12:01 UTC, jorg-vr commented on app/assets/javascripts/components/annotations/create_annotation_button.ts
> +        await new Promise(resolve => setTimeout(resolve, 10));
There aren't many good solutions: https://stackoverflow.com/questions/36379184/html5-draggable-hide-original-element

But I've updated it to use the drag event instead. (This will trigger multiple times, but that's less of an issue as its first trigger is after the image has been rendered)

2023-05-24 12:06 UTC, jorg-vr commented
@niknetniko the behavior is never unexpected for me. Wildly dragging around also doesn't really seem like a use case we should support

![Peek 2023-05-24 14-03](https://github.com/dodona-edu/dodona/assets/21177904/fa0d6684-9141-4f55-9925-ab0c757401ba)

2023-05-24 14:37 UTC, niknetniko approved these changes

2023-06-06 17:53 UTC, bmesuere requested changes
Sorry, I forgot about this PR due to the large number of dependabots.

- [ ] When moving the mouse where the button appears (while not dragging), there's a flicker effect. Maybe this can be solved by a slight delay?
[Echo---Dodona.webm](https://github.com/dodona-edu/dodona/assets/481872/4a2ef742-651c-4a9e-9cde-8b3f952eb775)

- [ ] While dragging, the button you drag is clipped to tight. This means the drop shadow has a hard cutoff.

- [ ] I'm still not a fan that you can drag the button over the entire page instead of only the vertical direction.

- [ ] If you drag a bunch of lines like this and release, the editor is opened (which is expected). However, if nothing it typed in the text area and click somewhere on the page, I would expect the section (and text area) to close.

2023-06-06 17:56 UTC, bmesuere commented
I've been thinking more about my last remark. I think what actually bugs me is that when de editor is open (multi-line or other), you can't add a new comment/selection. I don't think opening multiple input forms is the way to go, but maybe "cancel" the previous one if the input area is empty?

2023-06-07 07:43 UTC, jorg-vr commented
On not allowing to drag the button over the whole page:
Do you prefer the github method? (no drag image and a different pointer icon)
https://github.com/dodona-edu/dodona/assets/21177904/94991b99-8c80-406b-a441-74e8b1e6a112

2023-06-07 11:19 UTC, bmesuere commented
I think that it would probably offer a less confusing experience. Being able to drag a button over the entire screen is not a common UI pattern and users might experience this as a bug.

2023-06-07 14:02 UTC, jorg-vr commented
I fixed everything except changing the cursor while dragging. After three hours of trying to do this I gave up. 
I think the only viable solution would be not using the `draggable` api, but manually listening to pointer moves. But this would make the code a lot worse for a minor feature.

It is rather frustrating as github proves that it is possible, but non of the stackoverflow examples on how to achieve this work.

2023-06-08 12:08 UTC, bmesuere requested changes
sorry for nitpicking.

-  [x] The slight delay fixes the flickering, but the underlying problem isn't fixed: when hovering over a line, the comment button expands with an animation. When hovering over a different line, the button is small again and restarts the animation. I would expect that it stays expanded. In addition, if you for example click a single word, you see the button expanding (good), if you then doubleclick a different word on another line, you first see the small button which then expands.
- [x] The auto-dismiss of an empty comment is too fast. It already dismisses on drag start instead of when a new form should appear. This causes layout shifts. In addition, you can now  trigger the opening of a new form, but the button isn't shown.
- [ ] When dragging and releasing a few lines of code, there is a noticeable delay between releasing and the editor opening.
- [x] The "ask a question about your code" button on top of the code is not very button-like. Maybe change the button style to have an outline? Or add the question icon from the fab?

2023-07-12 11:09 UTC, bmesuere requested changes
There is still a bit of delay between releasing the button and the form appearing. I think this is the time that is usually spent while showing an animation where the "dragimage" moves back to its original position. When testing this with https://park.glitch.me/, it seems like the animation only plays when the item is released outside of a droptarget.

In the demo mentioned above, I see that the original image is visible during dragging (in addition to the image that is shown next to the pointer). Can we also do this in our example? potentially with modified button text "release to add comment" or so?

Is the expand/collapse delay still needed with the new solution?

2023-07-14 08:11 UTC, jorg-vr commented on app/assets/javascripts/code_listing.ts
> +}
I moved this and the above code to `annotation_form.ts` and rewrote it there.

2023-07-14 08:19 UTC, jorg-vr commented on app/assets/javascripts/components/annotations/code_listing_row.ts
>          const annotationsToMark = [...this.userAnnotationsToMark, ...this.machineAnnotationsToMark].sort(compareAnnotationOrders);
I'll handle this in #4821 where I am working on improving performance

2023-07-15 08:48 UTC, bmesuere commented
As an FYI for the rest, @jorg-vr and I sat together and did a thorough review of the code. The main thing that came up was that a lot of the performance issues are due to the squiggly lines which need to be applied to existing syntax-highlighted html. The solution we came up with is using a page from GitHub's playbook but the other way around: we will render a second version of the code (or spaces for that matter) above the current code. This second layer will not be visible to users, but will serve as the anchor to apply the squiggly lines and tooltips on. This change will be implemented in a later PR.

Other changes we discussed will simplify the code, improve the naming of the variables and better encapsulate certain implementation details that are now leaking.

2023-07-24 08:03 UTC, jorg-vr commented on app/assets/javascripts/components/annotations/create_annotation_button.ts
>      get addAnnotationTitle(): string {
'title' was not a valid option as this would overwrite html element functions
Renamed to "buttonText"

2023-07-24 11:38 UTC, jorg-vr commented
@bmesuere The discussed changes are applied.
I'll wait for this pr to be merged to work on redoing the marking

2023-07-25 07:17 UTC, merged