Update annotation form
dodona-edu/dodona pull request #4701
Opened 2023-06-01 12:54 UTC by jorg-vr

This pull request

- [ ] Tests were added
- [ ] Documentation update can be found at dodona-edu/dodona-edu.github.io#

Closes # .

2023-08-04 07:07 UTC, bmesuere requested changes
Feedback from running this on metra:
- [x] the hover button text shows ask question instead of add comment (the global button does show add comment)
- [x] if there are no saved annotations, the area to the right of the textarea is left blank. I would add an empty state there or show the textarea full width.
- [x] if you check "save annotation", the title form is shown to the right of the text area. This somewhat breaks the flow. Maybe placing it inline after the checkbox + save annotation text would make more sense?
- [ ] ~~when save annotation is checked, it would make sense to change the text on the submit button to also say something that hints that the annotation will be saved.~~
- [x] the help text under the "search for annotations" combobox is too long (at least in Dutch)
- [x] in the search annotations input, the list of suggestions is not the same width as the text input
- [ ] in the search annotations input, the list of suggestions "flickers" when searching
- [x] when picking a suggestion, the "save annotation" checkbox is disabled, but it is also shown as checked which might be confusion. Maybe replace it with a link to the page where you can edit that annotation?
- [x] when loading a saved annotation and then changing the text, a "not equals" sign is shown in the search annotation input. The icon is not aligned well (shown somewhere in the middle of the input field)

2023-08-04 12:13 UTC, jorg-vr commented
> when picking a suggestion, the "save annotation" checkbox is disabled, but it is also shown as checked which might be confusion. Maybe replace it with a link to the page where you can edit that annotation?

This page does not exist yet (It is a modal currently)
I will just hide the checkbox for now and reintroduce that link when that page is created.
Added this note in https://github.com/dodona-edu/dodona/issues/4564

2023-08-04 12:40 UTC, jorg-vr commented
> when save annotation is checked, it would make sense to change the text on the submit button to also say something that hints that the annotation will be saved.

I am not the biggest fan of this. I find it hard to come up with better wording for the button. A longer text is also makes it harder to properly layout the buttons (as they are on the same line as the checkbox currently)

The checkbox is also right next to the button, so the information is already provided on almost the same place

2023-08-04 13:43 UTC, jorg-vr commented
>  the help text under the "search for annotations" combobox is too long (at least in Dutch)

I removed `Saved annotations are automatically filtered by course and exercise. `
This will change in version 2 anyway

2023-08-09 09:53 UTC, niknetniko approved these changes

2023-08-14 12:15 UTC, bmesuere requested changes
- [x] The wording of "sla opmerking op om te hergebruiken" is quite verbose. Maybe make it "Opmerking opslaan" (maybe with an info icon with tooltip?). This would also help with my previous comment that it wasn't really clear that the comment would also be save when clicking the submit button
-  [ ] The "Titel:" label is a bit strange. Maybe [floating labels](https://getbootstrap.com/docs/5.3/forms/floating-labels/) are an option here?
- [x] Upon clicking "sla opmerking op", the titel input should get the focus
- [ ] On smaller screens, the form layout isn't optimal:
  ![image](https://github.com/dodona-edu/dodona/assets/481872/644f0dc2-0f97-4567-bdc5-87d2f9a4f8f3)

2023-08-16 09:02 UTC, jorg-vr commented
> The "Titel:" label is a bit strange. Maybe [floating labels](https://getbootstrap.com/docs/5.3/forms/floating-labels/) are an option here?

The floating labels don't work for our inputs, as we have a lot less vertical padding compared to the bootstrap default. Thus their is no vertical space for a label inside the input, without making the input look comically large compared to others.

I did make some custom styling based on the bootstrap css to put the label inside the input before the typing area 
![image](https://github.com/dodona-edu/dodona/assets/21177904/2c59fba8-61ab-40e3-b670-de5fb974a664)

2023-08-16 12:47 UTC, bmesuere approved these changes
There's a JS error on mestra when signed in as staff. Otherwise, looks good 👍

2023-08-16 12:47 UTC, bmesuere commented on app/assets/stylesheets/components/code_listing.css.scss
> +        top: 0;
```suggestion
        top: 1px;
```

In my Chrome, the label was not aligned with the textbox text.

2023-08-16 12:47 UTC, bmesuere commented on app/assets/javascripts/components/annotations/annotation_form.ts
> +            this.titleRef.value.focus();
I would also call `select()` here: https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/select

2023-08-16 13:08 UTC, merged