Unify css with bootstrap themes
dodona-edu/dodona pull request #4745
Opened 2023-06-08 10:27 UTC by jorg-vr

This pull request removes the separate dark mode css file. It is replaced by the new bootstrap 5.3 css theming.

A new js theme picker is also added, supporting, darkmode, lightmode and auto. This more general approach will allow more themes in the future.

Changes:
- [x] Rewrite js theme selection logic
- [x] Rename toggle_dark_mode to set_theme
- [x] Remove application_dark.scss
- [ ] Use css variables instead of sass variables everywhere
- [ ] Set correct variables for newly introduced bootstrap scss variables

Closes # .

2023-07-06 09:00 UTC, chvp requested changes
Some differences I noticed. Dodona on the left, naos on the right.

![screenshot_2023-07-06-100519](https://github.com/dodona-edu/dodona/assets/42220376/9fe3e5d9-b05e-4157-9206-29bb15ba04b5)
Color of "Nog niet opgelost".

![screenshot_2023-07-06-100944](https://github.com/dodona-edu/dodona/assets/42220376/32fefe27-1470-4e47-b406-b354b6356769)
Same color issue.
![screenshot_2023-07-06-101908](https://github.com/dodona-edu/dodona/assets/42220376/db93f727-ba74-48f4-98b1-49176d67a730)
There is more padding in the scrollspy on the right of a course.

These same issues exist in dark mode.

2023-07-06 09:00 UTC, chvp commented on app/views/announcements/edit.html.erb
> +          <%= link_to @announcement, method: :delete, data: { confirm: t("general.are_you_sure") }, class: "btn btn-filled with-icon  d-btn-danger" do %>
```suggestion
          <%= link_to @announcement, method: :delete, data: { confirm: t("general.are_you_sure") }, class: "btn btn-filled with-icon d-btn-danger" do %>
```

2023-07-06 09:00 UTC, chvp commented on app/controllers/pages_controller.rb
> +    session[:theme] = params[:theme].nil? ? 'auto' : ActiveModel::Type::String.new.cast(params[:theme])
Do we want to do validation of the options here? The string cast isn't necessary, params are strings by default.

2023-07-07 08:46 UTC, jorg-vr commented
`.text-muted` (eg niet opgelost)  still used bootstrap default color `#6c757d` which was not part of our color theme
 I replaced it with $gray-50 in both light and dark mode (which looks similar)
 I could also use $on-surface-muted which follows the m3 specs, but is a lot less muted.
 
$gray-50
![image](https://github.com/dodona-edu/dodona/assets/21177904/89f0b8d1-b624-49e3-a8df-8a82ef8a0bfb)

$on-surface-muted
![image](https://github.com/dodona-edu/dodona/assets/21177904/89ab4b28-cf17-4c2d-9cb9-337176c22a86)

Old: `#6c757d`
![image](https://github.com/dodona-edu/dodona/assets/21177904/0d101b2c-4676-45b2-be05-11f12ff59e9c)

2023-07-12 09:02 UTC, bmesuere requested changes
👍 nice work. This removes a few scss hacks and unifies our variables to css.

Some remarks:
- [x] I would not add a theme menu in the main navigation bar and instead make it a sub menu in the current user menu.
- [ ] The contrast of the selected option isn't great. The text should be white here (as is the case with the year selector on the signed in home page)
  ![image](https://github.com/dodona-edu/dodona/assets/481872/5c6deab0-eeb3-43a5-9656-92af3659f8b3)
- [ ] I found it odd that the icon for auto displayed the current state. Maybe use https://pictogrammers.com/library/mdi/icon/theme-light-dark/ ?
- [x] Is there a reason why the icons are inlined?
- [ ] The sign in page looks bad in dark mode due to the icons. Should we disable dark mode here?
- [ ] Why do we store theme in the session? (I know you didn't change this, just asking the question) I would make it entirely client side (and thus use local storage) or store it in the database as a user setting. If we store it in the database, we could also add the option to the profile page.
- [ ] The theme controller call should be excluded from being "stored". If you go to the sign in page, then switch themes and then sign in, you are redirected to /theme which doesn't exist.

2023-07-13 12:39 UTC, jorg-vr commented on app/assets/javascripts/heatmap.ts
> +    const darkMode = themeState.theme === "dark";
I have instead removed the hardcoded colors by using the css variables in javascript

2023-07-28 11:55 UTC, bmesuere approved these changes
- label for dark mode in menu
- always light mode when not signed in

2023-07-31 08:25 UTC, chvp approved these changes

2023-07-31 08:49 UTC, merged