Create overlay layer for marking annotations in code
dodona-edu/dodona pull request #4846
Opened 2023-07-25 11:30 UTC by jorg-vr

This pull request

- [ ] Tests were added
- [ ] Documentation update can be found at dodona-edu/dodona-edu.github.io#

Closes # .

2023-07-27 13:10 UTC, bmesuere requested changes
👍 looks good. I propose we go over this together once you're back in Ghent.

2023-07-27 13:10 UTC, bmesuere commented on app/assets/javascripts/components/annotations/code_listing_row.ts
> +                    <d-code-layers .row=${this.row} .renderedCode=${this.renderedCode}></d-code-layers>
Is "code-layers" the best name for this component? The layer part is an implementation detail and shouldn't be relevant here. Maybe code-listing is better?

2023-07-27 13:10 UTC, bmesuere commented on app/assets/javascripts/components/annotations/selection_layer.ts
> +        }</pre>`;
Is there a reason for the empty span and the strange indentation? The opening `${` tags are on the end of the previous line instead of the beginning.

2023-07-27 13:18 UTC, jorg-vr commented on app/assets/javascripts/components/annotations/selection_layer.ts
> +        }</pre>`;
empty span is a hack. If the `<pre>` is empty it's height slightly deviates from a `pre` element with content. I found that adding an empty span resolves this problem. I have not yet found another better solution. (can't set a fixed height because because it could span multiple lines. And line height is already set, but ignored when empty)
I should probably add that as a comment

The `${` start on different lines to be able to split this code in multiple lines. Within the `<pre>` tag every space in the html is rendered (as expected for code rendering). Spaces and line breaks within `${` are ignored as that part is parsed as javascript

2023-07-27 14:11 UTC, jorg-vr commented on app/assets/stylesheets/components/code_listing.css.scss
> +        }
I have grouped the css. But I am not really a fan of the result as it has become less readable and only three lines shorter (Most things are only common for three out of four classes, with always different sets of three)

2023-07-31 08:37 UTC, chvp requested changes
There's something wrong with the rendering in my Firefox: ![screenshot_2023-07-31-103231](https://github.com/dodona-edu/dodona/assets/42220376/cbb38c5f-f8ee-4a70-a417-14d0856edc79)

2023-07-31 11:16 UTC, chvp requested changes
The styling of the code is not monospace.

2023-07-31 11:30 UTC, jorg-vr commented
That was a bug from #4745, fixed now

2023-07-31 11:38 UTC, chvp approved these changes

2023-07-31 12:14 UTC, bmesuere approved these changes

2023-07-31 12:17 UTC, merged