Prevent crash on series creation without course
dodona-edu/dodona pull request #4848
Opened 2023-07-28 09:27 UTC by bmesuere

Reverts dodona-edu/dodona#4617 because of the comment in https://github.com/dodona-edu/dodona/pull/4617#discussion_r1277311420

2023-07-29 14:06 UTC, freyavs commented
just for info and checking if this is okay: by authorizing on series the error is now 422 `"course": ["must exist"]`

2023-07-31 07:49 UTC, jorg-vr approved these changes

2023-07-31 07:50 UTC, jorg-vr commented
You could maybe leave the test (Without the text check)

2023-07-31 09:37 UTC, niknetniko requested changes

2023-07-31 09:37 UTC, niknetniko commented on app/controllers/series_controller.rb
> +    authorize @series, :create?
```suggestion
    authorize @series
```

If you don't pass the second parameter, it is inferred from the action's name (in this case we are in the `create` action of the controller, so it should infer `create?`.

2023-08-01 09:07 UTC, merged