util.js: remove jquery and convert to typescript
dodona-edu/dodona pull request #4849
Opened 2023-07-30 14:46 UTC by freyavs

2023-08-02 07:33 UTC, jorg-vr requested changes
Looks good, some minor changes requested in the comments.

The copy button code will probably be removed in this issue  #4499. So no need to work on it further now

2023-08-02 07:33 UTC, jorg-vr commented on app/assets/javascripts/utilities.ts
> +        timer = window.setTimeout(callback, ms);
why is this change needed?

2023-08-02 07:33 UTC, jorg-vr commented on app/assets/javascripts/utilities.ts
> +// TODO: remove?
I think you should double check if we still use jquery to make ajax requests (I guess not after all your changes) And then indeed remove this function.

2023-08-02 07:42 UTC, bmesuere commented on app/assets/javascripts/utilities.ts
> +function getArrayURLParameter(name: string, _url: string): string[] {
I think url is optional here as well?

2023-08-02 07:55 UTC, jorg-vr commented on app/assets/javascripts/utilities.ts
>  const delay = createDelayer();
Using this global function could indeed lead to unexpected consequences. (I experienced that in practice and always use createDelayer since that experience)

I would indeed prefer a version of the debounce that can take a function as argument directly and keeps the same function signature as the original.
I am not sure if the signature of the result will exactly match the original (the way they use `this` as an argument makes me unsure, but maybe that is syntax I don't know)

2023-08-02 08:02 UTC, jorg-vr commented on app/assets/javascripts/utilities.ts
> +        document.querySelector("#time-zone-warning").classList.remove("hidden");
I do not see why it is a philosophical question?

I do think throwing an exception here is valid, as the warning not existing would be unexpected.

2023-08-02 08:17 UTC, jorg-vr commented on app/assets/javascripts/utilities.ts
>      return String(str).replace(/[&<>"'`=/]/g, function (s) {
This is my mistake. The only usecase is
```javascript
html`${unsafeHTML(htmlEncode(s).replace(new RegExp(this.filter, "gi"), m => `<b>${m}</b>`))}`
```
I'll rewrite it avoiding the unsafeHTML and the htmlEncode

2023-08-02 08:44 UTC, jorg-vr commented on app/assets/javascripts/utilities.ts
>      return String(str).replace(/[&<>"'`=/]/g, function (s) {
Removed this function in #4861

2023-08-02 09:17 UTC, jorg-vr commented on app/assets/javascripts/utilities.ts
>  const delay = createDelayer();
If we swap implementation, i would prefer something like the typescript function here: https://stackoverflow.com/a/54265129/7769243

It keeps function signature, replacing the return type by a promise (Which will be resolved for the executed function and canceled for all others)

2023-08-02 09:53 UTC, niknetniko approved these changes
No other remarks from me

2023-08-03 06:14 UTC, bmesuere commented on app/assets/javascripts/utilities.ts
> +        document.querySelector("#time-zone-warning").classList.remove("hidden");
I agree that this is probably what we want, but it is a change in behaviour. It could well be that some (similar) cases were previously failing silently and are now causing the website to break.

Suggestions for better client side error logging are thus very welcome.

2023-08-03 06:58 UTC, jorg-vr commented on app/assets/javascripts/utilities.ts
>  const delay = createDelayer();
moved to separate issue ##4863

2023-08-04 06:22 UTC, bmesuere approved these changes

2023-08-04 10:21 UTC, jorg-vr approved these changes

2023-08-04 10:21 UTC, merged