question_table.ts: remove jquery
dodona-edu/dodona pull request #4850
Opened 2023-07-30 16:32 UTC by freyavs

This pull request removes jQuery from question_table.ts

This is progress on #3590

2023-07-31 09:41 UTC, bmesuere approved these changes

2023-07-31 09:43 UTC, niknetniko approved these changes

2023-07-31 09:44 UTC, jorg-vr requested changes

2023-07-31 09:44 UTC, jorg-vr commented on app/assets/javascripts/question_table.ts
>          fetch(this.getRefreshUrl(), {
It would be better to use the fetch function from util here. This function already sets some of the headers that we need for every request, which avoids duplication

2023-08-01 07:16 UTC, jorg-vr approved these changes

2023-08-01 07:16 UTC, merged