Create separate show and edit page for saved-annotations
dodona-edu/dodona pull request #4885
Opened 2023-08-10 13:08 UTC by jorg-vr

This pull request

- [ ] Tests were added
- [ ] Documentation update can be found at dodona-edu/dodona-edu.github.io#

Closes # .

2023-08-14 12:46 UTC, bmesuere requested changes
- On the show page, the annotation data is listed as key value pairs which is a bit plain. Can't we make it a sentence? This annotation was use **x** times in the **Visualisation Test** course for the **Curling** exercise. The annotation itself could be formatted as a quote or callout or something like that.
- The table title is "linked annotations", shouldn't that be linked submissions?
- Maybe open the linked submissions in a new tab?
- On the save annotation index (not edited here) in the first column, the "1 keer gebruikt" text is wrapped in `p` tags which adds unnecessary bottom margin. This can probably be a div.

2023-08-16 09:45 UTC, niknetniko requested changes

2023-08-16 09:45 UTC, niknetniko commented on app/views/saved_annotations/edit.html.erb
> +        <%= form_for(@saved_annotation, :html => {:class => 'form-horizontal'}) do |f| %>
```suggestion
        <%= form_for(@saved_annotation, html: { class: 'form-horizontal' }) do |f| %>
```

2023-08-16 09:45 UTC, niknetniko commented on app/views/saved_annotations/edit.html.erb
> +              <h4><%= t('errors.validation_errors', :count => @saved_annotation.errors.count) %></h4>
```suggestion
              <h4><%= t('errors.validation_errors', count: @saved_annotation.errors.count) %></h4>
```

2023-08-16 09:45 UTC, niknetniko commented on app/views/saved_annotations/edit.html.erb
> +            <%= f.label :title, :class => "col-sm-3 col-form-label" %>
```suggestion
            <%= f.label :title, class: "col-sm-3 col-form-label" %>
```

2023-08-16 09:45 UTC, niknetniko commented on app/views/saved_annotations/edit.html.erb
> +            <%= f.label :annotation_text, :class => "col-sm-3 col-form-label" %>
```suggestion
            <%= f.label :annotation_text, class: "col-sm-3 col-form-label" %>
```

2023-08-16 09:45 UTC, niknetniko commented on app/controllers/saved_annotations_controller.rb
>    def index
While we are working on these pages, we might also want to set `@title`, so we get `Opgeslagen opmerkingen - Dodona` instead of `Dodona` in the title bar (the same thing can be done for the other pages, show and edit)

2023-08-16 12:31 UTC, bmesuere approved these changes

2023-08-16 12:31 UTC, bmesuere commented on config/locales/views/saved_annotations/nl.yml
> +      linked_submissions: Gekoppelde indieningen
```suggestion
      linked_submissions: Gekoppelde oplossingen
```

I think we use "oplossingen" or "ingediende oplossingen", but never "indieningen" on Dodona.

2023-08-16 12:31 UTC, bmesuere commented on config/locales/views/saved_annotations/nl.yml
> +      usage_info_html: Deze opmerking kan worden hergebruikt op alle indieningen voor de oefening <a href="%{exercise_path}">%{exercise_name}</a> in de cursus <a href="%{course_path}">%{course_name}<
```suggestion
      usage_info_html: Deze opmerking kan worden hergebruikt op alle ingediende oplossingen voor de oefening <a href="%{exercise_path}">%{exercise_name}</a> in de cursus <a href="%{course_path}">%{course_name}</a>.
```

2023-08-16 12:31 UTC, bmesuere commented on app/views/saved_annotations/show.html.erb
> +        <p><strong><%= SavedAnnotation.human_attribute_name("annotation_text") %>:</strong></p>
I would repeat the title here and not "Tekst"

2023-08-16 12:46 UTC, niknetniko approved these changes

2023-08-16 13:20 UTC, merged