Replace Ace Editor with CodeMirror
dodona-edu/dodona pull request #4933
Opened 2023-09-04 11:35 UTC by niknetniko

This pull request replaces the Ace Editor with [CodeMirror](https://codemirror.net/) (which is commonly-used text editing component for the web).

While functionally equivalent for end-users, it does have some benefits:

- No longer uses Sprockets
- Ready for use within WebComponents

On the other hand, it does need a bit more code to:

- Set up the language support (since the set of first-party language modules is smaller)
- Set up the theme. It applies the Rouge CSS classes to the code, so it uses the same theme. However, sometimes CodeMirror and Rouge don't agree on what a particular piece of code is, so I foresee that we might need to tweak the theme a bit sometimes.

Closes #4585 as a side effect.

2023-09-04 18:58 UTC, chvp approved these changes

2023-09-11 11:50 UTC, jorg-vr requested changes
Thank you for replacing the legacy editor!

2023-09-11 11:50 UTC, jorg-vr commented on app/assets/javascripts/editor.ts
> +    { tag: tags.variableName, class: "nv" },
```suggestion
    { tag: tags.variableName, class: "n" },
```

It bothered me that a lot of code was italic, which was not the case in the rouge code rendering. I found that rouge uses `n` or `nf` instead of `nv` as class for the same variables.

Another solution for this might be to remove the italic styling from `nv`

eg:
![image](https://github.com/dodona-edu/dodona/assets/21177904/59ed6598-93b0-4efd-ad27-e7b2415a939d)
![image](https://github.com/dodona-edu/dodona/assets/21177904/1d237ff9-d1ac-45e9-91a7-c1a82e9f4d0b)
vs:
![image](https://github.com/dodona-edu/dodona/assets/21177904/f5f68c74-230e-44d4-ac85-c4b6eafbcfce)
![image](https://github.com/dodona-edu/dodona/assets/21177904/12755f13-5f7d-49e5-a6a1-f07d49614521)

2023-09-11 11:50 UTC, jorg-vr commented on app/assets/javascripts/editor.ts
> +const rougeStyle = HighlightStyle.define([
Could this also be used for the papyros code editor? (as it also uses code mirror)
This would greatly improve styling

2023-09-12 11:18 UTC, niknetniko commented on app/assets/javascripts/editor.ts
> +const rougeStyle = HighlightStyle.define([
Since Papyros sets up its own editor, this is no small task: we would need to either hardcode a "dodona" mode (which isn't nice) or change the API to support configuring the CodeMirror instance used by Papyros (which is a lot of work).

2023-09-12 11:24 UTC, jorg-vr commented on app/assets/javascripts/editor.ts
> +const rougeStyle = HighlightStyle.define([
Can't we make the 'dodona mode' the default for papyros? ANd just make their default styling consistent.
I'll have a look at this at some later point. No need to fix that for this pr

2023-09-12 11:30 UTC, niknetniko commented on app/assets/javascripts/editor.ts
> +    { tag: tags.variableName, class: "nv" },
I removed the italic from `nv`, as it felt like a better solution than to make the css less specific.

2023-09-12 11:32 UTC, jorg-vr approved these changes

2023-09-12 11:56 UTC, merged