Create index page for annotations
dodona-edu/dodona pull request #4965
Opened 2023-09-13 13:38 UTC by jorg-vr

This pull request

- [ ] Tests were added
- [ ] Documentation update can be found at dodona-edu/dodona-edu.github.io#

Closes # .

2023-09-20 09:42 UTC, bmesuere approved these changes
I prefer the outlined button in the table instead of a primary

2023-09-21 08:30 UTC, niknetniko requested changes
As mentioned IRL, the button to save a comment doesn't seem to be translated sometimes.

(and we'll ignore the 403 as the beta will go away soon)

2023-09-21 08:30 UTC, niknetniko commented on app/assets/javascripts/components/saved_annotations/new_saved_annotation.ts
> +import { updateURLParameter } from "utilities";
These two imports don't seem to be used

2023-09-21 08:59 UTC, niknetniko approved these changes

2023-09-21 10:02 UTC, merged