Replace Ace Editor with CodeMirror II
dodona-edu/dodona pull request #4970
Opened 2023-09-15 13:19 UTC by niknetniko

This reverts commit 98c93fec44dca91bbb548b83528726fb0a089ec8, and thus re-introduces #4933.

In draft until it is clear why this doesn't work in production.

2023-09-20 07:51 UTC, jorg-vr commented
The potential problem might be dynamic loading of javascript

If codemirror loads certain packages only if the language requires them, it needs to use the correct paths.
The assets paths are still managed by rails sprockets, so the issue might be there.

I remember you also saying that on the broken pages there was a javascript fetch error

2023-10-26 15:07 UTC, jorg-vr commented
confirmed bug to be related to #5082
![image](https://github.com/dodona-edu/dodona/assets/21177904/b63cffa4-21ab-4019-ba90-eb1dacbdb7de)

So fix might have fixed this

2023-10-27 07:24 UTC, jorg-vr approved these changes

2023-10-27 12:12 UTC, bmesuere requested changes
- [x] Autocomplete doesn't seem to work. E.g. html autocomplete in the docs https://codemirror.net/examples/autocompletion/ vs on https://naos.dodona.be/nl/activities/1412931994/

- [ ] Font size is a little bigger, but not sure if this is a problem.

- [x] We seem to miss the highlighting of functions compared to ace.

- [x] Ace had basic linting (in javascript), this is missing now. Not sure if this is a problem (since the linting messages could be different from the ones in the judge and thus confusing), but maybe mention it in the PR.

- [x] I also think the python indentation is different (or at least not very smart). In a solution that used 4 spaces, it added just 2 when adding a new line.

- [ ] The active line isn't marked anymore.

2023-10-27 12:12 UTC, bmesuere commented on app/assets/javascripts/editor.ts
> +        alias: ["rlang"],
This shouldn't be rlang?

2023-10-27 15:37 UTC, bmesuere commented on app/assets/javascripts/exercise.ts
> +            await initEditor();
I don't think the await is needed on this line since the next few functions don't depend on it?
If this does stuff in a worker (or loads additional files), the await itself can probably move down a few lines to do things more async.

2023-10-27 15:42 UTC, jorg-vr commented
Changes:
- autocomplete now works and is applied by default
- font size > I prefer the larger size, but did make the line numbers a bit smaller
- The python lexer does not indicate builtins in the same way as  ace, so we canot color them specifically. For the fans of a bit more color, I did change the highlighting for functions to yellow in both the editor and rouge (to keep it consistent)
- Added a comment that linting is removed in pr
- I made the default indent 4 spaces. This is the most common for python and python is our most used language. I could not find a smart detection algorithm in the editor. We could write such an algorithm ourselves, or provide a different default for each language if desired
- I reintroduced active line marking. The color has to be a partially transparant version of the slection color to work well with selected code

2023-10-28 11:54 UTC, bmesuere approved these changes

2023-10-30 07:52 UTC, merged