Add draft flag to activities
dodona-edu/dodona pull request #4998
Opened 2023-09-22 12:47 UTC by jorg-vr

This pull request

- [ ] Tests were added
- [ ] Documentation update can be found at dodona-edu/dodona-edu.github.io#

Closes # .

2023-09-27 09:31 UTC, niknetniko requested changes
One small edge case I noticed:

- When an existing exercise is changed to draft, the exercise still seems to appear on the home page of students who have submitted to this exercise (although if you click on it, it correctly says you don't have access). Not sure if this needs fixing.

2023-09-27 12:02 UTC, jorg-vr commented
The activity is not directly linked if it is not accessible in the recent activities:
![image](https://github.com/dodona-edu/dodona/assets/21177904/a04595bf-1ea4-4bd0-bbc3-8ae9fdaa3a41)

On some other places (such as submission detail), the link to the activity can still be found, But gives a correct error message.

This behavior is similar to that of series without access our private exercises etc, I would not change it.

I guess it also won't happen often that an existing activity is set to draft after students used it.

2023-09-27 12:23 UTC, pdawyndt commented
Maybe it could help if students also see the draft status, which is in contrast with the private status that is completely transparent for students. At least, having the draft status visible for students would explain for them why clicking the exercise results in a "no access", and then students could remind their teachers that exercises are still in draft mode.

2023-09-27 12:34 UTC, niknetniko approved these changes
I don't immediately have better suggestions, so more as a mental note, but the "draft mode" and especially "ontwerpmodus" terminology feel a bit weird to me.

2023-09-27 12:40 UTC, pdawyndt commented
@niknetniko: would the mental model feel more natural if it were branded as published/unpublished?

2023-10-19 12:39 UTC, bmesuere requested changes

2023-10-19 12:39 UTC, bmesuere commented on config/locales/views/activities/en.yml
> +        toggle-label: "Put activity in draft mode."
```suggestion
        toggle-label: "Mark activity as draft."
```

2023-10-19 12:39 UTC, bmesuere commented on config/locales/views/activities/en.yml
> +        help: "Draft mode provides better error logging for teachers and hides the activity from students. Draft mode is activated by default for new activities."
```suggestion
        help: "Mark activities as draft while you are still working on them."
```
+ add link to documentation page about drafts

2023-10-19 12:39 UTC, bmesuere commented on config/locales/views/activities/en.yml
> +      draft-notice: "This activity is in draft mode. It is not visible for students."
```suggestion
      draft-notice: "This activity is a draft and thus not visible for students."
```

+ het woord "draft" linken naar de docs (zelfde met andere notice strings in deze PR)

2023-10-19 12:39 UTC, bmesuere commented on config/locales/views/activities/en.yml
> +      alert_draft: This activity is in draft mode. It is not visible for students.
```suggestion
      alert_draft: This activity is a draft and thus not visible for students.
```

2023-10-19 12:39 UTC, bmesuere commented on config/locales/views/activities/en.yml
> +      alert_draft_edit: Disable draft mode.
```suggestion
      alert_draft_edit: Publish activity.
```

2023-10-19 12:39 UTC, bmesuere commented on config/locales/views/activities/nl.yml
> +        help: "Wanneer een oefening in concept modus staat, is ze onzichtbaar voor studenten en krijgen leerkrachten betere foutmeldingen."
```suggestion
        help: "Markeer een oefening als concept zolang je ze nog aan het opstellen bent."
```
+ link naar docs

2023-10-19 12:39 UTC, bmesuere commented on config/locales/views/activities/nl.yml
> +      draft-notice: "Deze activiteit is een concept. Ze is niet zichtbaar voor studenten."
```suggestion
      draft-notice: "Deze activiteit is nog een concept. Ze is niet zichtbaar voor studenten."
```

2023-10-19 12:39 UTC, bmesuere commented on config/locales/views/activities/nl.yml
> +      alert_draft: Deze oefening is een concept. Ze is niet zichtbaar voor studenten.
```suggestion
      alert_draft: Deze oefening is nog een concept. Ze is niet zichtbaar voor studenten.
```

2023-10-19 12:39 UTC, bmesuere commented on config/locales/views/activities/nl.yml
> +      alert_draft_edit: Markeer deze oefening als af.
```suggestion
      alert_draft_edit: Deze oefening publiceren.
```

2023-10-19 12:39 UTC, bmesuere commented on config/locales/views/pages/nl.yml
> +      all-draft-exercises: Alle concept oefeningen
Maybe "ongepubliceerde oefeningen"?

2023-10-20 07:51 UTC, bmesuere reviewed
I've been thinking about this some more. I there a good reason why someone might convert an existing exercise back into draft? Right now, doing so might cause problems if the exercise is used in other courses.

2023-10-20 07:54 UTC, jorg-vr commented
When updating an exercise this might be usefull. Eg adding more tests: there might be mistakes in those new tests so while working on them it can be logical to make the exercise temporarily unavailable for students

Teachers of these other course will still have access and see the draft notice

2023-10-20 08:08 UTC, chvp commented on app/models/activity.rb
> +        return false
Wouldn't it be better to change the definition of `accessible_activities` and `visible_activities`? (Or at least accessible, visible might make less sense semantically.)

2023-10-20 08:08 UTC, chvp commented on app/views/activities/_form.html.erb
> -<% end %>
Why is this suddenly removed?

2023-10-20 08:08 UTC, chvp commented on app/models/activity.rb
> +        return false if course.accessible_activities.pluck(:id).exclude?(id) || draft?
Even if it wouldn't make sense to change the definitions, I would still split this up to be two return statements each with their own condition. This code is already quite complicated and that would make it easier to reason about IMO.

2023-10-20 08:08 UTC, chvp commented on app/models/activity.rb
> +        return false if course.accessible_activities.pluck(:id).exclude?(id) || draft?
(And same for the `||` in the `elsif` below.)

2023-10-20 12:23 UTC, bmesuere reviewed
As discussed during the day: if we make draft a one-way setting, we can just store it in the database instead of also in the config file. This would simplify the code a bit.

- The default value in the database can be set to true so we can remove the before_create action and the other logic to add it to the config file and set it for new exercises. We could also set it on creation in the tests and prevent a manual update. The migration would probably be something like
```ruby
add_column :activities, :draft, :boolean, default: true
Activity.reset_column_information # don't know if this is strictly needed
Activity.update_all(draft: false)
```
- The setting can be removed from the form. I would add the alert that is now shown on the show page to the edit and info page as well. `publish` could be added as a separate action to the controller (which would prevent adding a new check that only allows it to be set from true to false)

2023-10-26 08:30 UTC, jorg-vr commented on app/models/activity.rb
> +        return false
I have removed these draft checks as they are redundant considering the return false if draft below

2023-10-26 08:34 UTC, jorg-vr commented on app/views/activities/_form.html.erb
> -<% end %>
This was only imported for `initLabelsEdit` below. This function does not exist thus this was a noop.
Related to https://github.com/dodona-edu/dodona/issues/5055
It can be reintroduced when I work on that issue

2023-10-26 09:59 UTC, jorg-vr commented
Still have to add to alert to other pages, will fix.

2023-10-26 11:33 UTC, jorg-vr commented
> The migration would probably be something like

I took a slightly different approach: first create column with default false, then change the default to true
This results in the default only being true for new exercises

> `publish` could be added as a separate action to the controller

I prefer the current approach with an extra validation in activity. This keeps our api more default and more RESTfull

2023-10-26 11:46 UTC, bmesuere approved these changes

2023-10-26 11:46 UTC, bmesuere commented on app/models/activity.rb
> +  validates :draft, inclusion: { in: [false] }, unless: :draft_was
what does this do?

2023-10-26 11:47 UTC, niknetniko approved these changes

2023-10-26 11:50 UTC, jorg-vr commented on app/models/activity.rb
> +  validates :draft, inclusion: { in: [false] }, unless: :draft_was
if not `draft_was`, validate if `draft` is in the list of possible values, with the only possible value being `false` 
`draft_was` is the previous value of `draft`

so if the previous value of `draft` was `false`, only allow `false` as new value

2023-10-26 12:08 UTC, bmesuere commented on app/models/activity.rb
> +  validates :draft, inclusion: { in: [false] }, unless: :draft_was
You could argument that this check should be in the controller instead of the model, but not a strong opinion so ok for me.

2023-10-26 12:21 UTC, chvp approved these changes

2023-10-26 12:21 UTC, chvp commented on app/policies/activity_policy.rb
> +      %i[access name_nl name_en draft]
You could also check here that `draft` can only be updated if it's currently true. Might be a more clear than the `validates` in the model.

2023-10-26 14:08 UTC, merged