Add uniqueness validation to repository remote url
dodona-edu/dodona pull request #5118
Opened 2023-11-07 13:23 UTC by jorg-vr

This pull request avoids bugs that occur when the same repo is added to dodona twice.

2023-11-07 13:50 UTC, bmesuere approved these changes

2023-11-07 15:05 UTC, chvp approved these changes

2023-11-07 15:06 UTC, chvp requested changes
Ah, actually, the linting error is right. A migration should be added to enforce this uniqueness at the database level as well.

2023-11-08 09:40 UTC, chvp approved these changes

2023-11-08 09:41 UTC, merged