Stop Sprockets from compressing JS
dodona-edu/dodona pull request #5136
Opened 2023-11-13 11:58 UTC by bmesuere

This pull request removes terser as a rails dependency and disables js compression using Sprockets.

Since our JS modernization efforts, all JS is processed by webpack first which already runs Terser.

This should speed up deploys.

2023-11-13 15:57 UTC, bmesuere commented
This seems to work on naos.

2023-11-13 16:10 UTC, jorg-vr requested changes

2023-11-13 16:10 UTC, jorg-vr commented on Gemfile
> +# gem 'terser', '>= 1.1.1'
I would remove instead of comment this

2023-11-13 16:13 UTC, bmesuere commented on Gemfile
> +# gem 'terser', '>= 1.1.1'
I left it because it is part of the default rails gemfile (at least, git blame told me you last modified it while updating rails).

2023-11-13 20:00 UTC, chvp approved these changes

2023-11-14 08:23 UTC, jorg-vr approved these changes

2023-11-14 08:26 UTC, merged