Add edit submission link when evaluating a submission
dodona-edu/dodona pull request #5190
Opened 2023-11-22 10:13 UTC by jorg-vr

This pull request adds an edit submission link to to the feedback show page.

I have hidden this feature behind vertical dots as it is an advanced feature that will probably be used infrequently.
I can make it more prominent if there is disagreement about this hypotheses.
![image](https://github.com/dodona-edu/dodona/assets/21177904/bcf5a25c-edeb-4562-9e66-7b5c84e40bdb)

I also generalized some css about icon buttons in card titles. This also improved the submission index page.
old:
![image](https://github.com/dodona-edu/dodona/assets/21177904/0c2e7b5c-6f2f-4c89-a959-bc29a2a26498)

new:
![image](https://github.com/dodona-edu/dodona/assets/21177904/66c79506-2e03-42a7-bdc2-1f5c469260c0)

Closes #2054

2023-11-23 12:35 UTC, niknetniko commented on config/locales/js/nl.yml
> +        submit: Dien deze oplossing in
```suggestion
        submit: Deze oplossing indienen
```
This is more consistent with the button next to it

2023-11-23 12:35 UTC, niknetniko commented on app/assets/javascripts/i18n/translations.json
> +          "submit": "Dien deze oplossing in"
```suggestion
          "submit": "Deze oplossing indienen"
```

2023-11-23 12:47 UTC, niknetniko approved these changes

2023-11-23 13:05 UTC, bmesuere requested changes
The functionality looks good, but the buttons can use some margin.
In the normal view, the buttons are too close to each other horizontally (if you hover over the new button). On small screens, the same is true vertically.

I would also move the breakpoint down 1 tier (to large). This then overflows in Dutch for an evaluation, but I would then hide the word "annotations" (the label next to the toggle buttons) instead.

2023-11-23 13:05 UTC, bmesuere commented on app/assets/javascripts/components/annotations/annotation_options.ts
> +
I understand that the button visually fits in with the rest of these options, but functionality wise, it has nothing to with the rest of this class. Can't these 2 getters move to the submission?

2023-12-05 13:28 UTC, jorg-vr commented on app/assets/javascripts/code_listing.ts
> +function initAnnotations(submissionId: number, courseId: number, exerciseId: number, userId: number, code: string, userIsStudent: boolean, canSubmitAsOwn: boolean): void {
This function is only used in a single place, so making it an object would be very artificial, definitely with the rather specific options.

Although a case could be made to group the first options into a `submission` object. This would be more reusable in the frontend. But I see no reason to refactor that right now.

2023-12-19 11:00 UTC, bmesuere approved these changes

2023-12-19 12:12 UTC, merged