Always use svg series icon
dodona-edu/dodona pull request #5214
Opened 2023-12-04 11:03 UTC by jorg-vr

This pull request fixes #5213

It were actually to separate bugs:
1. the fallback for non signed in users was the simplified icon
2. empty series were not postloaded

The fix removes the simplified icon, always using the svg version.
The amount of html remains limited for non loaded series because the svg code is moved to a web component.

Closes #5213

2023-12-05 12:28 UTC, chvp reviewed
The tooltip location seems off: ![screenshot_2023-12-05-132544](https://github.com/dodona-edu/dodona/assets/42220376/446a6625-ab0c-463b-a4c8-ffd436f0a170)

2023-12-05 14:06 UTC, chvp approved these changes

2023-12-19 13:59 UTC, bmesuere requested changes

2023-12-19 13:59 UTC, bmesuere commented on app/assets/javascripts/components/series_icon.ts
> +                </defs>
only add this if needed?

2023-12-19 13:59 UTC, bmesuere commented on app/assets/javascripts/components/series_icon.ts
> + * @cssprop --deadline-icon-background-color - the background color of the deadline icon
Are these specified in a general css file? Why not add them here to make this component self contained?

2023-12-19 13:59 UTC, bmesuere commented on app/assets/javascripts/components/series_icon.ts
> +export class SeriesIcon extends ShadowlessLitElement {
I would refactor the properties of this component a bit since they now expose the inner working. The attributes should define the wanted state e.g. deadline = missed where the component then applies the appropriate icon and color. This would also allow to make the types stricter (enum like).

2024-01-03 11:39 UTC, jorg-vr commented on app/assets/javascripts/components/series_icon.ts
> + * @cssprop --deadline-icon-background-color - the background color of the deadline icon
Right now it is a shadowless lit component, which forces all style definitions to be in the global scope.
Changing it to use the shadow dom would not allow any use of globally defined classes. In this this would mean we had to redefine the material design icons used within this class. I do not think that is desired.

Sadly there is no way to 'partially' use the shadow dom. Which is why we also aren't using the shadow dom in most other components for now.

2024-01-09 13:39 UTC, bmesuere approved these changes

2024-01-09 14:07 UTC, merged