Update to papyros version with debugger
dodona-edu/dodona pull request #5236
Opened 2023-12-15 14:16 UTC by jorg-vr

This pull request

- [ ] Tests were added
- [ ] Documentation update can be found at dodona-edu/dodona-edu.github.io#

Closes # .

2024-01-13 11:48 UTC, chvp requested changes
Looks great to me. Just a small remark on the code.

2024-01-13 11:48 UTC, chvp commented on app/helpers/activity_helper.rb
> +  def description_iframe(activity, unique_id = 1)
I don't particularly like this way of making sure of the uniqueness of the id. Although I don't expect this will happen often, it's especially vulnerable to copy-paste errors. Can we not add a class/module variable? Or something in the `Current` object? (And then increment it each time.)

2024-01-16 12:00 UTC, chvp approved these changes

2024-01-18 09:20 UTC, bmesuere requested changes
Functionally, this looks very good! Some nitpicks:
- [x] the margin between the top bar and the "In dit venster kan je ..." is quite large
- [x] The gutter is very large right now
  ![image](https://github.com/dodona-edu/dodona/assets/481872/083285df-ef85-4088-b536-ad0cb99dc2d7)
- [x] What is the goal of the gray area below the buttons?
  ![image](https://github.com/dodona-edu/dodona/assets/481872/27345de5-aa9b-4671-8fa5-b8b651693d8a)
- [x] The debug button only appears when some code is present. Why not show it from the start?
- [x] The "geef invoer vooraf in" link uses a custom color
- [x] The left and right padding of the single line input might be a bit bigger

2024-01-18 10:21 UTC, jorg-vr commented
> What is the goal of the gray area below the buttons?

In which browser + os did you test this? this is not present in firefox or chrome on my system

2024-01-22 09:25 UTC, jorg-vr commented
@bmesuere I have used the clipboard with arrow icon for now.
Upgrading the material design icons in this pr caused to many issues.

![image](https://github.com/dodona-edu/dodona/assets/21177904/54621697-a832-402b-85ee-a9158f24c2fe)

2024-01-22 09:57 UTC, bmesuere approved these changes
In think the translations.json file is auto generated, so my language suggestions are probably in the wrong place.

The title (in the blue bar) should probably also be "Python sandbox".

2024-01-22 09:57 UTC, bmesuere commented on app/assets/javascripts/i18n/translations.json
> +        "copy_to_submit": "To submitionbox",
```suggestion
        "copy_to_submit": "Finalize and submit",
```

2024-01-22 09:57 UTC, bmesuere commented on app/assets/javascripts/i18n/translations.json
>          "overwrite_code": "Do you want to overwrite the code in the scratchpad with your latest changes?"
```suggestion
        "overwrite_code": "Do you want to overwrite the code in the sandbox with your latest changes?"
```

2024-01-22 09:57 UTC, bmesuere commented on app/assets/javascripts/i18n/translations.json
>          "overwrite_code": "Wil je de code in het kladblok overschrijven met je laatste aanpassingen?"
```suggestion
        "overwrite_code": "Wil je de code in de sandbox overschrijven met je laatste aanpassingen?"
```

2024-01-22 12:30 UTC, merged