Always show navigation on submission pages
dodona-edu/dodona pull request #5269
Opened 2024-01-04 13:30 UTC by jorg-vr

This pull request introduces the submission navigation on pages with published scores.

The score is now moved to the next row. It is now expanded by default as a student visiting this page will almost always want to see this information.

I have added a bit of padding and made scores an outlined button, which also helps it to stand out a bit more.

The edit button is only visible for relevant staff.

![image](https://github.com/dodona-edu/dodona/assets/21177904/59107919-0cf9-4e90-81c4-e6cd95a85ac3)

I might consider using a callout to make the scores even more prominent.

Closes #5268

2024-01-04 19:13 UTC, chvp approved these changes

2024-01-08 08:56 UTC, bmesuere requested changes
- Always showing the previous submissions is ok for me
- Showing the score full width is ok for me
- Removing the collapse feature for the score is also ok for me

I agree that the score could used some additional styling, but I'm not sure about reusing the exact style of the feedback table since they look very similar but show something completely different. This might however be a non-issue because the score is only shown on a fraction of the pages. 

I do think we can improve of the UI. There is no context right now, just a dump of the score. The user might be confused where this comes from. Can we use a proper title instead of the score? Is there an already used icon we can add? Can we link to a page that shows the rest of this evaluation for that user? Since we have space, maybe also add a text label to the edit button (similar to the debug button)...

2024-01-10 13:57 UTC, bmesuere requested changes

2024-01-10 13:57 UTC, bmesuere commented on app/views/feedbacks/_score_card.html.erb
> +      <span><%= t(".score")%></span>
I would use Evaluatie/Evaluation as title instead of punten.

2024-01-10 13:57 UTC, bmesuere commented on config/locales/views/feedbacks/en.yml
> +      info_html: "This solution has been evaluated by a teacher. They provided the following feedback. <a>See all evaluated solutions</a>."
```suggestion
      info_html: "This solution has been manually evaluated by a teacher as part of <a> an evaluation</a>. Below, you can find your feedback."
```
I think the href/url is missing here.

2024-01-10 13:57 UTC, bmesuere commented on config/locales/views/feedbacks/nl.yml
> +      info_html: "Deze oplossing werd nagekeken door een lesgever. Deze gaf onderstaande beoordeling. <a href=\"%{url}\">Bekijk de andere beoordelingen</a>."
```suggestion
      info_html: "Deze oplossing werd manueel nagekeken door een lesgever als deel van <a href=\"%{url}\">een evaluatie</a>. Hieronder vind je jouw feedback."
```

2024-01-10 15:22 UTC, bmesuere approved these changes

2024-01-10 15:46 UTC, merged