Add new support method and improve support visibility
dodona-edu/dodona pull request #5287
Opened 2024-01-12 10:09 UTC by jorg-vr

This pull request updates the support_us page. I have added a button to the new online donation https://actieplatform.ugent.be/nl-NL/p/dodona/step-1
I also updated the text a bit to the current reality.

I Also added a support us button in our navigation as suggested by the Universiteitsfonds. 

![image](https://github.com/dodona-edu/dodona/assets/21177904/125d8117-9385-411c-83d8-c55d89529e88)

The link is still present when signed in
![image](https://github.com/dodona-edu/dodona/assets/21177904/9c11b3b2-c7e8-4ae7-bdd0-0a4b8072b47a)

English version:
![image](https://github.com/dodona-edu/dodona/assets/21177904/9b4bafe3-e2c7-4847-a67c-0da984cf3aea)

Misc:
- i added a hover opacity to navbar links, as they didn't have any hover indication

2024-01-12 10:51 UTC, chvp commented on config/locales/views/pages/en.yml
> +      support_p2_html: "You can als make a deposit to the account of the University Fund account at <code>BE26 3900 9658 0329</code> (BIC: <code>BBRUBEBB</code>) by mentioning <code>Dodona</code>."
```suggestion
      support_p2_html: "You can also make a deposit to the account of the University Fund account at <code>BE26 3900 9658 0329</code> (BIC: <code>BBRUBEBB</code>) by mentioning <code>Dodona</code>."
```

2024-01-12 12:55 UTC, niknetniko approved these changes

2024-01-16 10:12 UTC, chvp approved these changes

2024-01-16 13:04 UTC, bmesuere requested changes
- [x] The top right navbar links could use a bit more horizontal margin/padding. The addition of the support us link caused the sign in button and language selector to be closer together (easiest to see if you compare a tab with mestra and dodona). In addition, I would add additional right margin to the nav bar button to make it stand out a bit.
- [x] On small screens, the top right navigation becomes a dropdown menu. There, the vertical spacing seems off a bit.
- [x] On the support us page itself, could we also add a button that links to the external platform to the top part of the page? Similar to where the "Sign in" button is on the signed out home page.
- [ ] Do we have any control over the external website? The default amounts are quite high.
- [ ] I would tweak the text in the "how can you support us" section a bit to make it clearer that the "make a donation" button is the easiest way to make a donation.

2024-01-16 15:08 UTC, jorg-vr commented
> Do we have any control over the external website? The default amounts are quite high.

We could email them, maybe with an update once this is rolled out.
We don't have control ourselves

2024-01-16 16:08 UTC, bmesuere approved these changes

2024-01-16 16:34 UTC, merged