Remove "actions" for labels for users who can't do actions on labels
dodona-edu/dodona pull request #5289
Opened 2024-01-13 17:24 UTC by BWindey

This pull request removes the actions-column entirely for users who don't have the right to perform actions on labels.

Before:
![image](https://github.com/dodona-edu/dodona/assets/93756910/ccbb66aa-6d19-4ad5-ab07-b80a1bdf7f85)
After:
![image](https://github.com/dodona-edu/dodona/assets/93756910/3815ae9e-9d8a-4d52-ba77-6f26986c00f7)

- [ ] Tests were added

2024-01-13 19:40 UTC, chvp requested changes
Thanks for your contribution! Just a small remark on your code.

2024-01-13 19:40 UTC, chvp commented on app/views/labels/_labels_table.html.erb
> +        <col class="col-10"/>
```suggestion
        <col class="col-9"/>
```
The column widths should add up to 12 in bootstrap. See https://getbootstrap.com/docs/5.0/layout/columns/ and https://getbootstrap.com/docs/5.0/layout/grid/.

2024-01-13 21:09 UTC, BWindey commented on app/views/labels/_labels_table.html.erb
> +        <col class="col-10"/>
Those are really useful links! I now understand more of what's what. I tested changing it to 9, and also changing the other column to 2, to see which one looks better. Personally I prefer using "10 - 2". Do you agree?  
10 - 2
![image](https://github.com/dodona-edu/dodona/assets/93756910/419cf264-26cb-49b2-a9ee-42df9ed498a5)
9-3
![image](https://github.com/dodona-edu/dodona/assets/93756910/0d5604dd-17f8-4577-86d5-85dbe3d020e1)

2024-01-13 22:00 UTC, chvp commented on app/views/labels/_labels_table.html.erb
> +        <col class="col-10"/>
I have no particular preference. Maybe try aligning the second column to the right, given its numeric nature that would probably look good.

2024-01-14 08:41 UTC, BWindey commented on app/views/labels/_labels_table.html.erb
> +        <col class="col-10"/>
I changed the exercise-count righ-aligned, and the actions too. The latter had to be right-aligned to keep some distance between the count and the buttons.
![image](https://github.com/dodona-edu/dodona/assets/93756910/aedc974b-dfc0-4546-aa37-c3e59da76bbd)
![image](https://github.com/dodona-edu/dodona/assets/93756910/d7a56a13-226d-425c-a702-14fa48a687c2)
![image](https://github.com/dodona-edu/dodona/assets/93756910/2ce8afaf-f554-454b-b2e5-35dc58b9b3b2)

2024-01-15 08:20 UTC, jorg-vr approved these changes
Thanks for the contribution.

Could you put the latest images in the pr description?

Also did you test this on smaller screen widths? The 9-3 vs 10-2 discussion might be more relevant in those cases

2024-01-15 08:35 UTC, BWindey commented
Updated the original PR to include the images

2024-01-16 12:37 UTC, bmesuere approved these changes

2024-01-16 12:37 UTC, bmesuere commented on app/views/labels/_labels_table.html.erb
> +        <th class="text-end"><%= t "labels.index.actions" %></th>
```suggestion
        <th class="text-end"></th>
```

The label is redundant, so I would remove it.

2024-01-16 13:31 UTC, BWindey commented on app/views/labels/_labels_table.html.erb
> +        <th class="text-end"><%= t "labels.index.actions" %></th>
That would remove the "Actions" title, correct?
![image](https://github.com/dodona-edu/dodona/assets/93756910/eb32d262-5c8e-4d81-aa8f-41f50d17d164)

2024-01-16 13:34 UTC, BWindey commented on app/views/labels/_labels_table.html.erb
> +        <th class="text-end"><%= t "labels.index.actions" %></th>
If so, then we could remove the conditional entirely for the tabel header.

2024-01-16 13:47 UTC, bmesuere commented on app/views/labels/_labels_table.html.erb
> +        <th class="text-end"><%= t "labels.index.actions" %></th>
Indeed, it would remove the Actions label. Removing the conditional for the table header is not a good idea. You should have the same number of header columns as body columns.

2024-01-16 13:56 UTC, BWindey commented on app/views/labels/_labels_table.html.erb
> +        <th class="text-end"><%= t "labels.index.actions" %></th>
That seems logical, ok.

I just noticed something too. There are always 3 body columns, as the conditional is seperated into permission to edit and permission to destroy. Both checks happen inside the <td> column tag. 

How does that work with there only being 2 columns defined (for users without permission), but 3 actual columns, the last one empty?

```html
...
  <colgroup>
      <% if policy(Label).edit? %>
        <col class="col-6"/>
        <col class="col-3"/>
        <col class="col-3"/>
      <% else %>
        <col class="col-10"/>
        <col class="col-2"/>
      <% end %>
    </colgroup>
  
  ...
  <tbody>
    <% labels.each do |label| %>
      <tr>
        <td><%= link_to label.name, label_path(label) %></td>
        <td class="text-end"><%= link_to label.activities.count, activities_path({"labels[]" => label.name}) %></td>
        <td class="text-end">
          <% if policy(Label).edit? %>
            <%= link_to edit_label_path(label), class: "btn btn-icon" do %>
              <i class="mdi mdi-pencil"></i>
            <% end %>
          <% end %>
          <% if policy(Label).destroy? %>
            <%= link_to label, method: :delete, data: {confirm: t("general.are_you_sure")}, class: "btn btn-icon btn-icon-filled d-btn-danger" do %>
              <i class="mdi mdi-delete"></i>
            <% end %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>

...
```

2024-01-16 16:02 UTC, chvp approved these changes

2024-01-16 17:02 UTC, merged