Require at least one correct submission and a valid config before publishing
dodona-edu/dodona pull request #5330
Opened 2024-01-29 15:25 UTC by jorg-vr

This pull request adds a validation to activities that checks if an activity has at least one correct submission and a valid config before publishing.

This info is displayed to the user in the notice.

![image](https://github.com/dodona-edu/dodona/assets/21177904/2c54e42a-483d-4206-ac2a-149c606f5bd7)

- [x] Tests were added

Closes  #5084

2024-01-30 08:39 UTC, chvp requested changes
- [x] In general I would not use the `valid` terminology, but use `correct` everywhere.

2024-01-30 08:39 UTC, chvp commented on app/models/activity.rb
> +    self.draft = true
This shouldn't be necessary. If errors are added during validation, the record isn't saved to the database.

2024-01-30 08:39 UTC, chvp commented on config/locales/models/nl.yml
> +          no_valid_submission: "Er moet minstens één geldige oplossing zijn, vooraleer de oefening kan worden gepubliceerd."
```suggestion
          no_valid_submission: "Er moet minstens één correcte oplossing zijn, vooraleer de oefening kan worden gepubliceerd."
```

2024-01-30 08:43 UTC, jorg-vr commented on app/models/activity.rb
> +    self.draft = true
It isn't saved, but the unsaved activity is reused to re render the edit screen with the same invalid state and the corresponding errors.
For the case of draft this is odd as this hides the draft notice on top...

2024-01-30 08:58 UTC, chvp approved these changes

2024-01-30 13:36 UTC, bmesuere requested changes
In the current implementation, the check is only done when trying to publish. I would do this every time when we render the "this exercise is a draft" callout and add some kind of checklist there so it is clear which steps need to be taken, like
- have a problem description in Dutch and/or English
- have a valid configuration
- have at least one correct submission

In the future, we could expand that list if we would think of other requirements.

2024-02-01 14:07 UTC, bmesuere commented on config/locales/views/activities/en.yml
> +        correct_submission: "There must be at least one correct submission."
```suggestion
        text_html: This activity is currently a <a href="https://docs.dodona.be/en/faq/activities/#what-is-a-draft-activity" target="_blank">draft</a> and is not yet visible to students.
        edit: Publish activity.
        before_publish: "Before you can publish this activity, please ensure the following criteria are met:"
        valid_config: "The exercise must have a valid configuration file."
        is_valid: "The activity must have a name and a description."
        correct_submission: "You must submit at least one correct solution."
```

2024-02-01 14:09 UTC, bmesuere commented on config/locales/views/activities/nl.yml
> +        correct_submission: "Er moet minstens één correcte oplossing zijn."
```suggestion
        text_html: Deze oefening is momenteel een <a href="https://docs.dodona.be/nl/faq/activities/#wat-is-een-conceptactiviteit" target="_blank">concept</a> en nog niet zichtbaar voor studenten.
        edit: Deze oefening publiceren.
        before_publish: "Vooraleer je deze oefening kan publiceren, moet aan de volgende voorwaarden voldaan zijn:"
        valid_config: "De oefening moet een geldig configuratiebestand hebben."
        is_valid: "De oefening moet een naam en een beschrijving hebben."
        correct_submission: "Je moet minstens één correcte oplossing indienen."
```

2024-02-01 14:57 UTC, bmesuere approved these changes

2024-02-02 09:30 UTC, chvp approved these changes

2024-02-02 09:33 UTC, merged