Use papyros to debug testcases
dodona-edu/dodona pull request #5336
Opened 2024-02-02 08:52 UTC by jorg-vr

This pull request

- [ ] Tests were added
- [ ] Documentation update can be found at dodona-edu/dodona-edu.github.io#

Closes # .

2024-02-11 14:51 UTC, bmesuere requested changes
This is amazing work, @jorg-vr! This gets rid of a lot of legacy code, improves the current experience, allows us to add an even better integration in the future and is incredibly fast!

I encountered a small issue when running a simple input/output exercise (sum of 2 numbers): the input of the test was correctly loaded into the input area, but the lines were marked as checked from the start. 

I don't know if possible, but can you add a little more whitespace between the real code and the test code?

Some other suggestions, probably for a later PR:
- If you click debug, wait for the traces to generate and then edit the code you are still debugging the old code. In addition, there is no good way to make the code arrow go away. I would enter a "debug mode" when clicking debug which restricts some features to make this more clear (show stop button, read only editor).
- Remove the "run your code" button and add a new, more prominent button as discussed with the previous PR
- When debugging a test from the feedback table, it would make sense to also show that test in the modal. This might help figuring out what the expected value/output was. 
- The "code arrow" doesn't scroll into view when it's not visible. Maybe we can reuse the active line feature of the editor?

2024-02-11 14:51 UTC, bmesuere commented on app/assets/javascripts/coding_scratchpad.ts
> +let editor: EditorView | undefined = undefined;
I don't think the `= undefined` is needed here.

2024-02-11 14:51 UTC, bmesuere commented on app/assets/javascripts/coding_scratchpad.ts
> +                    registration.unregister();
I think this might cause a bug because the unregister is async and the register below doesn't wait for the unregisters (but the chance of that happening is quite low).

```
await Promise.all(navigator.serviceWorker.getRegistrations().then(registrations =>
    registrations.filter(registration => registration.scope !== document.location.origin + "/")
                 .map(registration => registration.unregister())
));
```

2024-02-11 14:51 UTC, bmesuere commented on app/assets/javascripts/coding_scratchpad.ts
> +                const currentCode = papyros.getCode();
can't papyros be undefined?

2024-02-11 14:51 UTC, bmesuere commented on app/assets/javascripts/tutor.ts
> +        document.getElementById(DEBUG_BUTTON_ID).click();
Can't we trigger the debug from code instead of fake clicking the button?

2024-02-12 08:27 UTC, jorg-vr commented on app/assets/javascripts/coding_scratchpad.ts
> +                    registration.unregister();
The registration happens on scope "/", which equals to `document.location.origin + "/"`
This code will thus never unregister the newly registered serviceworker.

It is here because we used to register the service worker on a different, more specific path. Which caused the old serviceworkers to get priority.

I was actually thinking about removing this code in this pr, as for 99% of cases it will no longer be relevant. But I decided to wait another semester, to avoid issues

2024-02-12 09:19 UTC, jorg-vr commented on app/assets/javascripts/coding_scratchpad.ts
> +export const OFFCANVAS_ID = "scratchpad-offcanvas";
I have a personal preference for this style. It is sometimes useful to know whether something is exported when looking at the definition. I have never had a use case where I needed a quick overview of all exported definitions from a file.

I have almost always used this style over the past years, except when explicitly modifying older files.
This has caused for a divergence in styles across files. I am open to fixing this in another pr.

2024-02-12 17:20 UTC, bmesuere commented on app/assets/javascripts/coding_scratchpad.ts
> +export const OFFCANVAS_ID = "scratchpad-offcanvas";
I liked the idea of having a clear overview in the "old" style, but have no strong opinion about this. I just noticed a mix of two styles. According to "The Internet" multiple exports from the same file is a code smell. We can discuss this in person over lunch or coffee ;)

2024-02-12 17:22 UTC, bmesuere approved these changes

2024-02-13 09:52 UTC, chvp approved these changes

2024-02-13 10:27 UTC, merged