Add tips that nudge users to better use of Dodona
dodona-edu/dodona pull request #5386
Opened 2024-02-26 09:23 UTC by jorg-vr

This pull request

- [ ] Tests were added
- [ ] Documentation update can be found at dodona-edu/dodona-edu.github.io#

Closes # .

2024-02-26 12:42 UTC, chvp approved these changes

2024-02-28 12:59 UTC, bmesuere requested changes
I do think it's important to update the series tip dynamically. We want to inform people when they are adding a lot of exercises and make them think twice at that moment. If we only show it on page load, there a big chance they won't even see the message and if they do, it might already be too late.

2024-02-28 12:59 UTC, bmesuere commented on config/locales/views/activities/en.yml
> +        deprecated_judge_html: "You are using the legacy %{judge} judge. For new exercises, we recommend switching to the TESTed for a better experience. See <a href='https://docs.dodona.be/nl/guides
```suggestion
        deprecated_judge_html: "You are using the legacy %{judge} judge. For new exercises, we recommend switching to the TESTed judge for a better experience. See <a href='https://docs.dodona.be/nl/guides/exercises/testsuites/' target='_blank'>our documentation</a> for how to make the switch."
```

2024-02-28 15:16 UTC, jorg-vr commented
I have updated them to be dynamic

2024-02-28 15:28 UTC, bmesuere approved these changes

2024-02-28 15:42 UTC, merged