Allow exporting submission for users with at least one correct submission
dodona-edu/dodona pull request #5405
Opened 2024-02-29 13:29 UTC by jorg-vr

This pull request allows filtering out students who don't have a correct submission for a certain exercise from the result.

![image](https://github.com/dodona-edu/dodona/assets/21177904/d4f860f6-c779-48e7-8b1a-354773dd9563)

- [x] Tests were added

Closes https://github.com/dodona-edu/dodona/issues/2561

2024-03-04 13:56 UTC, chvp approved these changes

2024-03-06 09:22 UTC, bmesuere requested changes

2024-03-06 09:22 UTC, bmesuere commented on app/helpers/export_helper.rb
> +      @options[:filter_students].present? && @options[:filter_students] == 'correct'
Are the first parts of these checks needed here? (I can be wrong due to my lack of sleep)

2024-03-06 09:22 UTC, bmesuere commented on config/locales/views/exports/nl.yml
> +      only_correct_submitted_help: Studenten die nooit een correcte oplossing hebben ingediend zullen niet te vinden zijn in het resultaat.
```suggestion
      only_submitted_help: Studenten die nooit hebben ingediend zullen niet opgenomen worden in het resultaat.
      only_correct_submitted: Enkel studenten die minstens één correcte oplossing hebben ingediend
      only_correct_submitted_help: Studenten die nooit een correcte oplossing hebben ingediend zullen niet opgenomen worden in het resultaat.
```

2024-03-06 09:22 UTC, bmesuere commented on config/locales/views/exports/en.yml
> +      only_correct_submitted_help: Students who never submitted a correct solution will not be found anywhere in the result.
```suggestion
      only_submitted_help: Students who never submitted will not be recorded in the result.
      only_correct_submitted: Only students with at least one correct submission
      only_correct_submitted_help: Students who never submitted a correct solution will not be recorded in the result.
```

2024-03-06 09:36 UTC, jorg-vr commented on config/locales/views/exports/en.yml
> +      only_correct_submitted_help: Students who never submitted a correct solution will not be found anywhere in the result.
Is recorded used like this in English? It feels odd to me, but I could be wrong.
Maybe 'included' is better?

2024-03-06 09:52 UTC, bmesuere commented on config/locales/views/exports/en.yml
> +      only_correct_submitted_help: Students who never submitted a correct solution will not be found anywhere in the result.
included is ok for me

2024-03-08 14:13 UTC, bmesuere approved these changes

2024-03-11 08:27 UTC, merged