Add export of course users
dodona-edu/dodona pull request #5411
Opened 2024-03-04 11:02 UTC by jorg-vr

This pull request adds an export of all users in a course. 
![image](https://github.com/dodona-edu/dodona/assets/21177904/b62d725a-7783-4d90-9a38-7196840f02eb)

The csv is a different content type for the index api endpoint.
This means that all filters and sort features of the index page can also be applied.

The export now also includes the student progress in the course.
![image](https://github.com/dodona-edu/dodona/assets/21177904/e2bd6d3b-a125-46f0-9dec-d6c3d6e375f1)

This export also replaces the old specific export labels csv

Closes # .

2024-03-05 10:57 UTC, niknetniko approved these changes

2024-03-08 14:17 UTC, bmesuere requested changes
I agree with the export-related code changes and the fact that we make this more prominent, but I'm not convinced that the overflow menu of the search bar is the right place to put those options. They are still hidden and I would never check that menu.

Can we add figure out another way to place these actions? Maybe right-aligned buttons (but that might not be possible on smaller screens)?

2024-04-03 16:37 UTC, bmesuere approved these changes

2024-04-03 16:37 UTC, bmesuere commented on app/controllers/course_members_controller.rb
> +      format.csv do
The x_sendfile setting isn't present here (and was in the old code). Is this something that isn't needed anymore?

2024-04-04 07:51 UTC, jorg-vr commented on app/controllers/course_members_controller.rb
> +      format.csv do
"X-Sendfile is a special header option that tells the web server to ignore the content of the response and replace it by the file that is specified in the X-Sendfile header."

This is not relevant in this case, as the response is now the actual csv

2024-04-04 07:51 UTC, merged