Automatically trigger download of exported files
dodona-edu/dodona pull request #5418
Opened 2024-03-05 10:19 UTC by jorg-vr

This pull request

- [ ] Tests were added
- [ ] Documentation update can be found at dodona-edu/dodona-edu.github.io#

Closes # .

2024-03-06 10:31 UTC, niknetniko requested changes
Do we also want to handle the case where the download doesn't happen or isn't successful? For example, if you have your browser set to ask where a download should be saved and you press cancel, the button still says downloaded, and there is no way I see to download again (except going back through everything).

2024-03-06 10:31 UTC, niknetniko commented on config/locales/js/nl.yml
> +      downloading: Bezig met het voorbereiden van de download, dit kan enkele minuten duren. Sluit dit deze pagina niet.
```suggestion
      downloading: Bezig met het voorbereiden van de download, dit kan enkele minuten duren. Sluit deze pagina niet.
```

2024-03-06 10:36 UTC, jorg-vr commented
Hmm, maybe the text should not say 'downloaded', but ready to download

We could add a separate 'retry' and 'go back' button

Maybe:
"Export is ready. The download should start automatically. <btn-outline>Retry</btn-outline> <btn-filled>Go Back</btn-filled>"

2024-03-06 10:56 UTC, jorg-vr commented
@niknetniko 
![image](https://github.com/dodona-edu/dodona/assets/21177904/cd251956-771d-418b-9afd-932e3c3f8cc0)

2024-03-06 13:02 UTC, niknetniko approved these changes

2024-03-08 14:23 UTC, bmesuere requested changes
Functionality-wise, it would make sense to make the waiting/downloading step 3 in the stepper. This, also because:
- the text above the buttons in the action area of the card is a bit strange
- making "go back" the primary action is strange
- next to the automatic download, you also need an explicit button to trigger the download. Some browsers ask for permission to download first, or block such automatic downloads. In such cases, the download would fail.

2024-03-11 12:39 UTC, jorg-vr commented
> Functionality-wise, it would make sense to make the waiting/downloading step 3 in the stepper.

Great idea. Indeed a big improvement

> making "go back" the primary action is strange

Is it? I think this is the action everyone would preform after download?

> next to the automatic download, you also need an explicit button to trigger the download.

This is what the "retry download" button is for. Is this not clear enough? or do you expect something totally different?

2024-03-13 18:28 UTC, bmesuere approved these changes

2024-03-14 15:04 UTC, chvp commented on app/assets/stylesheets/components/btn.css.scss
> +  &:disabled{
```suggestion
  &:disabled {
```

2024-03-14 15:14 UTC, merged