Add dolos plagiarism detection
dodona-edu/dodona pull request #5420
Opened 2024-03-06 15:31 UTC by jorg-vr

This pull request adds a button to detect plagiarism on the submissions of an activity.

TODO:
- [ ] Fix cors, either add dodona and naos as expected frontends in dolos or route dolos api request through dodona backend.
- [ ] https://github.com/dodona-edu/dolos/issues/1398
- [ ] Dolos api should return report frontend url
- [ ] https://github.com/dodona-edu/dolos/issues/1399

![image](https://github.com/dodona-edu/dodona/assets/21177904/e008d05b-418c-4eb5-9de7-9b9ce8cb142c)

- [ ] Tests were added
- [ ] Documentation update can be found at dodona-edu/dodona-edu.github.io#

I would suggest handling  #2503 as a separate pr after this one.

Closes #5338

2024-03-06 15:34 UTC, jorg-vr commented
@rien  we should discuss how we want to handle cors

Let me know when you have found the time for the dolos modifications

2024-03-08 14:18 UTC, bmesuere commented
I have no strong opinion on this.

2024-03-11 09:08 UTC, jorg-vr commented
@rien, performing a post request from dodona is fine for me.
I'll adjust this implementation in dodona

It is not clear for me why Dodona needs to store the report URL in this case?

2024-03-11 09:18 UTC, jorg-vr commented
```mermaid
sequenceDiagram
  Dodona Front ->> Dodona Back: POST create export
  Note over Dodona Back: collect submissions
  Dodona Back -->> Dodona Front: export status URL
  loop untill ready
    Dodona Front -->> Dodona Back: GET export status
    Dodona Back -->> Dodona Front: status
  end
  Dodona Front ->> Dodona Back: POST create report with export URL
  Dodona Back ->> Dolos API: POST create report with zip file
  Note over Dolos API: download export & start analysis job
  Dolos API -->> Dodona Back: report URL 
  Dodona Back -->> Dodona Front: report URL
  Dodona Front ->> Dolos Front: GET report URL
  Note over Dolos Front: save report URL in LocalStorage
  loop untill ready
    Dolos Front ->> Dolos API: GET report status
    Dolos API -->> Dolos Front: status
  end
  Note over Dolos Front: show report
```

2024-03-15 15:21 UTC, rien commented
I have added some documentation of the Dolos API on our website: https://dolos.ugent.be/docs/api.html

2024-04-24 16:02 UTC, rien commented
Dolos will now show a loading page when redirected to the `html_url` if the report is not finished yet. You can validate if this PR works and release when ready :tada:

2024-04-29 08:58 UTC, jorg-vr commented
This button is currently on the submissions list page. This is not ideal as it does not interact with the search functionality.

Other possibilities are on the activity information page, or replacing the right chevron with a three dot menu on activity lists.
![image](https://github.com/dodona-edu/dodona/assets/21177904/0a8981bc-b221-4f6d-91bf-7dc5a63b281d)

![image](https://github.com/dodona-edu/dodona/assets/21177904/63a0ab1e-dac2-4445-b34e-6163f9706ce6)

2024-04-29 11:46 UTC, niknetniko requested changes
- I would disable the button in the time between pressing the button and the dolos site launching.
- I have no direct opinion on the placement of the button

2024-04-29 11:46 UTC, niknetniko commented on app/views/submissions/index.html.erb
> +             actions << {icon: 'graph-outline', text: 'detect plagiarism', js: "window.dodona.startDolos(\"#{series_exports_path(@series, token: (@series.access_token if @series.hidden?), selected_id
We probably want to i18n this button's text

2024-04-29 11:47 UTC, jorg-vr commented on app/views/submissions/index.html.erb
> +             actions << {icon: 'graph-outline', text: 'detect plagiarism', js: "window.dodona.startDolos(\"#{series_exports_path(@series, token: (@series.access_token if @series.hidden?), selected_id
totally forgot, thanks for noticing!

2024-04-29 14:32 UTC, niknetniko approved these changes

2024-04-29 14:32 UTC, niknetniko commented on config/locales/views/submissions/nl.yml
> +      detect_plagiarism: Detecteer plagiaat
```suggestion
      detect_plagiarism: Plagiaat detecteren
```

For consistency with the button next to it

2024-05-13 08:26 UTC, bmesuere requested changes

2024-05-13 08:26 UTC, bmesuere commented on app/assets/javascripts/dolos.ts
> +    btn.classList.remove("disabled");
Some browsers might block "popups". In that case, there is no way to retrigger opening the results without rerunning the analysis. I think it would make sense to make the button open the analysis page after a first run (and potentially also change the wording on the button then).

2024-05-13 08:26 UTC, bmesuere commented on app/controllers/dolos_reports_controller.rb
> +    export.archive.open do |file|
This code should not really be in a controller action, but since it's quite small and don't have a better place for it right now I think it's ok.

2024-05-13 11:37 UTC, bmesuere approved these changes

2024-05-13 11:37 UTC, bmesuere commented on app/assets/javascripts/i18n/translations.json
> +        "view_report": "Plagiaat bekijken"
```suggestion
        "view_report": "Rapport bekijken"
```

2024-05-13 11:42 UTC, merged