Improve discoverability of evaluations and scoresheets
dodona-edu/dodona pull request #5421
Opened 2024-03-07 09:19 UTC by jorg-vr

This pull request improves the discoverability of the evaluations feature.

Important series actions, such as evaluations and the scoresheet are now displayed in the new footer.

![image](https://github.com/dodona-edu/dodona/assets/21177904/8714c44e-1185-4166-8556-0119a499a2aa)

For students only feedback is considered important. If no feedback is present, no footer is shown
![image](https://github.com/dodona-edu/dodona/assets/21177904/ce4e8051-b505-44c0-a80e-bf290831c4c5)

Other series actions are still hidden behind the dropdown
![image](https://github.com/dodona-edu/dodona/assets/21177904/ecf7a6cc-a8b7-4986-9f84-cb5e0ab05ebe)
![image](https://github.com/dodona-edu/dodona/assets/21177904/a7d55954-10ac-462f-a17b-dbb907b360ae)

- [ ] Documentation update can be found at dodona-edu/dodona-edu.github.io#

Closes #5408

2024-03-07 15:17 UTC, chvp approved these changes

2024-03-08 14:34 UTC, bmesuere reviewed
Some things to discuss:
- Does it make sense to add buttons to the bottom, but keep the overflow button at the top? I would expect the overflow to be in the same area. I do acknowledge that for students, without bottom bar, the top right seems the most logical.
- I feel like we should prioritize the buttons depending on the state. If a series has no evaluation, the scoresheet button (and/or the future "live view" button) should be more prominent than the button to start an evaluation which will be hardly used (we might even move it to the overflow button in case the series has a deadline which hasn't passed yet?). In case the series has an evaluation, the opposite is possibly true.

2024-03-11 08:54 UTC, jorg-vr commented
> Does it make sense to add buttons to the bottom, but keep the overflow button at the top? I would expect the overflow to be in the same area. I do acknowledge that for students, without bottom bar, the top right seems the most logical.

I tried out moving it to the bottom, but I was hesitant about what we would do for students, as they can have a combination of series both with and without bottom bar.

We can also just always leave it on top for students, and always in the bottom row for teachers.

But I don't have a strong opinion.

> I feel like we should prioritize the buttons depending on the state. If a series has no evaluation, the scoresheet button (and/or the future "live view" button) should be more prominent than the button to start an evaluation which will be hardly used (we might even move it to the overflow button in case the series has a deadline which hasn't passed yet?). In case the series has an evaluation, the opposite is possibly true.

I experimented with the other button styles, but I don't think they look visually appealing:
![image](https://github.com/dodona-edu/dodona/assets/21177904/6eae1763-ee46-48af-b42d-50696d4d5612)
![image](https://github.com/dodona-edu/dodona/assets/21177904/14094884-6725-45a1-9a8a-7df0d0d5fe5d)

It will start to look very crowded if every series on a page has a primary action button.
From a UX perspective, I would also never consider either of these actions to be the primary action a teachers wants to perform on this series. In every case they remain optional links.

We could hide the evaluation button when the deadline hasn't passed yet. But I am wondering why we would do that?
It might just confuse the user why the button is present on some but not all series.
If we want to make evaluating impossible before the deadline passed, we should disable the button and add a tooltip explanation.

2024-04-02 11:51 UTC, bmesuere requested changes
For students:
- no bottom bar
- "show evaluation"-button at the same position as graph toggle buttons

For teachers:
- no border buttons
- if series has evaluation, make it primary
- move 3 dots to bottom bar

2024-04-03 17:43 UTC, bmesuere approved these changes

2024-04-18 08:48 UTC, merged