Add dynamic counts to search filters
dodona-edu/dodona pull request #5471
Opened 2024-04-05 12:28 UTC by jorg-vr

This pull request contains a refactor of search filters. 

The initial goal was to get rid of some old code that used js functions as part of 'filterCollection' objects to extract the color and paramVal from a filter option. This made most related code quite ugly and there was no longer any need for it.

So with cc610d658950ff2679f3a362dca044e81194b20a and 810fa47aae22c7cc2bd3ece8d745be697e3497c4 I made filterCollection a pure map of data objects.

With these changes it becomes a lot simpler to dynamically update filters.
I tried to write generic concerns that automatically define a dynamic option count when defining a scope. This way the end result should be less specific code.

- [ ] Tests were added
- [ ] Documentation update can be found at dodona-edu/dodona-edu.github.io#

Closes # .

2024-04-16 12:37 UTC, chvp approved these changes

2024-04-16 12:37 UTC, chvp commented on app/views/layouts/_searchbar.html.erb
> +        <% end %>
The indent seems weird here?

2024-04-16 12:37 UTC, chvp commented
(There are still some test and linting issues here.)

2024-05-13 08:17 UTC, bmesuere requested changes
This PR seems to include a bunch of changes from other PRs as well (dependencies, fix for graph time, ...) Maybe double check why this is and if we won't merge things we don't want.

Did you test the performance of these changes? I don't know if adding the counts needs a lot of additional queries? e.g. for the submissions table this might be quite impactful.

Can you explain the user of the Filters header?

2024-05-13 08:17 UTC, bmesuere commented on app/controllers/concerns/has_filter.rb
> +    self.filter_options = []
I'm not sure about this. filter_options is delegated to the class, but then set? In addition, vscode shows a warning here because "set a class-level attribute within an instance context"

2024-05-13 08:17 UTC, bmesuere commented on app/models/activity.rb
> +    )
I'm not too fond of adding explicit sql to ruby code

2024-05-13 08:17 UTC, bmesuere commented on app/models/concerns/filterable.rb
> +      scope :by_filter, ->(filter) { filter.split.map(&:strip).select(&:present?).inject(self) { |query, part| query.where("#{table_name}.search LIKE ?", "%#{part}%") } }
Where does `part` come from? Can a user inject something here?

2024-05-13 08:17 UTC, bmesuere commented on app/models/concerns/filterable.rb
> +  class_methods do
This class is very complex and needs more documentation.

2024-05-13 08:17 UTC, bmesuere commented on app/models/concerns/filterable.rb
> +    def filterable_by_course_labels(through_user: false)
Why is there a specific course label filter in a generic concern?

2024-05-13 13:30 UTC, jorg-vr commented on app/models/concerns/filterable.rb
> +      scope :by_filter, ->(filter) { filter.split.map(&:strip).select(&:present?).inject(self) { |query, part| query.where("#{table_name}.search LIKE ?", "%#{part}%") } }
this is the query string by the user (so user generated text)
But it is give as the second argument for a where query that uses a `?`. When replacing a `?` rails will handle the proper escaping to avoid sql injection

2024-05-13 14:21 UTC, jorg-vr commented on app/models/concerns/filterable.rb
> +    def filterable_by_course_labels(through_user: false)
The course_labels filter differs slightly from all the other filters as it requires an extra argument: `course_id`

Adding the flexibility to support an extra argument to `filterable_by` would make that method even more complex. Course_labels is also the only usecase of this feature.

Though this usecase is reused by three models. So it still made sense to not write the functionality three times.
If you like I could write this in a separate concern.
But I would prefer to keep it here as `filterable_by_course_labels` is just a specific implementation of `filterable_by` with slight variations. If changes should be applied to one method they might also be relevant for the other.

2024-05-14 07:54 UTC, jorg-vr commented on app/controllers/concerns/has_filter.rb
> +    self.filter_options = []
This variable has to be delegated to the class.
If I don't do that, the list of filters is stored in the concern, which means that every class that includes the concern is using the same list.

I tried a lot of different options and the only other method that worked was storing a dictionary where lists were indexed by controller name.
I found delegating the variable to the class to be a cleaner solution.

2024-05-14 08:18 UTC, jorg-vr commented
> This PR seems to include a bunch of changes from other PRs as well (dependencies, fix for graph time, ...) Maybe double check why this is and if we won't merge things we don't want.

These were all changes already on main. A new merge with main has fixed the issue of them being listed here.

> Can you explain the user of the Filters header?

This is only used in a single place. This usecase is saved annotations. The saved annotations list is the only page that doesn't fetch javascript upon search, but instead fetches the json data and feeds that to the web components.
This request now also needs the filter information to update the filters.
I treated the filter metadata the same way as the pagination metadata by including them in the headers of the request.

2024-05-14 09:02 UTC, jorg-vr commented
> Did you test the performance of these changes? I don't know if adding the counts needs a lot of additional queries? e.g. for the submissions table this might be quite impactful.

I minimized the amount of queries. But testing it on naos, the queries are unusable slow.
I'll have a look if they can be easily improved

2024-05-14 09:48 UTC, jorg-vr commented
We might have to reconsider this whole pr :(
I underestimated how hard it would be to optimize 'COUNT' queries...
There is no simple fix such as adding indexes as it seems innoDB does not use these indexes for counting.

The only suggested solution is keeping track of summary tables. But implementing this in a flexible way for all our search pages would add a whole new layer of complexity...

2024-05-14 12:50 UTC, jorg-vr commented
Maybe I overreacted.

The newly added count queries have a similar speed as the existing count query that already ran for pagination.
For most pages it doesn't have a big impact. Most pages only have one or two filters and this results into at most 100ms extra response time on naos, but often a lot less.

I have already removed the counts for the submission pages, as it was unbearably slow there (but these pages where already way to slow on naos anyway). 
For reference the pagination count takes 15.8 seconds out of the total 16.7 seconds on the submissions page. Adding up to two extra count queries to this page tripled response time. 
Side note: removing the page count on this page would greatly speed up the page.

The activities page is an edge case. With 7 filters the increase in query time can be up to 300ms, which is about 20% of the total time required to render the page. This makes interactivity on naos feel slightly suboptimal. 
But our production server is always a bit faster, and the UX improvement is greatest for activity selection, so it might be worth a 20% increase in loading time. 
This page also has room for speed ups in other places, such as removing the need for n+1 queries for popularity and activity status.

2024-05-21 11:55 UTC, chvp requested changes

2024-05-21 11:55 UTC, chvp commented on app/controllers/concerns/has_filter.rb
> +    self.filter_options = []
This also seems weird to me. It should be possible to delegate to the controller instance instead of the class, which would be better, IMO.

2024-05-21 11:55 UTC, chvp commented on app/controllers/feedbacks_controller.rb
> +    @submissions = Submission
```suggestion
    @submissions = Submission.all
```
This should at least by a activerecord query, IMO. Right now it's just referring to the class, which seems counter-intuitive.

2024-05-21 11:55 UTC, chvp commented on app/models/application_record.rb
> +  include Filterable
Do we want this in `ApplicationRecord`? Not all models will use this, I guess, so I would do it in the relevant models.

2024-05-21 11:55 UTC, chvp commented on app/models/concerns/filterable.rb
> +    def filterable_by_course_labels(through_user: false)
I would move this to a separate concern.

2024-05-21 11:55 UTC, chvp commented on app/models/activity.rb
> +  end
Can we add an extra method to the concern that handles cases like this (and popularity below). It also occurs in submission, IIUC.

2024-05-21 11:55 UTC, chvp commented on config/locales/models/en.yml
> +          no_auth_id_sign_in: User logged in without auth_id
Is this relevant to this PR? What does this mean?

2024-05-21 11:55 UTC, chvp commented on test/javascript/components/search/search_field.test.ts
> +import { Label, FilterOptions } from "../../../../app/assets/javascripts/components/search/filter_element";
Is this full path necessary? It didn't seem to be before?

2024-05-21 11:55 UTC, chvp commented on test/javascript/components/search/search_token.test.ts
> +import { Label } from "../../../../app/assets/javascripts/components/search/filter_element";
Same here.

2024-05-22 07:50 UTC, jorg-vr commented on app/models/application_record.rb
> +  include Filterable
I changed this.

The reason I did put it here was because already 9 different models used it, so that is pretty general. Also the concern does not have any effect upon include. It only makes extra class functions available to the models.

But in the end it doesn't matter much.

2024-05-22 08:50 UTC, jorg-vr commented on app/models/activity.rb
> +  end
I have now added this extra method:
```ruby
def filter_options_for(name, &block)
  define_singleton_method("#{name}_filter_options", &block)
end
```

Which does make it a bit more readable. But except for hiding the `define_singleton_method` it doesn't do much, as these functions don't have much in common

2024-05-22 08:59 UTC, jorg-vr commented on config/locales/models/en.yml
> +          no_auth_id_sign_in: User logged in without auth_id
This is an event type which did not have a translation yet

In production this causes an ugly missing translation text:
![image](https://github.com/dodona-edu/dodona/assets/21177904/d24826dc-76b7-4e10-be39-a2baf5f20ff7)

With the current change, the missing translation became a hard error (breaking my page), which made me notice and fix it.

This event is created in the authentication flow as suggested here: https://github.com/dodona-edu/dodona/pull/3663#discussion_r886917099

It has actually never been logged so far. I'll create an issue to clean up the authentication code and remove the event type

2024-05-23 11:07 UTC, chvp approved these changes

2024-07-29 12:55 UTC, bmesuere commented
https://github.com/coderabbitai review

2024-07-29 14:16 UTC, jorg-vr commented
@coderabbitai review

2024-07-29 14:28 UTC, bmesuere commented
@coderabbitai review

2024-10-24 11:44 UTC, jorg-vr commented
rebase and request review

2024-11-13 16:36 UTC, bmesuere approved these changes

2024-11-13 16:39 UTC, merged