Use exercise name for dolos report
dodona-edu/dodona pull request #5530
Opened 2024-05-14 14:27 UTC by jorg-vr

This pull request makes it so that for all exports, if only one option (eg. course, series, exercise) is selected, the name of that option is used for the exported file.

I have also removed the `.zip` extension in the name of the dolos report.

Closes #5525

2024-05-14 15:29 UTC, bmesuere requested changes

2024-05-14 15:29 UTC, bmesuere commented on app/assets/javascripts/i18n/translations.json
> -        "view_report": "Rapport bekijken"
Why has this been changed back?

2024-05-14 15:29 UTC, bmesuere commented on app/helpers/export_helper.rb
> +      name_source.is_a?(User) ? "#{name_source.full_name.parameterize}.zip" : "#{name_source.name.parameterize}.zip"
```suggestion
      name_source = @list.present? && @list.one? ? @list.first : @item
      base_name = name_source.is_a?(User) ? name_source.full_name : name_source.name
      "#{base_name.parameterize}.zip"
```
I think this is more readable and equivalent?

2024-05-16 07:47 UTC, jorg-vr commented on app/assets/javascripts/i18n/translations.json
> -        "view_report": "Rapport bekijken"
This file is a computed version of the yml file.
I'll update it in the yaml file instead

2024-05-16 11:03 UTC, niknetniko approved these changes

2024-05-16 11:30 UTC, merged