Add plagiarism detection for evaluations
dodona-edu/dodona pull request #5534
Opened 2024-05-16 12:50 UTC by jorg-vr

This pull request

- [ ] Tests were added
- [ ] Documentation update can be found at dodona-edu/dodona-edu.github.io#

Closes # .

2024-05-21 11:59 UTC, chvp approved these changes
Maybe this was discussed in the initial PR, but I don't particularly like the wording "Plagiaat controleren". As far as I understand it, Dolos can never say with certainty plagiarism occurred, only whether certain submissions are similar to others.

2024-05-22 12:50 UTC, jorg-vr commented
This has not been discussed before. But I am not sure about the alternative.

I think the button should clearly state the intent of the action, which is detecting plagiarism.
More detailed information about what to do with the info, and witch caveats to take  into account should be listed in Dolos.

But I am open to changing the button text if you have a good alternative suggestion

2024-05-27 13:08 UTC, bmesuere requested changes

2024-05-27 13:08 UTC, bmesuere commented on app/views/evaluations/_exercises_progress_table.html.erb
> +<%= javascript_include_tag 'dolos' %>
I didn't do a search, but is this a common pattern in our code base? I thought we included all js in the head through a yield/content_for combination.

2024-05-28 08:36 UTC, bmesuere approved these changes

2024-05-28 08:36 UTC, merged