Save series_id for submissions
dodona-edu/dodona pull request #5609
Opened 2024-06-14 13:52 UTC by jorg-vr

This pull request

- [ ] Tests were added
- [ ] Documentation update can be found at dodona-edu/dodona-edu.github.io#

Closes # .

2024-06-14 14:45 UTC, pdawyndt commented
While working on this issue, we might also consider storing some other submission properties that are now missed. It concerns those properties that are passed to the judge upon submission. One such property is the language setting of the user upon submission. As this is not stored, we no longer have that information upon re-evaluation. As a result, the language setting of the person re-evaluating is taken as the language passed to the judge upon re-evaluation (which changes the feedback in that respect).

2024-06-26 07:46 UTC, bmesuere requested changes

2024-06-26 07:46 UTC, bmesuere commented on app/assets/javascripts/exercise.ts
> +async function initExerciseShow(exerciseId: number, programmingLanguage: string, loggedIn: boolean, editorShown: boolean, courseId: number, _deadline: string, baseSubmissionsUrl: string, boilerplate:
This is becoming a very long parameter list. Do we already use option objects in other places.

2024-06-26 07:46 UTC, bmesuere commented on app/models/activity.rb
> +      return false unless series.accessible_to?(user) && series.activities.pluck(:id).include?(id)
Is there a reason why this return is here and not 2 lines higher with the other early termination return statement?

2024-06-26 07:46 UTC, bmesuere commented on app/models/activity.rb
> +    if course.present?
I'm a bit confused about this `course.present?` here. There is already a similar check in the elsif above and all paths end in a return there. So we only end up here as a continuation of the first if above if none of the 2 return statements return? It seems like this could be restructured to be more clear. At least, comments should be added explaining all these cases.

2024-06-26 07:46 UTC, bmesuere commented on app/models/submission.rb
>    scope :in_series, ->(series) { where(course_id: series.course.id).where(exercise: series.exercises) }
I don't think we can have 2 `in_series` scopes?

2024-06-26 07:46 UTC, bmesuere commented on db/migrate/20240614111643_add_series_id_to_submissions.rb
> +    add_index :submissions, :series_id
Adding an index on this table has a big impact. The current indexes were added only after checking if they were used (and what the best combination of potentially combining multiple columns in the index was).

2024-06-26 08:32 UTC, jorg-vr commented on app/models/submission.rb
>    scope :in_series, ->(series) { where(course_id: series.course.id).where(exercise: series.exercises) }
no, and this new one should not have been in this update.
Before we can change this scope, we'll have to determine what to do with submissions without series_id

2024-06-26 08:54 UTC, jorg-vr commented on app/models/activity.rb
> +    if course.present?
I've added comments

The reason this if is separate is that the course can be updated in the 'if series.present?' case

Also the `elsif course.present?` can be removed once we disallow submitting in a course without series, which will greatly simplify this code

2024-06-26 08:55 UTC, jorg-vr commented on app/assets/javascripts/exercise.ts
> +async function initExerciseShow(exerciseId: number, programmingLanguage: string, loggedIn: boolean, editorShown: boolean, courseId: number, _deadline: string, baseSubmissionsUrl: string, boilerplate:
not that I know, but we can start doing it here if you desire

2024-07-01 09:37 UTC, bmesuere approved these changes

2024-07-02 12:15 UTC, niknetniko reviewed
Besides the single comment, the code looks good.

Do we also want to include this information in the JSON API, or is it better to do this later?

2024-07-02 12:15 UTC, niknetniko commented on app/models/series.rb
> +  def visible_to?(user)
Would it be possible to use these methods in the series policy as well? Because now this logic is essentially duplicated in the `show?` method of the series policy, while I think we should strive to only have one source of truth for these kinds of things. Alternatively, if there are differences, we should probably put them in a comment here or in the policy to indicate why.

2024-07-02 13:15 UTC, jorg-vr commented on app/models/series.rb
> +  def visible_to?(user)
Even though there was a difference in implementation I opted for reusing the code.

This results in a change: hidden series are now only accessible to users who are member of a course (Instead of any signed in user as was the case previously)

I think this is an improvement

2024-07-02 13:37 UTC, niknetniko approved these changes

2024-07-03 09:11 UTC, merged